### ISSUE TITLE
[sdk] Please update pyyaml version - current version of KFP is incompatible with modern poetry 

### ISSUE THREAD

**Issue by JakeSummers** [kubeflow/pipelines#10007]
### Environment

*  KFP version: 1.8.12

*  KFP SDK version: NA

### Steps to reproduce

1. Install Poetry `1.5.1`
2. Add the following dependencies: 

```
[tool.poetry.dependencies]
python = ">=3.10.2,<4.0.0"
kfp = "1.8.12"
click = "^8.1.3"
dacite = "^1.6.0"
hvac = "^1.0.2"
types-PyYAML = "^6.0.12.4"
```

3. Install

```
$ poetry install

Package operations: 74 installs, 2 updates, 0 removals

  • Installing pyasn1 (0.4.8)
  ...
  <Hidden>
  ...
  • Installing pyyaml (5.4.1): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel

  /var/folders/t3/4_r66zqx2p72t0k_818__x2m0000gp/T/tmpwf9bk9f6/.venv/lib/python3.10/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
  !!

          ********************************************************************************
          The license_file parameter is deprecated, use license_files instead.

          By 2023-Oct-30, you need to update your project and remove deprecated calls
          or your builds will no longer be supported.

          See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
          ********************************************************************************

  !!
    parsed = self.parsers.get(option_name, lambda x: x)(value)
  running egg_info
  writing lib3/PyYAML.egg-info/PKG-INFO
  writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
  writing top-level names to lib3/PyYAML.egg-info/top_level.txt
  Traceback (most recent call last):
    File "/Users/jacob.summers/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/Users/jacob.summers/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/jacob.summers/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/var/folders/t3/4_r66zqx2p72t0k_818__x2m0000gp/T/tmpwf9bk9f6/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/var/folders/t3/4_r66zqx2p72t0k_818__x2m0000gp/T/tmpwf9bk9f6/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
      self.run_setup()
    File "/var/folders/t3/4_r66zqx2p72t0k_818__x2m0000gp/T/tmpwf9bk9f6/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
      exec(code, locals())
    File "<string>", line 271, in <module>
    File "/var/folders/t3/4_r66zqx2p72t0k_818__x2m0000gp/T/tmpwf9bk9f6/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
      return distutils.core.setup(**attrs)
    File "/var/folders/t3/4_r66zqx2p72t0k_818__x2m0000gp/T/tmpwf9bk9f6/.venv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
    File "/var/folders/t3/4_r66zqx2p72t0k_818__x2m0000gp/T/tmpwf9bk9f6/.venv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/var/folders/t3/4_r66zqx2p72t0k_818__x2m0000gp/T/tmpwf9bk9f6/.venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/var/folders/t3/4_r66zqx2p72t0k_818__x2m0000gp/T/tmpwf9bk9f6/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
      super().run_command(command)
    File "/var/folders/t3/4_r66zqx2p72t0k_818__x2m0000gp/T/tmpwf9bk9f6/.venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/var/folders/t3/4_r66zqx2p72t0k_818__x2m0000gp/T/tmpwf9bk9f6/.venv/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 318, in run
      self.find_sources()
    File "/var/folders/t3/4_r66zqx2p72t0k_818__x2m0000gp/T/tmpwf9bk9f6/.venv/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 326, in find_sources
      mm.run()
    File "/var/folders/t3/4_r66zqx2p72t0k_818__x2m0000gp/T/tmpwf9bk9f6/.venv/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 548, in run
      self.add_defaults()
    File "/var/folders/t3/4_r66zqx2p72t0k_818__x2m0000gp/T/tmpwf9bk9f6/.venv/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 586, in add_defaults
      sdist.add_defaults(self)
    File "/var/folders/t3/4_r66zqx2p72t0k_818__x2m0000gp/T/tmpwf9bk9f6/.venv/lib/python3.10/site-packages/setuptools/command/sdist.py", line 113, in add_defaults
      super().add_defaults()
    File "/var/folders/t3/4_r66zqx2p72t0k_818__x2m0000gp/T/tmpwf9bk9f6/.venv/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
      self._add_defaults_ext()
    File "/var/folders/t3/4_r66zqx2p72t0k_818__x2m0000gp/T/tmpwf9bk9f6/.venv/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
      self.filelist.extend(build_ext.get_source_files())
    File "<string>", line 201, in get_source_files
    File "/var/folders/t3/4_r66zqx2p72t0k_818__x2m0000gp/T/tmpwf9bk9f6/.venv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
      raise AttributeError(attr)
  AttributeError: cython_sources


  at ~/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/poetry/installation/chef.py:147 in _prepare
      143│
      144│                 error = ChefBuildError("\n\n".join(message_parts))
      145│
      146│             if error is not None:
    → 147│                 raise error from None
      148│
      149│             return path
      150│
      151│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with PyYAML (5.4.1) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "pyyaml (==5.4.1)"'.
```

### Expected result

The KFP package and it's dependencies should be installed properly.  

This issue has been fixed in `pyyaml 6.0.1`.  Bumping to that version should resolve the issue.  See:  https://github.com/yaml/pyyaml/issues/724

---

Impacted by this bug? Give it a 👍.

**Comment by connor-mccarthy** [comment]
This version of pyyaml is supported in the latest version of [1.8](https://github.com/kubeflow/pipelines/blob/434b41a19c983432e5f1ba218ac29e5075604db9/sdk/python/requirements.in#L22) and [2.x](https://github.com/kubeflow/pipelines/blob/434b41a19c983432e5f1ba218ac29e5075604db9/sdk/python/requirements.in#L22).
