### ISSUE TITLE
[sdk] I can't pass json str as a parameter into the pipeline

### ISSUE THREAD

**Issue by WystanW** [kubeflow/pipelines#10086]
### Environment

*  KFP version:

*  KFP SDK version: 
kfp==2.3.0

Hi team.

I'm using the following code to pass a json string to a pipeline as I want to deserialized it into my own Python object

```python
import json
from kfp import dsl

# Define a complex object as a dictionary
complex_object = {'name': 'Alice', 'age': 30}

# Serialize the complex object to a JSON string
serialized_object = json.dumps(complex_object)

@dsl.pipeline
def my_pipeline(serialized_param: str):
    def deserialize_object(serialized_data: str) -> dict:
        # Deserialize the JSON string to a Python dictionary
        deserialized_data = json.loads(serialized_data)
        return deserialized_data

    deserialize_task = deserialize_object(serialized_param)

if __name__ == '__main__':
    kfp.compiler.Compiler().compile(my_pipeline, 'my_pipeline.yaml')
```

But get the following error

```
Traceback (most recent call last):
  File "/Volumes/Workspace/Projects/vertex-ai-test/pickle_test.py", line 11, in <module>
    def my_pipeline(serialized_param: str):
  File "/opt/miniconda3/envs/vertex-ai/lib/python3.8/site-packages/kfp/components/pipeline_context.py", line 65, in pipeline
    return component_factory.create_graph_component_from_func(
  File "/opt/miniconda3/envs/vertex-ai/lib/python3.8/site-packages/kfp/components/component_factory.py", line 616, in create_graph_component_from_func
    return graph_component.GraphComponent(
  File "/opt/miniconda3/envs/vertex-ai/lib/python3.8/site-packages/kfp/components/graph_component.py", line 58, in __init__
    pipeline_outputs = pipeline_func(*args_list)
  File "/Volumes/Workspace/Projects/vertex-ai-test/pickle_test.py", line 17, in my_pipeline
    deserialize_task = deserialize_object(serialized_param)
  File "/Volumes/Workspace/Projects/vertex-ai-test/pickle_test.py", line 14, in deserialize_object
    deserialized_data = json.loads(serialized_data)
  File "/opt/miniconda3/envs/vertex-ai/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not PipelineParameterChannel

Process finished with exit code 1
```

Is there any way to pass complex object as a parameter into a pipeline?

**Comment by connor-mccarthy** [comment]
@WystanW, you can pass a string into a pipeline using a string parameter, just as you've done. The difference is that you'll need to put the `deserialize_object` logic in your component definition, not your pipeline definition. The pipeline definition defines the orchestration logic, so arbitrary Python cannot be used inside the pipeline body.

Alternatively, you can type your component with a dictionary and skip the serialization step `def my_comp(var: dict):`.
