### ISSUE TITLE
Kubeflow metadata-writer pod failing "Connection broken: ConnectionResetError(104, 'Connection reset by peer'"

### ISSUE THREAD

**Issue by skuchipu** [kubeflow/pipelines#10129]
### Kubeflow 1.7 on AKS 1.25.6

Connected to the metadata store
Start watching Kubernetes Pods created by Argo
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 764, in read_chunked
    self._update_chunk_length()
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 694, in _update_chunk_length
    line = self._fp.fp.readline()
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/kfp/metadata_writer/metadata_writer.py", line 163, in <module>
    for event in pod_stream:
  File "/usr/local/lib/python3.7/site-packages/kubernetes/watch/watch.py", line 144, in stream
    for line in iter_resp_lines(resp):
  File "/usr/local/lib/python3.7/site-packages/kubernetes/watch/watch.py", line 48, in iter_resp_lines
    for seg in resp.read_chunked(decode_content=False):
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 793, in read_chunked
    self._original_response.close()
  File "/usr/local/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 455, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

*  How did you deploy Kubeflow Pipelines (KFP)?
deployed kubeflow using kustomization as per the installation documentation 
https://www.kubeflow.org/docs/pipelines/installation/overview/. -->
*  KFP version:  [2.0.0-alpha.7]

### Steps to reproduce
Deploy kubeflow on AKS 1.25.6 using kustomize and the below pods are going into crashloop back 
metadata-writer-5899c74595-c2422
ml-pipeline-7d5658846f-h7wxk
metadata-grpc-deployment-784b8b5fb4-x55bh

The pods should be in running state  and connect to mysql successfully 

---

Impacted by this bug? Give it a 👍.

**Comment by zijianjoy** [comment]
@mosabami
