### ISSUE TITLE
[backend] <Pipeline execution not initiatied with error job_spec["pipelineSpec"]["root"] KeyError: 'root' 

### ISSUE THREAD

**Issue by crbl1122** [kubeflow/pipelines#10340]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
* Using GCP Vertex AI (Kubeflow) pipeline
Versions:
```
google-api-core                  2.15.0
google-api-python-client         1.12.11
google-auth                      2.25.2
google-auth-httplib2             0.2.0
google-auth-oauthlib             1.2.0
google-cloud-aiplatform          1.18.1
google-cloud-bigquery            2.34.4
google-cloud-core                2.4.1
google-cloud-notebooks           1.9.0
google-cloud-pipeline-components 2.0.0
google-cloud-resource-manager    1.11.0
google-cloud-storage             2.14.0
google-crc32c                    1.5.0
google-resumable-media           2.7.0
googleapis-common-protos         1.62.0
grpc-google-iam-v1               0.13.0
```

*  KFP version: 

*  KFP SDK version: 

```
kfp                              2.0.1
kfp-pipeline-spec                0.2.2
kfp-server-api                   2.0.0
```

### Steps to reproduce

Trying to run a Kubeflow pipeline compiled as a json template. The components are defined from functions using @component decorator.

```
def trigger_pipeline(
    project_id: str,
    location: str,
    template_path: str,
    pipeline_root: str,
    service_account: str,
    experiment: str,
    parameter_values: dict,
    enable_caching: Optional[bool],
) -> aip.PipelineJob:

    
    aip.init(project=project_id, location=location, staging_bucket=pipeline_root, experiment=experiment)


    job = aip.PipelineJob(
        display_name='pipeline',
        template_path=template_path,
        pipeline_root=pipeline_root,
        location=location,
        enable_caching=enable_caching,
        parameter_values=parameter_values
    )

  
    job.submit(service_account=service_account, experiment=experiment)
    job.wait()
    status = not(job.has_failed)
    logging.info(f'Pipeline ran succesfully: {status}')

    return status
```

### Expected result
Succesfully initiate the pipeline execution in Vertex AI.

No error at execution initiation
### Materials and Reference

This is the error:

```
Traceback (most recent call last):
  File "/home/jupyter/.../trigger/main.py", line 182, in <module>
    process_request()
  File "/home/jupyter/.../trigger/main.py", line 128, in process_request
    enable_caching = attributes['enable_caching'],
  File "/home/jupyter/.../trigger/main.py", line 161, in trigger_pipeline
    parameter_values=parameter_values
  File "/home/jupyter/.../venv/lib/python3.7/site-packages/google/cloud/aiplatform/pipeline_jobs.py", line 244, in __init__
    pipeline_job
  File "/home/jupyter/.../venv/lib/python3.7/site-packages/google/cloud/aiplatform/utils/pipeline_utils.py", line 84, in from_job_spec_json
    job_spec["pipelineSpec"]["root"]
KeyError: 'root'
```
---

Impacted by this bug? Give it a 👍.

**Comment by crbl1122** [comment]
Solved. KFP2.4
