### ISSUE TITLE
Question about how to use `dsl.PipelineTaskFinalStatus` with `dsl.container_component`

### ISSUE THREAD

**Issue by ysk24ok** [kubeflow/pipelines#10362]
macOS Sonoma 14.2.1
Python 3.11
kfp 2.4.0

I tried implementing a container component which does exit handling.

```py
from kfp import dsl


@dsl.container_component
def SampleExitOp(status: dsl.PipelineTaskFinalStatus):
    return dsl.ContainerSpec(
        image="gcr.io/...",
        command=["python3", "main.py"],
        args=["--state", status.state],
    )
```

When I compiled a pipeline which has the `SampleExitOp` component, the following error was shown.

```
Traceback (most recent call last):
  File "/Users/y-nishioka/repos/examples/kfp_v2/pipeline_with_reusable_components.py", line 7, in <module>
    import components
  File "/Users/y-nishioka/repos/examples/kfp_v2/components.py", line 6, in <module>
    @dsl.container_component
     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/y-nishioka/repos/examples/kfp_v2/venv/lib/python3.11/site-packages/kfp/dsl/container_component_decorator.py", line 53, in container_component
    return component_factory.create_container_component_from_func(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/y-nishioka/repos/examples/kfp_v2/venv/lib/python3.11/site-packages/kfp/dsl/component_factory.py", line 643, in create_container_component_from_func
    container_spec = func(*arg_list)
                     ^^^^^^^^^^^^^^^
  File "/Users/y-nishioka/repos/examples/kfp_v2/components.py", line 16, in SampleExitOp
    status.state,
    ^^^^^^^^^^^^
AttributeError: 'InputValuePlaceholder' object has no attribute 'state'
```

Does it mean we can't use `dsl.PipelineTaskFinalStatus` with `dsl.container_component`?

**Comment by HeGaoYuan** [comment]
@ysk24ok 

Hi, have you known how to fix this problem?

**Comment by connor-mccarthy** [comment]
`dsl.PipelineTaskFinalStatus` is a placeholder, not a type annotation. Usage is as follows:

```python
@dsl.container_component
def SampleExitOp(status: str = dsl.PipelineTaskFinalStatus):
```

**Comment by ysk24ok** [comment]
@connor-mccarthy Thank you for your response.

I tried with the following pipeline,

<details><summary>pipeline</summary>

```py
from kfp import dsl

PIPELINE_NAME = "exit-handler-pipeline"
LOCAL_PIPELINE_PATH = f"outputs/{PIPELINE_NAME}.yaml"


@dsl.container_component
def exit_op(status: str = dsl.PipelineTaskFinalStatus):
    return dsl.ContainerSpec(image='alpine', command=['echo'], args=[status])


@dsl.component(base_image="python:3.11")
def fail_op():
    import sys

    sys.exit(1)


@dsl.pipeline(name=PIPELINE_NAME)
def pipeline():
    print_status_task = exit_op()
    with dsl.ExitHandler(exit_task=print_status_task):
        fail_op()

compiler.Compiler().compile(pipeline_func=pipeline, package_path=LOCAL_PIPELINE_PATH)
```
</details>

but got the following error.

```
  File "/Users/y-nishioka/repos/examples/kfp_v2/venv/lib/python3.11/site-packages/kfp/compiler/pipeline_spec_builder.py", line 667, in _fill_in_component_input_default_value
    input_name].default_value.string_value = default_value
                              ^^^^^^^^^^^^
```

<details><summary>entire traceback</summary>

```
Traceback (most recent call last):
  File "/Users/y-nishioka/repos/examples/kfp_v2/exit_handler_pipeline.py", line 29, in <module>
    @dsl.pipeline(name=PIPELINE_NAME)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/y-nishioka/repos/examples/kfp_v2/venv/lib/python3.11/site-packages/kfp/dsl/pipeline_context.py", line 65, in pipeline
    return component_factory.create_graph_component_from_func(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/y-nishioka/repos/examples/kfp_v2/venv/lib/python3.11/site-packages/kfp/dsl/component_factory.py", line 673, in create_graph_component_from_func
    return graph_component.GraphComponent(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/y-nishioka/repos/examples/kfp_v2/venv/lib/python3.11/site-packages/kfp/dsl/graph_component.py", line 68, in __init__
    pipeline_spec, platform_spec = builder.create_pipeline_spec(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/y-nishioka/repos/examples/kfp_v2/venv/lib/python3.11/site-packages/kfp/compiler/pipeline_spec_builder.py", line 1934, in create_pipeline_spec
    build_exit_handler_groups_recursively(
  File "/Users/y-nishioka/repos/examples/kfp_v2/venv/lib/python3.11/site-packages/kfp/compiler/pipeline_spec_builder.py", line 1583, in build_exit_handler_groups_recursively
    exit_task_component_spec = build_component_spec_for_exit_task(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/y-nishioka/repos/examples/kfp_v2/venv/lib/python3.11/site-packages/kfp/compiler/pipeline_spec_builder.py", line 330, in build_component_spec_for_exit_task
    return build_component_spec_for_task(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/y-nishioka/repos/examples/kfp_v2/venv/lib/python3.11/site-packages/kfp/compiler/pipeline_spec_builder.py", line 356, in build_component_spec_for_task
    component_spec = _build_component_spec_from_component_spec_structure(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/y-nishioka/repos/examples/kfp_v2/venv/lib/python3.11/site-packages/kfp/compiler/pipeline_spec_builder.py", line 387, in _build_component_spec_from_component_spec_structure
    _fill_in_component_input_default_value(
  File "/Users/y-nishioka/repos/examples/kfp_v2/venv/lib/python3.11/site-packages/kfp/compiler/pipeline_spec_builder.py", line 667, in _fill_in_component_input_default_value
    input_name].default_value.string_value = default_value
                              ^^^^^^^^^^^^
```
</details>

I'm using kfp 2.7.0. Am I missing something?

It seems like `dsl.PipelineTaskFinalStatus` is a [dataclass](https://github.com/kubeflow/pipelines/blob/sdk-2.7.0/sdk/python/kfp/dsl/task_final_status.py#L20), not a placeholder like `dsl.PIPELINE_JOB_NAME_PLACEHOLDER`.

**Comment by connor-mccarthy** [comment]
@ysk24ok, you are correct. My [previous comment](https://github.com/kubeflow/pipelines/issues/10362#issuecomment-2043272965) was a mistake.

Can you please share how you are using your component in your pipeline?

**Comment by hhenke-mle** [comment]
Have same problem more or less and yes it seems that `PipelineTaskFinalStatus` doesnt work in container_components as it does in components - fails with `AttributeError: 'InputValuePlaceholder' object has no attribute 'state'`

**Comment by Yilinana** [comment]
Is there a way to get the final status of pipeline in kfp v2? I tried to use `PipelineTaskFinalStatus` in a container component, but I encountered the same issue and obtained the same result as mentioned above.

**Comment by ricardo-rolo** [comment]
I'm having the same issue when trying to create an exit_op container component that will be used to publish the PipelineTaskFinalStatus info into pub/sub.
Is there a way that I can serialize PipelineTaskFinalStatus info correctly to parse it inside the component? I tried to call asdict() from dataclasses but it broke the compilation since we don't have it at compile time, obviously :D.

```python
@container_component
def exit_op(
    image: str,
    status: PipelineTaskFinalStatus,
    outputs: Output[Artifact],
):
    return ContainerSpec(
        image=f"{image}",
        command=[
            "python",
            "-m",
            "module",
        ],
        args=[
            "--status",
            dumps(asdict(status)), # this is not possible, but is there a way to achieve similar behavior?
            "--outputs",
            outputs.path,
        ],
    )
```
It would be great if we can use container components as ExitOp components :)

**Comment by chrispyl** [comment]
Hello, this issue still persists, is there any way to get the `state` out of `PipelineTaskFinalStatus` in a container component?

**Comment by HumairAK** [comment]
hello this is now resolved by https://github.com/kubeflow/pipelines/pull/11953 and should be supported in the next kfp release

**Comment by chrispyl** [comment]
@HumairAK That's great to hear, thanks for the update!
