### ISSUE TITLE
[sdk] InputPath can't consume OutputPath

### ISSUE THREAD

**Issue by ysk24ok** [kubeflow/pipelines#10378]
### Environment

*  ~~KFP version:~~ I'm using Vertex AI.

*  KFP SDK version: 2.5.0

*  All dependencies version:

```
kfp                           2.5.0
kfp-pipeline-spec             0.2.2
kfp-server-api                2.0.3
```

### Steps to reproduce

<details><summary>pipeline</summary>

```py
import google.cloud.aiplatform as aip
from kfp import compiler, components, dsl

PROJECT = ...
LOCATION = ...
PIPELINE_NAME = "hello-pipeline"
PIPELINE_PACKAGE_PATH = f"{PIPELINE_NAME}.yaml"


@dsl.container_component
def say_hello(name: str, greeting: dsl.OutputPath(str)):
    """Log a greeting and return it as an output."""

    return dsl.ContainerSpec(
        image='alpine',
        command=[
            'sh', '-c', '''RESPONSE="Hello, $0!"\
                            && echo $RESPONSE\
                            && mkdir -p $(dirname $1)\
                            && echo $RESPONSE > $1
                            '''
        ],
        args=[name, greeting])


@dsl.component(base_image="python:3.12")
def print_text(text: dsl.InputPath(str)):
    print(text)


@dsl.pipeline(name=PIPELINE_NAME)
def hello_pipeline(person_to_greet: str) -> None:
    hello_task = say_hello(name=person_to_greet)
    print_text(text=hello_task.outputs["greeting"])


if __name__ == "__main__":
    compiler.Compiler().compile(pipeline_func=hello_pipeline, package_path=PIPELINE_PACKAGE_PATH)

    arguments = dict(person_to_greet="Alice")
    aip.init(project=PROJECT, location=LOCATION)
    job = aip.PipelineJob(
        display_name=PIPELINE_NAME,
        template_path=PIPELINE_PACKAGE_PATH,
        parameter_values=arguments,
    )
    job.submit()
```
</details>

Compile succeeds, but running the pipeline job fails. Logs on Vertex AI are as follows:

```py
Traceback (most recent call last): 
  File "<frozen runpy>", line 198, in _run_module_as_main 
  File "<frozen runpy>", line 88, in _run_code 
  File "/usr/local/lib/python3.12/site-packages/kfp/dsl/executor_main.py", line 109, in <module> 
    executor_main() 
  File "/usr/local/lib/python3.12/site-packages/kfp/dsl/executor_main.py", line 101, in executor_main 
    output_file = executor.execute() 
                  ^^^^^^^^^^^^^^^^^^ 
  File "/usr/local/lib/python3.12/site-packages/kfp/dsl/executor.py", line 359, in execute 
    func_kwargs[k] = self.get_input_artifact_path(k) 
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "/usr/local/lib/python3.12/site-packages/kfp/dsl/executor.py", line 158, in get_input_artifact_path 
    raise ValueError( 
ValueError: Failed to get input artifact path for artifact name text 
Job failed.
```

### Expected result

The pipeline job succeeds.

### Materials and Reference

Used the same component as shown in https://www.kubeflow.org/docs/components/pipelines/v2/components/container-components/#create-component-outputs.
https://github.com/kubeflow/pipelines/issues/9986 shared a workaround for this, but I think we should either fix the bug, or update the doc not to use `OutputPath`.

---

Impacted by this bug? Give it a 👍.

**Comment by SebastianCallh** [comment]
I am affected by this when trying to return values from a container component. Has anyone here found a way to do that? Not being able to output values from our components is a major issue

**Comment by connor-mccarthy** [comment]
`dsl.InputPath` is never preferred over a simple type annotation. Please use a type annotation as described [above](https://github.com/kubeflow/pipelines/issues/10378#issuecomment-1942267609).

**Comment by SebastianCallh** [comment]
Thank you for responding Connor. How would one do that with a container component?

**Comment by thesuperzapper** [comment]
@connor-mccarthy @zijianjoy, is there any way to provide large string parameters as file-paths in KFP v2?

This was previously possible in KFP v1 using `components.InputPath(str)` as the component type annotation.

As stated in this issue, using `dsl.InputPath(str)` does not work in v2, always giving an error like:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/site-packages/kfp/dsl/executor_main.py", line 109, in <module>
    executor_main()
  File "/usr/local/lib/python3.10/site-packages/kfp/dsl/executor_main.py", line 101, in executor_main
    output_file = executor.execute()
  File "/usr/local/lib/python3.10/site-packages/kfp/dsl/executor.py", line 359, in execute
    func_kwargs[k] = self.get_input_artifact_path(k)
  File "/usr/local/lib/python3.10/site-packages/kfp/dsl/executor.py", line 158, in get_input_artifact_path
    raise ValueError(
ValueError: Failed to get input artifact path for artifact name input_test
```

The code for the above component:

```python
@dsl.component(base_image="python:3.10")
def step_1(
    intro_message: str,
    input_test: dsl.InputPath(str),
    output_file: dsl.Output[dsl.Artifact],
):
    print(intro_message)
    print(input_test)

    with open(output_file.path, "w") as f:
        f.write(input_test)
```
