### ISSUE TITLE
[sdk] create_custom_training_job_from_component does not work

### ISSUE THREAD

**Issue by uedar** [kubeflow/pipelines#10418]
### Environment
* KFP Version
Vertex AI Pipelines
*  KFP SDK version: 
2.4.0
*  All dependencies version:

Here is my Dockerfile for building pipeline.
```Dockerfile
FROM python:3.11.4-slim-bullseye

COPY ./requirements.txt .
RUN pip install -r requirements.txt
```

requierements.txt
```
kfp==2.4.0
google-cloud-pipeline-components==2.8.0
```

### Steps to reproduce
I used the following pipeline code.
```python
from google_cloud_pipeline_components.v1.custom_job import create_custom_training_job_from_component
from kfp import compiler, dsl


@dsl.container_component
def train() -> dsl.ContainerSpec:
    return dsl.ContainerSpec(
        image="python:3.11.4-slim-bullseye",
        command=["python3", "--version"],
    )


@dsl.pipeline(name="train")
def pipeline() -> None:
    create_custom_training_job_from_component(
        train(),
        machine_type="n1-highmem-8",
        accelerator_type="NVIDIA_TESLA_V100",
    )


compiler.Compiler().compile(
    pipeline_func=pipeline,
    package_path=f"./pipeline.yaml",
)

```

When executing above code, the following error occurred.
```
Traceback (most recent call last):
  File "/work/pipeline.py", line 15, in <module>
    @dsl.pipeline(name="train")
     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kfp/dsl/pipeline_context.py", line 65, in pipeline
    return component_factory.create_graph_component_from_func(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kfp/dsl/component_factory.py", line 669, in create_graph_component_from_func
    return graph_component.GraphComponent(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kfp/dsl/graph_component.py", line 58, in __init__
    pipeline_outputs = pipeline_func(*args_list)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/pipeline.py", line 17, in pipeline
    create_custom_training_job_from_component(
  File "/usr/local/lib/python3.11/site-packages/google_cloud_pipeline_components/v1/custom_job/utils.py", line 141, in create_custom_training_job_from_component
    user_pipeline_spec = json_format.MessageToDict(component_spec.pipeline_spec)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/google/protobuf/json_format.py", line 168, in MessageToDict
    return printer._MessageToJsonObject(message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/google/protobuf/json_format.py", line 203, in _MessageToJsonObject
    message_descriptor = message.DESCRIPTOR
                         ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'DESCRIPTOR'
task: Failed to run task "build": exit status 1
```

### Expected result
I expected the code to compile successfully and generate a pipeline.yaml file.
I would like to know if the issue I'm encountering is due to an error in my code or if it is a bug. 

### Materials and Reference

Impacted by this bug? Give it a 👍.

**Comment by miguelalba96** [comment]
did you tried to not call `train` but pass the function `train`:
```python
@dsl.pipeline(name="train")
def pipeline() -> None:
    create_custom_training_job_from_component(
        train, #here my change
        machine_type="n1-highmem-8",
        accelerator_type="NVIDIA_TESLA_V100",
    )
```

**Comment by uedar** [comment]
@miguelalba96
I tried it, but I encountered this error. Does it work in your environment?
```
Traceback (most recent call last):
  File "/work/pipeline.py", line 15, in <module>
    @dsl.pipeline(name="train")
     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kfp/dsl/pipeline_context.py", line 65, in pipeline
    return component_factory.create_graph_component_from_func(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kfp/dsl/component_factory.py", line 669, in create_graph_component_from_func
    return graph_component.GraphComponent(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kfp/dsl/graph_component.py", line 61, in __init__
    raise ValueError('Task is missing from pipeline.')
ValueError: Task is missing from pipeline.
task: Failed to run task "build": exit status 1
```

**Comment by miguelalba96** [comment]
why don't you try this:
```
from google_cloud_pipeline_components.v1.custom_job import create_custom_training_job_from_component
from kfp import compiler, dsl


@dsl.container_component
def train() -> dsl.ContainerSpec:
    return dsl.ContainerSpec(
        image="python:3.11.4-slim-bullseye",
        command=["python3", "--version"],
    )


train_model_component = create_custom_training_job_from_component(
        train,
        machine_type="n1-highmem-8",
        accelerator_type="NVIDIA_TESLA_V100",
    )


@dsl.pipeline(name="train")
def pipeline() -> None:
    train_model = train_model_component(
        project=...,
        location=...,
    )


compiler.Compiler().compile(
    pipeline_func=pipeline,
    package_path=f"./pipeline.yaml",
)
```
I think you need to create first the component (in this case using`create_custom_training_job_from_component`) and then call it in the pipeline

**Comment by uedar** [comment]
@miguelalba96 
Thank you. I'm not sure why this is the solution, but it worked!

**Comment by uedar** [comment]
@miguelalba96
Is it possible to use arguments like this in a container_component? I've attempted several approaches, , but it's not working...

```python
@dsl.container_component
def train(dt: str) -> dsl.ContainerSpec:
    return dsl.ContainerSpec(
        image="python:3.11.4-slim-bullseye",
        command=["python3", "--version"],
    )
```

**Comment by miguelalba96** [comment]
@uedar yes it is possible, I have done it with Python contenarized components, you have to do it like this in the pipeline:

```python

@dsl.pipeline(name="train")
def pipeline(dt: str) -> None:
    train_model = train_model_component(
        project=...,
        location=...,
        dt=dt
    )
```

**Comment by uedar** [comment]
@miguelalba96
It worked well in my environment. Thank you!!
