### ISSUE TITLE
[backend] <Cannot get MLMD objects from Metadata store. Cannot find context>(version 1.8.0 and 1.10.0)

### ISSUE THREAD

**Issue by ZDowney926** [kubeflow/pipelines#11086]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
Following the guide of https://github.com/kubeflow/manifests/tree/v1.10-branch
*  KFP version: 
v2.2.0
*  KFP SDK version: 
(kfp: 2.4.0
kfp-pipeline-spec: 0.2.2
kfp-server-api: 2.0.3)

### Steps to reproduce
Here is a pipeline issue, I try in KubeFlow both v1.8.0 and v1.10.0 ,it both have same issue. I have read relevant issue, and try lots of method, it doesn't work. It seems like MLMD problem?( I don't know is it about database?) 
I followed the example to build a simple pipeline, here is the code. 
![image](https://github.com/user-attachments/assets/731c9a82-2d02-4c62-a128-89ff12242659)

The pipeline.yaml show:
![image](https://github.com/user-attachments/assets/66e4fa39-20d2-4f00-91fb-b14a8d3e0dca)
![image](https://github.com/user-attachments/assets/f994cd30-1e6f-481b-acd4-17b307542cd7)
![image](https://github.com/user-attachments/assets/69481ad1-0575-41d3-93f3-717048757021)

Then, I put the yaml file to pipleline
![image](https://github.com/user-attachments/assets/ec7090cf-602b-41a1-9518-588db4e22867)

I create run of pipeline, then I get the result of this "Cannot get MLMD objects from Metadata store.", if click Details, it shows 
![image](https://github.com/user-attachments/assets/e84373ca-11f5-456c-b048-13e48aa1d0ae)
![image](https://github.com/user-attachments/assets/407c68c3-323c-44e9-b197-139f08f2acdc)

---

Impacted by this bug? Give it a 👍.

**Comment by rimolive** [comment]
https://github.com/kubeflow/manifests/tree/v1.10-branch is still under development. I recommend use https://github.com/kubeflow/manifests/tree/v1.9-branch or the v1.9.0 tag.

**Comment by ESKYoung** [comment]
I'm encountering the same issue, but from [installing only Kubeflow Pipelines as detailed here](https://www.kubeflow.org/docs/components/pipelines/operator-guides/installation/). Will investigate the full installation.

**Comment by nparkstar** [comment]
I have the same problem.

**Comment by nparkstar** [comment]
I solved my issue at last.
I did fresh install on the new machine, and the problem has not appear anymore.

But I think the following instruction is wrong.
"Install individual components" of https://github.com/kubeflow/manifests/tree/v1.9.0.

I cannot connect to the central dashboard after installing kubeflow according to the above instruction.

I succeeded after installing using bellow command.

while ! kustomize build example | kubectl apply -f -; do echo "Retrying to apply resources"; sleep 10; done

Thanks,

**Comment by 922tech** [comment]
```
Failed to access the Metadata store. Exception: "failed to connect to all addresses; last error: UNKNOWN: ipv4:10.96.142.82:8080: Failed to connect to remote host: Connection refused"
Failed to access the Metadata store. Exception: "failed to connect to all addresses; last error: UNKNOWN: ipv4:10.96.142.82:8080: Failed to connect to remote host: Connection refused"
Traceback (most recent call last):
  File "/kfp/metadata_writer/metadata_writer.py", line 68, in <module>
    mlmd_store = connect_to_mlmd()
  File "/kfp/metadata_writer/metadata_helpers.py", line 62, in connect_to_mlmd
    raise RuntimeError('Could not connect to the Metadata store.')
RuntimeError: Could not connect to the Metadata store.
```

**Comment by shivanibhargove** [comment]
Hi, 
I am also facing the same issue with kfp upgrade. Could anyone help?
Details:
kfp-pipeline: 2.3.0
kfp-server-api: 2.0.3 )
kubeflow: I have tried with 1.8, 1.9
Error: Cannot find context with {"typeName":"system.PipelineRun","contextName":"9d29166b-68e1-433f-b506-62a70f0e1a13"}: Cannot find specified context

It is a blocker for us to upgrade to kfp v2.

**Comment by 922tech** [comment]
I think if you guys send pods' status in kubeflow and related namespaces (auth, admission-controllee, etc.) and also k8s system pods would help a lot. Because these pods are almost like a chain and each pod depends on another one to work and you must find the broken link.

**Comment by shivanibhargove** [comment]
Any update on the issue fix?
Not able to run pipelines because of this issue.

**Comment by juliusvonkohout** [comment]
I got a pipeline to finish, but there are still errors with ml-metadata ![image](https://github.com/user-attachments/assets/734cdf6e-3812-4b61-a0f6-c8b9fa6f5a5d)
Also no clear errors in the ml-metadata deployments. I think i have to examine the database directly Maybe I know more in a few weeks @rimolive 

CC @kubeflow/release-team

**Comment by juliusvonkohout** [comment]
It seems to be fixed now. It can happen with very large azure oidc info that you exceed the limit of the grpc server. But most things reported here and in https://github.com/kubeflow/pipelines/issues/8733#issuecomment-2624991816 seem to be from unclean installations or are probably fixed in KFP 2.4.0 or the master branch. If you upgrade from KF 1.9.1 cleanup your istio-system namespace. Also some here had problems with the launcher and driver image which had no proper versioning until 2.4.0 https://github.com/kubeflow/manifests/pull/2953. So please create separate issues focused on a single problem. The master branch is probably also affected by https://github.com/kubeflow/manifests/issues/2970 and we hope to resolve it soon.

/close
