### ISSUE TITLE
[backend] YAML Load Crashes on PipelineJob Creation When Specifying Kube PVC to Mount

### ISSUE THREAD

**Issue by pickles-bread-and-butter** [kubeflow/pipelines#11241]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?

*  KFP version: 

*  KFP SDK version: 

1. Kubeflow pipelines on VertexAI Pipelines
2. KFP version 2.7.0
3. KFP Kuberenetes version 1.3.0
4. KFP pipeline-spec version 0.3.0
5. KFP server api version 2.0.5

### Steps to reproduce

Run this script

```python 

from typing import Any, List, Tuple

import kfp

from google.cloud import aiplatform
from kfp import kubernetes


@kfp.dsl.container_component
def verify_dir():
    return kfp.dsl.ContainerSpec(
                image = "alpine",
                command = ["test"],
                args = ["-d", "/dev/shm"]
            )


# Define the workflow of the pipeline.
@kfp.dsl.pipeline(
    name="proj-print",
    pipeline_root=pipeline_root_path)
def pipeline():
    verify_task = (verify_dir(
    ))

    shared_mem = kubernetes.CreatePVC(
        # can also use pvc_name instead of pvc_name_suffix to use a pre-existing PVC
        pvc_name_suffix='-shared-mem',
        access_modes=['ReadWriteMany'],
        size='1Gi',
        storage_class_name='standard', # corresponds to k8s storage class
    )
    # like why hide the k8s package, it doesn't make sense, keep it simple
    kubernetes.mount_pvc(
        verify_task,
        pvc_name=shared_mem.outputs['name'],
        mount_path="/dev/shm",
    )
    
    return None


kfp.compiler.Compiler().compile(pipeline, "shared_mem_verify.yaml")


aiplatform.init(
    project=GCP_PROJECT,
    location=LOCATION,
)

job = aiplatform.PipelineJob(
    display_name="test",
    template_path="shared_mem_verify.yaml",
    pipeline_root=PIPELINE_ROOT,
)

job.submit(
    service_account=SERVICE_ACCOUNT
)

```

### Expected result

I would expect the dag that was compiled into yaml to submit to the Vertex AI Platform or at the least be able to form into a pipeline job. The error seems to be that yaml.load needs to change to enable `load_all`.

### Actual Result

```bash

Traceback (most recent call last):
  File line 8, in <module>
    sys.exit(main())
  File line 50, in main
    cli()
  File "site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "cli.py", line 27, in compile_pipeline
    compile_pipeline_command(
  File "cli/commands.py", line 12, in compile_pipeline_command
    compile_pipeline(
  File "cli/kfp/compile.py", line 10, in compile_pipeline
    imported_module = import_module(kfp_file_import_path)
  File "/home/isaak-willett/.pyenv/versions/3.10.13/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "examples/hello_world/hello_world_shared_mem.py", line 74, in <module>
    job = aiplatform.PipelineJob(
  File "site-packages/google/cloud/aiplatform/pipeline_jobs.py", line 226, in __init__
    pipeline_json = yaml_utils.load_yaml(
  File "site-packages/google/cloud/aiplatform/utils/yaml_utils.py", line 65, in load_yaml
    return _load_yaml_from_local_file(path)
  File "site-packages/google/cloud/aiplatform/utils/yaml_utils.py", line 117, in _load_yaml_from_local_file
    return yaml.safe_load(f)
  File "yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "site-packages/yaml/composer.py", line 41, in get_single_node
    raise ComposerError("expected a single document in the stream",
yaml.composer.ComposerError: expected a single document in the stream
  in "shared_mem_verify.yaml", line 3, column 1
but found another document
  in "shared_mem_verify.yaml", line 119, column 1

```

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by pickles-bread-and-butter** [comment]
A follow up question is that, does vertex pipelines support mounting the PVCs like this or am I totally restricted to the one output file object defined. I understand that I don't have access to the underlying infrastructure given that this is an abstraction but this is very limiting in a lot of scenarios. If it's not supported I'd say it's a high priority feature request.

**Comment by pickles-bread-and-butter** [comment]
Just another quick thought. I'm aware that it's not supported on Vertex and is mentioned in the docs no support but this has severe limitations. When I'm not able to pass the fuse cache around the i/o wait is now entirely back on the instance and I'm paying for I/O that's already been completed.
