### ISSUE TITLE
Backend Docker build fails with python error in resnet-train-pipeline.py

### ISSUE THREAD

**Issue by rileyjbauer** [kubeflow/pipelines#1142]
Ran on master branch (`086d4763d9f163acdeb423bc2bc49ab470442a92`) with `--no-cache` arg and got the following the error:
```
Step 20/31 : RUN  find . -maxdepth 2 -name '*.py' -type f | while read pipeline; do dsl-compile --py "$pipeline" --output "$pipeline.tar.gz"; done
 ---> Running in 3205bef0c5cb
Traceback (most recent call last):
  File "/usr/local/bin/dsl-compile", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/kfp/compiler/main.py", line 103, in main
    compile_pyfile(args.py, args.function, args.output, not args.disable_type_check)
  File "/usr/local/lib/python3.5/site-packages/kfp/compiler/main.py", line 92, in compile_pyfile
    _compile_pipeline_function(function_name, output_path, type_check)
  File "/usr/local/lib/python3.5/site-packages/kfp/compiler/main.py", line 72, in _compile_pipeline_function
    kfp.compiler.Compiler().compile(pipeline_func, output_path, type_check)
  File "/usr/local/lib/python3.5/site-packages/kfp/compiler/compiler.py", line 644, in compile
    workflow = self._compile(pipeline_func)
  File "/usr/local/lib/python3.5/site-packages/kfp/compiler/compiler.py", line 596, in _compile
    pipeline_func(*args_list)
  File "./resnet-cmle/resnet-train-pipeline.py", line 127, in resnet_train
    export_output = os.path.join(str(train.outputs['job-dir']), 'export')
KeyError: 'job-dir'
The command '/bin/sh -c find . -maxdepth 2 -name '*.py' -type f | while read pipeline; do dsl-compile --py "$pipeline" --output "$pipeline.tar.gz"; done' returned a non-zero code: 1

**Comment by gaoning777** [comment]
Replacing 'job_dir' with 'job-dir' in the resnet sample.
This is a bug. I'll send a PR to fix it.

**Comment by gaoning777** [comment]
fixed in https://github.com/kubeflow/pipelines/pull/1154
