### ISSUE TITLE
Train,Evaluate & Schema.json in xgboost-spark pipleine example

### ISSUE THREAD

**Issue by hitesh1907nayyar** [kubeflow/pipelines#1475]
Hi, 
I am trying to run the analyze.py script which is there in xgboost-spark pipeline example ( Link - https://github.com/kubeflow/pipelines/tree/master/samples/xgboost-spark). In order to run the script and understand the flow i need to give inputs for train.csv and schema.json. In addition eval.csv is also taken as input in transform script. From where can i get these files? I am not able to understand from where these files are coming.

In addition i tried to run like this : python3 analyze.py --project softwarization-net --region us-central1 --cluster kubesparkles1 --output gs://playgroundbucket1234/analysis --train gs://bradley-playground/sfpd/train.csv --schema gs://bradley-playground/schema.json 

It gave me an error:

Traceback (most recent call last):
  File "analyze.py", line 62, in <module>
    main()
  File "analyze.py", line 52, in main
    _utils.wait_for_job(api, args.project, args.region, job_id)
  File "/home/hcl_google_pri_infra/pipelines/components/dataproc/analyze/src/common/_utils.py", line 81, in wait_for_job
    raise Exception(result['status']['details'])
Exception: Job failed with message [KeyError: u'UNIQUE']. Additional details can be found in 'gs://dataproc-67063ea6-e22f-4176-b121-855bccd9a014-us-central1/google-cloud-dataproc-metainfo/df5c9e14-fbbd-411c-840d-4a1d7e25a917/jobs/d9d2ec98-94ca-483c-8cdf-31a4d451a553/driveroutput'.

**Comment by hitesh1907nayyar** [comment]
Closing as same issue reported with detailed logs on #1477
