### ISSUE TITLE
Code format may be different between Python versions 3.5 and 3.6

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#1507]
This can cause problems with Lightweight components in cases when the python version of the notebook is not the same as in the base image.

See also https://github.com/keras-team/keras/issues/9595

I got this error while playing with python code pickling:

```
def train(trainset='gs://....', learnrate=0.01) -> str:
    import sys
    print('Training')
    sys.stdout.flush()
    #print(trainset)
    return "Trained model"
```

```
Collecting cloudpickle==1.1.1
  Downloading 
https://files.pythonhosted.org/packages/24/fb/4f92f8c0f40a0d728b4f3d5ec5ff84353e705d8ff5e3e447620ea98b06bd/cloudpickle-1.1.1-py2.py3-none-any.whl
Installing collected packages: cloudpickle
Successfully installed cloudpickle-1.1.1
You are using pip version 18.0, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
XXX lineno: 2, opcode: 100
Traceback (most recent call last):
  File "<string>", line 33, in <module>
  File "<ipython-input-14-948543ef9ce8>", line 2, in train
SystemError: unknown opcode
ZZZZZ
cloudpickle is not installed
Installed cloudpickle globally
```

Command line and arguments:
```
['python3', '-c', 'print("ZZZZZ")\ntry:\n    import cloudpickle as _cloudpickle\nexcept ImportError:\n    print("cloudpickle is not installed")\n    import subprocess\n    import sys\n    try:\n        subprocess.run([sys.executable, "-m", "pip", "install", "cloudpickle==1.1.1"], check=True)\n        print("Installed cloudpickle globally")\n    except:\n        print("Failed to install cloudpickle globally. Installing for the current user.")\n        subprocess.run([sys.executable, "-m", "pip", "install", "cloudpickle==1.1.1", "--user"], check=True)\n        print("Installed cloudpickle for the current user")\n        import sys\n        import site\n        sys.path.append(site.getusersitepackages())\n    import cloudpickle as _cloudpickle\n\nimport pickle\n\ntrain = pickle.loads(b\'\\x80\\x03ccloudpickle.cloudpickle\\n_fill_function\\nq\\x00(ccloudpickle.cloudpickle\\n_make_skel_func\\nq\\x01ccloudpickle.cloudpickle\\n_builtin_type\\nq\\x02X\\x08\\x00\\x00\\x00CodeTypeq\\x03\\x85q\\x04Rq\\x05(K\\x02K\\x00K\\x03K\\x02KCC\\x1ed\\x01d\\x00l\\x00}\\x02t\\x01d\\x02\\x83\\x01\\x01\\x00|\\x02j\\x02j\\x03\\x83\\x00\\x01\\x00d\\x03S\\x00q\\x06(NK\\x00X\\x08\\x00\\x00\\x00Trainingq\\x07X\\r\\x00\\x00\\x00Trained modelq\\x08tq\\t(X\\x03\\x00\\x00\\x00sysq\\nX\\x05\\x00\\x00\\x00printq\\x0bX\\x06\\x00\\x00\\x00stdoutq\\x0cX\\x05\\x00\\x00\\x00flushq\\rtq\\x0eX\\x08\\x00\\x00\\x00trainsetq\\x0fX\\t\\x00\\x00\\x00learnrateq\\x10h\\n\\x87q\\x11X\\x1f\\x00\\x00\\x00<ipython-input-17-17fa41bc5dfe>q\\x12X\\x05\\x00\\x00\\x00trainq\\x13K\\x01C\\x08\\x00\\x01\\x08\\x01\\x08\\x01\\n\\x02q\\x14))tq\\x15Rq\\x16J\\xff\\xff\\xff\\xff}q\\x17(X\\x0b\\x00\\x00\\x00__package__q\\x18NX\\x08\\x00\\x00\\x00__name__q\\x19X\\x08\\x00\\x00\\x00__main__q\\x1au\\x87q\\x1bRq\\x1c}q\\x1d(X\\x07\\x00\\x00\\x00globalsq\\x1e}q\\x1fX\\x08\\x00\\x00\\x00defaultsq X\\t\\x00\\x00\\x00gs://....q!G?\\x84z\\xe1G\\xae\\x14{\\x86q"X\\x04\\x00\\x00\\x00dictq#}q$X\\x0e\\x00\\x00\\x00closure_valuesq%NX\\x06\\x00\\x00\\x00moduleq&h\\x1aX\\x04\\x00\\x00\\x00nameq\\\'h\\x13X\\x03\\x00\\x00\\x00docq(NX\\x08\\x00\\x00\\x00qualnameq)h\\x13utR.\')\n\nimport sys\n_args = {\n    \'trainset\': str(sys.argv[1]),\n    \'learnrate\': str(sys.argv[2]),\n}\n_output_files = [\n    sys.argv[3],\n]\n\n_outputs = train(**_args)\n\nif not hasattr(_outputs, \'__getitem__\') or isinstance(_outputs, str):\n    _outputs = [_outputs]\n\nfrom pathlib import Path\nfor idx, filename in enumerate(_output_files):\n    _output_path = Path(filename)\n    _output_path.parent.mkdir(parents=True, exist_ok=True)\n    _output_path.write_text(str(_outputs[idx]))\n']
['{{pipelineparam:op=;name=trainset;value=;type=;}}', '0.01', '/outputs/Output/data']
```

**Comment by Ark-kun** [comment]
I've discovered that there is a serious opcode incompatibility between python versions 3.5 and 3.6+. See my analysis of the issue: https://github.com/cloudpipe/cloudpickle/issues/293

Due to this issue I decided to switch back to using source code copying by default and to continue improving it. https://github.com/kubeflow/pipelines/pull/1512

Until we stop supporting python 3.5 (https://github.com/kubeflow/pipelines/pull/668) it's better to disable code pickling by default.

Code pickling can be enabled by specifying `pickle_code=True` when calling `func_to_container_op`

**Comment by Ark-kun** [comment]
This a "by design" bug in Python.
