### ISSUE TITLE
IAP authorization discrepancy between Python 3.5 and 3.7

### ISSUE THREAD

**Issue by pjo256** [kubeflow/pipelines#1678]
**What happened:**

When using `kfp.Client` to invoke various endpoints in a kubeflow deployment behind IAP, Python 3.5 returns with an authorization error while Python 3.7 returns a successful result when given the same input.

**What did you expect to happen:**

`kfp.Client` behavior should be consistent if we officially support >= Python 3.5, and return successfully in both cases. 

**What steps did you take:**
[A clear and concise description of what the bug is.]

```
export GOOGLE_APPLICATION_CREDENTIALS=/path/to/service-account.json
python
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import kfp
>>> client = kfp.Client(host=..., client_id=...)
>>>  client.upload_pipeline(pipeline_package_path=..., pipeline_name=...)
{ JSON response containing metadata about uploaded pipeline }
```

```
export GOOGLE_APPLICATION_CREDENTIALS=/path/to/service-account.json
python
Python 3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 16:30:03) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import kfp
>>> client = kfp.Client(host=..., client_id=...)
>>>  client.upload_pipeline(pipeline_package_path=..., pipeline_name=...)
Traceback (most recent call last):
  File "upload.py", line 16, in <module>
    upload_pipeline(host=args.host, client_id=args.client_id, pipeline_name=args.pipeline_name, pipeline_path=args.pipeline_path)
  File "upload.py", line 6, in upload_pipeline
    client.list_runs()
  File "/miniconda3/envs/py35/lib/python3.5/site-packages/kfp/_client.py", line 357, in list_runs
    response = self._run_api.list_runs(page_token=page_token, page_size=page_size, sort_by=sort_by)
  File "/miniconda3/envs/py35/lib/python3.5/site-packages/kfp_server_api/api/run_service_api.py", line 447, in list_runs
    (data) = self.list_runs_with_http_info(**kwargs)  # noqa: E501
  File "/Users/ottesenp/miniconda3/envs/py35/lib/python3.5/site-packages/kfp_server_api/api/run_service_api.py", line 535, in list_runs_with_http_info
    collection_formats=collection_formats)
  File "/miniconda3/envs/py35/lib/python3.5/site-packages/kfp_server_api/api_client.py", line 322, in call_api
    _preload_content, _request_timeout)
  File "/miniconda3/envs/py35/lib/python3.5/site-packages/kfp_server_api/api_client.py", line 153, in __call_api
    _request_timeout=_request_timeout)
  File "/miniconda3/envs/py35/lib/python3.5/site-packages/kfp_server_api/api_client.py", line 343, in request
    headers=headers)
  File "/miniconda3/envs/py35/lib/python3.5/site-packages/kfp_server_api/rest.py", line 238, in GET
    query_params=query_params)
  File "/miniconda3/envs/py35/lib/python3.5/site-packages/kfp_server_api/rest.py", line 228, in request
    raise ApiException(http_resp=r)
kfp_server_api.rest.ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Alt-Svc': 'clear', 'Date': 'Thu, 25 Jul 2019 20:53:08 GMT', 'Content-Length': '36', 'X-Goog-IAP-Generated-Response': 'true', 'Content-Type': 'text/html; charset=UTF-8'})
HTTP response body: Invalid IAP credentials: empty token
```

**Comment by pjo256** [comment]
So looks like I'm not able to reproduce this again after reinstalling python, not quite sure what caused this.

**Comment by Ark-kun** [comment]
I was able to repro. But after re-installing `kfp` and maybe more importantly `kfp-server-api` packages it stopped repro.
