### ISSUE TITLE
mlmetadata mysql database Type table missing two columns 

### ISSUE THREAD

**Issue by daikeshi** [kubeflow/pipelines#1722]
**What happened:**
`Type` table in mlmetadata mysql database are missing `input_type` and `output_type` columns. We are using ml-metadata for our TFX pipelines, and those two missing columns caused our pipeline failure:
```
Traceback (most recent call last):
  File "spotify_kubeflow/component/sdk/execution/run_component.py", line 82, in <module>
    fire.Fire(main)
  File "/usr/local/lib/python2.7/dist-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python2.7/dist-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python2.7/dist-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "spotify_kubeflow/component/sdk/execution/run_component.py", line 78, in main
    runner.launch()
  File "/ml/spotify_kubeflow/component/sdk/execution/component_launcher.py", line 67, in launch
    self._input_dict, self._output_dict, self._exec_properties
  File "/usr/local/lib/python2.7/dist-packages/tfx/orchestration/component_launcher.py", line 78, in _run_driver
    with metadata.Metadata(self._metadata_connection_config) as m:
  File "/usr/local/lib/python2.7/dist-packages/tfx/orchestration/metadata.py", line 99, in __enter__
    self._store = metadata_store.MetadataStore(self._connection_config)
  File "/usr/local/lib/python2.7/dist-packages/ml_metadata/metadata_store/metadata_store.py", line 50, in __init__
    logging.log(logging.INFO, "MetadataStore initialized")
  File "/usr/local/lib/python2.7/dist-packages/absl/logging/__init__.py", line 476, in log
    _absl_logger.log(standard_level, msg, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/absl/logging/__init__.py", line 1038, in log
    super(ABSLLogger, self).log(level, msg, *args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1231, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1285, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/logging/__init__.py", line 1259, in makeRecord
    rv = LogRecord(name, level, fn, lno, msg, args, exc_info, func)
  File "/usr/lib/python2.7/logging/__init__.py", line 285, in __init__
    self.threadName = threading.current_thread().name
  File "/usr/lib/python2.7/threading.py", line 1151, in currentThread
    return _active[_get_ident()]
RuntimeError: mysql_query failed: errno: 1054, error: Unknown column 'input_type' in 'field list'
``` 

**What did you expect to happen:**
Based on current `Type` table [schema](https://github.com/google/ml-metadata/blob/master/ml_metadata/util/metadata_source_query_config.cc#L339) in ml-metadata, those two columns should be created during database initialization. 

**What steps did you take:**
I did some investigation, and found that since this [PR](https://github.com/kubeflow/pipelines/pull/1289) got merged, KFP started depending on [an older version](https://github.com/kubeflow/pipelines/pull/1289/files#diff-09498dbadf45966909850dc8a47ebb13L53) of ml-metadata. This change caused ml-metadata used in KFP lost `Type` table [schema change](https://github.com/google/ml-metadata/commit/7ab9b647b049c080c6a6c97dc308b96287f741c3#diff-012e97001c838915cc2cb643ac5f62a6R332), where `input_type` and `out_type` are added.

**Anything else you would like to add:**
I wonder if we can bump `ml-metadata` commit version that KFP depends on.

**Comment by jessiezcc** [comment]
/cc @neuromage 
@Ark-kun, can you take a look asap?

**Comment by Ark-kun** [comment]
> I did some investigation, and found that since this [PR](https://github.com/kubeflow/pipelines/pull/1289) got merged, KFP started depending on [an older version](https://github.com/kubeflow/pipelines/pull/1289/files#diff-09498dbadf45966909850dc8a47ebb13L53) of ml-metadata.

The version of the ml-metadata package in the `go.mod` (which is the source of truth) has always been github.com/google/ml-metadata v0.0.0-20190214221617-0fb82dc56ff7 : https://github.com/Ark-kun/pipelines/commit/ba64bd3866023c36c93cf2b46a066a1b008bb6c4#diff-37aff102a57d3d7b797f152915a6dc16R35

The `WORKSPACE` was just out of sync with `go.mod` which was fixed when I ran the procedures outlinened in the [README.md](https://github.com/kubeflow/pipelines/blob/master/backend/README.md#updating-build-files) .

I've created a PR to update the version in `go.mod` and `WORKSPACE`.
