### ISSUE TITLE
target_image parameter is missed in the build_docker_image method

### ISSUE THREAD

**Issue by pahask8** [kubeflow/pipelines#1953]
**What happened:**

`target_image` is missed in the `build_docker_image ` method:

` image_name_with_digest = container_builder.build(local_build_dir, dockerfile_rel_path, timeout)`

**What did you expect to happen:**
It is impossible to build a docker image because of missed parameter using [this code](https://github.com/kubeflow/pipelines/blob/27d67420db012f534c561c2534bd1a306e9493ca/sdk/python/kfp/compiler/_component_builder.py#L442):

```
2019-08-26 10:40:49:INFO:Generate build files.
Traceback (most recent call last):
  File "/Users/user/Documents/WORK/git/emlp-project/kubeflow_pipelines/docker_build/build_kubeflow.py", line 12, in <module>
    namespace="kubeflow"
  File "/Users/user/Documents/WORK/venv/kubeflow_pipelines/lib/python3.6/site-packages/kfp/compiler/_component_builder.py", line 442, in build_docker_image
    image_name_with_digest = container_builder.build(local_build_dir, dockerfile_rel_path, timeout)
  File "/Users/user/Documents/WORK/venv/kubeflow_pipelines/lib/python3.6/site-packages/kfp/compiler/_container_builder.py", line 177, in build
    target_image=target_image)
  File "/Users/user/Documents/WORK/venv/kubeflow_pipelines/lib/python3.6/site-packages/kfp/compiler/_container_builder.py", line 125, in _generate_kaniko_spec
    '--destination=' + target_image,
TypeError: must be str, not int

Process finished with exit code 1

```

As you can see, the `build` method takes `target_image` parameter which is missed.

```
  def build(self, local_dir, docker_filename, target_image=None, timeout=1000):
    """
    Args:
      local_dir (str): local directory that stores all the necessary build files
      docker_filename (str): the dockerfile name that is in the local_dir
      target_image (str): the target image tag to push the final image.
      timeout (int): time out in seconds. Default: 1000
    """

```
**What steps did you take:**

Opening a pull request to fix it:

`
image_name_with_digest = container_builder.build(local_build_dir, dockerfile_rel_path, target_image, timeout)
`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Ark-kun** [comment]
Fixed by https://github.com/kubeflow/pipelines/pull/1955
