### ISSUE TITLE
samples/contrib/resnet-cmle trainer crashes on AI Platform 

### ISSUE THREAD

**Issue by ucdmkt** [kubeflow/pipelines#2028]
**What happened:**

Compiling and executing `./samples/contrib/resnet-cmle` pipeline does not succeed.

The second component in the pipeline "submitting-a-cloud-ml-training-job-as-a-pipeline-step-job-dir" fails on AI Platform training job.

Specifically, with the following stack trace.

```
Traceback (most recent call last):
  [...]
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2866, in computation
    with ops.control_dependencies(op_fn()):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 795, in enqueue_ops_fn
    features, labels = inputs.features_and_labels()  # Calls get_next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 3053, in features_and_labels
    return _Inputs._parse_inputs(self._iterator.get_next())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 421, in get_next
    name=name)), self._output_types,
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2069, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

OutOfRangeError (see above for traceback): End of sequence
	 [[node input_pipeline_task0/while/IteratorGetNext (defined at /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py:3053)  = IteratorGetNext[_class=["loc:@input_pipeline_task0/while/InfeedQueue/enqueue/0"], output_shapes=[[224,224,3,128], [128]], output_types=[DT_BFLOAT16, DT_INT32], _device="/job:worker/replica:0/task:0/device:CPU:0"](input_pipeline_task0/while/IteratorGetNext/Enter, ^input_pipeline_task0/while/Identity)]]
```

**What did you expect to happen:**

Training succeeds. A model (SavedModel) is produced. The third component "deploying-a-trained-model-to-cloud-machine-learning-engine" gets invoked.

**What steps did you take:**
[A clear and concise description of what the bug is.]

1. `git clone ...` the repository
1. Edited `./samples/contrib/resnet-cmle/build_pipeline.sh` and `./samples/contrib/resnet-cmle/resnet-train-pipeline.py` to use appropriate Google Cloud Storage buckets and GCP project.
1. Executed `./samples/contrib/resnet-cmel/build_pipeline.sh`. `resnet-train-pipeline.py.zip` was generated.
1. Uploaded `resnet-train-pipeline.py.zip` to Kubeflow Pipeline and create a Run, with appropriate GCP project. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

* Dataflow and AI Platform service account has been established, hence the first component "launch-python" succeeds, and the second component can create a job in AI Platform.
*  TPU service account has been established for the GCP project, as instructed in [this article](https://cloud.google.com/blog/products/ai-machine-learning/how-to-train-a-resnet-image-classifier-from-scratch-on-tpus-on-cloud-ml-engine)
* The Kubeflow Pipeline is deployed using [lightweight deployment](https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize). Running build ["cd898..."](https://github.com/kubeflow/pipelines/commit/0d898cb40f2bf30b711fce07c3d8769a9dc819b9)

**Comment by gaoning777** [comment]
Thanks for bringing up the resnet issue. We also noticed it and are currently working to resolve the issue.

**Comment by SinaChavoshi** [comment]
This sample is currently out dated, I have submitted a request to remove this sample #2053 and created three new tracking feature request for TPU #2049 , ResNet #2050 , and DataFlow #2051 samples to track creation of replacement samples.
