### ISSUE TITLE
kfp 0.1.35 tar.gz in pypi.org is missing diagnose_me directory

### ISSUE THREAD

**Issue by stephenhenderson** [kubeflow/pipelines#2609]
**What happened:**
The 0.1.35 release of kfp available on pypi.org (i.e. what is installed via `pip3 install kfp`) seems to be missing the `kfp/cli/diagnose_me` directory containing the diagnose_me modules required by the cli. The release hosted on github contains these files.

This is the tar.gz file hosted on pypi: https://files.pythonhosted.org/packages/e8/02/51dbeae211ddf1c931b2d1613db90856b7d94a53c1d9f704593dfa6253ae/kfp-0.1.35.tar.gz

If you try to install and run kfp 0.1.35 via pip it causes an error:
```
Traceback (most recent call last):
  File "/Users/shenderson/venvs/kubeflow/bin/kfp", line 5, in <module>
    from kfp.__main__ import main
  File "/Users/shenderson/venvs/kubeflow/lib/python3.7/site-packages/kfp/__main__.py", line 15, in <module>
    from .cli.cli import main
  File "/Users/shenderson/venvs/kubeflow/lib/python3.7/site-packages/kfp/cli/cli.py", line 21, in <module>
    from .diagnose_me_cli import diagnose_me
  File "/Users/shenderson/venvs/kubeflow/lib/python3.7/site-packages/kfp/cli/diagnose_me_cli.py", line 6, in <module>
    from .diagnose_me import dev_env
ModuleNotFoundError: No module named 'kfp.cli.diagnose_me'
```

**What did you expect to happen:**
All kfp modules including the diagnose_me package to be installed.

**What steps did you take:**
* Run `pip3 install --upgrade --force --no-cache-dir kfp`
* Run `kfp`

**Comment by stephenhenderson** [comment]
Looks like the `kfp.cli.diagnose_me` package is missing from setup.py:
https://github.com/kubeflow/pipelines/blob/master/sdk/python/setup.py#L64-L73
