### ISSUE TITLE
pipeline failed with error : This step is in Error state with this message: invalid character 'x' in string escape code

### ISSUE THREAD

**Issue by praveen049** [kubeflow/pipelines#2642]
**What happened:**

I am trying to run a simple kubeflow pipeline with 2 components, (1) preprocessor and (2) train

However, when I the run the pipeline, I get the message :
`This step is in Error state with this message: invalid character 'x' in string escape code`
in the second stage.
<img width="1170" alt="Screen Shot 2019-11-22 at 16 05 02" src="https://user-images.githubusercontent.com/24820914/69408574-39fb6200-0d42-11ea-8cd4-96764dcc705e.png">

This is my pipeline definition
```
import kfp.dsl as dsl
import kfp.compiler as compiler

@dsl.pipeline(name='load-predict-pipeline-logreg')
def pipeline(project_id='loan-predict'):
    preprocessor = dsl.ContainerOp(
        name='preprocessor',
        image='praveen049/loan-predict-logreg-preproc',
        command=['python', 'preprocessor.py'],
        arguments=[
            '--output-x-path', '/tmp/x.pkl',
            '--output-x-path-file', '/tmp/x.txt',
            '--output-y-path', '/tmp/y.pkl',
            '--output-y-path-file', '/tmp/y.txt',
    ],
        file_outputs={
            'x-output': '/tmp/x.pkl',
            'y-output': '/tmp/y.pkl',
        }
    )
    trainer = dsl.ContainerOp(
        name='trainer',
        image='praveen049/loan-predict-logreg-train',
        command=['python', 'train.py'],
        arguments=[
            '--input-x-path', preprocessor.outputs['x-output'],
            '--input-y-path', preprocessor.outputs['y-output'],
            '--output-model-path', '/tmp/model.pkl',
            '--output-model-path-file', '/tmp/model.txt'
        ],
        file_outputs={
            'model': '/tmp/model.pkl',
            'model-path': '/tmp/model.txt',
        }
    )
    trainer.after(preprocessor)


if __name__ == '__main__':
    compiler.Compiler().compile(pipeline, 'load-predict-pipeline-logreg.zip')
```

This is the code for the second stage
```
def load_feature(input_x_path):
  with open(input_x_path, 'rb') as input_x_file:
    return pickle.loads(input_x_file.read())


def load_label(input_y_path):
  with open(input_y_path, 'rb') as input_y_file:
    return pickle.loads(input_y_file.read())

parser = argparse.ArgumentParser()
parser.add_argument('--input-x-path', type=str, help='')
parser.add_argument('--input-y-path', type=str, help='')

parser.add_argument('--output-model-path', type=str, help='')
parser.add_argument('--output-model-path-file', type=str, help='')

args = parser.parse_args()

X = load_feature(args.input_x_path)
y = load_label(args.input_y_path)

x_train, x_cv, y_train, y_cv = train_test_split(X, y,
                                             test_size=0.3,
                                             random_state=1)

logistic_model = LogisticRegression(random_state=1, solver='liblinear')

logistic_model.fit(x_train,y_train.values.ravel())

pred_cv_logistic = logistic_model.predict(x_cv)
score_logistic = accuracy_score(pred_cv_logistic,y_cv)*100


with open(args.output_model_path, 'wb') as output_model:
  pickle.dump(logistic_model, output_model)

Path(args.output_model_path_file).parent.mkdir(parents=True, exist_ok=True)
Path(args.output_model_path_file).write_text(args.output_model_path)
```

The second stage pod is not created and i suspect that i have some error in my pipeline definition.

Version information: 
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
Kubeflow version is `0.5.0`
**What did you expect to happen:**

Any idea what is the problem and how to troubleshoot ?

Thanks

**Comment by Ark-kun** [comment]
Can you please run 
`kubectl get pods --all-namespaces --output yaml load_predict.........0002` and post the output here?

**Comment by praveen049** [comment]
@Ark-kun 
I am rerun the pipelines and  I am getting the below outputs for the command for the failing stage

```
root@ml# kubectl get pods load-predict-pipeline-logreg-m457s-3566486345 -o yaml --all-namespaces
error: a resource cannot be retrieved by name across all namespaces
```
```
root@ml# kubectl get pods load-predict-pipeline-logreg-m457s-3566486345 -o yaml
Error from server (NotFound): pods "load-predict-pipeline-logreg-m457s-3566486345" not found
```
```
root@ml# kubectl get pods load-predict-pipeline-logreg-m457s-3566486345
Error from server (NotFound): pods "load-predict-pipeline-logreg-m457s-3566486345" not found
```

For the first stage, the outputs are:

```
root@ml# kubectl get pods load-predict-pipeline-logreg-m457s-4121457743
NAME                                            READY   STATUS      RESTARTS   AGE
load-predict-pipeline-logreg-m457s-4121457743   0/2     Completed   0          13m
```
```
root@ml# kubectl get pods load-predict-pipeline-logreg-m457s-4121457743 -o yaml
error: error converting JSON to YAML: yaml: control characters are not allowed
```
```
root@mlb# kubectl get pods load-predict-pipeline-logreg-m457s-4121457743 -o yaml --all-namespaces
error: a resource cannot be retrieved by name across all namespaces
```

**Comment by Ark-kun** [comment]
Looks like the Kubernetes' YAML module might be buggy...
Can you also try
`kubectl get pods load-predict-pipeline-logreg-m457s-3566486345 -o json`

Also let's try to see the controller logs: `kubectl logs -l app=workflow-controller`

Maybe you can also post the contents of `load-predict-pipeline-logreg.zip`. We can try to recreate it, but it might better to see the exact YAML you have.

**Comment by praveen049** [comment]
@Ark-kun 

For the second stage components i am getting the below error

```
root@ml# kubectl get pods load-predict-pipeline-logreg-m457s-3566486345 -o json
Error from server (NotFound): pods "load-predict-pipeline-logreg-m457s-3566486345" not found
```

```
root@ml# kubectl logs -l app=workflow-controller
time="2019-11-23T10:57:55Z" level=info msg="Alloc=6254 TotalAlloc=862430 Sys=72638 NumGC=6404 Goroutines=61"
time="2019-11-23T10:57:55Z" level=info msg="Processing workflow" namespace=kubeflow workflow=pipe1-pj4r4
time="2019-11-23T11:02:55Z" level=info msg="Alloc=6274 TotalAlloc=862645 Sys=72638 NumGC=6407 Goroutines=61"
time="2019-11-23T11:07:55Z" level=info msg="Alloc=6275 TotalAlloc=862705 Sys=72638 NumGC=6409 Goroutines=61"
time="2019-11-23T11:09:54Z" level=info msg="Processing workflow" namespace=kubeflow workflow=pipe1-pj4r4
time="2019-11-23T11:12:55Z" level=info msg="Alloc=6290 TotalAlloc=863908 Sys=72638 NumGC=6412 Goroutines=61"
time="2019-11-23T11:17:55Z" level=info msg="Alloc=6254 TotalAlloc=863929 Sys=72638 NumGC=6414 Goroutines=61"
time="2019-11-23T11:17:55Z" level=info msg="Processing workflow" namespace=kubeflow workflow=pipe1-pj4r4
time="2019-11-23T11:22:55Z" level=info msg="Alloc=6255 TotalAlloc=864137 Sys=72638 NumGC=6417 Goroutines=61"
time="2019-11-23T11:27:55Z" level=info msg="Alloc=6274 TotalAlloc=864184 Sys=72638 NumGC=6419 Goroutines=61"
```

Also attaching the pipeline yaml
[load-predict-pipeline-logreg.zip](https://github.com/kubeflow/pipelines/files/3882390/load-predict-pipeline-logreg.zip)

**Comment by Ark-kun** [comment]
The issue might be partially cause by a bug in Kubernetes or Go-YAML, bit what's triggering it is the issue in a pipeline:

>             '--input-x-path', preprocessor.outputs['x-output'],
>             '--input-y-path', preprocessor.outputs['y-output'],

You're inserting the *value* of the output in the command line. The pickles are binary, so this causes insertion of arbitrary binary data into command-line, which is not supported by Linux.

Please check the [Data passing tutorial](https://github.com/kubeflow/pipelines/blob/8dfa2d9/samples/tutorials/Data%20passing%20in%20python%20components.ipynb) on how to pass big or binary data between python components. There is also sample for arbitrary command line programs: https://github.com/Ark-kun/kfp_samples/tree/master/2019-10%20Kubeflow%20summit/106%20-%20Creating%20components%20from%20command-line%20programs You need to use the `OutputPath()` and `InputPath()` annotations in python components or `inputPath`/`outputPath` placeholders in `component.yaml`.

**Comment by praveen049** [comment]
@Ark-kun 

Thanks for the input, this solved the issue.

Also many thanks for the related links on how to proceed.

**Comment by praveen049** [comment]
@Ark-kun 

Sorry, i still have couple of questions.

I have modified the code to pass a text file containing the name of the binary pickle file and the reported issue is not seen. But the second stage is not able to find the pickle file.

Here is the update yaml file

```
import kfp.dsl as dsl
import kfp.compiler as compiler

@dsl.pipeline(name='load-predict-pipeline-logreg')
def pipeline(project_id='loan-predict'):
    preprocessor = dsl.ContainerOp(
        name='preprocessor',
        image='praveen049/loan-predict-logreg-preproc',
        command=['python', 'preprocessor.py'],
        arguments=[
            '--output-x', '/x.pkl',
            '--output-x-path-file', '/x.txt',
            '--output-y', '/y.pkl',
            '--output-y-path-file', '/y.txt',
    ],
        file_outputs={
            'x-file': '/x.pkl',
            'y-file': '/y.pkl',
            'x-output': '/x.txt',
            'y-output': '/y.txt',
        }
    )
    trainer = dsl.ContainerOp(
        name='trainer',
        image='praveen049/loan-predict-logreg-train',
        command=['python', 'train.py'],
        arguments=[
            '--input_x_path_file', preprocessor.outputs['x-output'],
            '--input_y_path_file', preprocessor.outputs['y-output'],
            '--output_model', '/model.pkl',
            '--output_model_path_file', '/model.txt'
        ],
        file_outputs={
            'model': '/model.pkl',
            'model-path': '/model.txt',
        }
    )
    trainer.after(preprocessor)


if __name__ == '__main__':
    compiler.Compiler().compile(pipeline, 'load-predict-pipeline-logreg.zip')

```

Now, i am getting this error in the second stage
```
preprocessor
load-predict-pipeline-logreg-t5dw7-2314756664
This step is in Failed state with this message: failed with exit code 1
/x.pkl
Traceback (most recent call last):
  File "train.py", line 31, in <module>
    X = load_feature(args.input_x_path_file)
  File "train.py", line 13, in load_feature
    with open(input_x_path_file, 'rb') as input_x_file:
FileNotFoundError: [Errno 2] No such file or directory: '/x.pkl'
```

The second stage code is:
```
def load_feature(input_x_path_file):
  print (input_x_path_file)
  with open(input_x_path_file, 'rb') as input_x_file:
    print ('File exists')
    return pickle.loads(input_x_file.read())


def load_label(input_y_path_file):
  with open(input_y_path_file, 'rb') as input_y_file:
    return pickle.loads(input_y_file.read())

parser = argparse.ArgumentParser()
parser.add_argument('--input_x_path_file', type=str, help='')
parser.add_argument('--input_y_path_file', type=str, help='')

parser.add_argument('--output_model', type=str, help='')
parser.add_argument('--output_model_path_file', type=str, help='')

args = parser.parse_args()

X = load_feature(args.input_x_path_file)
y = load_label(args.input_y_path_file)
```

I have tried the example in the tutorial by converting the python functions directly into containerOp and then generating a pipeline and the data transfer is working fine. 
But using the above approach i am not able to get the data transfer working.

Can you please comment what is the mistake i am doing ?

Thanks

**Comment by Ark-kun** [comment]
> I have tried the example in the tutorial by converting the python functions directly into containerOp and then generating a pipeline and the data transfer is working fine.

That's the preferred way to do do so. Using `func_to_container_op` or writing `component.yaml` files manually you're creating a reusable component that you can share. This takes the same effort as writing code to instantiate `ContainerOp` manually (which is not shareable).

>I have modified the code to pass a text file containing the name of the binary pickle file and the reported issue is not seen. But the second stage is not able to find the pickle file.

JFYI: I think you're doing something unnecessary there. There is no need to output both `x.pkl` and `x.txt` (what's there?).

>Can you please comment what is the mistake i am doing ?

The problematic part remained the same:

```
            '--input_x_path_file', preprocessor.outputs['x-output'],
            '--input_y_path_file', preprocessor.outputs['y-output'],
```
You're putting the **contents** of the output data in the command-line.
You need to tell the system to write the data to a local file and put the **path** to the file in the command-line. When you use `ContainerOp` directly, the way to do that is to wrap the argument in `dsl.InputArgumentPath`:

```
import kfp.dsl as dsl
import kfp.compiler as compiler

def load_predict_logreg_pipeline(project_id='loan-predict'):
    preprocessor = dsl.ContainerOp(
        name='preprocessor',
        image='praveen049/loan-predict-logreg-preproc',
        command=['python', 'preprocessor.py'],
        arguments=[
            '--output-x-path', '/tmp/x.pkl',
            '--output-y-path', '/tmp/y.pkl',
        ],
        file_outputs={
            'x-output': '/tmp/x.pkl',
            'y-output': '/tmp/y.pkl',
        }
    )
    trainer = dsl.ContainerOp(
        name='trainer',
        image='praveen049/loan-predict-logreg-train',
        command=['python', 'train.py'],
        arguments=[
            '--input-x-path', dsl.InputArgumentPath(preprocessor.outputs['x-output']),
            '--input-y-path', dsl.InputArgumentPath(preprocessor.outputs['y-output']),
            '--output-model-path', '/tmp/model.pkl',
        ],
        file_outputs={
            'model': '/tmp/model.pkl',
        }
    )
```

**Comment by praveen049** [comment]
@Ark-kun 

Thanks for the detailed explanation. Now the pipeline is working.

As you suggested, i will try using the func_to_container_op or component.yaml instead.

**Comment by areshytko** [comment]
Why is there no place in documentation about this requirement of using `dsl.InputArgumentPath`?
