### ISSUE TITLE
Can't use katib-launcher component from python

### ISSUE THREAD

**Issue by prcastro** [kubeflow/pipelines#2678]
**What happened:**

I tried to compile a pipeline written in Python SDK using the `katib-laucher` component provided here on this repo, but it fails to compile. Followed [this notebook](https://github.com/hougangliu/pipelines/blob/e2e-pipeline-sample/samples/contrib/e2e-mnist/mnist-pipeline.ipynb).

**What did you expect to happen:**

Produce a valid pipeline YAML after compiling

**What steps did you take:**

I wrote this `pipeline.py` file:

```python
import json

from kfp import dsl
from kfp.components import load_component_from_url

katib_op = load_component_from_url("https://raw.githubusercontent.com/kubeflow/pipelines/master/components/kubeflow/katib-launcher/component.yaml")

def hyperopt_op(repo_name: str, branch_name: str):
    name = "hyperopt"
    namespace = "paulocastro"

    objective_config = {
        "type": "minimize",
        "goal": 0.001,
        "objectiveMetricName": "loss",
    }

    algorithm_config = {
        "algorithmName" : "random"
    }

    parameters = [
        {"name": "learning_rate", "parameterType": "double", "feasibleSpace": {"min": "0.01","max": "0.1"}},
    ]

    github_env = {
        "name": "GITHUB_TOKEN",
        "valueFrom": {
            "secretKeyRef": {
                "name": "git",
                "key": "token"
            }
        }
    }

    aws_timeout_env = {
        "name": "AWS_METADATA_SERVICE_TIMEOUT",
        "value": "3"
    }

    aws_num_attempts_env = {
        "name": "AWS_METADATA_SERVICE_NUM_ATTEMPTS",
        "value": "5"
    }

    image = f"my_image"

    command = f"train_model --repo {repo_name} --branch {branch_name}" + "{{- with .HyperParameters}} {{- range .}} --param {{.Name}}={{.Value}} {{- end}} {{- end\}}"

    container_template = {
        "name": "{{.Trial}}",
        "image": image,
        "env": [github_env, aws_timeout_env, aws_num_attempts_env],
        "command": command
    }

    job_template = {
        "metadata": {
            "annotations": {
                "iam.amazonaws.com/role": "my-kubeflow-role"
            }
        },
        "spec": {
            "containers": [container_template],
            "restartPolicy": "Never"
        }
    }

    raw_template = {
      "apiVersion": "batch/v1",
      "kind": "Job",
      "metadata": {
         "name": "{{.Trial}}",
         "namespace": "{{.NameSpace}}"
      },
      "spec": {
          "template": job_template
      }
    }
    
    trial_template = {
      "goTemplate": {
        "rawTemplate": json.dumps(raw_template)
      }
    }
    
    return katib_op(
        experiment_name=name,
        experiment_namespace=namespace,
        experiment_version="v1alpha2",
        parallel_trial_count=3,
        max_trial_count=12,
        objective=json.dumps(objective_config),
        algorithm=json.dumps(algorithm_config),
        trial_template=json.dumps(trial_template),
        parameters=json.dumps(parameters),
        delete_finished_experiment="False"
    )

@dsl.pipeline(name="hyperopt-test", description="hyperopt")
def my_pipeline():
    hyperparam_opt_op = hyperopt_op(repo_name="model", branch_name="paulo-test")
    return hyperparam_opt_op
```

And tried to compile using:

```
dsl-compile --py pipeline.py --output pipeline.yaml
```

And it throws the following error:

```
Traceback (most recent call last):
  File "/Users/paulo.castro/miniconda3/bin/dsl-compile", line 10, in <module>
    sys.exit(main())
  File "/Users/paulo.castro/miniconda3/lib/python3.6/site-packages/kfp/compiler/main.py", line 123, in main
    compile_pyfile(args.py, args.function, args.output, not args.disable_type_check)
  File "/Users/paulo.castro/miniconda3/lib/python3.6/site-packages/kfp/compiler/main.py", line 112, in compile_pyfile
    _compile_pipeline_function(pipeline_funcs, function_name, output_path, type_check)
  File "/Users/paulo.castro/miniconda3/lib/python3.6/site-packages/kfp/compiler/main.py", line 71, in _compile_pipeline_function
    kfp.compiler.Compiler().compile(pipeline_func, output_path, type_check)
  File "/Users/paulo.castro/miniconda3/lib/python3.6/site-packages/kfp/compiler/compiler.py", line 846, in compile
    package_path=package_path)
  File "/Users/paulo.castro/miniconda3/lib/python3.6/site-packages/kfp/compiler/compiler.py", line 908, in _create_and_write_workflow
    pipeline_conf)
  File "/Users/paulo.castro/miniconda3/lib/python3.6/site-packages/kfp/compiler/compiler.py", line 790, in _create_workflow
    workflow = fix_big_data_passing(workflow)
  File "/Users/paulo.castro/miniconda3/lib/python3.6/site-packages/kfp/compiler/_data_passing_rewriter.py", line 178, in fix_big_data_passing
    raise AssertionError
AssertionError
```

**Comment by prcastro** [comment]
Finally solved by updating kfp. Sorry about that
