### ISSUE TITLE
PyArrow dependency broken for TFX

### ISSUE THREAD

**Issue by numerology** [kubeflow/pipelines#2811]
Temporarily disable TFX test

**Comment by numerology** [comment]
Investigation shows that TFX has the requirement PyArrow < 0.15, but we somehow get PyArrow 0.15.1

**Comment by numerology** [comment]
Currently observed two failure mode:
1. backend server image failure, for [example](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/2797/kubeflow-pipeline-sample-test/1214582774061600770/build-log.txt):
```
[0m[91mTraceback (most recent call last):
  File "core/parameterized_tfx_oss/parameterized_tfx_oss.py", line 22, in <module>
    from tfx.components.evaluator.component import Evaluator
  File "/usr/local/lib/python3.5/site-packages/tfx/components/__init__.py", line 27, in <module>
    from tfx.components.example_validator.component import ExampleValidator
  File "/usr/local/lib/python3.5/site-packages/tfx/components/example_validator/component.py", line 24, in <module>
    from tfx.components.example_validator import executor
  File "/usr/local/lib/python3.5/site-packages/tfx/components/example_validator/executor.py", line 22, in <module>
    import tensorflow_data_validation as tfdv
  File "/usr/local/lib/python3.5/site-packages/tensorflow_data_validation/__init__.py", line 24, in <module>
    from tensorflow_data_validation.api.stats_api import GenerateStatistics
  File "/usr/local/lib/python3.5/site-packages/tensorflow_data_validation/api/stats_api.py", line 52, in <module>
    from tensorflow_data_validation.statistics import stats_impl
  File "/usr/local/lib/python3.5/site-packages/tensorflow_data_validation/statistics/stats_impl.py", line 32, in <module>
    from tensorflow_data_validation.arrow import arrow_util
  File "/usr/local/lib/python3.5/site-packages/tensorflow_data_validation/arrow/arrow_util.py", line 24, in <module>
    from tfx_bsl.arrow import array_util
  File "/usr/local/lib/python3.5/site-packages/tfx_bsl/arrow/array_util.py", line 17, in <module>
    from tfx_bsl.cc.tfx_bsl_extension.arrow.array_util import *
ImportError: libarrow.so.14: cannot open shared object file: No such file or directory
The command '/bin/sh -c set -e; find core -maxdepth 2 -name '*.py' -type f | while read pipeline; do python3 $pipeline; done' returned a non-zero code: 1
```
This is because in `RUN python3 -m pip install tfx==0.15.0`, pyarrow 0.15.1 was installed. However, tfx-bsl requires pyarrow<0.15.0 as stated [here](https://github.com/tensorflow/tfx-bsl/blob/0.15.3/third_party/pyarrow_version.bzl)

2. Sample test failure, for [example](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/2804/kubeflow-pipeline-sample-test/1214582521161846784/build-log.txt).

My guess is that somehow there is another dependency of TFX shadowing the tfx-bsl requirements. Thus one solution can be we pin down the PyArrow version temporarily before TFX 0.21
