### ISSUE TITLE
using VolumeOp in ExitHandler

### ISSUE THREAD

**Issue by kim-sardine** [kubeflow/pipelines#2979]
**What happened:**

```
vop = dsl.VolumeOp(
    name="create-pvc",
    resource_name="my-pvc",
    modes=dsl.VOLUME_MODE_RWM,
    size='15G'
)

exit_task = dsl.ContainerOp(
    name='echo',
    image='library/bash:4.4.23',
    command=['ls -al', '/usr/mnt/data'],
    pvolumes={"/usr/mnt": vop.volume},
)

with dsl.ExitHandler(exit_task):
    run = dsl.ContainerOp(
        name='cat dog sample',
        image=image,
        command=["bash", script_path],
        arguments=[
            bucket_name,
        ],
        pvolumes={"/usr/mnt": vop.volume}
    ).apply(gcp.use_gcp_secret('user-gcp-sa'))

```

when I compiled it, 
_(I'm using latest dsl-compiler (kfp==0.2.0)_)

```
Original exception was:
Traceback (most recent call last):
  File "/home/honey/.local/bin/dsl-compile", line 8, in <module>
    sys.exit(main())
  File "/home/honey/.local/lib/python3.6/site-packages/kfp/compiler/main.py", line 123, in main
    compile_pyfile(args.py, args.function, args.output, not args.disable_type_check)
  File "/home/honey/.local/lib/python3.6/site-packages/kfp/compiler/main.py", line 112, in compile_pyfile
    _compile_pipeline_function(pipeline_funcs, function_name, output_path, type_check)
  File "/home/honey/.local/lib/python3.6/site-packages/kfp/compiler/main.py", line 71, in _compile_pipeline_function
    kfp.compiler.Compiler().compile(pipeline_func, output_path, type_check)
  File "/home/honey/.local/lib/python3.6/site-packages/kfp/compiler/compiler.py", line 879, in compile
    package_path=package_path)
  File "/home/honey/.local/lib/python3.6/site-packages/kfp/compiler/compiler.py", line 941, in _create_and_write_workflow
    pipeline_conf)
  File "/home/honey/.local/lib/python3.6/site-packages/kfp/compiler/compiler.py", line 819, in _create_workflow
    pipeline_conf,
  File "/home/honey/.local/lib/python3.6/site-packages/kfp/compiler/compiler.py", line 634, in _create_pipeline_workflow
    templates = self._create_dag_templates(pipeline, op_transformers)
  File "/home/honey/.local/lib/python3.6/site-packages/kfp/compiler/compiler.py", line 593, in _create_dag_templates
    op_name_to_for_loop_op,
  File "/home/honey/.local/lib/python3.6/site-packages/kfp/compiler/compiler.py", line 254, in _get_inputs_outputs
    self._get_uncommon_ancestors(op_groups, opsgroup_groups, upstream_op, op)
  File "/home/honey/.local/lib/python3.6/site-packages/kfp/compiler/compiler.py", line 155, in _get_uncommon_ancestors
    raise ValueError(op1.name + ' does not exist.')
ValueError: create-pvc does not exist.
```

**What did you expect to happen:**

In main containerOP (run), my tensorflow code generates checkpoint files and save these files to PVC (/usr/mnt/data).

I want to send checkpoint files in PVC to Google Cloud Storage bucket when I terminate it. (== in exitHandler).

but it seems like volumeOp in exitHandler is not working as above.

**Comment by rmgogogo** [comment]
ExitHandler is more for GC etc. purpose. I would prefer you save files to GCS before exit.
Try our latest 0.2.2 release's TFX sample as a reference. It has a Trainer and Pusher.

**Comment by kim-sardine** [comment]
I see.. I just wondered if I can save downloading and uploading time.
using TFX looks cool but it's useful only for tensorflow user.
