### ISSUE TITLE
batch_predict component - model_path regex validation inconsistent

### ISSUE THREAD

**Issue by maiconmattos** [kubeflow/pipelines#2983]
**What happened:**
When executing the component with model_path following `projects/[PROJECT_ID]/models/[MODEL_ID]` or `projects/[PROJECT_ID]/models/[MODEL_ID]/versions/[VERSION_ID]` the following message is presented :

```
Batch prediction
This step is in Failed state with this message: failed with exit code 1
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/ml/kfp_component/launcher/__main__.py", line 45, in <module>
    main()
  File "/ml/kfp_component/launcher/__main__.py", line 42, in main
    launch(args.file_or_module, args.args)
  File "kfp_component/launcher/launcher.py", line 45, in launch
    return fire.Fire(module, command=args, name=module.__name__)
  File "/usr/local/lib/python2.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/usr/local/lib/python2.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/usr/local/lib/python2.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "kfp_component/google/ml_engine/_batch_predict.py", line 55, in batch_predict
    raise ValueError('model_path value is invalid.')
ValueError: model_path value is invalid.
```

Modifying the model_path to start with '/', causes to another error :

```
  File "kfp_component/google/ml_engine/_batch_predict.py", line 70, in batch_predict
    create_job(project_id, job, job_id_prefix, wait_interval)
  File "kfp_component/google/ml_engine/_create_job.py", line 46, in create_job
    wait_interval).execute_and_wait()
  File "kfp_component/google/ml_engine/_create_job.py", line 60, in execute_and_wait
    self._create_job()
  File "kfp_component/google/ml_engine/_create_job.py", line 76, in _create_job
    job = self._job
  File "kfp_component/google/ml_engine/_client.py", line 40, in create_job
    body = job
  File "/usr/local/lib/python2.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/googleapiclient/http.py", line 851, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting 
https://ml.googleapis.com/v1/projects/my-project/jobs?alt=json
 returned "Field: prediction_input.version_name Error: Name should be in the form of 'projects/your-project-id/models/your-model-name/versions/your-version-name'">
```

To sum up: The `model_path` regex validation should be changed to remove the starting '/'. Since -- as the log states -- the 'model' or 'version' should not have the starting '/'.

**Comment by laurentbastien** [comment]
Can this be re-opened? This is a bug that makes the component not usable unless specifying a GCS path.

**Comment by laurentbastien** [comment]
/reopen

This bug makes the component unusable unless specifying a GCS path.
