### ISSUE TITLE
component/pipeline name clash: compiles fine, but causes run-time error

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#2993]
(This is with Build commit: ca58b22)

Running [this pipeline](https://gist.github.com/amygdala/c5d644d65e55c2b7a2b2fee5ea57fb27) gives the following run-time error, due to a name clash:
![image](https://user-images.githubusercontent.com/115093/73873440-76e5d980-4806-11ea-887c-d395a2226e01.png)

This issue was not caught at compile-time.  And, I'd argue that it should be allowed and handled in some way (renaming the pipeline name in the yaml?) It breaks modularity to have to know the name of a component when loading it from a URL.

[Here](https://gist.github.com/amygdala/2e4aa8cb20d52d84bff49c067181a1d8) is the component definition.

**Comment by amygdala** [comment]
hmm... I did need to update kfp.  

However (not to sidetrack), while I can compile this example pipeline using kfp==0.1.38, when I compile the same pipeline using kfp>0.1.38 (including the latest 0.2.2), I get this error:
```
Traceback (most recent call last):
  File "viz_test_pipeline_nameclash.py", line 42, in <module>
    compiler.Compiler().compile(viz_test, __file__ + '.tar.gz')
  File "/Users/amyu/devrel/TensorFlow-World-Adv-Introduction-TF-Serving/tf-world-tf-serving2/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 879, in compile
    package_path=package_path)
  File "/Users/amyu/devrel/TensorFlow-World-Adv-Introduction-TF-Serving/tf-world-tf-serving2/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 941, in _create_and_write_workflow
    pipeline_conf)
  File "/Users/amyu/devrel/TensorFlow-World-Adv-Introduction-TF-Serving/tf-world-tf-serving2/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 758, in _create_workflow
    pipeline_meta = _extract_pipeline_metadata(pipeline_func)
  File "/Users/amyu/devrel/TensorFlow-World-Adv-Introduction-TF-Serving/tf-world-tf-serving2/lib/python3.7/site-packages/kfp/dsl/_metadata.py", line 85, in _extract_pipeline_metadata
    component_spec = _extract_component_interface(func)
  File "/Users/amyu/devrel/TensorFlow-World-Adv-Introduction-TF-Serving/tf-world-tf-serving2/lib/python3.7/site-packages/kfp/components/_python_op.py", line 267, in _extract_component_interface
    type_struct = annotation_to_type_struct(parameter_annotation)
  File "/Users/amyu/devrel/TensorFlow-World-Adv-Introduction-TF-Serving/tf-world-tf-serving2/lib/python3.7/site-packages/kfp/components/_python_op.py", line 231, in annotation_to_type_struct
    annotation = annotation.to_dict()
TypeError: to_dict() missing 1 required positional argument: 'self'
```
Has the API changed?

**Comment by amygdala** [comment]
Update: It looks like the compilation error comes from this `String` type spec syntax, which worked through 1.38:
```
from kfp.dsl.types import String
...
def viz_test(  
  input1: String = 'qwerty'
  ):
```
If I change that line to `input1 = 'qwerty'` it's fine.

(I know this is 'forking' the topic, sorry-- if this is a real issue I'll file a sep. bug).

**Comment by Ark-kun** [comment]
> Update: It looks like the compilation error comes from this `String` type spec syntax, which worked through 1.38:

I'll look into this.
As a workaround, please use the native `str` type annotation.

**Comment by amygdala** [comment]
Thanks.  And: at least with 0.1.38, the original 'name clash' issue is fixed. I assume that remains the case with newer releases.
So I'll close this, but if you open another issue for the compilation problem, can you cc me on it?

**Comment by Ark-kun** [comment]
I've looked into the `String` issue. Looks like the current SDK version only supports `input1: String() = 'qwerty'` (an instance of `String`, not the type itself).
I'll try to fix that.
