### ISSUE TITLE
Importing kfp results in ModuleNotFoundError: No module named 'deprecated.sphinx'

### ISSUE THREAD

**Issue by sadeel** [kubeflow/pipelines#3206]
### What steps did you take:
pip install kfp
python3
>>> import kfp

### What happened:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/google/home/sadeel/testenv/lib/python3.7/site-packages/kfp/__init__.py", line 17, in <module>
    from . import components
  File "/usr/local/google/home/sadeel/testenv/lib/python3.7/site-packages/kfp/components/__init__.py", line 15, in <module>
    from ._airflow_op import *
  File "/usr/local/google/home/sadeel/testenv/lib/python3.7/site-packages/kfp/components/_airflow_op.py", line 23, in <module>
    from ._python_op import _func_to_component_spec, _create_task_factory_from_component_spec
  File "/usr/local/google/home/sadeel/testenv/lib/python3.7/site-packages/kfp/components/_python_op.py", line 40, in <module>
    from deprecated.sphinx import deprecated
ModuleNotFoundError: No module named 'deprecated.sphinx'

### What did you expect to happen:
No error
### Environment:
Debian

How did you deploy Kubeflow Pipelines (KFP)?
GCP 

KFP version: 

KFP SDK version: 

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by Ark-kun** [comment]
Please show the log for `pip3 install kfp`. It should install the `deprecated` package
