### ISSUE TITLE
Method Not Allowed. Upload Pipeline Version. SDK Version/API mismatch

### ISSUE THREAD

**Issue by eedorenko** [kubeflow/pipelines#3442]
### What steps did you take:
Invoke this code:
```python
pipeline_version = client.pipeline_uploads.upload_pipeline_version(pipeline_file,
                                                                   name="Version1",
                                                                   pipelineid=pipeline.id)
```

### What happened:
Got an error:2020-04-04T00:15:09Z
Traceback (most recent call last):
  File "/Users/efedorenko/work/kubeflow-play/code/publish_pipeline.py", line 16, in <module>
    pipelineid=pipeline.id)
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api/pipeline_upload_service_api.py", line 157, in upload_pipeline_version
    (data) = self.upload_pipeline_version_with_http_info(uploadfile, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api/pipeline_upload_service_api.py", line 240, in upload_pipeline_version_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 330, in call_api
    _preload_content, _request_timeout)
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 161, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 373, in request
    body=body)
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/rest.py", line 275, in POST
    body=body)
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/rest.py", line 228, in request
    raise ApiException(http_resp=r)
kfp_server_api.rest.ApiException: (405)
Reason: Method Not Allowed
HTTP response headers: HTTPHeaderDict({'x-powered-by': 'Express', 'content-type': 'text/plain; charset=utf-8', 'x-content-type-options': 'nosniff', 'date': 'Sat, 04 Apr 2020 00:15:09 GMT', 'content-length': '19', 'server': 'istio-envoy', 'connection': 'close'})
HTTP response body: Method Not Allowed

### What did you expect to happen:
In the generated **pipeline_upload_service_api**, upload_pipeline_version_with_http_info invokes 'POST /apis/v1beta1/pipelines/upload_version'. This API doesn't exist. There is 'POST /apis/v1beta1/pipeline_versions' instead. So there is a mismatch in the API and swagger generated client.  

### Environment:

KFP version: Build commit: ca58b22

KFP SDK version: 0.3.0

/kind bug

**Comment by Bobgy** [comment]
@eedorenko sorry for getting back to you late.

KFP version: Build commit: ca58b22, this is KFP 0.2.0, KFP backend hasn't supported the new feature.
