### ISSUE TITLE
KFP behind a reverse proxy crashes upon specific request

### ISSUE THREAD

**Issue by amitripshtos** [kubeflow/pipelines#3465]
### What steps did you take:
1. Start a new run of a pipeline version.
2. When it started, the UI redirects to the experiments list page.
3. The UI container crashes

### What happened:
ml-pipeline-ui container has crashed.

### What did you expect to happen:
Keep working

### Environment:
GKE
Nginx-proxy

How did you deploy Kubeflow Pipelines (KFP)?
Standalone

KFP version: 0.3.0

KFP SDK version: 0.3.0

### Anything else you would like to add:
The Nginx proxy code:

```
            location /pipeline/ {
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://ml-pipeline-ui:80;
            }

            location ~ ^/ml_metadata.(.*?)/?$ {
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://metadata-envoy-service:9090;
            }
```

The logs of the container were:
```
I 2020-04-07T14:36:38.147494712Z GET /pipeline/apis/v1beta1/pipeline_versions/7b32c82c-bdef-47c1-9063-a339b0c67175
 
I 2020-04-07T14:36:38.147499497Z Proxied request:  /apis/v1beta1/pipeline_versions/7b32c82c-bdef-47c1-9063-a339b0c67175
 
E 2020-04-07T14:36:38.150310918Z _http_outgoing.js:405
 
E 2020-04-07T14:36:38.150341108Z     throw new ERR_HTTP_TRAILER_INVALID();
 
E 2020-04-07T14:36:38.150347157Z     ^
 
E 2020-04-07T14:36:38.150351868Z 
 
E 2020-04-07T14:36:38.150356704Z Error [ERR_HTTP_TRAILER_INVALID]: Trailers are invalid with this transfer encoding
 
E 2020-04-07T14:36:38.150361853Z     at ServerResponse._storeHeader (_http_outgoing.js:405:11)
 
E 2020-04-07T14:36:38.150366351Z     at ServerResponse.writeHead (_http_server.js:308:8)
 
E 2020-04-07T14:36:38.150370975Z     at ServerResponse._implicitHeader (_http_server.js:237:8)
 
E 2020-04-07T14:36:38.150376205Z     at write_ (_http_outgoing.js:607:9)
 
E 2020-04-07T14:36:38.150380893Z     at ServerResponse.write (_http_outgoing.js:586:15)
 
E 2020-04-07T14:36:38.150385284Z     at IncomingMessage.ondata (_stream_readable.js:728:22)
 
E 2020-04-07T14:36:38.150390137Z     at IncomingMessage.emit (events.js:223:5)
 
E 2020-04-07T14:36:38.150394682Z     at IncomingMessage.Readable.read (_stream_readable.js:526:10)
 
E 2020-04-07T14:36:38.150399924Z     at flow (_stream_readable.js:1001:34)
 
E 2020-04-07T14:36:38.150404365Z     at resume_ (_stream_readable.js:982:3) {
 
E 2020-04-07T14:36:38.150408919Z   code: 'ERR_HTTP_TRAILER_INVALID'
 
E 2020-04-07T14:36:38.150413336Z }
 
```

Thank you very much for your help!
Amit.

/kind bug
/area frontend

**Comment by Bobgy** [comment]
Thanks for the report @amitripshtos!

Sorry I don't have experience with this specific issue, looks like it relates to using nginx with node/express, rather than any business logic with Kubeflow Pipelines.

Help wanted on troubleshooting the issue and (even better if we have a tutorial to set up nginx with Kubeflow Pipelines).

**Comment by yiyuanyu17** [comment]
@amitripshtos  how you solve this problem, i meet this problem again

**Comment by amitripshtos** [comment]
Actually I didn’t solved the problem, but since then I stopped using KFP
