### ISSUE TITLE
Very long loading times in UI on OpenShift 4.3 fresh installation 

### ISSUE THREAD

**Issue by mkrakow** [kubeflow/pipelines#3473]
### What steps did you take:
1. Fresh installation KF 1.0.1 on Openshift 4.3.0 (Kubernetes Version: v1.16.2)
Image: ml-pipeline/frontend@sha256:848fc568b88542b1c9ec42a2c9b7f2eae1ac784e5fbde96fde4282a9da227b01
2. Walk through Web UI Pipelines then: Pipelines => Experiments => Artifacts => Executions responses for 1st time display each frame were less then 500 ms.  I walked 2-3 times through menu Pipelines => Experiments => Artifacts => Executions and UI started responding very slowly up to almost 10 minutes  (547471ms) 
![image](https://user-images.githubusercontent.com/31541923/78731655-98675c80-7940-11ea-8bdc-28f881a29550.png)
3. I added DISABLE_GKE_METADATA=true in ml-pipeline-ui deployment like in [comment](https://github.com/kubeflow/pipelines/issues/3070#issuecomment-588978533) but it didn't fix this issue. 

### What happened:
FireFox browser "hangs" in 2-3 "**walks through menu**" in case of Chrome in 5-6 walks
It looks like Browser stop sending requests (waits for _old_ responses)  because in the same time 2nd session from another browser works correctly 
Hard reload (ctrl+F5) fix this issue. 
In such case with single session I don't see in logs opened on pod `oc -n kubeflow logs -f ml-pipeline-ui-9c7f8749d-nml4l` any new incoming requests when I click on menu.

### What did you expect to happen:
Web UI should work always like in 1st opening page ( less then 500 ms) 

### Environment:
KF 1.0.1 on Openshift 4.3.0 (Kubernetes Version: v1.16.2)
Image: ml-pipeline/frontend@sha256:848fc568b88542b1c9ec42a2c9b7f2eae1ac784e5fbde96fde4282a9da227b01

How did you deploy Kubeflow Pipelines (KFP)?
Installation were made by KFCTL (kubeflow operator ) log line with pulled version:
```
time="2020-04-07T21:41:22Z" level=info msg="Fetching https://github.com/kubeflow/manifests/archive/v1.0.1.tar.gz to /tmp/.cache/manifests"
```

KFP version: ml-pipeline/frontend:0.2.0 (frontend@sha256:848fc568b88542b1c9ec42a2c9b7f2eae1ac784e5fbde96fde4282a9da227b01) 

Logs from pod I see mostly new rejections (in short time more then 500) 
```
(node:1) UnhandledPromiseRejectionWarning: FetchError: request to http://metadata/computeMetadata/v1/instance/attributes/cluster-name failed, reason: getaddrinfo ENOTFOUND metadata
    at ClientRequest.<anonymous> (/server/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:223:5)
    at Socket.socketErrorListener (_http_client.js:406:9)
    at Socket.emit (events.js:223:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 530)
GET /pipeline/system/project-id
(node:1) UnhandledPromiseRejectionWarning: FetchError: request to http://metadata/computeMetadata/v1/project/project-id failed, reason: getaddrinfo ENOTFOUND metadata
    at ClientRequest.<anonymous> (/server/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:223:5)
    at Socket.socketErrorListener (_http_client.js:406:9)
    at Socket.emit (events.js:223:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 531)
GET /pipeline/system/project-id
GET /pipeline/system/cluster-name
(node:1) UnhandledPromiseRejectionWarning: FetchError: request to http://metadata/computeMetadata/v1/project/project-id failed, reason: getaddrinfo ENOTFOUND metadata
    at ClientRequest.<anonymous> (/server/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:223:5)
    at Socket.socketErrorListener (_http_client.js:406:9)
    at Socket.emit (events.js:223:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 532)
(node:1) UnhandledPromiseRejectionWarning: FetchError: request to http://metadata/computeMetadata/v1/instance/attributes/cluster-name failed, reason: getaddrinfo ENOTFOUND metadata
    at ClientRequest.<anonymous> (/server/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:223:5)
    at Socket.socketErrorListener (_http_client.js:406:9)
    at Socket.emit (events.js:223:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 533)

**Comment by Bobgy** [comment]
KF 1.0.1 included KFP 0.2.0 and didn't include the fix in https://github.com/kubeflow/pipelines/issues/3070#issuecomment-588978533.

(Updated the comment including the versioning information) You may try changing just ml-pipeline-ui deployment image version, it may (or may not) work for you. Please wait for Kubeflow 1.0.2 if you don't want to try hacky workaround.
