### ISSUE TITLE
ml-pipeline pod crashes when run pipeline called with empty parameters list and has_default_bucket = true

### ISSUE THREAD

**Issue by pselden** [kubeflow/pipelines#3542]
### What steps did you take:
1. Created a pipeline with some runtime parameters, some of which have default values and some of with are empty
2. Used the kfp client to run pipeline
```py
run = self._client.run_pipeline(
  experiment.id,
  job_name=run_name,
  pipeline_id=pipeline_id,
  params={}
)

```
### What happened:
The ml-pipeline pod crashes with the following error:

```
panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12f9bc4] goroutine 168 [running]: github.com/kubeflow/pipelines/backend/src/apiserver/resource.OverrideParameterWithSystemDefault(0xc0000db800, 0xc00084c0d0, 0xf, 0x0) backend/src/apiserver/resource/resource_manager_util.go:209 +0x2e4 github.com/kubeflow/pipelines/backend/src/apiserver/resource.(*ResourceManager).CreateRun(0xc0001ce1c0, 0xc00084c0d0, 0xc000447e90, 0xc0000b69f0, 0x1) backend/src/apiserver/resource/resource_manager.go:290 +0x2d6 github.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).CreateRun(0xc00000e450, 0x1941ba0, 0xc000447e90, 0xc000447ec0, 0xc00000e450, 0x1, 0x1) backend/src/apiserver/server/run_server.go:43 +0xc5 github.com/kubeflow/pipelines/backend/api/go_client._RunService_CreateRun_Handler.func1(0x1941ba0, 0xc000447e90, 0x1696ce0, 0xc000447ec0, 0x1, 0x0, 0xc000466380, 0x0) bazel-out/k8-opt/bin/backend/api/linux_amd64_stripped/go_client_go_proto%/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:1269 +0x86 main.apiServerInterceptor(0x1941ba0, 0xc000447e90, 0x1696ce0, 0xc000447ec0, 0xc0000b3120, 0xc0000b3140, 0x15a5ec0, 0x25ad330, 0x171cca0, 0xc0005c6700) backend/src/apiserver/interceptor.go:30 +0xf4 github.com/kubeflow/pipelines/backend/api/go_client._RunService_CreateRun_Handler(0x16c95e0, 0xc00000e450, 0x1941ba0, 0xc000447e90, 0xc000ae2e60, 0x18060e0, 0x0, 0x0, 0xc000a32180, 0x7f) bazel-out/k8-opt/bin/backend/api/linux_amd64_stripped/go_client_go_proto%/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:1271 +0x158 google.golang.org/grpc.(*Server).processUnaryRPC(0xc000725800, 0x194ea40, 0xc00073fc80, 0xc0005c6700, 0xc000599650, 0x2527f80, 0x0, 0x0, 0x0) external/org_golang_google_grpc/server.go:966 +0x4a2 google.golang.org/grpc.(*Server).handleStream(0xc000725800, 0x194ea40, 0xc00073fc80, 0xc0005c6700, 0x0) external/org_golang_google_grpc/server.go:1245 +0xd61 google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000475a20, 0xc000725800, 0x194ea40, 0xc00073fc80, 0xc0005c6700) external/org_golang_google_grpc/server.go:685 +0x9f created by google.golang.org/grpc.(*Server).serveStreams.func1 external/org_golang_google_grpc/server.go:683 +0xa1
```

### What did you expect to happen:
Should run successfully with default parameters.

### Environment:
kfp==0.4.0
kfp-server-api==0.3.0

How did you deploy Kubeflow Pipelines (KFP)?
GCP Marketplace installer

KFP version: 0.2.5

KFP SDK version: 0.4.0

### Anything else you would like to add:
This happens at this line: https://github.com/kubeflow/pipelines/blob/master/backend/src/apiserver/resource/resource_manager_util.go#L210

And only happens when HAS_DEFAULT_BUCKET env is true.

/kind bug

/area backend

**Comment by Bobgy** [comment]
looks like already fixed
