### ISSUE TITLE
run-frontend-integration-tests failure

### ISSUE THREAD

**Issue by hongye-sun** [kubeflow/pipelines#3577]
[33mrun-frontend-integration-tests[0m:	Starting ChromeDriver 74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}) on port 25251
[33mrun-frontend-integration-tests[0m:	Only local connections are allowed.
[33mrun-frontend-integration-tests[0m:	Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
[33mrun-frontend-integration-tests[0m:	[1587495724.731][SEVERE]: bind() failed: Cannot assign requested address (99)
[33mrun-frontend-integration-tests[0m:	19:02:05.291 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
[33mrun-frontend-integration-tests[0m:	19:02:05.648 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 20d052ac3549d0696569df074b01f69c (org.openqa.selenium.chrome.ChromeDriverService)
[33mrun-frontend-integration-tests[0m:	Handling connection for 3000
[33mrun-frontend-integration-tests[0m:	Handling connection for 3000
[33mrun-frontend-integration-tests[0m:	Handling connection for 3000
[33mrun-frontend-integration-tests[0m:	Handling connection for 3000
[33mrun-frontend-integration-tests[0m:	FFFFFFFFFFFFFFFHandling connection for 3000
[33mrun-frontend-integration-tests[0m:	․Handling connection for 3000
[33mrun-frontend-integration-tests[0m:	FFFFFHandling connection for 3000
[33mrun-frontend-integration-tests[0m:	F19:03:26.061 INFO [ActiveSessions$1.onStop] - Removing session 20d052ac3549d0696569df074b01f69c (org.openqa.selenium.chrome.ChromeDriverService)
[33mrun-frontend-integration-tests[0m:	1 passing (82.10s)
[33mrun-frontend-integration-tests[0m:	21 failing
[33mrun-frontend-integration-tests[0m:	1) deploy helloworld sample run open pipeline creation page:
[33mrun-frontend-integration-tests[0m:	An element could not be located on the page using the given search parameters ("#createPipelineVersionBtn").
[33mrun-frontend-integration-tests[0m:	running chrome
[33mrun-frontend-integration-tests[0m:	Error: An element could not be located on the page using the given search parameters ("#createPipelineVersionBtn").
[33mrun-frontend-integration-tests[0m:	    at click() - index.js:312:3
[33mrun-frontend-integration-tests[0m:	2) deploy helloworld sample run uploads the sample pipeline:
[33mrun-frontend-integration-tests[0m:	An element could not be located on the page using the given search parameters ("#localPackageBtn").
[33mrun-frontend-integration-tests[0m:	running chrome
[33mrun-frontend-integration-tests[0m:	Error: An element could not be located on the page using the given search parameters ("#localPackageBtn").
[33mrun-frontend-integration-tests[0m:	    at click() - index.js:312:3
[33mrun-frontend-integration-tests[0m:	3) deploy helloworld sample run shows a 4-node static graph:
[33mrun-frontend-integration-tests[0m:	element (".graphNode") still not visible after 10000ms
[33mrun-frontend-integration-tests[0m:	running chrome
[33mrun-frontend-integration-tests[0m:	Error: element (".graphNode") still not visible after 10000ms
[33mrun-frontend-integration-tests[0m:	    at elements(".graphNode") - isVisible.js:54:17
[33mrun-frontend-integration-tests[0m:	    at isVisible(".graphNode") - waitForVisible.js:73:22
[33mrun-frontend-integration-tests[0m:	4) deploy helloworld sample run creates a new experiment out of this pipeline:
[33mrun-frontend-integration-tests[0m:	An element could not be located on the page using the given search parameters ("#newExperimentBtn").
[33mrun-frontend-integration-tests[0m:	running chrome
[33mrun-frontend-integration-tests[0m:	Error: An element could not be located on the page using the given search parameters ("#newExperimentBtn").
[33mrun-frontend-integration-tests[0m:	    at click() - index.js:312:3
[33mrun-frontend-integration-tests[0m:	5) deploy helloworld sample run creates a new run in the experiment:
[33mrun-frontend-integration-tests[0m:	element ("#choosePipelineBtn") still not visible after 10000ms
[33mrun-frontend-integration-tests[0m:	running chrome
[33mrun-frontend-integration-tests[0m:	Error: element ("#choosePipelineBtn") still not visible after 10000ms
[33mrun-frontend-integration-tests[0m:	    at elements("#choosePipelineBtn") - isVisible.js:54:17
[33mrun-frontend-integration-tests[0m:	    at isVisible("#choosePipelineBtn") - waitForVisible.js:73:22
[33mrun-frontend-integration-tests[0m:	6) deploy helloworld sample run redirects back to experiment page:
[33mrun-frontend-integration-tests[0m:	Promise was rejected with the following reason: timeout
[33mrun-frontend-integration-tests[0m:	running chrome
[33mrun-frontend-integration-tests[0m:	Error: Promise was rejected with the following reason: timeout
[33mrun-frontend-integration-tests[0m:	    at getUrl() - at url() - getUrl.js:30:28
[33mrun-frontend-integration-tests[0m:	7) deploy helloworld sample run finds the new run in the list of runs, navigates to it:
[33mrun-frontend-integration-tests[0m:	An element could not be located on the page using the given search parameters ("#refreshBtn").
[33mrun-frontend-integration-tests[0m:	running chrome
[33mrun-frontend-integration-tests[0m:	Error: An element could not be located on the page using the given search parameters ("#refreshBtn").
[33mrun-frontend-integration-tests[0m:	    at click() - index.js:312:3
[33mrun-frontend-integration-tests[0m:	8) deploy helloworld sample run switches to config tab:
[33mrun-frontend-integration-tests[0m:	element ("button=Config") still not visible after 5000ms
[33mrun-frontend-integration-tests[0m:	running chrome
[33mrun-frontend-integration-tests[0m:	Error: element ("button=Config") still not visible after 5000ms
[33mrun-frontend-integration-tests[0m:	    at elements("button=Config") - isVisible.js:54:17
[33mrun-frontend-integration-tests[0m:	    at isVisible("button=Config") - waitForVisible.js:73:22
[33mrun-frontend-integration-tests[0m:	9) deploy helloworld sample run waits for run to finish:
[33mrun-frontend-integration-tests[0m:	Cannot read property 'ELEMENT' of null
[33mrun-frontend-integration-tests[0m:	running chrome
[33mrun-frontend-integration-tests[0m:	TypeError: Cannot read property 'ELEMENT' of null
[33mrun-frontend-integration-tests[0m:	    at $("..") - at element("..") - $.js:42:17
[33mrun-frontend-integration-tests[0m:	10) deploy helloworld sample run displays run created at date correctly:
[33mrun-frontend-integration-tests[0m:	Cannot read property 'ELEMENT' of null
[33mrun-frontend-integration-tests[0m:	running chrome
[33mrun-frontend-integration-tests[0m:	TypeError: Cannot read property 'ELEMENT' of null
[33mrun-frontend-integration-tests[0m:	    at $("..") - at element("..") - $.js:42:17
[33mrun-frontend-integration-tests[0m:	11) deploy helloworld sample run displays run inputs correctly:
[33mrun-frontend-integration-tests[0m:	Cannot read property 'ELEMENT' of null
[33mrun-frontend-integration-tests[0m:	running chrome
[33mrun-frontend-integration-tests[0m:	TypeError: Cannot read property 'ELEMENT' of null
[33mrun-frontend-integration-tests[0m:	    at $("..") - at element("..") - $.js:42:17
[33mrun-frontend-integration-tests[0m:	12) deploy helloworld sample run switches back to graph tab:
[33mrun-frontend-integration-tests[0m:	An element could not be located on the page using the given search parameters ("button=Graph").
[33mrun-frontend-integration-tests[0m:	running chrome
[33mrun-frontend-integration-tests[0m:	Error: An element could not be located on the page using the given search parameters ("button=Graph").
[33mrun-frontend-integration-tests[0m:	    at click() - index.js:312:3
[33mrun-frontend-integration-tests[0m:	13) deploy helloworld sample run has a 4-node graph:
[33mrun-frontend-integration-tests[0m:	should have a 4-node graph, instead has: 0
[33mrun-frontend-integration-tests[0m:	running chrome
[33mrun-frontend-integration-tests[0m:	AssertionError [ERR_ASSERTION]: should have a 4-node graph, instead has: 0
[33mrun-frontend-integration-tests[0m:	    at Context.it (/src/helloworld.spec.js:180:5)
[33mrun-frontend-integration-tests[0m:	    at new Promise (<anonymous>)
[33mrun-frontend-integration-tests[0m:	    at new F (/src/node_modules/core-js/library/modules/_export.js:36:28)
[33mrun-frontend-integration-tests[0m:	14) deploy helloworld sample run opens the side panel when graph node is clicked:
[33mrun-frontend-integration-tests[0m:	An element could not be located on the page using the given search parameters (".graphNode").
[33mrun-frontend-integration-tests[0m:	running chrome
[33mrun-frontend-integration-tests[0m:	Error: An element could not be located on the page using the given search parameters (".graphNode").
[33mrun-frontend-integration-tests[0m:	    at click() - index.js:312:3
[33mrun-frontend-integration-tests[0m:	15) deploy helloworld sample run shows logs from node:
[33mrun-frontend-integration-tests[0m:	An element could not be located on the page using the given search parameters ("button=Logs").
[33mrun-frontend-integration-tests[0m:	running chrome
[33mrun-frontend-integration-tests[0m:	Error: An element could not be located on the page using the given search parameters ("button=Logs").
[33mrun-frontend-integration-tests[0m:	    at click() - index.js:312:3
[33mrun-frontend-integration-tests[0m:	16) deploy helloworld sample run creates a new run without selecting an experiment:
[33mrun-frontend-integration-tests[0m:	element (".tableRow") still not visible after 10000ms
[33mrun-frontend-integration-tests[0m:	running chrome
[33mrun-frontend-integration-tests[0m:	Error: element (".tableRow") still not visible after 10000ms
[33mrun-frontend-integration-tests[0m:	    at elements(".tableRow") - isVisible.js:54:17
[33mrun-frontend-integration-tests[0m:	    at isVisible(".tableRow") - waitForVisible.js:73:22
[33mrun-frontend-integration-tests[0m:	17) deploy helloworld sample run redirects back to all runs page:
[33mrun-frontend-integration-tests[0m:	URL was: http://localhost:3000/#/runs/new?experimentId=
[33mrun-frontend-integration-tests[0m:	running chrome
[33mrun-frontend-integration-tests[0m:	Error: URL was: http://localhost:3000/#/runs/new?experimentId=
[33mrun-frontend-integration-tests[0m:	    at getUrl() - at url() - getUrl.js:30:28
[33mrun-frontend-integration-tests[0m:	18) deploy helloworld sample run displays both runs in all runs page:
[33mrun-frontend-integration-tests[0m:	element (".tableRow") still not visible after 10000ms
[33mrun-frontend-integration-tests[0m:	running chrome
[33mrun-frontend-integration-tests[0m:	Error: element (".tableRow") still not visible after 10000ms
[33mrun-frontend-integration-tests[0m:	    at elements(".tableRow") - isVisible.js:54:17
[33mrun-frontend-integration-tests[0m:	    at isVisible(".tableRow") - waitForVisible.js:73:22
[33mrun-frontend-integration-tests[0m:	19) deploy helloworld sample run navigates back to the experiment list:
[33mrun-frontend-integration-tests[0m:	element click intercepted: Element <button class="jss35 jss9 jss11 jss14 button_f17w3f2d active_f17ohq9e" tabindex="0" type="button">...</button> is not clickable at point (110, 157). Other element would receive the click: <span class="pageName_fe4yf9p ellipsis_f15ay66x" data-testid="page-title">...</span>
[33mrun-frontend-integration-tests[0m:	running chrome
[33mrun-frontend-integration-tests[0m:	Error: Remote end send an unknown status code.
[33mrun-frontend-integration-tests[0m:	    at elementIdClick("0.8111077669779752-1") - click.js:20:22
[33mrun-frontend-integration-tests[0m:	20) deploy helloworld sample run displays both experiments in the list:
[33mrun-frontend-integration-tests[0m:	element (".tableRow") still not visible after 10000ms
[33mrun-frontend-integration-tests[0m:	running chrome
[33mrun-frontend-integration-tests[0m:	Error: element (".tableRow") still not visible after 10000ms
[33mrun-frontend-integration-tests[0m:	    at elements(".tableRow") - isVisible.js:54:17
[33mrun-frontend-integration-tests[0m:	    at isVisible(".tableRow") - waitForVisible.js:73:22
[33mrun-frontend-integration-tests[0m:	21) deploy helloworld sample run filters the experiment list:
[33mrun-frontend-integration-tests[0m:	element (".tableRow") still not visible after 10000ms
[33mrun-frontend-integration-tests[0m:	running chrome
[33mrun-frontend-integration-tests[0m:	Error: element (".tableRow") still not visible after 10000ms
[33mrun-frontend-integration-tests[0m:	    at elements(".tableRow") - isVisible.js:54:17
[33mrun-frontend-integration-tests[0m:	    at isVisible(".tableRow") - waitForVisible.js:73:22
[33mrun-frontend-integration-tests[0m:	Wrote xunit report "junit_FrontendIntegrationTestOutput.xml" to [./].
[33mrun-frontend-integration-tests[0m:	npm ERR! Test failed.  See above for more details.
[33mrun-frontend-integration-tests[0m:	+ TEST_EXIT_CODE=1
[33mrun-frontend-integration-tests[0m:	+ set -e
[33mrun-frontend-integration-tests[0m:	+ JUNIT_TEST_RESULT=junit_FrontendIntegrationTestOutput.xml
[33mrun-frontend-integration-tests[0m:	+ echo 'Copy test result to GCS gs://ml-pipeline-test/ef83ca90433a0073490d7b7fe80dd3d9116afd61/e2e_test/junit_FrontendIntegrationTestOutput.xml'
[33mrun-frontend-integration-tests[0m:	+ gsutil cp junit_FrontendIntegrationTestOutput.xml gs://ml-pipeline-test/ef83ca90433a0073490d7b7fe80dd3d9116afd61/e2e_test/junit_FrontendIntegrationTestOutput.xml
[33mrun-frontend-integration-tests[0m:	Copy test result to GCS gs://ml-pipeline-test/ef83ca90433a0073490d7b7fe80dd3d9116afd61/e2e_test/junit_FrontendIntegrationTestOutput.xml
[33mrun-frontend-integration-tests[0m:	Copying file://junit_FrontendIntegrationTestOutput.xml [Content-Type=application/xml]...
[33mrun-frontend-integration-tests[0m:	/ [0 files][    0.0 B/ 63.2 KiB]                                                
[33mrun-frontend-integration-tests[0m:	/ [1 files][ 63.2 KiB/ 63.2 KiB]                                                
[33mrun-frontend-integration-tests[0m:	Operation completed over 1 objects/63.2 KiB.                                     
[33mrun-frontend-integration-tests[0m:	+ exit 1
++ echo '========All workflows============='

**Comment by hongye-sun** [comment]
Full log: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/3566/kubeflow-pipeline-e2e-test/1252662840892854272/build-log.txt
