### ISSUE TITLE
[Cache] Watcher needs to swallow periodic errors

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#3632]
A single watcher cannot last forever in Kubernetes. It expires.

We need to handle this gracefully. Usually Go functions return `err` that can be checked. But in this case we're iterating on a channel.

https://github.com/kubeflow/pipelines/blob/de0747ec8b9a4d4a412457004b3bbac2cea2e6a4/backend/src/cache/server/watcher.go#L40

The error from logs:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1148f25]

goroutine 13 [running]:
github.com/kubeflow/pipelines/backend/src/cache/server.WatchPods(0x7ffe334cf115, 0x8, 0x164f640, 0xc00018ce40)
	/go/src/github.com/kubeflow/pipelines/backend/src/cache/server/watcher.go:40 +0xc85
created by main.main
	/go/src/github.com/kubeflow/pipelines/backend/src/cache/main.go:73 +0x3ee
```

Right before that:
```
streamwatcher.go:109 : "Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=61, ErrCode=NO_ERROR, debug="""
```

```
2020/04/26 16:38:45 Watcher error:Get https://10.15.240.1:443/api/v1/namespaces/kubeflow/pods?labelSelector=pipelines.kubeflow.org%!F(MISSING)cache_id&watch=true: dial tcp 10.15.240.1:443: connect: connection refused
```
https://pantheon.corp.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22aju-vtests2%22%0Aresource.labels.location%3D%22us-central1-c%22%0Aresource.labels.cluster_name%3D%22kfp-test2%22%0Aresource.labels.namespace_name%3D%22kubeflow%22%0Aresource.labels.pod_name%3D%22cache-server-75f88895c-7pn78%22%0Aresource.labels.container_name%3D%22server%22;timeRange=P7D?project=aju-vtests2

**Comment by Ark-kun** [comment]
A recent Argo PR demonstrates how this can be done. https://github.com/argoproj/argo/pull/2830/files#diff-6f648c894d2b64e66fb80b9367104598L167

**Comment by Ark-kun** [comment]
I think this is not a P0 since the caching service just restarts and continues to work.
But since the service should have high availability, it's better to prevent restarts.
