### ISSUE TITLE
Problem running bigquery example from ai hub

### ISSUE THREAD

**Issue by oemergenc** [kubeflow/pipelines#3640]
### What steps did you take:
Hi i am trying to execute a bigquery to google cloud storage example which can be found in the google ai hub here:

https://aihub.cloud.google.com/p/products%2F4700cd7e-2826-4ce9-a1ad-33f4a5bf7433/v/1/downloadpage
### What happened:
I downloaded the example from the ai hub and imported the zip file using the kubeflow ui. When creating a run using this pipeline i get the following error message:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/ml/kfp_component/launcher/__main__.py", line 34, in <module>
    main()
  File "/ml/kfp_component/launcher/__main__.py", line 31, in main
    launch(args.file_or_module, args.args)
  File "kfp_component/launcher/launcher.py", line 45, in launch
    return fire.Fire(module, command=args, name=module.__name__)
  File "/usr/local/lib/python2.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/usr/local/lib/python2.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/usr/local/lib/python2.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "kfp_component/google/bigquery/_query.py", line 45, in query
    client = bigquery.Client(project=project_id)
  File "/usr/local/lib/python2.7/site-packages/google/cloud/bigquery/client.py", line 142, in __init__
    project=project, credentials=credentials, _http=_http
  File "/usr/local/lib/python2.7/site-packages/google/cloud/client.py", line 224, in __init__
    Client.__init__(self, credentials=credentials, _http=_http)
  File "/usr/local/lib/python2.7/site-packages/google/cloud/client.py", line 130, in __init__
    credentials, _ = google.auth.default()
  File "/usr/local/lib/python2.7/site-packages/google/auth/_default.py", line 305, in default
    credentials, project_id = checker()
  File "/usr/local/lib/python2.7/site-packages/google/auth/_default.py", line 165, in _get_explicit_environ_credentials
    os.environ[environment_vars.CREDENTIALS])
  File "/usr/local/lib/python2.7/site-packages/google/auth/_default.py", line 98, in _load_credentials_from_file
    six.raise_from(new_exc, caught_exc)
  File "/usr/local/lib/python2.7/site-packages/six.py", line 737, in raise_from
    raise value
google.auth.exceptions.DefaultCredentialsError: ('File /secret/gcp-credentials/user-gcp-sa.json is not a valid json file.', ValueError('No JSON object could be decoded',))
```
### What did you expect to happen:
The pipeline succeeds to run and generates a file on my google cloud storage bucket and that the 
generated secret contains valid data.

### How did you deploy Kubeflow Pipelines (KFP)?
Kubeflow is deployed on GCP using the AI Platform Pipeline UI, which uses the installer from here:

https://console.cloud.google.com/marketplace/details/google-cloud-ai-platform/kubeflow-pipelines?filter=solution-type%3Ak8s&filter=price%3Afree&filter=category%3Adeveloper-tools

### Anything else you would like to add:
Looking into the kubernetes secret it seems that the definition is not correct as the Data fields seem to be empty.

```
 kubectl describe secrets user-gcp-sa
Name:         user-gcp-sa
Namespace:    default
Labels:       app=gcp-sa
              app.kubernetes.io/name=kubeflow-pipelines
Annotations:
Type:         Opaque

Data
====
application_default_credentials.json:  0 bytes
user-gcp-sa.json:                      0 bytes
```

Any hints on this would be greatly apprechiated.

/kind bug

**Comment by Bobgy** [comment]
Hi @oemergenc, you may read this documentation: https://www.kubeflow.org/docs/gke/pipelines/authentication-pipelines/.

short answer is, your cluster doesn't have `user-gcp-sa` secret. It was legacy (but still useful in some other cases), I'd recommend getting source code for the pipeline from AI Hub, remove the secret usage and run it in your cluster (your cluster uses default Compute Enginge service account, you don't need any extra setup).

**Comment by Bobgy** [comment]
Feel free to reopen if there's still anything unclear in the documentation or you met further problems

**Comment by oemergenc** [comment]
Hi, thanks for you help. I am reopening this because i still have problems in running this example.
I read the documentation in your provided link. Here is what i did:
* I downloaded the pipeline source from here: https://aihub.cloud.google.com/u/0/p/products%2F4700cd7e-2826-4ce9-a1ad-33f4a5bf7433/v/1/downloadpage
* i edited the pipeline.yaml and removed all references to the service account `user-gcp-sa`
* i repacked the edited source files to a new pipeline.zip
* i uploaded the pipeline.zip using the kubeflow web ui and started a new run

Unfortunately the pipeline still keeps in error state. Using `kubectl` i can see that corresponding pods are in error state.

Here are some logs from the pods:
Kubectl container `wait`:
```
time="2020-05-08T06:26:59Z" level=info msg="Waiting on main container"
time="2020-05-08T06:27:15Z" level=info msg="main container started with container ID: 38084e08d8e5539268d5bf75dd402822894a26acb9b5d618ee7c5255baa988e0"
time="2020-05-08T06:27:15Z" level=info msg="Starting annotations monitor"
time="2020-05-08T06:27:15Z" level=info msg="docker wait 38084e08d8e5539268d5bf75dd402822894a26acb9b5d618ee7c5255baa988e0"
time="2020-05-08T06:27:15Z" level=info msg="Starting deadline monitor"
time="2020-05-08T06:27:15Z" level=info msg="Main container completed"
time="2020-05-08T06:27:15Z" level=info msg="No sidecars"
time="2020-05-08T06:27:15Z" level=info msg="Saving output parameters"
time="2020-05-08T06:27:15Z" level=info msg="Saving path output parameter: bigquery-query-output-gcs-path"
time="2020-05-08T06:27:15Z" level=info msg="Copying /tmp/kfp/output/bigquery/query-output-path.txt from base image layer"
time="2020-05-08T06:27:15Z" level=info msg="[sh -c docker cp -a 38084e08d8e5539268d5bf75dd402822894a26acb9b5d618ee7c5255baa988e0:/tmp/kfp/output/bigquery/query-output-path.txt - | tar -ax -O]"
time="2020-05-08T06:27:15Z" level=info msg="Annotations monitor stopped"
time="2020-05-08T06:27:15Z" level=error msg="`[sh -c docker cp -a 38084e08d8e5539268d5bf75dd402822894a26acb9b5d618ee7c5255baa988e0:/tmp/kfp/output/bigquery/query-output-path.txt - | tar -ax -O]` stderr:\nError: No such container:path: 38084e08d8e5539268d5bf75dd402822894a26acb9b5d618ee7c5255baa988e0:/tmp/kfp/output/bigquery/query-output-path.txt\ntar: This does not look like a tar archive\ntar: Exiting with failure status due to previous errors\n"
time="2020-05-08T06:27:15Z" level=error msg="executor error: exit status 2\ngithub.com/argoproj/argo/errors.Wrap\n\t/go/src/github.com/argoproj/argo/errors/errors.go:88\ngithub.com/argoproj/argo/errors.InternalWrapError\n\t/go/src/github.com/argoproj/argo/errors/errors.go:71\ngithub.com/argoproj/argo/workflow/executor/docker.(*DockerExecutor).GetFileContents\n\t/go/src/github.com/argoproj/argo/workflow/executor/docker/docker.go:42\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).SaveParameters\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:412\ngithub.com/argoproj/argo/cmd/argoexec/commands.waitContainer\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:48\ngithub.com/argoproj/argo/cmd/argoexec/commands.NewWaitCommand.func1\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:16\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/src/github.com/spf13/cobra/command.go:766\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/src/github.com/spf13/cobra/command.go:852\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/src/github.com/spf13/cobra/command.go:800\nmain.main\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/main.go:17\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:201\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1333"
time="2020-05-08T06:27:15Z" level=info msg="Alloc=4147 TotalAlloc=10975 Sys=70078 NumGC=4 Goroutines=8"
time="2020-05-08T06:27:15Z" level=fatal msg="exit status 2\ngithub.com/argoproj/argo/errors.Wrap\n\t/go/src/github.com/argoproj/argo/errors/errors.go:88\ngithub.com/argoproj/argo/errors.InternalWrapError\n\t/go/src/github.com/argoproj/argo/errors/errors.go:71\ngithub.com/argoproj/argo/workflow/executor/docker.(*DockerExecutor).GetFileContents\n\t/go/src/github.com/argoproj/argo/workflow/executor/docker/docker.go:42\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).SaveParameters\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:412\ngithub.com/argoproj/argo/cmd/argoexec/commands.waitContainer\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:48\ngithub.com/argoproj/argo/cmd/argoexec/commands.NewWaitCommand.func1\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:16\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/src/github.com/spf13/cobra/command.go:766\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/src/github.com/spf13/cobra/command.go:852\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/src/github.com/spf13/cobra/command.go:800\nmain.main\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/main.go:17\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:201\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1333"
```

kubectl container `main`:
```
INFO:root:Fetching latest pod metadata: bigquery-query-pipeline-fqbqm-1081813438.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/ml/kfp_component/launcher/__main__.py", line 34, in <module>
    main()
  File "/ml/kfp_component/launcher/__main__.py", line 31, in main
    launch(args.file_or_module, args.args)
  File "kfp_component/launcher/launcher.py", line 45, in launch
    return fire.Fire(module, command=args, name=module.__name__)
  File "/usr/local/lib/python2.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/usr/local/lib/python2.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/usr/local/lib/python2.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "kfp_component/google/bigquery/_query.py", line 54, in query
    with KfpExecutionContext(on_cancel=cancel) as ctx:
  File "kfp_component/core/_kfp_execution_context.py", line 42, in __init__
    self._load_kfp_environment()
  File "kfp_component/core/_kfp_execution_context.py", line 88, in _load_kfp_environment
    self._argo_node_name = self._get_argo_node_name()
  File "kfp_component/core/_kfp_execution_context.py", line 94, in _get_argo_node_name
    pod = self._get_pod()
  File "kfp_component/core/_kfp_execution_context.py", line 152, in _get_pod
    self._pod_name, KF_NAMESPACE)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 18463, in read_namespaced_pod
    (data) = self.read_namespaced_pod_with_http_info(name, namespace, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 18554, in read_namespaced_pod_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 342, in request
    headers=headers)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Date': 'Fri, 08 May 2020 06:27:15 GMT', 'Audit-Id': 'f2a5ebf6-dff7-4964-9e7c-e2672ee3642a', 'Content-Length': '248', 'Content-Type': 'application/json'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"bigquery-query-pipeline-fqbqm-1081813438\" not found","reason":"NotFound","details":{"name":"bigquery-query-pipeline-fqbqm-1081813438","kind":"pods"},"code":404}
```

In the log of the `wait` container especially this log line looks to me suspicious:

```
time="2020-05-08T06:27:15Z" level=error msg="`[sh -c docker cp -a 38084e08d8e5539268d5bf75dd402822894a26acb9b5d618ee7c5255baa988e0:/tmp/kfp/output/bigquery/query-output-path.txt - | tar -ax -O]` 
stderr:\nError: No such container:path: 38084e08d8e5539268d5bf75dd402822894a26acb9b5d618ee7c5255baa988e0:/tmp/kfp/output/bigquery/query-output-path.txt\ntar: 
This does not look like a tar archive\ntar: Exiting with failure status due to previous errors\n"
```

Please also note that i am able to run the following pod in my cluster and execute a simple 
`gcloud auth list` or `bq ls`. Therefore i guess the authentication setup seems to be correct.

```
kubectl run --rm -it --generator=run-pod/v1 --image google/cloud-sdk:slim --serviceaccount default --namespace default simple-gcloud-test
```

**Comment by oemergenc** [comment]
@Bobgy unfortunately i am not able to reopen this issue, should i create a new one or can we stay with this one?

**Comment by Bobgy** [comment]
/reopen
taking a look

**Comment by Bobgy** [comment]
@oemergenc instead of patching `pipeline.yaml`, you should better use the sample notebook to run the pipeline (because pipeline.yaml is a generated asset not intended for human editing): https://github.com/kubeflow/pipelines/blob/master/components/gcp/bigquery/query/sample.ipynb

**Comment by Bobgy** [comment]
The error message come from Kubernetes api server, it doesn't fail at authenticating to Google Cloud, so I think your patches did change sth, but I think it wasn't completely correct. Can you try the notebook above instead?

**Comment by oemergenc** [comment]
Could you provide me some guidance or documentation on how i can use this notebook? I am pretty new to using Kubeflow. I am using the AI Plattform provided by the Google Cloud Platform.

I deployed my Kubeflow Cluster using the Marketplace installer from here:
https://console.cloud.google.com/marketplace/details/google-cloud-ai-platform/kubeflow-pipelines

This version of Kubeflow does not seem to have an integrated notebook server instead i can use the one provided by the AI Plattform which works and also give the possibility to query big query datasets. 

However at the end i am interested in running a Kubeflow Pipeline not a notebook. This Kubeflow pipeline should read a bigquery dataset and store the result in google cloud storage. The final version will be much more complicated than this, therefore running a Notebook does not meet all my requirements.

**Comment by Bobgy** [comment]
@oemergenc Understood, let me explain quickly here. I think that's probably something we should document better.
The sample: https://github.com/kubeflow/pipelines/blob/master/components/gcp/bigquery/query/sample.ipynb has a few steps, it builds a pipeline using kfp dsl and then compiles the pipeline to a package (locally, so you can see the file) and runs the package on your cluster directly using kfp client. documented here: https://cloud.google.com/ai-platform/pipelines/docs/connecting-with-sdk, you can specify the host parameter to connect to your own cluster.

For what you want, just stop at the compile pipeline step, you should see a .zip package in your working dir. You can upload it in KFP UI and start runs on UI. (or you can also upload the package as a pipeline through client SDK https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.client.html#kfp.Client.upload_pipeline)

**Comment by Bobgy** [comment]
and for the notebook, you may choose the managed notebook or your local notebook, both works
and the Kubeflow pipelines will run in your cluster

**Comment by oemergenc** [comment]
Hi, 

thank you for your detailed instructions and your patience with me ;-)

I hope if i ask you one more question, which seems to be really simple.
How can i compile the notebook locally? 
Here is what i did so far:

* clone this repository
* create a venv environment
* installed kubeflow sdk into the venv using the instructions from here: https://www.kubeflow.org/docs/pipelines/sdk/install-sdk/
* tried to compile the notebook locally using this: 
`dsl-compile --py ./sample.ipynb --output ./output`

This unfortunately results in the following error message:
```
ModuleNotFoundError: No module named 'sample'
```

Thanks in advance.

**Comment by Bobgy** [comment]
@oemergenc, no worries.

`dsl-compile` doesn't work with notebooks, it only supports python files.

The `compiler.Compiler().compile(pipeline_func, pipeline_filename)` code in the ipynb notebook is an alternative approach to compile the pipeline. (equivalent to calling cli `dsl-compile`). You can just run that notebook locally.

@numerology @Ark-kun Are confusions here documented anywhere? Can we improve something?

**Comment by oemergenc** [comment]
@Bobgy  thank you very much for your help. Finally i was able to run this example succesfully.

For anyone coming to this, here is what i did:

- clone this repository
- create a venv environment
- installed kubeflow sdk into the venv using the instructions from here: https://www.kubeflow.org/docs/pipelines/sdk/install-sdk/
- create a component.py python file with the code from sample.ipynb upto the compile step, like this
```
import kfp.compiler as compiler
import kfp.components as comp
import kfp.dsl as dsl

bigquery_query_op = comp.load_component_from_url(
    'https://raw.githubusercontent.com/kubeflow/pipelines/01a23ae8672d3b18e88adf3036071496aca3552d/components/gcp/bigquery/query/component.yaml')
help(bigquery_query_op)

QUERY = 'SELECT * FROM `bigquery-public-data.stackoverflow.posts_questions` LIMIT 10'
PROJECT_ID = 'PROJECT_ID'
DATASET_ID = 'DATASET_ID'
TABLE_ID = 'TABLE_ID'
GCS_WORKING_DIR = 'gs://your/bucket/path'  # No ending slash
EXPERIMENT_NAME = 'Bigquery -Query'
OUTPUT_PATH = '{}/bigquery/query/questions.csv'.format(GCS_WORKING_DIR)


@dsl.pipeline(
    name='Bigquery query pipeline',
    description='Bigquery query pipeline'
)
def pipeline(
        query=QUERY,
        project_id=PROJECT_ID,
        dataset_id=DATASET_ID,
        table_id=TABLE_ID,
        output_gcs_path=OUTPUT_PATH,
        dataset_location='US',
        job_config=''
):
    bigquery_query_op(
        query=query,
        project_id=project_id,
        dataset_id=dataset_id,
        table_id=table_id,
        output_gcs_path=output_gcs_path,
        dataset_location=dataset_location,
        job_config=job_config)


pipeline_func = pipeline
pipeline_filename = pipeline_func.__name__ + '.zip'

compiler.Compiler().compile(pipeline_func, pipeline_filename)
```
- execute this command: `dsl-compile --py component.py --output ./output/pipeline.zip`
- upload this zip file in the kubeflow web ui and create a run

I also needed to make sure your compute engine default service account has the following roles:

```
gcloud projects add-iam-policy-binding YOUR_PROJECT --member=serviceAccount:YOUR_SA@developer.gserviceaccount.com --role=roles/storage.admin
gcloud projects add-iam-policy-binding YOUR_PROJECT --member=serviceAccount:YOUR_SA@developer.gserviceaccount.com --role=roles/bigquery.admin
```
