### ISSUE TITLE
Using Pipeline parameters in metadata

### ISSUE THREAD

**Issue by ksonbol** [kubeflow/pipelines#4019]
### What steps did you take:
Create this component file `hello_component.yaml`
```
name: Hello component
description: Prints hello world
inputs:
- {name: input_1, type: String, description: 'Data for Input 1'}
metadata:
  annotations:
    my_annot: {inputValue: input_1}
implementation:
  container:
    image: image="library/bash:4.4.23",
    command: [sh, -c]
    args: ["echo", "hello, world!"]
```
and this pipeline file `hello_pipeline.py`
```
import kfp
from kfp import dsl

hello_op = kfp.components.load_component_from_file('hello_component.yaml')

@dsl.pipeline(
    name="Hello World Pipeline",
    description="This pipeline prints hello, world!")
def hello_pipeline():
    hello_op(input_1='my input') 
```

Try to compile the pipeline with:
`dsl-compile --py hello_pipeline.py --output hello_pipeline.yaml`

### What happened:
I receive this error,
```
Traceback (most recent call last):
  File "/Users/karim.sonbol/venv/bin/dsl-compile", line 8, in <module>
    sys.exit(main())
  File "/Users/karim.sonbol/venv/lib/python3.7/site-packages/kfp/compiler/main.py", line 148, in main
    not args.disable_telemetry
  File "/Users/karim.sonbol/venv/lib/python3.7/site-packages/kfp/compiler/main.py", line 129, in compile_pyfile
    __import__(os.path.splitext(filename)[0])
  File "hello_pipeline.py", line 4, in <module>
    hello_op = kfp.components.load_component_from_file('hello_component.yaml')
  File "/Users/karim.sonbol/venv/lib/python3.7/site-packages/kfp/components/_components.py", line 98, in load_component_from_file
    component_spec = _load_component_spec_from_file(path=filename)
  File "/Users/karim.sonbol/venv/lib/python3.7/site-packages/kfp/components/_components.py", line 132, in _load_component_spec_from_file
    return _load_component_spec_from_yaml_or_zip_stream(component_stream)
  File "/Users/karim.sonbol/venv/lib/python3.7/site-packages/kfp/components/_components.py", line 172, in _load_component_spec_from_yaml_or_zip_stream
    return _load_component_spec_from_component_text(stream)
  File "/Users/karim.sonbol/venv/lib/python3.7/site-packages/kfp/components/_components.py", line 177, in _load_component_spec_from_component_text
    component_spec = ComponentSpec.from_dict(component_dict)
  File "/Users/karim.sonbol/venv/lib/python3.7/site-packages/kfp/components/modelbase.py", line 273, in from_dict
    return parse_object_from_struct_based_on_class_init(cls, struct, serialized_names=cls._serialized_names)
  File "/Users/karim.sonbol/venv/lib/python3.7/site-packages/kfp/components/modelbase.py", line 226, in parse_object_from_struct_based_on_class_init
    args[python_name] = parse_object_from_struct_based_on_type(value, param_type)
  File "/Users/karim.sonbol/venv/lib/python3.7/site-packages/kfp/components/modelbase.py", line 150, in parse_object_from_struct_based_on_type
    raise TypeError('\n'.join(exception_lines))
TypeError: Error: MetadataSpec.from_dict(struct=OrderedDict([('annotations', OrderedDict([('my_annot, OrderedDict([('inputValue', 'input_1')]))]))])) failed with exception:
Error: Structure "OrderedDict([('inputValue', 'input_1')])" is incompatible with type "<class 'str'>". Structure is not the instance of the type, the type does not have .from_dict method and is not generic.
Error: Structure "OrderedDict([('my_annot', OrderedDict([('inputValue', 'input_1')]))])" is not None.
Error: Structure "OrderedDict([('my_annot', OrderedDict([('inputValue', 'input_1')]))])" is incompatible with type "typing.Union[typing.Dict[str, str], NoneType]" - none of the types in Union are compatible.
Error: Structure "OrderedDict([('annotations', OrderedDict([('my_annot', OrderedDict([('inputValue', 'input_1')]))]))])" is not None.
Error: Structure "OrderedDict([('annotations', OrderedDict([('my_annot', OrderedDict([('inputValue', 'input_1')]))]))])" is incompatible with type "typing.Union[kfp.components._structures.MetadataSpec, NoneType]" - none of the types in Union are compatible.
```
### What did you expect to happen:
A successful compilation to YAML.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

Did not deploy, just compiling the pipeline file fails.

KFP version: 
NA

KFP SDK version: 
0.5.1

### Anything else you would like to add:
It seems annotations are not able to handle inputs correctly as shown by this line:

```
Error: Structure "OrderedDict([('inputValue', 'input_1')])" is incompatible with type "<class 'str'>". Structure is not the instance of the type, the type does not have .from_dict method and is not generic.
```

/kind bug

**Comment by Ark-kun** [comment]
This is by design. The component annotations are currently supposed to be static.
And the fact that component annotations are translated to Kubernetes pod annotations might be considered a design mistake.
Components are designed to be portable and they have no Kubernetes-specific features.

But you can add Kubernetes-specific customizations to tasks (component instances).
You can add pod annotation to a task using `add_pod_annotation`:

```python
def hello_pipeline(input_annotation: str):
    hello_task = hello_op()
    hello_task.add_pod_annotation('my_annotation', input_annotation)
```

**Comment by ksonbol** [comment]
Thanks, that works fine and is exactly what I needed.

**Comment by Ark-kun** [comment]
> Thanks, that works fine and is exactly what I needed.

Great!
