### ISSUE TITLE
Metadata Writer can get stuck

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#4036]
I've seen a case where Metadata writer was working successfully for a while, (some restarts when Kubernetes watch has ended), but then just stopped doing anything. Usually it lists any new pods it sees, but it has stopped doing printing anything to the logs.

Version: Marketplace 0.5.1 manually upgraded to 0.5.2

Investigating...

Maybe I need to put timeout in the watch.

**Comment by Ark-kun** [comment]
Got a traceback of what the stuck process was doing today. As expected it's Kubernetes watch reading from a network connection:

```
Traceback (most recent call last):
  File "/kfp/metadata_writer/metadata_writer.py", line 131, in <module>
    label_selector=ARGO_WORKFLOW_LABEL_KEY,
  File "/usr/local/lib/python3.7/site-packages/kubernetes/watch/watch.py", line 144, in stream
    for line in iter_resp_lines(resp):
  File "/usr/local/lib/python3.7/site-packages/kubernetes/watch/watch.py", line 48, in iter_resp_lines
    for seg in resp.read_chunked(decode_content=False):
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 752, in read_chunked
    self._update_chunk_length()
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 682, in _update_chunk_length
    line = self._fp.fp.readline()
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
```
