### ISSUE TITLE
kfp.Client: Can't specify localhost host

### ISSUE THREAD

**Issue by discordianfish** [kubeflow/pipelines#4277]
### What steps did you take:
```
client = kfp.Client(host="http://localhost:8888")
...
client.upload_pipeline(filename, name, description)
```

### What happened:
```
Traceback (most recent call last):
  File "../kubeflow-apply/kubeflow-apply.py", line 73, in <module>
    args.func()
  File "../kubeflow-apply/kubeflow-apply.py", line 33, in pipelines
    self.client.upload_pipeline(filename, name, description)
  File "/usr/local/lib/python3.8/site-packages/kfp/_client.py", line 723, in upload_pipeline
    response = self._upload_api.upload_pipeline(pipeline_package_path, name=pipeline_name, description=description)
  File "/usr/local/lib/python3.8/site-packages/kfp_server_api/api/pipeline_upload_service_api.py", line 83, in upload_pipeline
    return self.upload_pipeline_with_http_info(uploadfile, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.8/site-packages/kfp_server_api/api/pipeline_upload_service_api.py", line 177, in upload_pipeline_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 379, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 196, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 422, in request
    return self.rest_client.POST(url,
  File "/usr/local/lib/python3.8/site-packages/kfp_server_api/rest.py", line 279, in POST
    return self.request("POST", url,
  File "/usr/local/lib/python3.8/site-packages/kfp_server_api/rest.py", line 196, in request
    r = self.pool_manager.request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/request.py", line 79, in request
    return self.request_encode_body(
  File "/usr/local/lib/python3.8/site-packages/urllib3/request.py", line 172, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.8/site-packages/urllib3/poolmanager.py", line 326, in urlopen
    conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
  File "/usr/local/lib/python3.8/site-packages/urllib3/poolmanager.py", line 231, in connection_from_host
    raise LocationValueError("No host specified.")
urllib3.exceptions.LocationValueError: No host specified.
```
### What did you expect to happen:
Being able to specify the host

### Environment:
KFP SDK version: 1.0.0

### Anything else you would like to add:
The problem is that for unclear reasons kfp strips the schema from the url, causing urllib3's parse_url to interpret the 'localhost' part as schema. This was working with kfp==0.1.31

**Comment by Bobgy** [comment]
also
/cc @numerology

**Comment by discordianfish** [comment]
This has been broken since 0.4.0 with 0.3.0 working. So must be something in https://github.com/kubeflow/pipelines/compare/0.3.0...0.4.0

**Comment by rmgogogo** [comment]
```
import kfp
client = kfp.Client(host='https://19b3ea4f841c52a3-dot-us-central2.pipelines.googleusercontent.com')
client.list_pipelines()
```

I tested it and it works well.

Do you mean localhost?

**Comment by rmgogogo** [comment]
to be fixed in https://github.com/kubeflow/pipelines/pull/4285

**Comment by nlarusstone** [comment]
This is a blocking issue for us -- is there a plan to release a patch for `1.0.0`?

**Comment by Bobgy** [comment]
@nlarusstone 1.0.1 will be released in a week
