### ISSUE TITLE
Executing pipeline with non-default SA, fails to start

### ISSUE THREAD

**Issue by sbakiu** [kubeflow/pipelines#4288]
### What steps did you take:
When trying to execut pipeline with another service account, exectution fails. However, executing the same pipeline with the default `pipeline-runner` SA is successful. 

### What happened:
Pipeline fails with the following error message:
```
time="2020-07-29T13:33:44Z" level=info msg="Starting Workflow Executor" version=v2.7.5+ede163e.dirty
panic: invalid configuration: no configuration has been provided

goroutine 1 [running]:
github.com/argoproj/argo/cmd/argoexec/commands.checkErr(0x1f29c80, 0xc0004bade0)
	/go/src/github.com/argoproj/argo/cmd/argoexec/commands/root.go:112 +0xee
github.com/argoproj/argo/cmd/argoexec/commands.initExecutor(0xa)
	/go/src/github.com/argoproj/argo/cmd/argoexec/commands/root.go:72 +0x146
github.com/argoproj/argo/cmd/argoexec/commands.waitContainer(0x0, 0x0)
	/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:26 +0x42
github.com/argoproj/argo/cmd/argoexec/commands.NewWaitCommand.func1(0xc00016af00, 0x2d2e670, 0x0, 0x0)
	/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:16 +0x26
github.com/spf13/cobra.(*Command).execute(0xc00016af00, 0x2d2e670, 0x0, 0x0, 0xc00016af00, 0x2d2e670)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20181021141114-fe5e611709b0/command.go:766 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc00016a780, 0xc00005a750, 0xc0005f5f50, 0x40576f)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20181021141114-fe5e611709b0/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20181021141114-fe5e611709b0/command.go:800
main.main()
	/go/src/github.com/argoproj/argo/cmd/argoexec/main.go:17 +0x2b
```

Log message from `workflow-controller`:
```
ime="2020-07-29T13:33:41Z" level=info msg="Created pod: foodgraph-training-xltmc.extract-config (foodgraph-training-xltmc-4276779115)" namespace=kubeflow workflow=foodgraph-training-xltmc
time="2020-07-29T13:33:41Z" level=info msg="Workflow update successful" namespace=kubeflow phase=Running resourceVersion=19155139 workflow=foodgraph-training-xltmc
time="2020-07-29T13:33:42Z" level=info msg="Processing workflow" namespace=kubeflow workflow=foodgraph-training-xltmc
time="2020-07-29T13:33:42Z" level=info msg="Updating node &NodeStatus{ID:foodgraph-training-xltmc-4276779115,Name:foodgraph-training-xltmc.extract-config,DisplayName:extract-config,Type:Pod,TemplateName:extract-config,TemplateRef:nil,Phase:Pending,BoundaryID:foodgraph-training-xltmc,Message:,StartedAt:2020-07-29 13:33:11 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} message: ContainerCreating"
time="2020-07-29T13:33:42Z" level=info msg="Workflow update successful" namespace=kubeflow phase=Running resourceVersion=19155147 workflow=foodgraph-training-xltmc
time="2020-07-29T13:33:43Z" level=info msg="Processing workflow" namespace=kubeflow workflow=foodgraph-training-xltmc
time="2020-07-29T13:33:48Z" level=info msg="Processing workflow" namespace=kubeflow workflow=foodgraph-training-xltmc
time="2020-07-29T13:33:48Z" level=info msg="Updating node &NodeStatus{ID:foodgraph-training-xltmc-4276779115,Name:foodgraph-training-xltmc.extract-config,DisplayName:extract-config,Type:Pod,TemplateName:extract-config,TemplateRef:nil,Phase:Pending,BoundaryID:foodgraph-training-xltmc,Message:ContainerCreating,StartedAt:2020-07-29 13:33:11 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} status Pending -> Error"
time="2020-07-29T13:33:48Z" level=info msg="Updating node &NodeStatus{ID:foodgraph-training-xltmc-4276779115,Name:foodgraph-training-xltmc.extract-config,DisplayName:extract-config,Type:Pod,TemplateName:extract-config,TemplateRef:nil,Phase:Error,BoundaryID:foodgraph-training-xltmc,Message:,StartedAt:2020-07-29 13:33:11 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} message: failed to save outputs: invalid configuration: no configuration has been provided"
time="2020-07-29T13:33:48Z" level=info msg=catch-config namespace=kubeflow workflow=foodgraph-training-xltmc
time="2020-07-29T13:33:48Z" level=info msg="Outbound nodes of foodgraph-training-xltmc set to []" namespace=kubeflow workflow=foodgraph-training-xltmc
time="2020-07-29T13:33:48Z" level=info msg="node &NodeStatus{ID:foodgraph-training-xltmc,Name:foodgraph-training-xltmc,DisplayName:foodgraph-training-xltmc,Type:DAG,TemplateName:foodgraph-training,TemplateRef:nil,Phase:Running,BoundaryID:,Message:,StartedAt:2020-07-29 13:33:11 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[foodgraph-training-xltmc-4276779115],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} phase Running -> Error" namespace=kubeflow workflow=foodgraph-training-xltmc
time="2020-07-29T13:33:48Z" level=info msg="node &NodeStatus{ID:foodgraph-training-xltmc,Name:foodgraph-training-xltmc,DisplayName:foodgraph-training-xltmc,Type:DAG,TemplateName:foodgraph-training,TemplateRef:nil,Phase:Error,BoundaryID:,Message:,StartedAt:2020-07-29 13:33:11 +0000 UTC,FinishedAt:2020-07-29 13:33:48.312078979 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[foodgraph-training-xltmc-4276779115],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} finished: 2020-07-29 13:33:48.312078979 +0000 UTC" namespace=kubeflow workflow=foodgraph-training-xltmc
time="2020-07-29T13:33:48Z" level=info msg="Checking daemoned children of foodgraph-training-xltmc" namespace=kubeflow workflow=foodgraph-training-xltmc
time="2020-07-29T13:33:48Z" level=info msg="Updated phase Running -> Error" namespace=kubeflow workflow=foodgraph-training-xltmc
time="2020-07-29T13:33:48Z" level=info msg="Marking workflow completed" namespace=kubeflow workflow=foodgraph-training-xltmc
time="2020-07-29T13:33:48Z" level=error msg="Unable to create audit event: events is forbidden: User \"system:serviceaccount:kubeflow:argo\" cannot create resource \"events\" in API group \"\" in the namespace \"kubeflow\"" reason=WorkflowFailed type=Warning workflow=foodgraph-training-xltmc
time="2020-07-29T13:33:48Z" level=info msg="Checking daemoned children of " namespace=kubeflow workflow=foodgraph-training-xltmc
time="2020-07-29T13:33:48Z" level=info msg="Workflow update successful" namespace=kubeflow phase=Error resourceVersion=19155184 workflow=foodgraph-training-xltmc
time="2020-07-29T13:33:49Z" level=info msg="Labeled pod kubeflow/foodgraph-training-xltmc-4276779115 completed"
```
### What did you expect to happen:
Expected the pipeline to succeed 

### Environment:
GCP Private GKE cluster

How did you deploy Kubeflow Pipelines (KFP)?
Standalone deployment

KFP version: 1.0.0

KFP SDK version: 

### Anything else you would like to add:
I added the minimal permissions defined: [here](https://github.com/argoproj/argo/blob/v2.3.0/docs/workflow-rbac.md) to the custom SA.
The following argo project [issue](https://github.com/argoproj/argo/issues/2793) seems related, but it should be solved already. Maybe upgrading argoexec to a newer version might solve this

UPDATE:

After some more testing, executing the pipeline with `default` SA successed also. However, with my custom SA, named `kubeflow-sa` it fails with the above error. Can it me the naming of the SA causing this error? Also `kubeflow-sa` is linked to a google service account, in case it is relevant.

/kind bug

**Comment by Bobgy** [comment]
Not sure, can you verify If your custom sa got all required permissions correctly?

kubectl auth command help Do that.

There should be nothing related to naming

**Comment by Bobgy** [comment]
Can you verify running the workflow using argo directly? If it fails without KFP, it can be an argo problem

**Comment by sbakiu** [comment]
Seems like the problem is how the service accounts are created by our infrstructure team. Not sure exactly what the problem is. Anyways, closing the issue
