### ISSUE TITLE
AssertionError [ERR_ASSERTION]: logs do not look right: 1

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#453]
https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/430/presubmit-e2e-test/630/

```
run-frontend-integration-tests:	․․․․․․Handling connection for 3000
run-frontend-integration-tests:	F22:40:04.744 INFO [ActiveSessions$1.onStop] - Removing session 0fba00219d7e59cb2f76e1d38031312a (org.openqa.selenium.chrome.ChromeDriverService)
run-frontend-integration-tests:	15 passing (34.10s)
run-frontend-integration-tests:	1 failing
run-frontend-integration-tests:	1) deploy helloworld sample run shows logs from node:
run-frontend-integration-tests:	logs do not look right: 1
run-frontend-integration-tests:	running chrome
run-frontend-integration-tests:	AssertionError [ERR_ASSERTION]: logs do not look right: 1
run-frontend-integration-tests:	    at Context.it (/src/helloworld.spec.js:169:5)
run-frontend-integration-tests:	    at new Promise (<anonymous>)
run-frontend-integration-tests:	    at new F (/src/node_modules/core-js/library/modules/_export.js:36:28)
run-frontend-integration-tests:	Wrote xunit report "junit_FrontendIntegrationTestOutput.xml" to [./].
run-frontend-integration-tests:	npm ERR! Test failed.  See above for more details.
```

**Comment by Ark-kun** [comment]
I'm seeing this flaky error quite often.

**Comment by yebrahim** [comment]
I hope https://github.com/kubeflow/pipelines/pull/459 fixes it. Will run it a few times before merging.
