### ISSUE TITLE
Error 401 (Unauthorized)!!1 for run_pipeline()

### ISSUE THREAD

**Issue by montenegrodr** [kubeflow/pipelines#4624]
### What steps did you take:
Created a kfp_client providing host and existing_token (also tested without the latter). 

### What happened:

It runs on k8s, first 5-10 minutes requests are working fine. After some time it starts returning **Error 401 (Unauthorized)!!1** for **run_pipeline()**.

### What did you expect to happen:

Create a pipeline run successfully.

### Environment:
GCP
Kubernetes
Kubeflow pipelines 1.0.0
Python 3.7

How did you deploy Kubeflow Pipelines (KFP)?
Managed Service at GCP

KFP version: 1.0.0

KFP SDK version: 1.0.1

### Anything else you would like to add:

```
2020-10-13 06:52:58.573 ERROR grpc._server - Exception calling application: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Length': '1452', 'Content-Type': 'text/html; charset=utf-8', 'Date': 'Tue, 13 Oct 2020 06:52:58 GMT', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '0', 'Set-Cookie': 'S=cloud_datalab_tunnel=; Path=/; Max-Age=3600'})
HTTP response body: 
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 401 (Unauthorized)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>401.</b> <ins>That’s an error.</ins>
  <p>  <ins>That’s all we know.</ins>

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/grpc/_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "my_lib/run.py", line 169, in wrapped
    return method(self, request, context)
  File "my_lib/run.py", line 187, in FOO
    run_id = self.pipeline_mgr.start_pipeline(request)
  File "/app/my_lib/pipeline_manager.py", line 33, in start_pipeline
    "banner_id": args.banner_ids[0],
  File "/usr/local/lib/python3.7/site-packages/kfp/_client.py", line 433, in run_pipeline
    response = self._run_api.create_run(body=run_body)
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api/run_service_api.py", line 201, in create_run
    return self.create_run_with_http_info(body, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api/run_service_api.py", line 299, in create_run_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 383, in call_api
    _preload_content, _request_timeout, _host)
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 202, in __call_api
    raise e
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 199, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 427, in request
    body=body)
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/rest.py", line 285, in POST
    body=body)
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/rest.py", line 238, in request
    raise ApiException(http_resp=r)
kfp_server_api.exceptions.ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Length': '1452', 'Content-Type': 'text/html; charset=utf-8', 'Date': 'Tue, 13 Oct 2020 06:52:58 GMT', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '0', 'Set-Cookie': 'S=cloud_datalab_tunnel=; Path=/; Max-Age=3600'})
HTTP response body: 
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 401 (Unauthorized)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>401.</b> <ins>That’s an error.</ins>
  <p>  <ins>That’s all we know.</ins>

```
/kind bug

**Comment by montenegrodr** [comment]
`kf_client._refresh_api_client_token()` seems to workaround.

**Comment by montenegrodr** [comment]
ping

**Comment by akiyamasho** [comment]
This still happens to me. my replication steps are a little strange however:

1. I was connected to a different AI platform pipelines version (KFP A) and tried connecting to a new one (KFP B)
2. Running any `kfp` command via python or bash gives me `401 unauthorized`
3. Run `gcloud auth revoke` on all accounts and run `gcloud auth init` to refresh gcloud settings
4. Reinstall `kfp` via `pip`
5. Issue still happens

I tried on a different device, and it works. I'm not sure if `kfp` is caching credentials somewhere.
