### ISSUE TITLE
Bug in pipeline samples' parameters

### ISSUE THREAD

**Issue by nikhilsharma93** [kubeflow/pipelines#478]
https://github.com/kubeflow/pipelines/blob/master/samples/basic/parallel_join.py#L25-L26 are not a `dsl.PipelineParam` as they should be

**Comment by gaoning777** [comment]
This is one of the features we shipped recently. Users can specify the parameters directly(url='hello') instead of using PipelineParam class.
If it is not working for you, try the newest version SDK, please.

**Comment by nikhilsharma93** [comment]
I upgraded my SDK (`pip3 install https://storage.googleapis.com/ml-pipeline/release/0.1.2/kfp.tar.gz --upgrade`), which is now at `kfp-0.1`

But I still get this error when I try to compile that file:

```
Traceback (most recent call last):
  File "/home/nikhil/.virtualenvs/python_3_5/venp35/bin/dsl-compile", line 11, in <module>
    sys.exit(main())
  File "/home/nikhil/.virtualenvs/python_3_5/venp35/lib/python3.5/site-packages/kfp/compiler/main.py", line 100, in main
    compile_pyfile(args.py, args.function, args.output)
  File "/home/nikhil/.virtualenvs/python_3_5/venp35/lib/python3.5/site-packages/kfp/compiler/main.py", line 89, in compile_pyfile
    _compile_pipeline_function(function_name, output_path)
  File "/home/nikhil/.virtualenvs/python_3_5/venp35/lib/python3.5/site-packages/kfp/compiler/main.py", line 69, in _compile_pipeline_function
    kfp.compiler.Compiler().compile(pipeline_func, output_path)
  File "/home/nikhil/.virtualenvs/python_3_5/venp35/lib/python3.5/site-packages/kfp/compiler/compiler.py", line 526, in compile
    workflow = self._compile(pipeline_func)
  File "/home/nikhil/.virtualenvs/python_3_5/venp35/lib/python3.5/site-packages/kfp/compiler/compiler.py", line 491, in _compile
    self._validate_args(argspec)
  File "/home/nikhil/.virtualenvs/python_3_5/venp35/lib/python3.5/site-packages/kfp/compiler/compiler.py", line 465, in _validate_args
    'Default values of argument has to be type dsl.PipelineParam or its child.')
ValueError: Default values of argument has to be type dsl.PipelineParam or its child.
```

**Comment by gaoning777** [comment]
Could you try the newest version: pip3 install https://storage.googleapis.com/ml-pipeline/release/0.1.3-rc.3/kfp.tar.gz --upgrade. It works at my end.

**Comment by nikhilsharma93** [comment]
Yes, that works. Thank you
