### ISSUE TITLE
GCS Component input type is incompatible with `str` or `dsl.types.GCSPath`

### ISSUE THREAD

**Issue by xinbinhuang** [kubeflow/pipelines#4794]
### What steps did you take:

cc: @Ark-kun 

GCS component operation accepts type `URI` but it does not work well with either `str` or `dsl.types.GCSPath` on pipeline function type annotations. If I remove  the pipeline type annotation, it will still work

Testing script:

```python
import kfp
from kfp import components, dsl

download_from_gcs_op = components.load_component_from_url(
    "https://raw.githubusercontent.com/kubeflow/pipelines/master/components/google-cloud/storage/download_blob/component.yaml"
)


@dsl.pipeline(name="Test download")
def download_gcs_pipeline(gcs_uri: str):
    download_task = download_from_gcs_op(gcs_uri)


if __name__ == "__main__":

    print("Submit pipeline to run!")
    client = kfp.Client()
    test_run = client.create_run_from_pipeline_func(
        download_gcs_pipeline,
        experiment_name='Test exp',
        arguments={
            "gcs_uri": "gs://ml-pipeline/sample-data/shakespeare/shakespeare1.txt",
        }
    )
    print(f"Run ID: {test_run.run_id}")
```

### What happened:
```bash
Submit pipeline to run!
type name String is different from expected: URI
Traceback (most recent call last):
  File "pipelines/test_ppl.py", line 18, in <module>
    test_run = client.create_run_from_pipeline_func(
  File "/home/guava/.cache/pypoetry/virtualenvs/kfp-pipelines-aTzueVjq-py3.8/lib/python3.8/site-packages/kfp/_client.py", line 556, in create_run_from_pipeline_func
    compiler.Compiler().compile(pipeline_func, pipeline_package_path, pipeline_conf=pipeline_conf)
  File "/home/guava/.cache/pypoetry/virtualenvs/kfp-pipelines-aTzueVjq-py3.8/lib/python3.8/site-packages/kfp/compiler/compiler.py", line 902, in compile
    self._create_and_write_workflow(
  File "/home/guava/.cache/pypoetry/virtualenvs/kfp-pipelines-aTzueVjq-py3.8/lib/python3.8/site-packages/kfp/compiler/compiler.py", line 955, in _create_and_write_workflow
    workflow = self._create_workflow(
  File "/home/guava/.cache/pypoetry/virtualenvs/kfp-pipelines-aTzueVjq-py3.8/lib/python3.8/site-packages/kfp/compiler/compiler.py", line 804, in _create_workflow
    pipeline_func(*args_list)
  File "pipelines/test_ppl.py", line 11, in download_gcs_pipeline
    download_task = download_from_gcs_op(gcs_uri)
  File "https://raw.githubusercontent.com/kubeflow/pipelines/master/components/google-cloud/storage/download_blob/component.yaml", line 2, in Download from GCS
  File "/home/guava/.cache/pypoetry/virtualenvs/kfp-pipelines-aTzueVjq-py3.8/lib/python3.8/site-packages/kfp/components/_components.py", line 318, in create_task_from_component_and_arguments
    task = _container_task_constructor(
  File "/home/guava/.cache/pypoetry/virtualenvs/kfp-pipelines-aTzueVjq-py3.8/lib/python3.8/site-packages/kfp/dsl/_component_bridge.py", line 34, in _create_container_op_from_component_and_arguments
    dsl.types.verify_type_compatibility(reference_type, input_type, 'Incompatible argument passed to the input "{}" of component "{}": '.format(input_name, component_spec.name))
  File "/home/guava/.cache/pypoetry/virtualenvs/kfp-pipelines-aTzueVjq-py3.8/lib/python3.8/site-packages/kfp/dsl/types.py", line 128, in verify_type_compatibility
    raise InconsistentTypeException(error_text)
kfp.dsl.types.InconsistentTypeException: Incompatible argument passed to the input "GCS path" of component "Download from GCS": Argument type "String" is incompatible with the input type "URI"
```

### What did you expect to happen:

Combine and run the pipeline

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: 1.1

KFP SDK version: 1.1

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by Ark-kun** [comment]
You can use `def download_gcs_pipeline(gcs_uri: 'URI'):` or remove the type annotation.

This issue would be solved once we add support for type inheritance and have `type: {GcsUri: {base_type: {Uri: {base_type: String}}}}`

**Comment by xinbinhuang** [comment]
Thanks for the advice! That totally makes sense. I was thinking that if it will make sense to change the input type from `URI` -> `GCSPath`, but I realize that it will probably break a lot of people's pipelines. 

I will follow up on the Type inheritance issue for implementation.
