### ISSUE TITLE
Network errors when instantiating kfp.Client

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#4846]
This is likely related to the https://github.com/kubeflow/pipelines/pull/4638 PR.
```
$ python -c "import kfp; kfp.Client()"
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000019C105194C8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/v1/namespaces/kubeflow/services/ml-pipeline:http/proxy//apis/v1beta1/healthz
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000019C10530D08>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/v1/namespaces/kubeflow/services/ml-pipeline:http/proxy//apis/v1beta1/healthz
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000019C1052DF88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/v1/namespaces/kubeflow/services/ml-pipeline:http/proxy//apis/v1beta1/healthz
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000019C10333488>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/v1/namespaces/kubeflow/services/ml-pipeline:http/proxy//apis/v1beta1/healthz
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000019C10533748>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/v1/namespaces/kubeflow/services/ml-pipeline:http/proxy//apis/v1beta1/healthz
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000019C10551808>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/v1/namespaces/kubeflow/services/ml-pipeline:http/proxy//apis/v1beta1/healthz
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000019C10551188>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/v1/namespaces/kubeflow/services/ml-pipeline:http/proxy//apis/v1beta1/healthz
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000019C10551308>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/v1/namespaces/kubeflow/services/ml-pipeline:http/proxy//apis/v1beta1/healthz
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000019C105517C8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/v1/namespaces/kubeflow/services/ml-pipeline:http/proxy//apis/v1beta1/healthz
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000019C105563C8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/v1/namespaces/kubeflow/services/ml-pipeline:http/proxy//apis/v1beta1/healthz
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000019C10556948>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/v1/namespaces/kubeflow/services/ml-pipeline:http/proxy//apis/v1beta1/healthz
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "sdk\python\kfp\_client.py", line 148, in __init__
    if not self._context_setting['namespace'] and self.get_kfp_healthz().multi_user is True:
  File "sdk\python\kfp\_client.py", line 310, in get_kfp_healthz
    raise TimeoutError('API call timeout')
TimeoutError: API call timeout
```
/cc @DavidSpek

**Comment by DavidSpek** [comment]
I'm running the regular KFP version that is deployed with Kubeflow 1.2 and have not had issues in the notebook servers I am running where I installed kfp and kfp-server-api using ` python3 -m pip install kfp kfp-server-api --pre --upgrade`.

**Comment by Bobgy** [comment]
Probably not the same as this issue, is the change in #4638 backward compatible with old KFP servers?
e.g. can we use the latest `kfp` pypi package with an old deployment?

I guess we cannot, and it's worth fixing that IMO.

**Comment by DavidSpek** [comment]
@Bobgy Just to make sure I started a fresh notebook in my cluster which has the "old" KFP server deployment that is included with Kubeflow 1.2 and I executed `python -c "import kfp; kfp.Client()"` in the terminal or in a notebook and I get no errors whatsoever. The only error I see is when the page first loads, which is caused by Kale trying to list the experiments but it fails as no namespace has been set. 

Unless I am missing something this should be compatible with old KFP server deployments. I am wondering if this might not be related to https://github.com/kubeflow/pipelines/issues/4440, for which I have deployed the workaround using the ServiceRoleBinding and the EnvoyFilter. However, after removing the EnvoyFilter for the given notebook I still do not receive any network errors. 

@Ark-kun Given https://github.com/kubeflow/pipelines/issues/4847, can you provide more details how you worked around that issue to end up with this network error issue? Did you install the `kfp-api-server` from master as well?

**Comment by Bobgy** [comment]
Thanks for confirming it's backward compatible, then I have no concern with it.

**Comment by Ark-kun** [comment]
@DavidSpek
AFAIR, I was using a Marketplace deployment.

>Unless I am missing something this should be compatible with old KFP server deployments.

Can you please elaborate on this? Does #4638 add a new API to the backend?

P.S. Perhaps we should try to avoid doing network requests in the class constructors.

**Comment by DavidSpek** [comment]
@Ark-kun It's been a while, so I will try and explain it as best I can. What that PR did is add the `IsMultiUserMode` flag to the `/apis/v1beta1/healthz` endpoint. This was then added to the API backends as well, as doing a standard request was not possible with all deployments (during testing faced a 403). The KFP SDK then uses the healthz api endpoint to determine if the installation is multi-user or not, and given that information tries to automatically set the namespace in the context.

**Comment by msinghg123** [comment]
reopen
