### ISSUE TITLE
Metadata Writer can get stuck even with timeout

### ISSUE THREAD

**Issue by sylus** [kubeflow/pipelines#4940]
### What happened:

I think this issue was reported prior but even with the timeout increases I still seem to get problem resulting in the metadata-writer constantly in a crash loop. The Metadata writer works successfully for a while but then just stops doing anything. Usually it lists any new pods it sees, but it has stopped doing printing anything to the logs.

```sh
Traceback (most recent call last):  File "/kfp/metadata_writer/metadata_writer.py", line 135, in <module>    _request_timeout=2000,  # Sometimes HTTP GET gets stuck  
File "/usr/local/lib/python3.7/site-packages/kubernetes/watch/watch.py", line 144, in stream    for line in iter_resp_lines(resp):  
File "/usr/local/lib/python3.7/site-packages/kubernetes/watch/watch.py", line 48, in iter_resp_lines    for seg in resp.read_chunked(decode_content=False):  
File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 781, in read_chunked    self._original_response.close()  File "/usr/local/lib/python3.7/contextlib.py", line 130, in __exit__    self.gen.throw(type, value, traceback)  
File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 443, in _error_catcher    raise ProtocolError("Connection broken: %r" % e, e)urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104
```

### What did you expect to happen:

The metadata-writer doesn't go into a crashloop and can successfully watch.

### Environment:

KFP version: 1.0.4

### Anything else you would like to add:

Related to this issue:

https://github.com/kubeflow/pipelines/issues/4036

/kind bug
/area backend

**Comment by Ark-kun** [comment]
>metadata-writer constantly in a crash loop

Does it print many exceptions? Can you post more logs?

Is the `metadata-grpc-service` service online?

**Comment by sylus** [comment]
I think this was solved by increasing the Istio timeout, a related issue I found I'll try to find it and post back here :)

**Comment by Ark-kun** [comment]
Just to make sure the Metadata Writer is fine: Was it writing this exception many times (restarting)?

**Comment by sylus** [comment]
As I remember it was restarting and writing this message a bit but was fixed as soon as did the Istio timeout fix.

**Comment by Ark-kun** [comment]
Sounds good.
Closing this issue then.

**Comment by JBosom** [comment]
Please @sylus, could you precise how did you change the Istio timeout or could you give the link to the related issue you talked about ? I'm not sure which timeout to change and I experience a similar behaviour : time to time, the metadata-writer restarts, printing a similar error.
