### ISSUE TITLE
External volume deletion stuck in infinite loop

### ISSUE THREAD

**Issue by ajinkya933** [kubeflow/pipelines#4941]
### What steps did you take:
[A clear and concise description of what the bug is.]
I ran MNIST example to train and predict results heres the code:

```
import kfp
import sys
import kfp.dsl as dsl
import kfp.components as comp


def train(data_path, model_file):
    '''
        This definition contains MNIST training steps:
            * Data Import
            * Data Preprocessing
            * Keras model creation
            * Model optimizer : adam
            * Training with specified epoch
            * Print test accuracy
            * Save the model
    '''
    import pickle
    import tensorflow as tf
    from tensorflow.python import keras

    # Load dataset
    fashion_mnist = keras.datasets.fashion_mnist
    (train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

    # Normalize dataset
    train_images = train_images / 255.0
    test_images = test_images / 255.0

    # Define the model using keras
    model = keras.Sequential([
        keras.layers.Flatten(input_shape=(28, 28)),
        keras.layers.Dense(128, activation='relu'),
        keras.layers.Dense(10)

    ])

    model.compile(optimizer='adam', loss=keras.losses.SparseCategoricalCrossentropy(
        from_logits=True), metrics=['accuracy'])
    model.fit(train_images, train_labels, epochs=10)
    test_loss, test_acc = model.evaluate(test_images, test_labels, verbose=2)
    print('Test accuracy', test_acc)

    # IMP this specifies the path inside the Docker container where our model will be saved
    model.save(f'{data_path}/{model_file}')

    # Save test data pickle file
    with open(f'{data_path}/test_data', 'wb') as f:
        pickle.dump((test_images, test_labels), f)


def predict(data_path, model_file, image_number):
    
    # func_to_container_op requires packages to be imported inside of the function.
    import pickle

    import tensorflow as tf
    from tensorflow import keras

    import numpy as np
    
    # Load the saved Keras model
    model = keras.models.load_model(f'{data_path}/{model_file}')

    # Load and unpack the test_data
    with open(f'{data_path}/test_data','rb') as f:
        test_data = pickle.load(f)
    # Separate the test_images from the test_labels.
    test_images, test_labels = test_data
    # Define the class names.
    class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
                   'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

    # Define a Softmax layer to define outputs as probabilities
    probability_model = tf.keras.Sequential([model, 
                                            tf.keras.layers.Softmax()])

    # See https://github.com/kubeflow/pipelines/issues/2320 for explanation on this line.
    image_number = int(image_number)

    # Grab an image from the test dataset.
    img = test_images[image_number]

    # Add the image to a batch where it is the only member.
    img = (np.expand_dims(img,0))

    # Predict the label of the image.
    predictions = probability_model.predict(img)

    # Take the prediction with the highest probability
    prediction = np.argmax(predictions[0])

    # Retrieve the true label of the image from the test labels.
    true_label = test_labels[image_number]
    
    class_prediction = class_names[prediction]
    confidence = 100*np.max(predictions)
    actual = class_names[true_label]
    
    
    with open(f'{data_path}/result.txt', 'w') as result:
        result.write(" Prediction: {} | Confidence: {:2.0f}% | Actual: {}".format(class_prediction,
                                                                        confidence,
                                                                        actual))
    
    print('Prediction has be saved successfully!')

# Glue together training function to the docker container
train_op = comp.func_to_container_op(train, base_image='tensorflow/tensorflow:latest-gpu-py3')
predict_op = comp.func_to_container_op(predict, base_image='tensorflow/tensorflow:latest-gpu-py3')


# define pipeline metadata like name, description etc.
@dsl.pipeline(
    name='MNIST Pipeline',
    description='Pipeline that trains MNIST models on GPU'
)
# define virtual HDD space that the pipeline will take to run
def mnist_container_pipeline(data_path='/mnt', model_file='mnist_model.h5'):
    vop = dsl.VolumeOp(
        name='create_volume',
        resource_name='data-volume',
        size='1Gi',
        modes=["ReadWriteOnce"]
        #modes=dsl.VOLUME_MODE_RWM
    )

# We have already created a volume and a Glued component(Docker+Python script). This Glued component needs 
# to communicate with the volume so lets attach a volume to Glued component 
    mnist_training_container = train_op(data_path, model_file) \
        .add_pvolumes({data_path: vop.volume})

# Create MNIST prediction component.
    mnist_predict_container = predict_op(data_path, model_file, image_number=0) \
                                    .add_pvolumes({data_path: mnist_training_container.pvolume})

    

# Print the result of the prediction
    mnist_result_container = dsl.ContainerOp(
        name="print_prediction",
        image='library/bash:4.4.23',
        pvolumes={data_path: mnist_predict_container.pvolume},
        arguments=['cat', f'{data_path}/result.txt']
    )

    delete_vop = dsl.ResourceOp(
        name="delete-volume",
        k8s_resource=vop.k8s_resource,
        action="delete"
    ).after(mnist_result_container)

# pass these paths inside the volume that we made
pipeline_func = mnist_container_pipeline
#experiment_name = 'fashion_mnist_kubeflow_training2'
experiment_name = sys.argv[0]
run_name = pipeline_func.__name__ + ' run'


if __name__ == '__main__':
    kfp.compiler.Compiler().compile(pipeline_func, __file__ + '.yaml')
```

### What happened:
The experiment Ran but the attached volume to this experiment is not getting deleted.

![mnist](https://user-images.githubusercontent.com/17012391/103172965-93a35980-487d-11eb-8390-5217d4c98698.gif)

![Screenshot from 2020-12-27 20-00-08](https://user-images.githubusercontent.com/17012391/103173072-5be8e180-487e-11eb-8bdd-51332f3beff4.png)

### What did you expect to happen:
The attached volume should get deleted. 

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?
By converting above python script to -> yaml file and uploading this yaml file to Kubeflow dashboard

KFP version: 1.2

KFP SDK version: 
```
kfp                                1.1.2   
kfp-pipeline-spec                  0.1.2   
kfp-server-api                     1.1.2rc1
```

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

How do I delete this volume ?

/kind bug

**Comment by ajinkya933** [comment]
@Bobgy ^ please suggest me what is going wrong ?

**Comment by munagekar** [comment]
This is a known issue with Kubeflow <= 1.2. https://github.com/kubeflow/pipelines/pull/4820 has the required fix.

**Comment by ajinkya933** [comment]
@munagekar please elaborate wht do you mean by :  Install the python package from master branch.
What are these packages ?

**Comment by ajinkya933** [comment]
I have also tried this :
```
$ git clone https://github.com/kubeflow/pipelines.git
$ cd pipelines-master/sdk/python
$ python3 setup.py install
```
After installation is complete:
```
% python3
Python 3.8.3 (default, Jul  2 2020, 11:26:31) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import kfp
>>> kfp.__version__
'1.2.0'
```

When I create a yaml file of above code using kfp==1.2.0 I still am stuck on infinite loop.

<img width="1316" alt="Screenshot 2020-12-30 at 11 58 46 AM" src="https://user-images.githubusercontent.com/17012391/103334157-641b6980-4a96-11eb-9b88-3e8912c95ea2.png">

@munagekar @elikatsis

How do I get out of this infinite loop ?

**Comment by munagekar** [comment]
Based on the logs, I think no-wait delete flat was not set to True. 

Uninstall kfp first and then install from master. Post the yaml manifest on this issue after recompiling, if this does not work.

**Comment by boarder7395** [comment]
See PR https://github.com/kubeflow/pipelines/pull/4820 that addressed this issue.

**Comment by elikatsis** [comment]
Hi @ajinkya933 and happy new year!

You should use `vop.delete()` instead of creating a new `ResourceOp` to delete the PVC you created at the beginning.
This is for two reasons:
1. Using `vop.delete()` you ensure you will delete the proper resource (using the same name and all)
2. Currently if you use a `ResourceOp` to delete a `VolumeOp` you will be bumping into https://github.com/kubeflow/pipelines/issues/4506, because we haven't upgraded Argo to allow the extra no-wait flag (yet), and this is the reason why this gets stuck.

**Comment by ajinkya933** [comment]
@elikatsis Please refer correct use of `vop.delete()` 

Is this the correct use ?
```
    delete_vop = vop.delete(
        name="delete-volume",
        k8s_resource=vop.k8s_resource,
        action="delete"
    ).after(mnist_result_container)

```

**Comment by munagekar** [comment]
Probably this should work

```
vop.delete().after(mnist_result_container)
```

**Comment by ajinkya933** [comment]
For `vop.delete().after(mnist_result_container)`

I get this error:
```
python3 mnist_REST_API.py 
/home/ajinkya/anaconda3/lib/python3.7/site-packages/kfp-1.2.0-py3.7.egg/kfp/components/_data_passing.py:168: UserWarning: Missing type name was inferred as "Integer" based on the value "0".
  warnings.warn('Missing type name was inferred as "{}" based on the value "{}".'.format(type_name, str(value)))
/home/ajinkya/anaconda3/lib/python3.7/site-packages/kfp-1.2.0-py3.7.egg/kfp/dsl/_container_op.py:1039: FutureWarning: Please create reusable components instead of constructing ContainerOp instances directly. Reusable components are shareable, portable and have compatibility and support guarantees. Please see the documentation: https://www.kubeflow.org/docs/pipelines/sdk/component-development/#writing-your-component-definition-file The components can be created manually (or, in case of python, using kfp.components.create_component_from_func or func_to_container_op) and then loaded using kfp.components.load_component_from_file, load_component_from_uri or load_component_from_text: https://kubeflow-pipelines.readthedocs.io/en/stable/source/kfp.components.html#kfp.components.load_component_from_file
  category=FutureWarning,
I am in delete
Traceback (most recent call last):
  File "mnist_REST_API.py", line 158, in <module>
    kfp.compiler.Compiler().compile(pipeline_func, __file__ + '.yaml')
  File "/home/ajinkya/anaconda3/lib/python3.7/site-packages/kfp-1.2.0-py3.7.egg/kfp/compiler/compiler.py", line 946, in compile
    package_path=package_path)
  File "/home/ajinkya/anaconda3/lib/python3.7/site-packages/kfp-1.2.0-py3.7.egg/kfp/compiler/compiler.py", line 1000, in _create_and_write_workflow
    pipeline_conf)
  File "/home/ajinkya/anaconda3/lib/python3.7/site-packages/kfp-1.2.0-py3.7.egg/kfp/compiler/compiler.py", line 836, in _create_workflow
    pipeline_func(*args_list)
  File "mnist_REST_API.py", line 148, in mnist_container_pipeline
    vop.delete().after(mnist_result_container)
  File "/home/ajinkya/anaconda3/lib/python3.7/site-packages/kfp-1.2.0-py3.7.egg/kfp/dsl/_resource_op.py", line 193, in delete
    flags=flags or ["--wait=false"]
  File "/home/ajinkya/anaconda3/lib/python3.7/site-packages/kfp-1.2.0-py3.7.egg/kfp/dsl/_resource_op.py", line 217, in kubernetes_resource_delete_op
    command.extend(flags)
NameError: name 'command' is not defined
```

**Comment by ajinkya933** [comment]
The problem is observed and reproduced for non pip kfp installs: https://github.com/kubeflow/pipelines/issues/4967

**Comment by elikatsis** [comment]
@ajinkya933, sorry for the late responses.

It looks like you reach a state which we have tested during #4506 and #4820 and you are now bumping into a different issue.

So, I'll close this one and feel free to reopen if you come across it again :smiley: 

/close

**Comment by ajinkya933** [comment]
My solution will depend whether I solve this issue or not : https://github.com/kubeflow/pipelines/issues/4967. The current issue is directly related to additional issue caused by kfp on Kubeflow 1.2 Linked here: https://github.com/kubeflow/pipelines/issues/4967

**Comment by ajinkya933** [comment]
#5046

**Comment by pretidav** [comment]
Current bug is still there with kf1.3 and minikube. 
Even deleting the pv manually from command line 
kubectl delete PersistentVolumeClaim myvolume -n myuser --wait=false --output name
cause it to get struck into Terminating state, without really deleting it.

**Comment by Windfarer** [comment]
The same issue as @pretidav 
Maybe we should provide a volume GC step after the workerflow pods' GC in pipeline system instead of let user manage it in workflow.
