### ISSUE TITLE
Return type Object like BatchDataset is not JSON serializable and does not have to_struct() method

### ISSUE THREAD

**Issue by ankur47** [kubeflow/pipelines#4968]
Hi
I am trying to process training datasets using tensorflow keras library. Problem is that output of data is not working as an input of another function in creating kubeflow pipelines with GCP.
From the doc perspective return type each function should be str, int ,bool so i tried pickle package to convert BatchDataset object to string.But getting the error
```
Using 734 files for validation.
Traceback (most recent call last):
  File "/tmp/tmp.tluFUz2Xpp", line 66, in <module>
    _outputs = data_investigation_and_validations_training_sets(**_parsed_args)
  File "/tmp/tmp.tluFUz2Xpp", line 43, in data_investigation_and_validations_training_sets
    train_dataset = pickle.dumps(train_ds)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py", line 1000, in __reduce__
    return convert_to_tensor, (self._numpy(),)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py", line 1039, in _numpy
    six.raise_from(core._status_to_exception(e.code, e.message), None)  # pylint: disable=protected-access
  File "<string>", line 3, in raise_from
  tensorflow.python.framework.errors_impl.InternalError: Tensorflow type 21 not convertible to numpy dtype.
```

But if i tried without pickling
`TypeError: Object of type 'BatchDataset' is not JSON serializable and does not have .to_struct() method.
`
Please find below code snippets:

```
import kfp
import kfp.components as comp
from kfp.components import func_to_container_op, InputPath, OutputPath
import kfp.dsl as dsl
from typing import NamedTuple
@func_to_container_op
def data_investigation_and_validations_training_sets()-> NamedTuple("out", [("d", "dict")]):
    import tensorflow as tf
    from tensorflow import keras
    import PIL
    import pathlib
    import pickle
    train_ds = tf.keras.preprocessing.image_dataset_from_directory(
        data_dir,
        validation_split=0.2,
        subset="training",
        seed=123,
        image_size=(img_height, img_width),
        batch_size=batch_size)
    val_ds = tf.keras.preprocessing.image_dataset_from_directory(
        data_dir,
        validation_split=0.2,
        subset="validation",
        seed=123,
        image_size=(img_height, img_width),
        batch_size=batch_size)
    class_names = train_ds.class_names
    d = {"train_ds":train_ds,"val_ds":val_ds,"class_names":class_names}
    return d 
@func_to_container_op
def model_fitting(data) -> NamedTuple("out", [("d", "dict")]):
    import tensorflow as tf
    from tensorflow import keras
    from tensorflow.keras import layers
    import numpy as np
    from tensorflow.keras.models import Sequential
    train_ds = data.get("train_ds")
    val_ds = data.get("val_ds")
    class_names = data.get("class_names")
    model = Sequential([
        layers.experimental.preprocessing.Rescaling(1. / 255, input_shape=(img_height, img_width, 3)),
        layers.Conv2D(16, 3, padding='same', activation='relu'),
        layers.MaxPooling2D(),
        layers.Conv2D(32, 3, padding='same', activation='relu'),
        layers.MaxPooling2D(),
        layers.Conv2D(64, 3, padding='same', activation='relu'),
        layers.MaxPooling2D(),
        layers.Flatten(),
        layers.Dense(128, activation='relu'),
        layers.Dense(num_classes)
    ])
    model.compile(optimizer='adam',
                  loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
                  metrics=['accuracy'])
    model.summary()
    d = {"train_ds":train_ds,"val_ds":val_ds,"num_classes":num_classes,"model":model,"class_names":class_names}
    return d
@dsl.pipeline(name='Classification_pipeline',description='Classification pipeline via code')
def classification_pipeline():
    data = data_investigation_and_validations_training_sets()
    model_data = model_fitting(data.output)
if __name__ == '__main__':
    workflow_dict = kfp.compiler.Compiler()._create_workflow(classification_pipeline)
    workflow_dict['metadata']['namespace'] = "default"
    kfp.compiler.Compiler._write_workflow(workflow_dict, 'classification_pipeline.yaml')
```

_Originally posted by @ankur47 in https://github.com/kubeflow/pipelines/issues/2206#issuecomment-756802767_

**Comment by Ark-kun** [comment]
KFP auto-serializes only a very minimal number of types (`str`, `int`, `float`, `bool`, `list`(JSON), `dict`(JSON)).
Everything else bust be serialized explicitly.
The `dict`-type  outputs are serialized using `json.dump`, so everything that cannot be automatically serialized to JSON (e.g. `BatchDataset`) will fail.

You can check the generated code by doing 
`func_to_container_op(data_investigation_and_validations_training_sets, output_component_path='component.yaml')`

>train_ds = tf.keras.preprocessing.image_dataset_from_directory(

I'm not sure that this approach wikk work. The resulting Dataset object probably does not contain the actual data. So serializing or pickling the object probably won't capture the actual data. You need to find a way to serialize the datasets to some format like TF Example or Parquet.

>        data_dir,

Where does this one come from?

Here is how the component should look like (but again, it probably won't work).
```
@func_to_container_op
def data_investigation_and_validations_training_sets(
    data_uri: str
    train_ds_path: OutputPath(),
    val_ds_path: OutputPath(),
) -> NamedTuple("Outputs", [
    ("class_names", "list"),
]):
    import tensorflow as tf
    from tensorflow import keras
    import PIL
    import pathlib
    import pickle
    train_ds = tf.keras.preprocessing.image_dataset_from_directory(
        data_dir,
        validation_split=0.2,
        subset="training",
        seed=123,
        image_size=(img_height, img_width),
        batch_size=batch_size)
    val_ds = tf.keras.preprocessing.image_dataset_from_directory(
        data_dir,
        validation_split=0.2,
        subset="validation",
        seed=123,
        image_size=(img_height, img_width),
        batch_size=batch_size)
    class_names = train_ds.class_names
    with open(train_ds_path, 'wb') as train_ds_file:
        pickle.dump(train_ds, train_ds_file)
    with open(val_ds_path, 'wb') as val_ds_file:
        pickle.dump(val_ds, val_ds_file)
    return [class_names]
```

>def model_fitting

Please check the [keras/Train_classifier](https://github.com/kubeflow/pipelines/blob/master/components/keras/Train_classifier/from_CSV/component.py) component for reference. And the sample pipeline: https://github.com/kubeflow/pipelines/blob/master/components/keras/Train_classifier/_samples/sample_pipeline.py

**Comment by jtlz2** [comment]
@ankur47 @Ark-kun Is there a workaround for this short of writing a custom encoder?

Thanks

**Comment by Ark-kun** [comment]
> @Ark-kun Is there a workaround for this short of writing a custom encoder?

You need to save the object to a file somehow. Often particular library has a built-in method. Otherwise you need to write your own saving and loading code.
Usually, datasets are in CSV, Parquet, Arrow formats.

**Comment by rimolive** [comment]
Closing this issue. No activity for more than a year.

/close
