### ISSUE TITLE
Tests - Marketplace verification does not fail on errors

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#4991]
https://storage.googleapis.com/kubernetes-jenkins/logs/kubeflow-pipeline-postsubmit-mkp-e2e-test/1346987369131151360/build-log.txt

```
Step #1 - "verify": === SCHEMA VALIDATION WARNING ===
Step #1 - "verify": WARNING: Schema is incompatible with the latest deployer, would fail with:
Step #1 - "verify": 
Step #1 - "verify": Traceback (most recent call last):
Step #1 - "verify":   File "/bin/validate_schema.py", line 35, in <module>
Step #1 - "verify":     main()
Step #1 - "verify":   File "/bin/validate_schema.py", line 31, in main
Step #1 - "verify":     schema_values_common.load_schema_and_validate(args)
Step #1 - "verify":   File "/bin/schema_values_common.py", line 65, in load_schema_and_validate
Step #1 - "verify":     return load_schema(parsed_args).validate()
Step #1 - "verify":   File "/bin/config_helper.py", line 170, in validate
Step #1 - "verify":     self._x_google_marketplace._deployer_service_account.validate()
Step #1 - "verify":   File "/bin/config_helper.py", line 1039, in validate
Step #1 - "verify":     'SERVICE_ACCOUNT must have a `description` '
Step #1 - "verify": config_helper.InvalidSchema: SERVICE_ACCOUNT must have a `description` explaining purpose and permission requirements. See docs: https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/master/docs/schema.md#type-service_account
Step #1 - "verify": ======== END OF WARNING =========
Step #1 - "verify": === ERROR SUMMARY ===
Step #1 - "verify": 
Step #1 - "verify": Error events found in namespace "apptest-lf0xqn9s"
Step #1 - "verify": LAST SEEN   TYPE      REASON        OBJECT                                          MESSAGE
Step #1 - "verify": 4m26s       Warning   FailedMount   pod/cache-server-d97bc8bdb-n9w2c                MountVolume.SetUp failed for volume "webhook-tls-certs" : secret "webhook-server-tls" not found
Step #1 - "verify": 3m27s       Warning   FailedMount   pod/cache-server-d97bc8bdb-n9w2c                Unable to mount volumes for pod "cache-server-d97bc8bdb-n9w2c_apptest-lf0xqn9s(08120b68-63c6-48e3-b1c2-cda8cbe18f66)": timeout expired waiting for volumes to attach or mount for pod "apptest-lf0xqn9s"/"cache-server-d97bc8bdb-n9w2c". list of unmounted volumes=[webhook-tls-certs]. list of unattached volumes=[webhook-tls-certs kubeflow-pipelines-cache-token-njs8b]
Step #1 - "verify": 2m17s       Warning   BackOff       pod/metadata-grpc-deployment-577c66c4dd-tvm5n   Back-off restarting failed container
Step #1 - "verify": 5m29s       Warning   FailedMount   pod/proxy-agent-795bfdc898-lt4g9                MountVolume.SetUp failed for volume "proxy-agent-runner-token-hphss" : couldn't propagate object cache: timed out waiting for the condition
Step #1 - "verify": 5m28s       Warning   FailedMount   pod/workflow-controller-87f56f879-df6fj         MountVolume.SetUp failed for volume "argo-token-v5l4z" : couldn't propagate object cache: timed out waiting for the condition
Step #1 - "verify": =====================
Step #1 - "verify": 
Step #1 - "verify": === VERIFICATION STATUS ===
Step #1 - "verify": PASSED
Step #1 - "verify": ===========================
Finished Step #1 - "verify"
```

**Comment by Bobgy** [comment]
It seems all of the findings are warnings though, and the verification status is PASSED
