### ISSUE TITLE
403 error or empty response when using KFP SDK to connect to AI Platform Pipelines / KFP standalone on GCP

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#5230]
The problem just started happening yesterday.

To resolve the problem, ensure you are doing BOTH of the following:
1. Use "kfp" SDK version 0.5.2 or >= 1.0.4:
    e.g. `pip install kfp==0.5.2` or `pip install kfp==1.0.4` or `pip install --upgrade kfp`.
    
    You can check which version you are using via `pip list | grep kfp`.
2. Use explicit https protocol, eg from python:
   ```
   import kfp
   client = kfp.Client(host='https://*.pipelines.googleusercontent.com')
   ```
   when following [the documentation to connect to KFP host in AI Platform Pipelines / KFP standalone on GCP](https://cloud.google.com/ai-platform/pipelines/docs/connecting-with-sdk).

**Comment by rky0930** [comment]
@Bobgy I also found this problem today. The solution you suggested it solves well thanks.

I want to know why this changes happened, and where I can find out before this kind of changes occurs.

**Comment by TDehaene** [comment]
Seconded, we also had the problem starting today. Your solution fixed it, though we had to use kfp==1.4.0

This was the stacktrace:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/thoma/git/fednot/valuation-kfp/pipelines/compile_and_upload.py", line 60, in <module>
    main(parser.parse_args())
  File "/home/thoma/git/fednot/valuation-kfp/pipelines/compile_and_upload.py", line 49, in main
    upload.upload_pipelines(yaml_files)
  File "/home/thoma/git/fednot/valuation-kfp/pipelines/helpers/upload.py", line 91, in upload_pipelines
    client.pipeline_uploads.upload_pipeline(file_path, name=name)
  File "/home/thoma/env_fednot_kfp/lib/python3.7/site-packages/kfp_server_api/api/pipeline_upload_service_api.py", line 56, in upload_pipeline
    (data) = self.upload_pipeline_with_http_info(uploadfile, **kwargs)  # noqa: E501
  File "/home/thoma/env_fednot_kfp/lib/python3.7/site-packages/kfp_server_api/api/pipeline_upload_service_api.py", line 139, in upload_pipeline_with_http_info
    collection_formats=collection_formats)
  File "/home/thoma/env_fednot_kfp/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 330, in call_api
    _preload_content, _request_timeout)
  File "/home/thoma/env_fednot_kfp/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 161, in __call_api
    _request_timeout=_request_timeout)
  File "/home/thoma/env_fednot_kfp/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 373, in request
    body=body)
  File "/home/thoma/env_fednot_kfp/lib/python3.7/site-packages/kfp_server_api/rest.py", line 275, in POST
    body=body)
  File "/home/thoma/env_fednot_kfp/lib/python3.7/site-packages/kfp_server_api/rest.py", line 228, in request
    raise ApiException(http_resp=r)
kfp_server_api.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Content-Length': '1449', 'Content-Type': 'text/html; charset=utf-8', 'Date': 'Thu, 04 Mar 2021 15:53:04 GMT', 'Vary': 'Origin', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '0', 'Set-Cookie': 'S=cloud_datalab_tunnel=piSB961yvViWsUe-wYMAzq0HPAsm9e-Bb7n7dSGcfGw; Path=/; Max-Age=3600'})
HTTP response body: 
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 403 (Forbidden)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>403.</b> <ins>That’s an error.</ins>
  <p>  <ins>That’s all we know.</ins>
  ```

**Comment by tszumowski** [comment]
@Bobgy thank you! I was poking around for quite a while this morning and wish I bothered to look at the most recent issues first! 

I confirmed it works both with `kfp==1.0.4` and `kfp==1.4.0`. 

This was on an AI Platforms Pipelines instance version `1.0.4`.

**Comment by tszumowski** [comment]
Also, for GitHub search indexing purposes, the empty response we were seeing when calling `list_pipelines()` for us was:

```
{'next_page_token': None, 'pipelines': None, 'total_size': None}
```

**Comment by hahns0lo** [comment]
@Bobgy thanks so much for the fix!

Interesting note: we have a script for uploading and running pipelines that was creating a KFP Client in the following way (replace * with the KFP instance’s hostname):

```
kfp.Client(host='*.pipelines.googleusercontent.com')
```

As you suggested, adding https:// fixes the problem. However, the problem only started appearing for us yesterday when we were running the script manually. Our Cloud Build pipelines use the same script and were unaffected.

**Comment by Bobgy** [comment]
@hahns0lo you should also change your Cloud Build pipelines as suggested here, even if it's currently unaffected.

**Comment by zijianjoy** [comment]
Issue has been resolved. Please follow guidance if you encounter this issue.
