### ISSUE TITLE
[backend] metadata writer multi-user mode incorrect list

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/pipelines#5413]
The metadata writer was failing with a strange error:
```
Start watching Kubernetes Pods created by Argo
Traceback (most recent call last):
  File "/kfp/metadata_writer/metadata_writer.py", line 145, in <module>
    _request_timeout=2000,  # Sometimes HTTP GET gets stuck
  File "/usr/local/lib/python3.7/site-packages/kubernetes/watch/watch.py", line 142, in stream
    resp = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 12372, in list_namespaced_pod
    (data) = self.list_namespaced_pod_with_http_info(namespace, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 12472, in list_namespaced_pod_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 344, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 178, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 365, in request
    headers=headers)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Thu, 01 Apr 2021 19:01:38 GMT', 'Content-Length': '347'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \\"pods\\" is forbidden: User \\"system:serviceaccount:kubeflow:kubeflow-pipelines-metadata-writer\\" cannot get resource \\"namespaces\\" in API group \\"\\" in the namespace \\"pods\\"","reason":"Forbidden","details":{"name":"pods","kind":"namespaces"},"code":403}\n'
```

This is the line that failed in the code:

```python
    for event in k8s_watch.stream(
        k8s_api.list_namespaced_pod,
        namespace=namespace_to_watch,
        label_selector=ARGO_WORKFLOW_LABEL_KEY,
        timeout_seconds=1800,  # Sometimes watch gets stuck
        _request_timeout=2000,  # Sometimes HTTP GET gets stuck
    ):
```

If the `namespace_to_watch` variable is empty (which is for multi-user installations), then the K8s library makes a request to `/api/v1/namespaces//pods`. Here is the excerpt from the library, which @elikatsis found:

```python
    def list_namespaced_pod(self, namespace, **kwargs):  # noqa: E501
        """list_namespaced_pod  # noqa: E501
        ...
        """
        kwargs['_return_http_data_only'] = True
        return self.list_namespaced_pod_with_http_info(namespace, **kwargs)  # noqa: E501

    def list_namespaced_pod_with_http_info(self, namespace, **kwargs):  # noqa: E501
        """list_namespaced_pod  # noqa: E501
        ...
        """

        ...

        return self.api_client.call_api(
            '/api/v1/namespaces/{namespace}/pods', 'GET',  # <------- namespace="": /api/v1/namespaces/pods
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='V1PodList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)
```

Fixed by changing the API call to `list_pod_for_all_namespaces` in case the `namespace_to_watch` variable is empty. All the kudos go to @elikatsis for this one.

**Comment by yanniszark** [comment]
I will be opening a PR with the aforementioned fix asap
/assign @yanniszark
