### ISSUE TITLE
[backend] Sample pipeline "[Demo] TFX - Taxi tip prediction model trainer" failed with "Invalid bucket name: '{{kfp-default-bucket}}'"

### ISSUE THREAD

**Issue by myoshimu** [kubeflow/pipelines#5450]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
Deployed the KFP from GCP marketplace with [this step](https://cloud.google.com/ai-platform/pipelines/docs/getting-started
).
*  KFP version: 
1.4.1
*  KFP SDK version: 
1.4.1

### Steps to reproduce
1) Deploy KFP with the step below
https://cloud.google.com/ai-platform/pipelines/docs/getting-started
2) From the Google Cloud AI Platform Pipelines, open Pipeline Dashboard. 
3) Go "Pipelines"
4) Open "[Demo] TFX - Taxi tip prediction model trainer"
5) Choose "Create Run" and you can see the csvexamplegen failed.
6) The log shows following error:
```
2021-04-09 06:48:54.757999: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib
2021-04-09 06:48:54.758104: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
INFO:absl:tensorflow_ranking is not available: No module named 'tensorflow_ranking'
INFO:absl:tensorflow_text is not available: No module named 'tensorflow_text'
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:apache_beam.typehints.native_type_compatibility:Using Any for unsupported type: typing.MutableMapping[str, typing.Any]
INFO:absl:Running driver for CsvExampleGen
INFO:absl:MetadataStore with gRPC connection initialized
INFO:absl:select span and version = (0, None)
INFO:absl:latest span and version = (0, None)
INFO:absl:Adding KFP pod name parameterized-tfx-oss-lgngg-449390883 to execution
INFO:absl:Adding KFP pod name parameterized-tfx-oss-lgngg-449390883 to execution
/usr/local/lib/python3.7/dist-packages/setuptools/distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/tfx/orchestration/kubeflow/container_entrypoint.py", line 360, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/tfx/orchestration/kubeflow/container_entrypoint.py", line 353, in main
    execution_info = launcher.launch()
  File "/usr/local/lib/python3.7/dist-packages/tfx/orchestration/launcher/base_component_launcher.py", line 198, in launch
    self._exec_properties)
  File "/usr/local/lib/python3.7/dist-packages/tfx/orchestration/launcher/base_component_launcher.py", line 167, in _run_driver
    component_info=self._component_info)
  File "/usr/local/lib/python3.7/dist-packages/tfx/dsl/components/base/base_driver.py", line 311, in pre_execution
    component_info=component_info)
  File "/usr/local/lib/python3.7/dist-packages/tfx/components/example_gen/driver.py", line 141, in _prepare_output_artifacts
    base_driver._prepare_output_paths(example_artifact)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.7/dist-packages/tfx/dsl/components/base/base_driver.py", line 46, in _prepare_output_paths
    if fileio.exists(artifact.uri):
  File "/usr/local/lib/python3.7/dist-packages/tfx/dsl/io/fileio.py", line 63, in exists
    return _get_filesystem(path).exists(path)
  File "/usr/local/lib/python3.7/dist-packages/tfx/dsl/io/plugins/tensorflow_gfile.py", line 54, in exists
    return tf.io.gfile.exists(path)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 268, in file_exists_v2
    _pywrap_file_io.FileExists(compat.path_to_bytes(path))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Error executing an HTTP request: HTTP response code 400 with body '{
  "error": {
    "code": 400,
    "message": "Invalid bucket name: '{{kfp-default-bucket}}'",
    "errors": [
      {
        "message": "Invalid bucket name: '{{kfp-default-bucket}}'",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}
'
	 when reading metadata of gs://{{kfp-default-bucket}}/tfx_taxi_simple/12cd6e2d-d7a7-4c4b-a1ad-970c24cd3166/CsvExampleGen/examples/11
Runtime execution graph. Only steps that are currently running or have already completed are shown.
```
![4ZeBZFX5ZitToW3](https://user-images.githubusercontent.com/8294746/114144819-b222f180-9950-11eb-925a-68da84ee6d65.png)

### Expected result
The sample pipeline successfully complete.

### Materials and Reference
It looks like the bucket 'tfx_taxi_simple' does not exist.
https://github.com/kubeflow/pipelines/blob/master/samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by Bobgy** [comment]
Hi @myoshimu, you can edit the parameter and replace {{kfp-default-bucket}} with your own bucket.

but you are right, it should be replaced automatically during installation, it's strange that failed

**Comment by capri-xiyue** [comment]
The root cause of this issue is because somehow https://github.com/kubeflow/pipelines/blob/master/manifests/kustomize/env/gcp/gcp-configurations-patch.yaml does not apply to the deployment of `ml-pipeline`, therefore https://github.com/kubeflow/pipelines/blob/e21ea18c1310eadc080cb21c0fc025de8b0b808f/backend/src/apiserver/resource/resource_manager_util.go#L208 here does not patch default values.

**Comment by capri-xiyue** [comment]
Hi @myoshimu ,
I tested with the same KFP version using with [this step](https://cloud.google.com/ai-platform/pipelines/docs/getting-started
). The "[Demo] TFX - Taxi tip prediction model trainer" works.(Screenshot attached)
<img width="1126" alt="Screen Shot 2021-07-30 at 10 58 50 AM" src="https://user-images.githubusercontent.com/52932582/127693862-da1865d2-d64c-4163-8b13-ed9e781706bd.png">
<img width="1052" alt="Screen Shot 2021-07-30 at 11 00 31 AM" src="https://user-images.githubusercontent.com/52932582/127693870-00c53692-2313-439f-bc1c-f916f104ed5c.png">

Can you help check whether you deploy the KFP via GCP Marketplace https://cloud.google.com/ai-platform/pipelines/docs/getting-started#set_up_your_instance or you deploy KFP via standalone deployment https://cloud.google.com/ai-platform/pipelines/docs/getting-started#set_up_your_instance and you don't apply manifests needed for gcp patched configurations during standalone deployment.

You can verify this via running `kubectl get configmaps -n {your-namespacce}` to see whether you have `gcp-default-config`(if you have this, it means you deploy KFP via marketplace).

If you install kfp via standalone deployment and you don't apply manifests needed for gcp patched configurations during standalone deployment, it is expected behavior that '{{kfp-default-bucket}}' doesn't get replaced with valid value and you will get invalid argument error.

**Comment by aivanou** [comment]
@capri-xiyue  Hi! Is it possible to create a single example that does not require me to set up a gcp account? It would be great if I can just run example, without reading on a side that kfp actually sets some hidden env. variables(e.g. {{kfp-default-bucket}}) 

It is very confusing for users that if I deployed my kfp cluster on aws, I cannot run any examples, and basically on my own.

**Comment by capri-xiyue** [comment]
> @capri-xiyue Hi! Is it possible to create a single example that does not require me to set up a gcp account? It would be great if I can just run example, without reading on a side that kfp actually sets some hidden env. variables(e.g. {{kfp-default-bucket}})
> 
> It is very confusing for users that if I deployed my kfp cluster on aws, I cannot run any examples, and basically on my own.

You don't have to set up a gcp account when you follow this doc https://cloud.google.com/ai-platform/pipelines/docs/getting-started
