### ISSUE TITLE
[bug] v2 Sample test: mysql_query aborted: errno: 1213, error: Deadlock found when trying to get lock; try restarting transaction

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#5467]
https://4e18c21c9d33d20f-dot-datalab-vm-staging.googleusercontent.com/#/runs/details/bb97866a-d8ad-44a1-bd8e-c28f8df1a560

```
1.1
F0413 20:03:23.231673       1 main.go:56] Failed to successfuly execute component: rpc error: code = Aborted desc = mysql_query aborted: errno: 1213, error: Deadlock found when trying to get lock; try restarting transaction
goroutine 1 [running]:
github.com/golang/glog.stacks(0xc000088e00, 0xc00022a280, 0xe0, 0x135)
	/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:769 +0xb9
github.com/golang/glog.(*loggingT).output(0x10ff320, 0xc000000003, 0xc000430380, 0x1082606, 0x7, 0x38, 0x0)
	/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:720 +0x3b3
github.com/golang/glog.(*loggingT).printf(0x10ff320, 0x3, 0xc1e218, 0x2b, 0xc00063ff58, 0x1, 0x1)
	/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:655 +0x153
github.com/golang/glog.Fatalf(...)
	/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:1148
main.main()
	/build/cmd/launch/main.go:56 +0x357
```

**Comment by Ark-kun** [comment]
P.S. The error is intermittent and disappeared after re-run.

**Comment by Bobgy** [comment]
It seems we should add retry when calling KFP API

**Comment by Bobgy** [comment]
https://4e18c21c9d33d20f-dot-datalab-vm-staging.googleusercontent.com/#/runs/details/26a16bda-2f69-4cc1-baf1-cde02947a64e

I'm seeing this once too, among many pipelines in one test, this was the only one that failed. This seems flaky.

**Comment by capri-xiyue** [comment]
This issue got fixed by https://github.com/kubeflow/pipelines/pull/5629
