### ISSUE TITLE
SDK - Creating lightweight component inside lightweight component function leads to wrong inner component

### ISSUE THREAD

**Issue by Shuai-Xie** [kubeflow/pipelines#5589]
### Environment

*  Kubernetes: 1.18.9

*  KFP version: 1.4.0

*  KFP SDK version: 1.4.0

*  All dependencies version:

```shell
$ pip list | grep kfp
kfp                      1.4.0
kfp-pipeline-spec        0.1.7
kfp-server-api           1.5.0
```

### Steps to reproduce

I want to launch a new pipeline (not local) from one component named `create_pipeline_in_pod` of the pipeline named `outer_pipeline` .  The demo codes are below.

```python
import kfp
import kfp.dsl as dsl
from kfp.components import func_to_container_op

EXP_NAME = 'demo'
RUN_NAME = 'outer_pipeline'

def create_pipeline_in_pod(data_dir: str):
    import kfp
    import kfp.dsl as dsl
    from kfp.components import func_to_container_op
    from typing import NamedTuple

    print('create_pipeline_in_pod')

    EXP_NAME = 'demo'
    RUN_NAME = 'pipeline_in_pod'

    @func_to_container_op
    def add(
        a: int,
        b: int  # todo: can't recognize return type
    ) -> NamedTuple('output', [('func_name', str), ('result', int)]):
        from collections import namedtuple
        output = namedtuple('output', ['func_name', 'result'])
        return output('add_two_numbers', a + b)

    @func_to_container_op
    def show_result(func_name, result):
        print(f'{func_name} result: {result}')

    @dsl.pipeline(name=RUN_NAME)
    def inpod_pipeline_func(a: int, b: int):
        add_task = add(a, b)
        show_result(add_task.outputs['func_name'], add_task.outputs['result'])

    if __name__ == '__main__':
        # compile and submit
        print('begin compile in pod...')
        kfp.compiler.Compiler().compile(inpod_pipeline_func,
                                        f'{data_dir}/{RUN_NAME}.yaml')
        print('finish compile in pod')

        # run pipeline outside
        client = kfp.Client(host='my_k8s_master_ip:8888', namespace='kubeflow')
        client.create_run_from_pipeline_func(inpod_pipeline_func,
                                             arguments={
                                                 'a': '1',
                                                 'b': '2'
                                             },
                                             experiment_name=EXP_NAME,
                                             run_name=RUN_NAME)
        print('submit pipeline in pod')


op = func_to_container_op(create_pipeline_in_pod, packages_to_install=['kfp'])


# Define the pipeline
@dsl.pipeline(name=RUN_NAME)
def pipeline_func(data_dir: str):
    vop = dsl.VolumeOp(
        name='create_pvc',
        resource_name='data_volume',
        size='1Gi',  # if size not change, then use the same pvc
        storage_class='local-path',
        modes=dsl.VOLUME_MODE_RWO)
    op(data_dir).add_pvolumes({data_dir: vop.volume})


if __name__ == '__main__':
    print('begin compile...')
    kfp.compiler.Compiler().compile(pipeline_func, f'{RUN_NAME}.yaml')
    print('finish compile')

    client = kfp.Client(host='my_k8s_master_ip:8888', namespace='kubeflow')
    client.create_run_from_pipeline_func(pipeline_func,
                                         arguments={'data_dir': '/mnt'},
                                         experiment_name=EXP_NAME,
                                         run_name=RUN_NAME)
    print('submit pipeline')
```

The above code will fail when doing `kfp.compiler.Compiler().compile(inpod_pipeline_func,                                       
 f'{data_dir}/{RUN_NAME}.yaml')`. 

And the error messages in the kubeflow pipeline ui are below.

```sh
create_pipeline_in_pod
begin compile in pod...
Traceback (most recent call last):
  File "/tmp/tmp.aHWqREfBIL", line 50, in <module>
    _outputs = create_pipeline_in_pod(**_parsed_args)
  File "/tmp/tmp.aHWqREfBIL", line 32, in create_pipeline_in_pod
    f'{data_dir}/{RUN_NAME}.yaml')
  File "/usr/local/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 975, in compile
    package_path=package_path)
  File "/usr/local/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 1029, in _create_and_write_workflow
    pipeline_conf)
  File "/usr/local/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 861, in _create_workflow
    pipeline_func(*args_list, **kwargs_dict)
  File "/tmp/tmp.aHWqREfBIL", line 26, in inpod_pipeline_func
    show_result(add_task.outputs['func_name'], add_task.outputs['result'])
KeyError: 'func_name'
```

I've adapted three ablation tests.

#### Ablation test 1: Directly compile the code inside `create_pipeline_in_pod` function

It compiles perfectly and the kubeflow pipeline ui shows the right results.

#### Ablation test 2: Define an inner pipeline without passing small values

It also compiles perfectly and the kubeflow pipeline ui shows the right results of two runs. (Yes. The two runs are parallel below the `demo` experiment). The codes of the new `create_pipeline_in_pod` function are below.

```python
def create_pipeline_in_pod(data_dir: str):
    import kfp
    import kfp.dsl as dsl
    from kfp.components import func_to_container_op

    print('create_pipeline_in_pod')

    EXP_NAME = 'demo'
    RUN_NAME = 'pipeline_in_pod'

    @func_to_container_op
    def show_result(info):
        print(info)

    @dsl.pipeline(name=RUN_NAME)
    def inpod_pipeline_func(info):
        show_result(info)

    # compile and submit
    print('begin compile in pod...')
    kfp.compiler.Compiler().compile(inpod_pipeline_func,
                                    f'{data_dir}/{RUN_NAME}.yaml')
    print('finish compile in pod')

    client = kfp.Client(host='my_k8s_master_ip:8888', namespace='kubeflow')
    client.create_run_from_pipeline_func(inpod_pipeline_func,
                                         arguments={
                                             'info': 'hello world',
                                         },
                                         experiment_name=EXP_NAME,
                                         run_name=RUN_NAME)
    print('submit pipeline in pod')
```

#### Ablation test 3: Change the `add` function name to `_add` or `add_here`

Still the same error messages as above.

### Expected result

The pipeline defined inside the `create_pipeline_in_pod` component compiles perfectly.

Thanks a lot.

### Materials and Reference

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by Ark-kun** [comment]
For quick debug try:
```python
    def inpod_pipeline_func(a: int, b: int):
        add_task = add(a, b)
        print(add_task.outputs)
        show_result(add_task.outputs['func_name'], add_task.outputs['result'])
```

**Comment by Shuai-Xie** [comment]
Thanks for your quick reply. I've made two tests with your guidance.

## Test 1

### 1.1. Pipeline function defined in a component

In the `inpod_pipeline_func`, I directly print the `add_task.outputs` as below and don't fetch values by keys in the `show_result` function.

```py
def create_pipeline_in_pod(data_dir: str):
    import kfp
    import kfp.dsl as dsl
    from kfp.components import func_to_container_op
    from typing import NamedTuple

    print('create_pipeline_in_pod')

    EXP_NAME = 'demo'
    RUN_NAME = 'pipeline_in_pod'

    @func_to_container_op
    def add(
        a: int,
        b: int  # todo: can't recognize return type
    ) -> NamedTuple('output', [('func_name', str), ('result', int)]):
        from collections import namedtuple
        output = namedtuple('output', ['func_name', 'result'])
        return output('add_two_numbers', a + b)

    @func_to_container_op
    def show_result(result):
        print(f'result: {result}')

    @dsl.pipeline(name=RUN_NAME)
    def inpod_pipeline_func(a: int, b: int):
        add_task = add(a, b)
        print(add_task.outputs)
        show_result(add_task.outputs)

    # compile and submit
    print('begin compile in pod...')
    kfp.compiler.Compiler().compile(inpod_pipeline_func,
                                    f'{data_dir}/{RUN_NAME}.yaml')
    print('finish compile in pod')

    client = kfp.Client(host='my_k8s_master_ip:8888', namespace='kubeflow')
    client.create_run_from_pipeline_func(inpod_pipeline_func,
                                         arguments={
                                             'a': '1',
                                             'b': '2'
                                         },
                                         experiment_name=EXP_NAME,
                                         run_name=RUN_NAME)
    print('submit pipeline in pod')
```

### 1.2. Pipeline logs 

It shows that `add_task.outputs` is `{}`, which means that no small values are passed in the pipeline. So I guess the return type definition in the `add` function may not be recognized by the `kfp.compiler` in the component.


```
create_pipeline_in_pod
begin compile in pod...
{}
/usr/local/lib/python3.7/site-packages/kfp/components/_data_passing.py:168: UserWarning: Missing type name was inferred as "JsonObject" based on the value "{}".
  warnings.warn('Missing type name was inferred as "{}" based on the value "{}".'.format(type_name, str(value)))
finish compile in pod
{}
submit pipeline in pod
```

### 1.3. Generated Pipeline Graph

More importantly, I found the components of the just created `pipeline_in_pod` pipeline are not connected like below. I guess I should adopt another experiment by passing values with PV.

![image](https://user-images.githubusercontent.com/18352713/117255014-ba048180-ae7b-11eb-942b-91522f4222a4.png)


## Test 2

### 2.1. Pipeline function defined with only one passing value

And I tested a more easy version with only one passing value below. 

Maybe a bit wired, I still use `add_task.outputs` to fetch the outputs of the `add` component. But this modification makes me pass the compilation successfully. And the passing value is `{}`, too.

```py
def create_pipeline_in_pod(data_dir: str):
    import kfp
    import kfp.dsl as dsl
    from kfp.components import func_to_container_op

    print('create_pipeline_in_pod')

    EXP_NAME = 'demo'
    RUN_NAME = 'pipeline_in_pod'

    @func_to_container_op
    def add(a: int, b: int) -> int:
        return a + b

    @func_to_container_op
    def show_result(result):
        print(f'result: {result}')

    @dsl.pipeline(name=RUN_NAME)
    def inpod_pipeline_func(a: int, b: int):
        add_task = add(a, b)
        print(add_task.outputs)
        show_result(add_task.outputs)

    # compile and submit
    print('begin compile in pod...')
    kfp.compiler.Compiler().compile(inpod_pipeline_func,
                                    f'{data_dir}/{RUN_NAME}.yaml')
    print('finish compile in pod')

    client = kfp.Client(host='my_k8s_master_ip:8888', namespace='kubeflow')
    client.create_run_from_pipeline_func(inpod_pipeline_func,
                                         arguments={
                                             'info': 'hello world',
                                         },
                                         experiment_name=EXP_NAME,
                                         run_name=RUN_NAME)
    print('submit pipeline in pod')
```

### 2.2. Pipeline logs 

```shell
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: 
https://pip.pypa.io/warnings/venv
create_pipeline_in_pod
begin compile in pod...
{}
/usr/local/lib/python3.7/site-packages/kfp/components/_data_passing.py:168: UserWarning: Missing type name was inferred as "JsonObject" based on the value "{}".
  warnings.warn('Missing type name was inferred as "{}" based on the value "{}".'.format(type_name, str(value)))
finish compile in pod
{}
submit pipeline in pod
```

### 2.3. Generated Pipeline Graph

Same to 1.3.

![image](https://user-images.githubusercontent.com/18352713/117257567-9db61400-ae7e-11eb-94c4-378c1f50c27b.png)



Thanks very much. I'll keep following up on this issue.

Warm Regrads.

**Comment by Shuai-Xie** [comment]
### Some new discoveries of the not connected components

In my experiment,  `Add` and `Show result` components are created by the pipeline defined in the `create_pipeline_in_pod` function. The two components are not connected in https://github.com/kubeflow/pipelines/issues/5589#issuecomment-833293618

I try to define the pipeline workflow explicitly with `kfp.dsl.ContainerOp`'s `after()` function as below.

```py
def create_add_two_numbers_pipeline_in_pod(data_dir: str):
    import kfp
    import kfp.dsl as dsl
    from kfp.components import func_to_container_op

    print('create_pipeline_in_pod')

    EXP_NAME = 'demo'
    RUN_NAME = 'add_two_numbers_in_pod'

    def add(a: int, b: int) -> int:
        return a + b

    def show_result(result):
        print(f'result: {result}')

    @dsl.pipeline(name=RUN_NAME)
    def inpod_pipeline_func(a: int, b: int):
        add_op = func_to_container_op(add)(a, b)
        print(add_op.outputs)
        show_op = func_to_container_op(show_result)(add_op.outputs)
        show_op.after(add_op)   # note: add after() here
```

The generated graph is ok, but the passing value is still `{}`.

![image](https://user-images.githubusercontent.com/18352713/117263279-b6292d00-ae84-11eb-808e-fc9a8808889c.png)


If I annotate `show_op.after(add_op)` as below, the two components are not connected again.

```py
def create_add_two_numbers_pipeline_in_pod(data_dir: str):
    import kfp
    import kfp.dsl as dsl
    from kfp.components import func_to_container_op

    print('create_pipeline_in_pod')

    EXP_NAME = 'demo'
    RUN_NAME = 'add_two_numbers_in_pod'

    def add(a: int, b: int) -> int:
        return a + b

    def show_result(result):
        print(f'result: {result}')

    @dsl.pipeline(name=RUN_NAME)
    def inpod_pipeline_func(a: int, b: int):
        add_op = func_to_container_op(add)(a, b)
        print(add_op.outputs)
        show_op = func_to_container_op(show_result)(add_op.outputs)
        # show_op.after(add_op)
```

![image](https://user-images.githubusercontent.com/18352713/117263157-91cd5080-ae84-11eb-9d7e-fca217714ed2.png)

**Comment by Shuai-Xie** [comment]
### Test results of `InputPath` and `OutputPath`

I've tried to use `InputPath` and `OutputPath` to pass values in a local file with the help of `minio`.

The codes are updated as below.

```py
def create_add_two_numbers_pipeline_in_pod(data_dir: str):
    import kfp
    import kfp.dsl as dsl
    from kfp.components import func_to_container_op, InputPath, OutputPath

    print('create_pipeline_in_pod')

    EXP_NAME = 'demo'
    RUN_NAME = 'add_two_numbers_in_pod'

    @func_to_container_op
    def add(a: int, b: int, output_sum_path: OutputPath(str)):   # pass by path
        with open(output_sum_path, 'w') as f:
            f.write(str(a + b))

    @func_to_container_op
    def show_result(input_sum_path: InputPath(str)):    # pass by path
        with open(input_sum_path, 'r') as f:
            res = f.readline()
            print('result:', res)

    @dsl.pipeline(name=RUN_NAME)
    def inpod_pipeline_func(a: int, b: int):
        add_task = add(a, b)
        show_result(add_task.output)

    if __name__ == '__main__':
        # compile and submit
        print('begin compile in pod...')
        kfp.compiler.Compiler().compile(inpod_pipeline_func,
                                        f'{data_dir}/{RUN_NAME}.yaml')
        print('finish compile in pod')

        # run pipeline outside
        client = kfp.Client(host='my_k8s_master_ip:8888', namespace='kubeflow')
        client.create_run_from_pipeline_func(inpod_pipeline_func,
                                             arguments={
                                                 'a': '1',
                                                 'b': '2'
                                             },
                                             experiment_name=EXP_NAME,
                                             run_name=RUN_NAME)
        print('submit pipeline in pod')
```

I got new errors as below. `OutputPath` is regarded as a common argument.

```
Add() missing 1 required positional argument: 'output_sum_path'
```

![image](https://user-images.githubusercontent.com/18352713/117267160-909e2280-ae88-11eb-8dc3-ffe2653880a5.png)

Best Regards.

**Comment by Shuai-Xie** [comment]
## Maybe a barely satisfactory solution

In the past days, I found it works well if I created a pipeline in a running pod.

For example :

```sh
# start a running python pod
$ kubectl apply -f python37.yaml

# go into the pod, and execute the pipeline code inside the pod
$ kubectl exec -it python37 bash

# in the shell of the running pod
# use vim to write create_pipeline_in_pod.py
...

# execute
$ python create_pipeline_in_pod.py
```

And I found the newly created `add_two_numbers_inpod` pipeline running well.

So I made a small change to the original code with 2 steps:

1. save the code of `create_pipeline_in_pod()` into a python file like `create_pipeline_in_pod.py`
2. use `os.system()` to execute the program.

The demo program is below.

```python
from webbrowser import open_new
from google.auth.credentials import with_scopes_if_required
import kfp
import kfp.dsl as dsl
from kfp.components import func_to_container_op

EXP_NAME = 'automl'
RUN_NAME = 'create_pipeline_in_pod'


def create_add_two_numbers_pipeline_in_pod():
    import os
    import textwrap

    code = """\
    import kfp
    import kfp.dsl as dsl
    from kfp.components import func_to_container_op
    from typing import NamedTuple

    print('create pipeline in pod')

    EXP_NAME = 'automl'
    RUN_NAME = 'add_two_numbers_inpod'


    @func_to_container_op
    def add(a: int,
            b: int) -> NamedTuple('output', [('func_name', str), ('result', int)]):
        from collections import namedtuple
        output = namedtuple('output', ['func_name', 'result'])
        return output('add_two_numbers', a + b)


    @func_to_container_op
    def show_result(func_name, result):
        print(f'{func_name} result: {result}')


    @dsl.pipeline(name=RUN_NAME)
    def inpod_pipeline_func(a: int, b: int):
        add_task = add(a, b)
        show_result(add_task.outputs['func_name'], add_task.outputs['result'])


    if __name__ == '__main__':
        client = kfp.Client(host='my_k8s_master_ip:8888')
        client.create_run_from_pipeline_func(inpod_pipeline_func,
                                            arguments={
                                                'a': '1',
                                                'b': '2'
                                            },
                                            experiment_name=EXP_NAME,
                                            run_name=RUN_NAME)
        print('submit pipeline in pod')
    """

    file_path = './create_pipeline_in_pod.py'

    # write
    with open(file_path, 'w') as f:
        f.write(textwrap.dedent(code))
    print('\nwrite codes')

    # read
    print('\nread codes')
    with open(file_path, 'r') as f:
        for line in f.readlines():
            print(line, end='')

    print('\nrun codes')
    os.system(f'python {file_path}')


inpipeline_op = func_to_container_op(create_add_two_numbers_pipeline_in_pod,
                                     base_image='shuaix/kfp_fairing:1.0')


# Define the pipeline
@dsl.pipeline(name=RUN_NAME)
def pipeline_func():
    inpipeline_op()


if __name__ == '__main__':
    client = kfp.Client(host='my_k8s_master_ip:8888')
    client.create_run_from_pipeline_func(pipeline_func,
                                         arguments={},
                                         experiment_name=EXP_NAME,
                                         run_name=RUN_NAME)
    print('submit pipeline')
```

The pipeline logs

```
write codes

read codes

import kfp
import kfp.dsl as dsl
from kfp.components import func_to_container_op
from typing import NamedTuple
print('create pipeline in pod')
EXP_NAME = 'automl'
RUN_NAME = 'add_two_numbers_inpod'
@func_to_container_op
def add(a: int,
        b: int) -> NamedTuple('output', [('func_name', str), ('result', int)]):
    from collections import namedtuple
    output = namedtuple('output', ['func_name', 'result'])
    return output('add_two_numbers', a + b)
@func_to_container_op
def show_result(func_name, result):
    print(f'{func_name} result: {result}')
@dsl.pipeline(name=RUN_NAME)
def inpod_pipeline_func(a: int, b: int):
    add_task = add(a, b)
    show_result(add_task.outputs['func_name'], add_task.outputs['result'])
if __name__ == '__main__':
    client = kfp.Client(host='10.252.192.47:8888')
    client.create_run_from_pipeline_func(inpod_pipeline_func,
                                        arguments={
                                            'a': '1',
                                            'b': '2'
                                        },
                                        experiment_name=EXP_NAME,
                                        run_name=RUN_NAME)
    print('submit pipeline in pod')

run codes
create pipeline in pod
submit pipeline in pod
```

Both of the pipelines run successfully.

![image](https://user-images.githubusercontent.com/18352713/117527363-0c6dab80-affe-11eb-8ae6-b866c8dbb327.png)

![image](https://user-images.githubusercontent.com/18352713/117527370-198a9a80-affe-11eb-9e63-af3f72514e58.png)

![image](https://user-images.githubusercontent.com/18352713/117527378-23140280-affe-11eb-9941-f3c0cf0b58bc.png)

Best Regards.

**Comment by jaminsore** [comment]
I am having a related issue (with the same `kfp*` package versions as OP), and it appears that the source of the problem is that multiple outputs is broken. To illustrate, the following test fails, and the only key in `called_multi_output_op.outputs` is `"Output"`.

```python
from typing import NamedTuple
from kfp import components

def test_multiple_outputs() -> None:
    def multi_ouptput_func(
        a: str, b: str
    ) -> NamedTuple("MultiOutputNoOp", [("a", str), ("b", str)]):  # type: ignore[valid-type]
        import namedtuple

        MultiOutputNoOp = namedtuple("MultiOutputNoOp", ["a", "b"])
        return MultiOutputNoOp(a=a, b=b)

    multi_ouptput_op = components.func_to_container_op(multi_ouptput_func)
    called_multi_output_op = multi_ouptput_op(a="some", b="args")

    assert all(k in called_multi_output_op.outputs for k in ["a", "b"]), list(
        called_multi_output_op.outputs
    )

```

**Comment by jaminsore** [comment]
It looks like the issue in my test was the `from __future__ import annotations` import. If I remove that, then the test passes. So @Shuai-Xie , you might be running on python 3.10 locally, and it works in a running pod because you're using python 3.7?

**Comment by Shuai-Xie** [comment]
Thanks for your kind reply @jaminsore.  But the problem may be not a version issue since the program can run successfully in a running pod if I use this method https://github.com/kubeflow/pipelines/issues/5589#issuecomment-835101733. By the way, I use python 3.6.13 both in the host and pod mode.

**Comment by Ark-kun** [comment]
I did a small investigation.

The easiest way to debug component-related issues like that is to look at the component definition:

```python
op = func_to_container_op(create_pipeline_in_pod, packages_to_install=['kfp'], output_component_file='nested.component.yaml')
```

We immediately see the issue that was causing the weird behavior:

```yaml
          @func_to_container_op
          def add(
              a,
              b  # todo: can't recognize return type
          ):
              from collections import namedtuple
              output = namedtuple('output', ['func_name', 'result'])
              return output('add_two_numbers', a + b)
```

All type annotations are gone. Most importantly the output type annotations.

Yes, the `create_component_from_func`/`func_to_container_op` does that.

Why?

When not using code pickling (the default), the function must be self-contained. However, the types used in the function signature are "outside" the function body.

The code only really needs to strip annotations from the outer function, but it strips all function annotations inside.

This can be considered a somewhat minor bug.

Can you please describe the scenario where you want to do static nested component authoring?

I see multiple viable workarounds:

1. Turn the pipeline into a graph component using `kfp.components.create_graph_component_from_pipleine_func`

2. Do not put pipeline code inside the component. You can get the pipeline code from an input or from some URL.

I'd split the outer pipeline into 2 or 3 components: Get pipeline code, [compile pipeline], Submit run

**Comment by Shuai-Xie** [comment]
Hi, @Ark-kun. Many thanks for your detailed analysis and a clear experiment. 

I'd like to describe my scenario first.  

Assuming the **outer pipeline** has two components `C1` and `C2`, both of them provide resident services.

- `C1`: a webui, which receives the user input, e.g. task categories: `[classification, detection]`
- `C2`: a pipeline manager, which generates **new (inner) pipelines** doing classification or detection tasks based on the user input.

Currently, I can't find an elegant way to launch new pipelines in `C2`.

---

I've tried your two solutions.

(1) using `kfp.components.create_graph_component_from_pipleine_func`

I guess you may want me to create an inner pipeline as below. This way can create a pipeline successfully. But the component functions of the inner pipeline are defined in the same scope of the outer pipeline.

```py
import kfp
import kfp.dsl as dsl
import kfp.components as comps
from typing import NamedTuple

EXP_NAME = 'automl'
RUN_NAME = 'outer_pipeline'


def add(a: int, b: int) -> NamedTuple('output', [('func_name', str), ('result', int)]):
    from collections import namedtuple
    output = namedtuple('output', ['func_name', 'result'])
    return output('add_two_numbers', a + b)


def show_result(func_name, result):
    print(f'{func_name} result: {result}')


def inner_pipeline_func(a: int, b: int):
    add_task = comps.create_component_from_func(add)(a, b)
    comps.create_component_from_func(show_result)(add_task.outputs['func_name'], add_task.outputs['result'])


@dsl.pipeline(name=RUN_NAME)
def pipeline_func(a: int, b: int):
    # create a componenet from inner pod
    create_pipeline_task = comps.create_graph_component_from_pipeline_func(inner_pipeline_func)(a, b)


if __name__ == '__main__':
    client = kfp.Client(host='my_k8s_master_ip:8888', namespace='kubeflow')
    client.create_run_from_pipeline_func(pipeline_func,
                                         arguments={
                                             'a': '1',
                                             'b': '2'
                                         },
                                         experiment_name=EXP_NAME,
                                         run_name=RUN_NAME)
    print('submit pipeline')
```

(2) Do not put pipeline code inside the component.

You're right. I can't define the inner pipeline code directly inside the component now. And this way https://github.com/kubeflow/pipelines/issues/5589#issuecomment-835101733 works by writing a complete inner pipeline code to a python file inside the container launched by the component. 

Next, I might try to define some template pipelines inside a customized container in advance.

Thanks again!

**Comment by Ark-kun** [comment]
>a pipeline manager, which generates new (inner) pipelines
Should it be *generating* new pipelines or just *launching* new pipeline runs? You can easily launch a pipeline or component from a component.

The issue only occurs when calling `create_component_from_func` inside function passed to `create_component_from_func`. It won't occur when they're called sequentially for example.

Could you create, say 5 components/pipelines for different tasks, then create a "manager" pipeline that launches one of them based on input?

**Comment by Ark-kun** [comment]
>I can't define the inner pipeline code directly inside the component now.
You cannot define it in the component function (used with `create_component_from_func `). But it can be anywhere else. E.g. You could load a function from a python module and use `create_component_from_func ` on it. Or you can download the source from GitHub. It's about the location of the source code. You cannot have component function source within component function source code. But only that is restricted.

**Comment by Ark-kun** [comment]
Another option to work around the issue - make either inner or outer component function without using `create_component_from_func` - you can create component.yaml directly.

**Comment by Shuai-Xie** [comment]
Hi @Ark-kun, thanks for your suggestion. I think I've got your points. The current python sdk features of kubeflow pipeline can meet my demands now. 

**In the past few days, I've connected the pipeline component functions with the native `@staticmethod` of python class. By doing this, I can define a `specific kubeflow pipeline template` with `a specific python class` now. And these self-defined template Pipeline Classes (e.g. `JobPipeline` below) will be included in a self-built container image `C1`. Then I can directly import a pre-defined pipeline in a component function by using `C1` container as the `base_image`. I don't need to inject the python code in this way https://github.com/kubeflow/pipelines/issues/5589#issuecomment-835101733 now.**


## Demo

Here is an example.

### 1. Define a `JobPipeline` class

I defined a `JobPipeline` class below. The component functions like `job_estimator()`, `task_estimator()` and `train()` are defined as static methods of this class.

```py
class JobPipeline:
    def __init__(self, job: Job, namespace: str = 'kubeflow', exp_name: str = 'Default', run_name: str = None) -> None:
        self.job = job
        self.name = self.job.job_args['job_name']
        self.namespace = namespace
        self.exp_name = exp_name
        self.run_name = run_name if run_name else self.name

        # ime images
        self.framework_image = config.framework_image
        self.kubekit_image = config.kubekit_image

        # constant pvc configs
        self.pvc_name = config.pvc_name
        self.pvc_mnt_path = '/mnt'

    @staticmethod
    def job_estimator(name: str,
                      pvc_name: str,
                      namespace: str,
                      job_container_image: str,
                      job_args: str,
                      job_worker_number: int,
                      job_resources_limits: str = None) -> None:
        import kubernetes.config as k8s_config
        from estimators import PytorchJobEstimator

        k8s_config.load_incluster_config()
        pytorch_job_estimator = PytorchJobEstimator(
            f'job-{name}',
            pvc_name,
            namespace,
            container_image=job_container_image,
            command=['python', 'examples/run_job_estimator.py'],
            args=job_args,
            worker_number=job_worker_number,
            # resources_limits=job_resources_limits,
            clean_as_finished=False)  # note must keep, or can't see pod logs in kubeflow
        pytorch_job_estimator.run()

    @staticmethod
    def task_estimator(name: str,
                       pvc_name: str,
                       namespace: str,
                       task_container_image: str,
                       task_args: str,
                       task_worker_number: int,
                       task_resources_limits: str = None) -> None:
        import kubernetes.config as k8s_config
        from estimators import PytorchJobEstimator

        k8s_config.load_incluster_config()
        pytorch_task_estimator = PytorchJobEstimator(
            f'task-{name}',
            pvc_name,
            namespace,
            container_image=task_container_image,
            command=['python', 'examples/run_task_estimator.py'],
            args=task_args,
            worker_number=task_worker_number,
            #  resources_limits=task_resources_limits,
            clean_as_finished=False)
        pytorch_task_estimator.run()

    @staticmethod
    def train() -> None:
        print('I am training with best candidates!')

    def pipeline_func(self,
                      name: str,
                      pvc_name: str,
                      namespace: str,
                      job_container_image: str,
                      task_container_image: str,
                      job_args: str,
                      task_args: str,
                      job_worker_number: int = 1,
                      task_worker_number: int = 1,
                      job_resources_limits: str = None,
                      task_resources_limits: str = None):
        job_op = func_to_container_op(self.job_estimator,
                                      base_image=self.kubekit_image)(name, pvc_name, namespace, job_container_image,
                                                                     job_args, job_worker_number, job_resources_limits)
        task_op = func_to_container_op(self.task_estimator,
                                       base_image=self.kubekit_image)(name, pvc_name, namespace, task_container_image,
                                                                      task_args, task_worker_number,
                                                                      task_resources_limits)
        train_op = func_to_container_op(self.train)()
        train_op.after(job_op)
        train_op.after(task_op)

    def run(self):
        client = kfp.Client(host=config.kfp_host)
        client.create_run_from_pipeline_func(
            self.pipeline_func,
            arguments={
                'name': self.name,
                'pvc_name': self.pvc_name,
                'namespace': self.namespace,
                'job_container_image': self.framework_image,
                'task_container_image': self.framework_image,
                'job_args': self.job.job_args,
                'task_args': self.job.task_args,
                'job_worker_number': self.job.job_worker_number,
                'task_worker_number': self.job.task_worker_number
            },
            experiment_name=self.exp_name,
            run_name=self.run_name)
        print('submit pipeline')
```

### 2. Using the `JobPipeline` class in a component function of the outer pipeline

The outer pipeline codes.

```py
import kfp
import kfp.dsl as dsl
from kfp.components import func_to_container_op

EXP_NAME = 'demo'
RUN_NAME = 'create_job_pipeline_in_pod'

def create_job_pipeline_in_pod():
    import Job, JobPipeline   # this class has been included in the C1 container

    job = Job(**kwargs)   # pass some args here
    job_pipeline = JobPipeline(job)    # instantiate the `job_pipeline` with a `job` object
    job_pipeline.run()

@dsl.pipeline(name=RUN_NAME)
def pipeline_func():
    # use C1 as the base image, which has included `Job` and `JobPipeline` classes
    create_op = func_to_container_op(create_job_pipeline_in_pod, base_image='C1')()

if __name__ == '__main__':
    client = kfp.Client(host='my_k8s_master_ip:8888')
    client.create_run_from_pipeline_func(pipeline_func,
                                         arguments={},
                                         experiment_name=EXP_NAME,
                                         run_name=RUN_NAME)
    print('submit pipeline')
```

In the above codes, after instantiating the `JobPipeline` class, I can get a specific pipeline based on the arguments defined in the `job` object. Then I can submit an inner pipeline run instance with ` job_pipeline.run()` method.

Below is the launched inner job pipeline. I guess this way can work with the component functions with return types, too.

![image](https://user-images.githubusercontent.com/18352713/119081713-2a400500-ba2f-11eb-9c35-0a8e0ae88d7c.png)


Best Regards.

**Comment by Ark-kun** [comment]
>(1) using kfp.components.create_graph_component_from_pipleine_func
>I guess you may want me to create an inner pipeline as below. This way can create a pipeline successfully. But the component functions of the inner pipeline are defined in the same scope of the outer pipeline.

I'm not sure I understand why this is a problem.

>two component functions, which are declared as staticmethod of this class.

Is there a reason why they cannot just be normal functions outside of the class? I'm not sure I understand why the class is needed.

P.S.
The low-level scenario you're showing seems pretty weird. I wonder whether there is a simpler way to do what you're doing.
For example, `func_to_container_op(self.add)(a, b)` is a pretty weird construct.
The usual flow is:

Create shareable components:
```python
def my_func1(): pass

create_component_from_func(my_func1, output_component_file='my_func1/component.yaml')
# Commit `component.yaml` and push to GitHub
```
[Optional] then optionally build a pipeline component:

```
my_func1_op = load_component_from_url('https://.../my_func1/component.yaml')
my_func2_op = load_component_from_url('https://.../my_func2/component.yaml')

def my_graph1():
    result1 = my_func1_op().outputs['out11']
    result2 = my_func2_op().outputs['out21']
    return {
      'GraphOut1': result1,
      'GraphOut2': result2,
    }

create_graph_component_from_pipeline_func(my_graph1, output_component_file='my_graph1/component.yaml')
# Commit `component.yaml` and push to GitHub
```

Then write a pipeline
```python
my_graph1_op = load_component_from_url('https://.../my_graph1/component.yaml')
my_func3_op = load_component_from_url('https://.../my_func3/component.yaml')

def my_pipeline():
  graph_result1 = my_graph1_op().outputs['GraphOut1']
  my_func3_op(in1=graph_result1 )
```
and submit it for execution:
```python
kfp.Client().create_run_from_pipeline_func(my_pipeline)
```
Or compile it:
```python
kfp.compiler.Compiler()compile(my_pipeline, 'my.pipeline.yaml')
```
And submit the compiled pipeline:
```python
kfp.Client().create_run_from_pipeline_package('my.pipeline.yaml')
```

Things are built step by step. Components are reused between pipelines (and graph components).

I'm not sure I understand the need to do everything recursively, not just sequentially.

**Comment by Shuai-Xie** [comment]
Hi, @Ark-kun. Thanks for your quick reply. I agree with the above pipeline-construct process.

>Is there a reason why they cannot just be normal functions outside of the class? I'm not sure I understand why the class is needed.

Of course, they can. Perhaps the reason for my weird way is that I what to include everything need to construct a pipeline in a class scope :joy:. It can make the codes in `create_job_pipeline_in_pod()` simpler.

All in all, my problem has been solved with your help.

Many thanks. Hope you will enjoy a good weekend :blush:.
