### ISSUE TITLE
[backend] Pipelines 1.5.0 api-server argo version mismatch & samples cannot be compiled

### ISSUE THREAD

**Issue by mgiessing** [kubeflow/pipelines#5590]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
Pipelines is not yet deployed, I want to build the api-server docker image
*  KFP version: 
1.5.0
*  KFP SDK version: 
1.5.0
### Steps to reproduce

Difficult to reproduce as you'd need a ppc64le system, however that problem is not related to the underlying platform as the error indicates a wrong argo version and also happened on x86-Macbook Pro. Essentially these steps have been performed

```
git clone https://github.com/kubeflow/pipelines.git
cd pipelines && git checkout 1.5.0
## changing some ppc64le specifics in the dockerfile ##
docker build -t api-server:1.5.0.ppc64le -f backend/Dockerfile .
```

I've also build the image on my x86-Macbook and get the same errors during the `dsl-compile ...` command 

See:

https://github.com/kubeflow/pipelines/blob/1.5.0/backend/Dockerfile#L35

and especially this line fails:

https://github.com/kubeflow/pipelines/blob/1.5.0/backend/Dockerfile#L40

### Expected result

I'd expect the to run without issues

#### Error output / docker build log ppc64le-linux
```
[...]
Step 27/42 : RUN set -e;     < /samples/sample_config.json jq .[].file --raw-output | while read pipeline_yaml; do         pipeline_py="${pipeline_yaml%.yaml}";         mv "$pipeline_py" "${pipeline_py}.tmp"; 	echo 'import kfp; kfp.components.default_base_image_or_builder="gcr.io/google-appengine/python:2020-03-31-141326"' | cat - "${pipeline_py}.tmp" > "$pipeline_py"; 	/bin/bash -c "source activate py37 && dsl-compile --py \"$pipeline_py\" --output \"$pipeline_yaml\" || python3 \"$pipeline_py\"";     done
 ---> Running in eb21ce3bd146
/root/miniconda3/envs/py37/lib/python3.7/site-packages/kfp-1.5.0-py3.7.egg/kfp/compiler/compiler.py:1117: UserWarning: Cannot validate the compiled workflow. Found the argo program in PATH, but it's not usable. argo v2.4.3 should work.
  warnings.warn("Cannot validate the compiled workflow. Found the argo program in PATH, but it's not usable. argo v2.4.3 should work.")
WARNING:absl:RuntimeParameter is only supported on Cloud-based DAG runner currently.
WARNING:absl:RuntimeParameter is only supported on Cloud-based DAG runner currently.
WARNING:absl:RuntimeParameter is only supported on Cloud-based DAG runner currently.
Traceback (most recent call last):
  File "/root/miniconda3/envs/py37/bin/dsl-compile", line 33, in <module>
    sys.exit(load_entry_point('kfp==1.5.0', 'console_scripts', 'dsl-compile')())
  File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/kfp-1.5.0-py3.7.egg/kfp/compiler/main.py", line 104, in main
    not args.disable_type_check,
  File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/kfp-1.5.0-py3.7.egg/kfp/compiler/main.py", line 91, in compile_pyfile
    _compile_pipeline_function(pipeline_funcs, function_name, output_path, type_check)
  File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/kfp-1.5.0-py3.7.egg/kfp/compiler/main.py", line 54, in _compile_pipeline_function
    raise ValueError('A function with @dsl.pipeline decorator is required in the py file.')
ValueError: A function with @dsl.pipeline decorator is required in the py file.
WARNING:absl:RuntimeParameter is only supported on Cloud-based DAG runner currently.
WARNING:absl:RuntimeParameter is only supported on Cloud-based DAG runner currently.
WARNING:absl:RuntimeParameter is only supported on Cloud-based DAG runner currently.
WARNING:absl:From /samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py:75: external_input (from tfx.utils.dsl_utils) is deprecated and will be removed in a future version.
Instructions for updating:
external_input is deprecated, directly pass the uri to ExampleGen.
WARNING:absl:The "input" argument to the CsvExampleGen component has been deprecated by "input_base". Please update your usage as support for this argument will be removed soon.
/root/miniconda3/envs/py37/lib/python3.7/site-packages/kfp-1.5.0-py3.7.egg/kfp/compiler/compiler.py:1117: UserWarning: Cannot validate the compiled workflow. Found the argo program in PATH, but it's not usable. argo v2.4.3 should work.
  warnings.warn("Cannot validate the compiled workflow. Found the argo program in PATH, but it's not usable. argo v2.4.3 should work.")
Traceback (most recent call last):
  File "/root/miniconda3/envs/py37/bin/dsl-compile", line 33, in <module>
    sys.exit(load_entry_point('kfp==1.5.0', 'console_scripts', 'dsl-compile')())
  File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/kfp-1.5.0-py3.7.egg/kfp/compiler/main.py", line 104, in main
    not args.disable_type_check,
  File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/kfp-1.5.0-py3.7.egg/kfp/compiler/main.py", line 91, in compile_pyfile
    _compile_pipeline_function(pipeline_funcs, function_name, output_path, type_check)
  File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/kfp-1.5.0-py3.7.egg/kfp/compiler/main.py", line 54, in _compile_pipeline_function
    raise ValueError('A function with @dsl.pipeline decorator is required in the py file.')
ValueError: A function with @dsl.pipeline decorator is required in the py file.
/root/miniconda3/envs/py37/lib/python3.7/site-packages/kfp-1.5.0-py3.7.egg/kfp/compiler/compiler.py:1117: UserWarning: Cannot validate the compiled workflow. Found the argo program in PATH, but it's not usable. argo v2.4.3 should work.
  warnings.warn("Cannot validate the compiled workflow. Found the argo program in PATH, but it's not usable. argo v2.4.3 should work.")
Traceback (most recent call last):
  File "/root/miniconda3/envs/py37/bin/dsl-compile", line 33, in <module>
    sys.exit(load_entry_point('kfp==1.5.0', 'console_scripts', 'dsl-compile')())
  File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/kfp-1.5.0-py3.7.egg/kfp/compiler/main.py", line 104, in main
    not args.disable_type_check,
  File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/kfp-1.5.0-py3.7.egg/kfp/compiler/main.py", line 91, in compile_pyfile
    _compile_pipeline_function(pipeline_funcs, function_name, output_path, type_check)
  File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/kfp-1.5.0-py3.7.egg/kfp/compiler/main.py", line 58, in _compile_pipeline_function
    raise ValueError('There are multiple pipelines: %s. Please specify --function.' % func_names)
ValueError: There are multiple pipelines: ['flipcoin_pipeline', 'flipcoin_exit_pipeline']. Please specify --function.
/root/miniconda3/envs/py37/lib/python3.7/site-packages/kfp-1.5.0-py3.7.egg/kfp/compiler/compiler.py:1117: UserWarning: Cannot validate the compiled workflow. Found the argo program in PATH, but it's not usable. argo v2.4.3 should work.
  warnings.warn("Cannot validate the compiled workflow. Found the argo program in PATH, but it's not usable. argo v2.4.3 should work.")
Removing intermediate container eb21ce3bd146
 ---> 6bd1cd1530e1
Step 28/42 : FROM ppc64le/debian:stretch
[...]
```

#### Error output / docker build log x86-Macbook

```
[...]
Step 21/36 : RUN set -e;     < /samples/sample_config.json jq .[].file --raw-output | while read pipeline_yaml; do         pipeline_py="${pipeline_yaml%.yaml}";         mv "$pipeline_py" "${pipeline_py}.tmp";         echo 'import kfp; kfp.components.default_base_image_or_builder="gcr.io/google-appengine/python:2020-03-31-141326"' | cat - "${pipeline_py}.tmp" > "$pipeline_py";         dsl-compile --py "$pipeline_py" --output "$pipeline_yaml" || python3 "$pipeline_py";     done
 ---> Running in a008c231c82d
/usr/local/lib/python3.7/site-packages/kfp-1.5.0-py3.7.egg/kfp/compiler/compiler.py:1117: UserWarning: Cannot validate the compiled workflow. Found the argo program in PATH, but it's not usable. argo v2.4.3 should work.
  warnings.warn("Cannot validate the compiled workflow. Found the argo program in PATH, but it's not usable. argo v2.4.3 should work.")
2021-05-05 11:10:07.987152: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-05 11:10:07.987241: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING:absl:RuntimeParameter is only supported on Cloud-based DAG runner currently.
WARNING:absl:RuntimeParameter is only supported on Cloud-based DAG runner currently.
WARNING:absl:RuntimeParameter is only supported on Cloud-based DAG runner currently.
Traceback (most recent call last):
  File "/usr/local/bin/dsl-compile", line 33, in <module>
    sys.exit(load_entry_point('kfp==1.5.0', 'console_scripts', 'dsl-compile')())
  File "/usr/local/lib/python3.7/site-packages/kfp-1.5.0-py3.7.egg/kfp/compiler/main.py", line 104, in main
    not args.disable_type_check,
  File "/usr/local/lib/python3.7/site-packages/kfp-1.5.0-py3.7.egg/kfp/compiler/main.py", line 91, in compile_pyfile
    _compile_pipeline_function(pipeline_funcs, function_name, output_path, type_check)
  File "/usr/local/lib/python3.7/site-packages/kfp-1.5.0-py3.7.egg/kfp/compiler/main.py", line 54, in _compile_pipeline_function
    raise ValueError('A function with @dsl.pipeline decorator is required in the py file.')
ValueError: A function with @dsl.pipeline decorator is required in the py file.
2021-05-05 11:10:13.142424: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-05 11:10:13.142485: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING:absl:RuntimeParameter is only supported on Cloud-based DAG runner currently.
WARNING:absl:RuntimeParameter is only supported on Cloud-based DAG runner currently.
WARNING:absl:RuntimeParameter is only supported on Cloud-based DAG runner currently.
WARNING:absl:From /samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py:75: external_input (from tfx.utils.dsl_utils) is deprecated and will be removed in a future version.
Instructions for updating:
external_input is deprecated, directly pass the uri to ExampleGen.
WARNING:absl:The "input" argument to the CsvExampleGen component has been deprecated by "input_base". Please update your usage as support for this argument will be removed soon.
/usr/local/lib/python3.7/site-packages/kfp-1.5.0-py3.7.egg/kfp/compiler/compiler.py:1117: UserWarning: Cannot validate the compiled workflow. Found the argo program in PATH, but it's not usable. argo v2.4.3 should work.
  warnings.warn("Cannot validate the compiled workflow. Found the argo program in PATH, but it's not usable. argo v2.4.3 should work.")
Traceback (most recent call last):
  File "/usr/local/bin/dsl-compile", line 33, in <module>
    sys.exit(load_entry_point('kfp==1.5.0', 'console_scripts', 'dsl-compile')())
  File "/usr/local/lib/python3.7/site-packages/kfp-1.5.0-py3.7.egg/kfp/compiler/main.py", line 104, in main
    not args.disable_type_check,
  File "/usr/local/lib/python3.7/site-packages/kfp-1.5.0-py3.7.egg/kfp/compiler/main.py", line 91, in compile_pyfile
    _compile_pipeline_function(pipeline_funcs, function_name, output_path, type_check)
  File "/usr/local/lib/python3.7/site-packages/kfp-1.5.0-py3.7.egg/kfp/compiler/main.py", line 54, in _compile_pipeline_function
    raise ValueError('A function with @dsl.pipeline decorator is required in the py file.')
ValueError: A function with @dsl.pipeline decorator is required in the py file.
/usr/local/lib/python3.7/site-packages/kfp-1.5.0-py3.7.egg/kfp/compiler/compiler.py:1117: UserWarning: Cannot validate the compiled workflow. Found the argo program in PATH, but it's not usable. argo v2.4.3 should work.
  warnings.warn("Cannot validate the compiled workflow. Found the argo program in PATH, but it's not usable. argo v2.4.3 should work.")
Traceback (most recent call last):
  File "/usr/local/bin/dsl-compile", line 33, in <module>
    sys.exit(load_entry_point('kfp==1.5.0', 'console_scripts', 'dsl-compile')())
  File "/usr/local/lib/python3.7/site-packages/kfp-1.5.0-py3.7.egg/kfp/compiler/main.py", line 104, in main
    not args.disable_type_check,
  File "/usr/local/lib/python3.7/site-packages/kfp-1.5.0-py3.7.egg/kfp/compiler/main.py", line 91, in compile_pyfile
    _compile_pipeline_function(pipeline_funcs, function_name, output_path, type_check)
  File "/usr/local/lib/python3.7/site-packages/kfp-1.5.0-py3.7.egg/kfp/compiler/main.py", line 58, in _compile_pipeline_function
    raise ValueError('There are multiple pipelines: %s. Please specify --function.' % func_names)
ValueError: There are multiple pipelines: ['flipcoin_pipeline', 'flipcoin_exit_pipeline']. Please specify --function.
/usr/local/lib/python3.7/site-packages/kfp-1.5.0-py3.7.egg/kfp/compiler/compiler.py:1117: UserWarning: Cannot validate the compiled workflow. Found the argo program in PATH, but it's not usable. argo v2.4.3 should work.
  warnings.warn("Cannot validate the compiled workflow. Found the argo program in PATH, but it's not usable. argo v2.4.3 should work.")
Removing intermediate container a008c231c82d
 ---> 6ab54eda2f90
Step 22/36 : FROM debian:stretch
[...]
```

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by Bobgy** [comment]
Hi @mgiessing, this issue has been fixed in latest version. Can you confirm?
