### ISSUE TITLE
[05/07/2021] Presubmit failure: kubeflow-pipelines-tfx-python36

### ISSUE THREAD

**Issue by chensun** [kubeflow/pipelines#5614]
https://oss-prow.knative.dev/view/gs/oss-prow/pr-logs/pull/kubeflow_pipelines/5594/kubeflow-pipelines-tfx-python36/1390893518523731968
```
Traceback (most recent call last):
  File "kubeflow_dag_runner_test.py", line 26, in <module>
    from tfx.extensions.google_cloud_big_query.example_gen import component as big_query_example_gen_component
  File "/usr/local/lib/python3.6/site-packages/tfx/extensions/google_cloud_big_query/example_gen/component.py", line 26, in <module>
    from tfx.extensions.google_cloud_big_query.example_gen import executor
  File "/usr/local/lib/python3.6/site-packages/tfx/extensions/google_cloud_big_query/example_gen/executor.py", line 26, in <module>
    from google.cloud import bigquery
  File "/usr/local/lib/python3.6/site-packages/google/cloud/bigquery/__init__.py", line 35, in <module>
    from google.cloud.bigquery.client import Client
  File "/usr/local/lib/python3.6/site-packages/google/cloud/bigquery/client.py", line 59, in <module>
    from google.cloud.bigquery import _pandas_helpers
  File "/usr/local/lib/python3.6/site-packages/google/cloud/bigquery/_pandas_helpers.py", line 44, in <module>
    from google.cloud.bigquery import schema
  File "/usr/local/lib/python3.6/site-packages/google/cloud/bigquery/schema.py", line 19, in <module>
    from google.cloud.bigquery_v2 import types
  File "/usr/local/lib/python3.6/site-packages/google/cloud/bigquery_v2/__init__.py", line 19, in <module>
    from .types.encryption_config import EncryptionConfiguration
  File "/usr/local/lib/python3.6/site-packages/google/cloud/bigquery_v2/types/__init__.py", line 18, in <module>
    from .encryption_config import EncryptionConfiguration
  File "/usr/local/lib/python3.6/site-packages/google/cloud/bigquery_v2/types/encryption_config.py", line 24, in <module>
    __protobuf__ = proto.module(
AttributeError: module 'proto' has no attribute 'module'
```

/area testing

**Comment by chensun** [comment]
The test started to fail when we have `google-cloud-bigquery` 2.16.0 installed, and that is a result of https://github.com/tensorflow/tfx/pull/3644
Previous succeeded runs have `google-cloud-bigquery` 1.28.0. 

If I'm not mistaken, the module `proto` from `AttributeError: module 'proto' has no attribute 'module'` should be from [proto-plus](https://pypi.org/project/proto-plus/), and we installed `proto-plus-1.18.1` per https://github.com/kubeflow/pipelines/issues/5614#issuecomment-835179329.

Looking at [this code](https://github.com/googleapis/proto-plus-python/blob/e25dd7d65273a834f66d3be0445b88011103dc81/proto/__init__.py#L21), `proto.module` should exist. And this line has been there for a long time.

So now I suspect there was some other module or likely a variable named `proto` that shadowed this `proto` module package `proto-plus`.

For a temporary fix, we can pin to use `google-cloud-bigquery<2`: https://github.com/kubeflow/pipelines/pull/5616
