### ISSUE TITLE
[bug] Broken pipe when using AI platform training operator

### ISSUE THREAD

**Issue by zygm0nt** [kubeflow/pipelines#5694]
### What steps did you take

Start a long-running job on AI platform and have it succeed, to be able to progress to subsequent steps.

I have a job defined using this operator:

```
mlengine_train_op = kfp.components.load_component_from_url(
    'https://raw.githubusercontent.com/kubeflow/pipelines/master/components/gcp/ml_engine/train/component.yaml')
```

and I start it with the following parameters set (note that I'm running the job from docker image):

```
mlengine_train_op(
        name="",
        project_id=project_id,
        region=region,
        job_dir=job_dir,
        master_image_uri=master_image_uri,
        training_input=training_input,
        job_id=job_id,
        wait_interval=wait_interval
```

### What happened:
After some time the job fails with the following error - this is roughly an hour.
```
INFO:root:job status is RUNNING, wait for 30s
INFO:googleapiclient.discovery:URL being requested: GET 
https://ml.googleapis.com/v1/projects/xxx/jobs/xxxyyy_20210518_17000?alt=json
Traceback (most recent call last):
  File "/ml/kfp_component/google/ml_engine/_client.py", line 40, in wrapper
    return func(self, *args, **kwargs)
  File "/ml/kfp_component/google/ml_engine/_client.py", line 113, in get_job
    name=job_name).execute()
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 846, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 183, in _retry_request
    raise exception
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 164, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google_auth_httplib2.py", line 209, in request
    self.credentials.before_request(self._request, method, uri, request_headers)
  File "/usr/local/lib/python3.7/site-packages/google/auth/credentials.py", line 133, in before_request
    self.refresh(request)
  File "/usr/local/lib/python3.7/site-packages/google/auth/compute_engine/credentials.py", line 111, in refresh
    self._retrieve_info(request)
  File "/usr/local/lib/python3.7/site-packages/google/auth/compute_engine/credentials.py", line 88, in _retrieve_info
    request, service_account=self._service_account_email
  File "/usr/local/lib/python3.7/site-packages/google/auth/compute_engine/_metadata.py", line 234, in get_service_account_info
    return get(request, path, params={"recursive": "true"})
  File "/usr/local/lib/python3.7/site-packages/google/auth/compute_engine/_metadata.py", line 150, in get
    response = request(url=url, method="GET", headers=_METADATA_HEADERS)
  File "/usr/local/lib/python3.7/site-packages/google_auth_httplib2.py", line 120, in __call__
    url, method=method, body=body, headers=headers, **kwargs
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 1724, in new_request
    redirections, connection_type)
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1991, in request
    cachekey,
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1651, in _request
    conn, request_uri, method, body, headers
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1558, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1032, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 993, in send
    self.sock.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/ml/kfp_component/launcher/__main__.py", line 45, in <module>
    main()
  File "/ml/kfp_component/launcher/__main__.py", line 42, in main
    launch(args.file_or_module, args.args)
  File "/ml/kfp_component/launcher/launcher.py", line 45, in launch
    return fire.Fire(module, command=args, name=module.__name__)
  File "/usr/local/lib/python3.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/usr/local/lib/python3.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/usr/local/lib/python3.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "/ml/kfp_component/google/ml_engine/_train.py", line 105, in train
    job_dir_output_path=job_dir_output_path)
  File "/ml/kfp_component/google/ml_engine/_create_job.py", line 62, in create_job
    job_dir_output_path=job_dir_output_path,
  File "/ml/kfp_component/google/ml_engine/_create_job.py", line 89, in execute_and_wait
    job_dir_output_path=self._job_dir_output_path,
  File "/ml/kfp_component/google/ml_engine/_common_ops.py", line 93, in wait_for_job_done
    job = ml_client.get_job(project_id, job_id)
  File "/ml/kfp_component/google/ml_engine/_client.py", line 48, in wrapper
    e._class__.__name__, _delay
AttributeError: 'BrokenPipeError' object has no attribute '_class__
```

### What did you expect to happen:

Correct job tracking behaviour. The job itself is still running in AI platform, and finishes successfully after some more time - this particular job takes around 2h30min to complete.

### Environment:

*  How do you deploy Kubeflow Pipelines (KFP)? 

Deployed to GCP

*  KFP version: 

1.4.1

*  KFP SDK version: 

1.4.0

### Labels

/area frontend 

/area components

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by zygm0nt** [comment]
I see this was solved by a previous CR: https://github.com/kubeflow/pipelines/issues/5085
