### ISSUE TITLE
[sdk] compile() got an unexpected keyword argument 'mode'

### ISSUE THREAD

**Issue by lambertsbennett** [kubeflow/pipelines#5706]
### Environment
I have a minikube cluster running on a linux server (Ubuntu 18.04) where kubeflow pipelines is running. I am connected via an ssh tunnel from my laptop running Windows 10. I am writing code in Python 3.8.5. I can connect with kf pipelines and list current experiments/runs and all that from my environment. I also previously used function-based components and was able to submit those to KFP for execution.

*  KFP version: 1.5.0

*  KFP SDK version:  1.6.2

### Steps to reproduce
I am new to kfp, so I tried to model my own pipeline after the example found here: https://www.kubeflow.org/docs/components/pipelines/sdk/v2/build-pipeline/

When I run:

```  
    compiler.Compiler().compile(
    pipeline_func=prophet_pipeline,
    package_path='prophet-test.yaml',
    mode=kfp.dsl.PipelineExecutionMode.V2_COMPATIBLE
    )

   client.create_run_from_pipeline_package('prophet-test.yaml', arguments=arguments)  

```

I get the error:
```
Traceback (most recent call last):
  File "kfp_prophet.py", line 138, in <module>
    run_pipeline(args.path)
  File "kfp_prophet.py", line 126, in run_pipeline
    client.create_run_from_pipeline_package('prophet-test.json', arguments=arguments)
  File "\lib\site-packages\kfp\_client.py", line 843, in create_run_from_pipeline_package
    run_info = self.run_pipeline(
  File "\Anaconda3\lib\site-packages\kfp\_client.py", line 603, in run_pipeline
    job_config = self._create_job_config(
  File "\Anaconda3\lib\site-packages\kfp\_client.py", line 706, in _create_job_config
    pipeline_obj = self._extract_pipeline_yaml(pipeline_package_path)
  File "\Anaconda3\lib\site-packages\kfp\_client.py", line 532, in _extract_pipeline_yaml
    raise ValueError('The package_file '+ package_file + ' should end with one of the following formats: [.tar.gz, .tgz, .zip, .yaml, .yml]')
ValueError: The package_file prophet-test.json should end with one of the following formats: [.tar.gz, .tgz, .zip, .yaml, .yml]

Prophet> python kfp_prophet.py --f data.pkl
Traceback (most recent call last):
  File "kfp_prophet.py", line 131, in <module>
    compiler.Compiler().compile(
TypeError: compile() got an unexpected keyword argument 'mode'
```

### Expected result

The pipeline should be compiled and submitted to KFP for execution.

### Materials and Reference

I followed the example provided here https://www.kubeflow.org/docs/components/pipelines/sdk/v2/build-pipeline/ and modified it to execute my own code.

Thanks for your help! I can provide more code snippets if necessary to debug the issue.

**Comment by lambertsbennett** [comment]
Also, if I change the package_path to 'prophet-test.yaml' the upper error disappears, but the compiler error remains.

**Comment by lambertsbennett** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

To my knowledge this has not been resolved.
