### ISSUE TITLE
[bug] VertexAI Pipeline does not work ContainerOp

### ISSUE THREAD

**Issue by TrsNium** [kubeflow/pipelines#5727]
### What steps did you take
If you run the following code, you will get an error
```python
import kfp.v2.dsl as dsl
from kfp.v2 import compiler
from kfp.v2.google.client import AIPlatformClient


pipeline_root_path = ....
@dsl.pipeline(
    name="hello-world",
    description="test",
    pipeline_root=pipeline_root_path
)
def pipeline():
    dsl.ContainerOp(
        name="whalesay",
        image="docker/whalesay:latest",
        command=["cowsay"],
        arguments=["hello world"])

client = AIPlatformClient(project_id=MyProject, region="asia-east1")
with tempfile.TemporaryDirectory() as tmpdir:
    pipeline_package_path = os.path.join(tmpdir, 'pipeline.json')
    compiler.Compiler().compile(pipeline_func=pipeline, package_path=pipeline_package_path)
    client.create_run_from_job_spec(pipeline_package_path,)
```

### What happened:
The error message is as follows.
```
Traceback (most recent call last):
  File "/Users/takuya.hirata/.pyenv/versions/3.7.1rc1/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/takuya.hirata/.pyenv/versions/3.7.1rc1/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "pipelines/test/__main__.py", line 43, in <module>
    app()
  File "/Users/takuya.hirata/.pyenv/versions/3.7.1rc1/lib/python3.7/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Users/takuya.hirata/.pyenv/versions/3.7.1rc1/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/takuya.hirata/.pyenv/versions/3.7.1rc1/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/takuya.hirata/.pyenv/versions/3.7.1rc1/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/takuya.hirata/.pyenv/versions/3.7.1rc1/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/takuya.hirata/.pyenv/versions/3.7.1rc1/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/takuya.hirata/.pyenv/versions/3.7.1rc1/lib/python3.7/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "pipelines/test/__main__.py", line 34, in create_run
    parameter_values={},
  File "pipelines/test/../client_wrapper.py", line 38, in create_run_from_pipeline_func
    labels
  File "/Users/takuya.hirata/.pyenv/versions/3.7.1rc1/lib/python3.7/site-packages/kfp/v2/google/client/client.py", line 344, in create_run_from_job_spec
    job_id=job_id,
  File "/Users/takuya.hirata/.pyenv/versions/3.7.1rc1/lib/python3.7/site-packages/kfp/v2/google/client/client.py", line 228, in _submit_job
    response = request.execute()
  File "/Users/takuya.hirata/.pyenv/versions/3.7.1rc1/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/takuya.hirata/.pyenv/versions/3.7.1rc1/lib/python3.7/site-packages/googleapiclient/http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://asia-east1-aiplatform.googleapis.com/v1beta1/projects/MyProject/locations/asia-east1/pipelineJobs?pipelineJobId=hello-world-20210524165548&alt=json returned "Exactly one of deployment_config and deployment_spec is expected.">
```

### What did you expect to happen:
Successful deploy of the pipeline

### Environment:

*  KFP SDK version: 
* 1.6.2

If I have a problem with vertex ai pipelines, is it okay to create an issue in this repository?

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by Ark-kun** [comment]
Hello.
Thank you for trying Vertex AI.
Directly creating instances of `ContainerOp` has been deprecated for ~11 months.  See https://github.com/kubeflow/pipelines/pull/4166

Could you please use components instead? The comment in https://github.com/kubeflow/pipelines/pull/4166/files provides some examples of conversion.

**Comment by neuromage** [comment]
Hi @TrsNium,

Thanks for filing the bug. Yes, please feel free to file bugs against vertex AI here. 

Unfortunately, ContainerOp isn't supported going forward. For now, you should be able to write it like so instead:

```
import kfp
whalesay = kfp.components.load_component_from_text('''
name: WhaleSay
implementation:
  container:
    image: docker/whalesay:latest
    command:
    - cowsay
    - hello world
''')

@dsl.pipeline(
    name="hello-world",
    description="test",
    pipeline_root=pipeline_root_path
)
def pipeline():
   whalesay_op = whalesay()
```


We're working on adding back a drop-in replacement asap so you won't need to write a yaml text for container components like this going forward. Please stay tuned. In the meantime, @chensun, can we throw a more useful error in this case for the user?

**Comment by ritaarex** [comment]
Hi,

I have a similar issue, but I can't seem to be able to fix this. I am following the codelab [Intro to Vertex AI pipelines](https://codelabs.developers.google.com/vertex-pipelines-intro#0). At the final step, when I try to run the pipeline, I get the following error:
`HttpError: <HttpError 404 when requesting https://eu-aiplatform.googleapis.com/v1beta1/projects/arex-data/locations/eu/pipelineJobs?pipelineJobId=hello-world-20210909102517&alt=json returned "Not Found">`

Here is the code from my notebook:

```
@dsl.pipeline(
    name="hello-world",
    description="An intro pipeline",
    pipeline_root=PIPELINE_ROOT,
)

def intro_pipeline(text: str = "Vertex Pipelines", emoji_str: str = "sparkles"):
    product_task = product_name(text)
    emoji_task = emoji(emoji_str)
    consumer_task = build_sentence(
        product_task.output,
        emoji_task.outputs["emoji"],
        emoji_task.outputs["emoji_text"],
    )

compiler.Compiler().compile(
    pipeline_func=intro_pipeline, package_path="intro_pipeline_job.json"
)

api_client = AIPlatformClient(
    project_id=PROJECT_ID,
    region=REGION,
)
response = api_client.create_run_from_job_spec(
    job_spec_path="intro_pipeline_job.json",
    # pipeline_root=PIPELINE_ROOT  # this argument is necessary if you did not specify PIPELINE_ROOT as part of the pipeline definition.
)
```
Any ideas what might be the issue? Thanks!
