### ISSUE TITLE
[sdk] kfp cli giving errors

### ISSUE THREAD

**Issue by Ruminateer** [kubeflow/pipelines#5774]
### Environment

*  KFP version: 1.6.0

*  KFP SDK version:  1.4.0

*  All dependencies version:

```console
$ pip list | grep kfp
kfp                       1.4.0
kfp-pipeline-spec         0.1.7
kfp-server-api            1.5.0
```

### Steps to reproduce
Installed Kubeflow pipeline on an existing cluster. Installed SDK
```console
export PIPELINE_VERSION=1.6.0
kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=$PIPELINE_VERSION"
kubectl wait --for condition=established --timeout=60s crd/applications.app.k8s.io
kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/env/dev?ref=$PIPELINE_VERSION"
pip3 install kfp --upgrade
```

Got these errors. What I am doing wrong? Have no idea how to solve it.
```console
$ kfp run list
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.5) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Failed to get healthz info attempt 1 of 5.
Traceback (most recent call last):
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp/_client.py", line 312, in get_kfp_healthz
    response = self._healthz_api.get_healthz()
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api/healthz_service_api.py", line 63, in get_healthz
    return self.get_healthz_with_http_info(**kwargs)  # noqa: E501
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api/healthz_service_api.py", line 134, in get_healthz_with_http_info
    return self.api_client.call_api(
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 364, in call_api
    return self.__call_api(resource_path, method,
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 188, in __call_api
    raise e
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 181, in __call_api
    response_data = self.request(
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 389, in request
    return self.rest_client.GET(url,
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/rest.py", line 230, in GET
    return self.request("GET", url,
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/rest.py", line 224, in request
    raise ApiException(http_resp=r)
kfp_server_api.exceptions.ApiException: (503)
Reason: Service Unavailable
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Wed, 02 Jun 2021 07:23:00 GMT', 'Content-Length': '178'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"no endpoints available for service \"ml-pipeline:http\"","reason":"ServiceUnavailable","code":503}


Failed to get healthz info attempt 2 of 5.
Traceback (most recent call last):
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp/_client.py", line 312, in get_kfp_healthz
    response = self._healthz_api.get_healthz()
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api/healthz_service_api.py", line 63, in get_healthz
    return self.get_healthz_with_http_info(**kwargs)  # noqa: E501
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api/healthz_service_api.py", line 134, in get_healthz_with_http_info
    return self.api_client.call_api(
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 364, in call_api
    return self.__call_api(resource_path, method,
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 188, in __call_api
    raise e
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 181, in __call_api
    response_data = self.request(
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 389, in request
    return self.rest_client.GET(url,
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/rest.py", line 230, in GET
    return self.request("GET", url,
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/rest.py", line 224, in request
    raise ApiException(http_resp=r)
kfp_server_api.exceptions.ApiException: (503)
Reason: Service Unavailable
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Wed, 02 Jun 2021 07:23:05 GMT', 'Content-Length': '178'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"no endpoints available for service \"ml-pipeline:http\"","reason":"ServiceUnavailable","code":503}


^C
Aborted!
$ kfp -n default run list
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.5) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Failed to get healthz info attempt 1 of 5.
Traceback (most recent call last):
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp/_client.py", line 312, in get_kfp_healthz
    response = self._healthz_api.get_healthz()
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api/healthz_service_api.py", line 63, in get_healthz
    return self.get_healthz_with_http_info(**kwargs)  # noqa: E501
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api/healthz_service_api.py", line 134, in get_healthz_with_http_info
    return self.api_client.call_api(
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 364, in call_api
    return self.__call_api(resource_path, method,
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 188, in __call_api
    raise e
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 181, in __call_api
    response_data = self.request(
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 389, in request
    return self.rest_client.GET(url,
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/rest.py", line 230, in GET
    return self.request("GET", url,
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/rest.py", line 224, in request
    raise ApiException(http_resp=r)
kfp_server_api.exceptions.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Wed, 02 Jun 2021 07:23:25 GMT', 'Content-Length': '198'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services \"ml-pipeline\" not found","reason":"NotFound","details":{"name":"ml-pipeline","kind":"services"},"code":404}


Failed to get healthz info attempt 2 of 5.
Traceback (most recent call last):
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp/_client.py", line 312, in get_kfp_healthz
    response = self._healthz_api.get_healthz()
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api/healthz_service_api.py", line 63, in get_healthz
    return self.get_healthz_with_http_info(**kwargs)  # noqa: E501
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api/healthz_service_api.py", line 134, in get_healthz_with_http_info
    return self.api_client.call_api(
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 364, in call_api
    return self.__call_api(resource_path, method,
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 188, in __call_api
    raise e
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 181, in __call_api
    response_data = self.request(
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 389, in request
    return self.rest_client.GET(url,
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/rest.py", line 230, in GET
    return self.request("GET", url,
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/rest.py", line 224, in request
    raise ApiException(http_resp=r)
kfp_server_api.exceptions.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Wed, 02 Jun 2021 07:23:30 GMT', 'Content-Length': '198'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services \"ml-pipeline\" not found","reason":"NotFound","details":{"name":"ml-pipeline","kind":"services"},"code":404}


^C
Aborted!
$ kfp -n default run submit -e Default -w -f mnist.py.yml
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.5) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Failed to get healthz info attempt 1 of 5.
Traceback (most recent call last):
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp/_client.py", line 312, in get_kfp_healthz
    response = self._healthz_api.get_healthz()
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api/healthz_service_api.py", line 63, in get_healthz
    return self.get_healthz_with_http_info(**kwargs)  # noqa: E501
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api/healthz_service_api.py", line 134, in get_healthz_with_http_info
    return self.api_client.call_api(
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 364, in call_api
    return self.__call_api(resource_path, method,
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 188, in __call_api
    raise e
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 181, in __call_api
    response_data = self.request(
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 389, in request
    return self.rest_client.GET(url,
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/rest.py", line 230, in GET
    return self.request("GET", url,
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/rest.py", line 224, in request
    raise ApiException(http_resp=r)
kfp_server_api.exceptions.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Wed, 02 Jun 2021 09:01:22 GMT', 'Content-Length': '198'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services \"ml-pipeline\" not found","reason":"NotFound","details":{"name":"ml-pipeline","kind":"services"},"code":404}


Failed to get healthz info attempt 2 of 5.
Traceback (most recent call last):
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp/_client.py", line 312, in get_kfp_healthz
    response = self._healthz_api.get_healthz()
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api/healthz_service_api.py", line 63, in get_healthz
    return self.get_healthz_with_http_info(**kwargs)  # noqa: E501
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api/healthz_service_api.py", line 134, in get_healthz_with_http_info
    return self.api_client.call_api(
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 364, in call_api
    return self.__call_api(resource_path, method,
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 188, in __call_api
    raise e
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 181, in __call_api
    response_data = self.request(
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 389, in request
    return self.rest_client.GET(url,
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/rest.py", line 230, in GET
    return self.request("GET", url,
  File "/home/zzy/.local/lib/python3.8/site-packages/kfp_server_api/rest.py", line 224, in request
    raise ApiException(http_resp=r)
kfp_server_api.exceptions.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Wed, 02 Jun 2021 09:01:27 GMT', 'Content-Length': '198'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services \"ml-pipeline\" not found","reason":"NotFound","details":{"name":"ml-pipeline","kind":"services"},"code":404}


^C
Aborted!
```

### Expected result

kfp doesn't give the errors and tells that there is 0 run history.

### Materials and Reference

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by Bobgy** [comment]
Hi @Ruminateer, did you configure access to your KFP API endpoint?
https://www.kubeflow.org/docs/components/pipelines/sdk/connect-api/

e.g. for the CLI, configure your endpoint using env vars
```
export KF_PIPELINES_ENDPOINT=http://localhost:3000
```

**Comment by Ruminateer** [comment]
> Hi @Ruminateer, did you configure access to your KFP API endpoint?
> https://www.kubeflow.org/docs/components/pipelines/sdk/connect-api/
> 
> e.g. for the CLI, configure your endpoint using env vars
> 
> ```
> export KF_PIPELINES_ENDPOINT=http://localhost:3000
> ```

No, I did miss that. But after setting `KF_PIPELINES_ENDPOINT`, I am getting a different error message.
```console
$ export KF_PIPELINES_ENDPOINT=https://localhost:3000
$ kfp -n default run list
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.5) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f385ccef6a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /apis/v1beta1/healthz
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f385ccef9a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /apis/v1beta1/healthz
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f385ccefb20>: Failed to establish a new connection: [Errno 111] Connection refused')': /apis/v1beta1/healthz
HTTPSConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /apis/v1beta1/healthz (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f385cd5ed00>: Failed to establish a new connection: [Errno 111] Connection refused'))
```
I also tried the remote server address in my `KUBECONFIG` for `KF_PIPELINES_ENDPOINT`, but I got the same error as above. How can I decide the address for `KF_PIPELINES_ENDPOINT`?

**Comment by Bobgy** [comment]
Did you fully read https://www.kubeflow.org/docs/components/pipelines/sdk/connect-api/?
All answered in it.

**Comment by Ruminateer** [comment]
Sorry, my bad. I set up the port forward but I am getting new errors. Cannot find an answer on that page 😥
```console
$ kubectl port-forward svc/ml-pipeline-ui 3000:80 --namespace kubeflow
Forwarding from 127.0.0.1:3000 -> 3000
Forwarding from [::1]:3000 -> 3000
Handling connection for 3000
Handling connection for 3000
```

```console
$ kfp -n default run list
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.5) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
(504)
Reason: Gateway Timeout
HTTP response headers: HTTPHeaderDict({'X-Powered-By': 'Express', 'Date': 'Thu, 03 Jun 2021 03:37:07 GMT', 'Connection': 'keep-alive', 'Transfer-Encoding': 'chunked'})
HTTP response body: Error occured while trying to proxy to: localhost:3000/apis/v1beta1/runs?page_token=&page_size=100&sort_by=created_at+desc

$ kfp -n default run submit -e Default -w -f mnist.py.yml
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.5) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
(504)
Reason: Gateway Timeout
HTTP response headers: HTTPHeaderDict({'X-Powered-By': 'Express', 'Date': 'Thu, 03 Jun 2021 03:45:14 GMT', 'Connection': 'keep-alive', 'Transfer-Encoding': 'chunked'})
HTTP response body: Error occured while trying to proxy to: localhost:3000/apis/v1beta1/experiments?page_token=&page_size=100&sort_by=&resource_reference_key.type=NAMESPACE&resource_reference_key.id=

```

**Comment by Bobgy** [comment]
No prob!

The new error seems a bit weird. Did you check opening localhost:3000 in your browser? Everything working?

I didn't quite remember what the -n flag do. Can we remove it?

**Comment by Ruminateer** [comment]
> Did you check opening localhost:3000 in your browser? Everything working?

It is not working either. Error message
```console
Error occured while trying to proxy to: localhost:3000/apis/v1beta1/pipelines?page_token=&page_size=10&sort_by=created_at%20desc&filter=
```
![image](https://user-images.githubusercontent.com/31800808/120595022-59fdfc80-c474-11eb-9a86-25c092a509b4.png)

> I didn't quite remember what the -n flag do. Can we remove it?

It just specifies the namespace. Removing it makes no difference.
```console
$ kfp run list
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.5) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
(504)
Reason: Gateway Timeout
HTTP response headers: HTTPHeaderDict({'X-Powered-By': 'Express', 'Date': 'Thu, 03 Jun 2021 05:55:31 GMT', 'Connection': 'keep-alive', 'Transfer-Encoding': 'chunked'})
HTTP response body: Error occured while trying to proxy to: localhost:3000/apis/v1beta1/runs?page_token=&page_size=100&sort_by=created_at+desc

```

BTW I'm not using a proxy if that matters.
```console
$ env | grep proxy
GOPROXY=https://goproxy.io,https://goproxy.cn,direct
```

**Comment by Bobgy** [comment]
If visiting localhost:3000 already has errors, then sth is wrong with your deployment or the kubectl proxy. Use kubectl to debug your deployment.
