### ISSUE TITLE
Load samples returns an error in 0.4 Kubeflow

### ISSUE THREAD

**Issue by jlewi** [kubeflow/pipelines#603]
I deployed Kubeflow from the 0.4 release branch

The ml pipelines container is in an error state. Logs for the pod show

```
F1228 19:56:00.989700       1 client_manager.go:162] Failed to create a foreign key for RunID in run_metrics table. Error: Error 1022: Can't write; duplicate key in table '#sql-1_4'

(Error 1022: Can't write; duplicate key in table '#sql-1_4') 
[2018-12-28 19:56:00]  
goroutine 1 [running]:
github.com/kubeflow/pipelines/vendor/github.com/golang/glog.stacks(0xc00041c100, 0xc00087e000, 0xb6, 0x1b6)
	/go/src/github.com/kubeflow/pipelines/vendor/github.com/golang/glog/glog.go:769 +0xd4
github.com/kubeflow/pipelines/vendor/github.com/golang/glog.(*loggingT).output(0x263bee0, 0xc000000003, 0xc00060c840, 0x2397334, 0x11, 0xa2, 0x0)
	/go/src/github.com/kubeflow/pipelines/vendor/github.com/golang/glog/glog.go:720 +0x329
github.com/kubeflow/pipelines/vendor/github.com/golang/glog.(*loggingT).printf(0x263bee0, 0x3, 0x163355c, 0x48, 0xc0006c1bd0, 0x1, 0x1)
	/go/src/github.com/kubeflow/pipelines/vendor/github.com/golang/glog/glog.go:655 +0x14b
github.com/kubeflow/pipelines/vendor/github.com/golang/glog.Fatalf(0x163355c, 0x48, 0xc0006c1bd0, 0x1, 0x1)
	/go/src/github.com/kubeflow/pipelines/vendor/github.com/golang/glog/glog.go:1148 +0x67
main.initDBClient(0x53d1ac1000, 0x15)
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/client_manager.go:162 +0x455
main.(*ClientManager).init(0xc000913d50)
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/client_manager.go:103 +0x80
main.newClientManager(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/client_manager.go:242 +0x90
main.main()
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/main.go:53 +0x88
```
Related to: kubeflow/kubeflow#2098 0.4 release

/cc @IronPan

**Comment by TimZaman** [comment]
Same here! Followed the docs exactly using `export KUBEFLOW_TAG=v0.4.0-rc.2`.
```
tzaman@Tims-MacBook-Pro kf1337 $ kubectl logs ml-pipelines-load-samples-gwmhn
F0102 19:31:18.788858       1 client_manager.go:162] Failed to create a foreign key for RunID in run_metrics table. Error: Error 1022: Can't write; duplicate key in table '#sql-1_4'

(Error 1022: Can't write; duplicate key in table '#sql-1_4') 
[2019-01-02 19:31:18]  
goroutine 1 [running]:
github.com/kubeflow/pipelines/vendor/github.com/golang/glog.stacks(0xc000018100, 0xc00089e000, 0xb6, 0x1b6)
	/go/src/github.com/kubeflow/pipelines/vendor/github.com/golang/glog/glog.go:769 +0xd4
github.com/kubeflow/pipelines/vendor/github.com/golang/glog.(*loggingT).output(0x263bee0, 0xc000000003, 0xc000628790, 0x2397334, 0x11, 0xa2, 0x0)
	/go/src/github.com/kubeflow/pipelines/vendor/github.com/golang/glog/glog.go:720 +0x329
github.com/kubeflow/pipelines/vendor/github.com/golang/glog.(*loggingT).printf(0x263bee0, 0x3, 0x163355c, 0x48, 0xc0006ddbd0, 0x1, 0x1)
	/go/src/github.com/kubeflow/pipelines/vendor/github.com/golang/glog/glog.go:655 +0x14b
github.com/kubeflow/pipelines/vendor/github.com/golang/glog.Fatalf(0x163355c, 0x48, 0xc0006ddbd0, 0x1, 0x1)
	/go/src/github.com/kubeflow/pipelines/vendor/github.com/golang/glog/glog.go:1148 +0x67
main.initDBClient(0x53d1ac1000, 0x15)
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/client_manager.go:162 +0x455
main.(*ClientManager).init(0xc000933d50)
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/client_manager.go:103 +0x80
main.newClientManager(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/client_manager.go:242 +0x90
main.main()
	/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/main.go:53 +0x88
```

**Comment by jlewi** [comment]
@IronPan I deployed to a new cluster.

Has pipelines been upgraded to the 0.1.5 on the release branch? Do wee need to cherry pick the fix to kubeflow/pipelines#549?

**Comment by IronPan** [comment]
@hongye-sun On surface the error message looks relevant to the metrics table. do you have any idea on this failure?

meanwhile I'll create a cluster too and dive into the issue

**Comment by IronPan** [comment]
It seems the issue was due to the DB initialized twice during both k8s job to sample loading and api server startup. We can remove the DB initialization from the job to load samples

**Comment by IronPan** [comment]
I'll send a PR shortly

**Comment by TimZaman** [comment]
Cool

**Comment by IronPan** [comment]
Interestingly I wasn't able to reproduce it from a GKE cluster. Does it fail all the time?

**Comment by IronPan** [comment]
The source code shows it would handles gracefully if the foreign key already exist. 
https://github.com/jinzhu/gorm/blob/master/scope.go#L1220

It align with what I observed. Is there any cluster you can share with me to investigate?

**Comment by TimZaman** [comment]
I am now on v0.4.0-rc.3 and the issue went away.

**Comment by IronPan** [comment]
Nice I'll close this one
