### ISSUE TITLE
[sdk] add_pvolume failing with unhashable type error

### ISSUE THREAD

**Issue by jonasdebeukelaer** [kubeflow/pipelines#6394]
### Environment

*  KFP version: `1.7.0-rc.4`

*  KFP SDK version: `1.7.0rc4`
*  All dependencies version:
```
kfp                                   1.7.1
kfp-pipeline-spec                     0.1.9
kfp-server-api                        1.7.0rc4
```

### Steps to reproduce

I'm trying to mount an existing pvc 'azure-managed-disk'  to my components via add_pvolume, but is failing with a type error I can't pin down.

Minimal code snippet:
```python
import kfp
import kfp.v2.dsl as dsl
from kfp.v2.dsl import component
from kubernetes.client.models.v1_volume import V1Volume


@component(base_image='python:3')
def get_data():
    import os
    print('list:')
    print(os.listdir('/mnt/data'))


@dsl.pipeline(name='test')
def pipeline():
    vol = kfp.dsl.PipelineVolume(pvc='azure-managed-disk')
    # tried with following as well:
    # vol = V1Volume(name='vol', persistent_volume_claim='azure-managed-disk')

    get_data_task = get_data()
    get_data_task.add_pvolumes({"/mnt/data", vol})


client = kfp.Client(host='http://localhost:8081')
client.create_run_from_pipeline_func(
    pipeline, arguments={}, run_name='testing',
    experiment_name='Default', enable_caching=True,
    mode=kfp.dsl.PipelineExecutionMode.V2_COMPATIBLE
)
```

full error trace:
```
Traceback (most recent call last):
  File "/Users/jonas/repositories/traffic4cast-2021/pipeline/pipeline_err_snippet.py", line 25, in <module>
    client.create_run_from_pipeline_func(
  File "/opt/homebrew/lib/python3.9/site-packages/kfp/_client.py", line 881, in create_run_from_pipeline_func
    compiler.Compiler(mode=mode, launcher_image=launcher_image).compile(
  File "/opt/homebrew/lib/python3.9/site-packages/kfp/compiler/compiler.py", line 1061, in compile
    self._create_and_write_workflow(
  File "/opt/homebrew/lib/python3.9/site-packages/kfp/compiler/compiler.py", line 1114, in _create_and_write_workflow
    workflow = self._create_workflow(
  File "/opt/homebrew/lib/python3.9/site-packages/kfp/compiler/compiler.py", line 900, in _create_workflow
    pipeline_func(*args_list, **kwargs_dict)
  File "/Users/jonas/repositories/traffic4cast-2021/pipeline/pipeline_err_snippet.py", line 21, in pipeline
    get_data_task.add_pvolumes({"/mnt/data", vol})
TypeError: unhashable type: 'PipelineVolume'
```

### Expected result

The pvc would be mount to path `'/mnt/data'`

### Materials and Reference

Or is there something I'm missing that needs to change when using v2 of the sdk?

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by zijianjoy** [comment]
cc @chensun for sdk advice.

**Comment by jonasdebeukelaer** [comment]
Note: I tried the same thing using the v1 sdk but got the same `unhashable type` error

**Comment by jonasdebeukelaer** [comment]
ohhhhhh jeez closing this as it seems I forgot how to define dicts in python 🤦 

`{"/mnt/data", vol}` -> `{"/mnt/data": vol}`

🤦 🤦 🤦 🤦
