### ISSUE TITLE
[sdk] VolumeOp support for sdk v2

### ISSUE THREAD

**Issue by jonasdebeukelaer** [kubeflow/pipelines#6429]
### Environment

*  KFP version: 1.7.0
*  KFP SDK version:  1.7.0
*  All dependencies version:
```
kfp                                   1.7.0
kfp-pipeline-spec                     0.1.9
kfp-server-api                        1.7.0
```

### Steps to reproduce

try to create a PVC using `kfp.dsl.VolumeOp`

end up with 
```
Traceback (most recent call last):
  File "/Users/jonas/repositories/traffic4cast-2021/pipeline/data_pipeline.py", line 27, in <module>
    client.create_run_from_pipeline_func(
  File "/opt/homebrew/lib/python3.9/site-packages/kfp/_client.py", line 881, in create_run_from_pipeline_func
    compiler.Compiler(mode=mode, launcher_image=launcher_image).compile(
  File "/opt/homebrew/lib/python3.9/site-packages/kfp/compiler/compiler.py", line 1055, in compile
    self._create_and_write_workflow(
  File "/opt/homebrew/lib/python3.9/site-packages/kfp/compiler/compiler.py", line 1108, in _create_and_write_workflow
    workflow = self._create_workflow(
  File "/opt/homebrew/lib/python3.9/site-packages/kfp/compiler/compiler.py", line 946, in _create_workflow
    workflow = self._create_pipeline_workflow(
  File "/opt/homebrew/lib/python3.9/site-packages/kfp/compiler/compiler.py", line 713, in _create_pipeline_workflow
    templates = self._create_dag_templates(pipeline, op_transformers)
  File "/opt/homebrew/lib/python3.9/site-packages/kfp/compiler/compiler.py", line 677, in _create_dag_templates
    v2_compat.update_op(op,
  File "/opt/homebrew/lib/python3.9/site-packages/kfp/compiler/v2_compat.py", line 53, in update_op
    op.add_volume_mount(
AttributeError: 'VolumeOp' object has no attribute 'add_volume_mount'
```

code sample:
```python
import kfp
import kfp.v2.dsl as dsl

@component(base_image='python:3')
def get_data():
    print('dummy component')

@dsl.pipeline(
    name='Data prep pipeline'
)
def pipeline():
    pvc = kfp.dsl.VolumeOp(name='data-vol', resource_name='azure-disk-rw2',
                           volume_name='azure-disk', modes=[kfp.dsl.VOLUME_MODE_RWO], size='400G')

    get_data_task = get_data()
    get_data_task.add_pvolumes({'/mnt/data': pvc.volume})


client = kfp.Client(host='http://localhost:8081')
client.create_run_from_pipeline_func(
    pipeline, arguments={}, run_name='data prep pipeline',
    experiment_name='Default', enable_caching=False,
    mode=kfp.dsl.PipelineExecutionMode.V2_COMPATIBLE
)

```

and there are a number of other incompatibilities too.

### Expected result

The pipeline compiles, and a pvc would be created for an existing pv.

### Materials and Reference

Happy to help fix this issue if it's not too convoluted/some basic guidance can be given.
SDK v2 is shaping up nicely though, looking forward to it getting fleshed out fully 👌 .

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by StefanoFioravanzo** [comment]
Hi @chensun ! This discussion is very dear to us, as many of our workflows do require us to run pipelines that declare volumes and use persistent storage. We have seen many customers using this and enterprise use cases. I wouldn't want this discussion to becomes stale.

We have been working with KFP v1 until now but we want to to transition to V2 as well. Can I ask what is the state wrt supporting VolumeOps in V2, if you are planning on doing something about it or if you are open to contributions?

**Comment by droctothorpe** [comment]
After reviewing this issue, we've decided to close it:

VolumeOp and ResourceOp were deprecated in KFP SDK v2. The v2 SDK uses a different paradigm where volumes are handled via kubernetes extension (kubernetes.CreatePVC, kubernetes.mount_pvc). This is by design and documented.

If you believe this was closed in error, please feel free to reopen with additional context.
