### ISSUE TITLE
[backend] Kale pipelines always fails

### ISSUE THREAD

**Issue by ConverJens** [kubeflow/pipelines#6487]
We are trying to setup Kale in Kubeflow v1.3.0 with KFP 1.7 in multi-user mode.

Kale can access the KFP API and perform compile, upload and start a run. 

However, the run always fails on the first user-made component (the kale-marshall-volume step succeds). The error message indicates that the user service-account doesn't have access to the workflow. Pipelines uploaded through the UI or using REST calls to the KFP API runs successfully. Only pipelines uploaded by Kale fails. See logs below.

### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
Using KubeFlow v1.3 on-prem manifests. Multi-user installation.
*  KFP version: 
1.7
*  KFP SDK version: 
1.7.1 (1.7.2 has a mismatch with kfp-server-api)

### Steps to reproduce

Create notebook from web UI.
Create single cell notebook with print statement.
Annotate as pipeline step and hit compile and run.

### Expected result

Pipelines produced by Kale should work.

### Materials and Reference
Logs from the failing component:
```
2021-09-01 07:33:55 Kale mlmdutils:90         [INFO]     ---------- Initializing MLMD context... ----------
2021-09-01 07:33:55 Kale mlmdutils:91         [INFO]     Connecting to MLMD...
2021-09-01 07:33:55 Kale mlmdutils:93         [INFO]     Successfully connected to MLMD
2021-09-01 07:33:55 Kale mlmdutils:94         [INFO]     Getting step details...
2021-09-01 07:33:55 Kale mlmdutils:95         [INFO]     Getting pod name...
2021-09-01 07:33:55 Kale mlmdutils:97         [INFO]     Successfully retrieved pod name: kale-test-2lq4m-2937332039
2021-09-01 07:33:55 Kale mlmdutils:98         [INFO]     Getting pod namespace...
2021-09-01 07:33:55 Kale mlmdutils:101        [INFO]     Successfully retrieved pod namespace: jars
2021-09-01 07:33:55 Kale mlmdutils:102        [INFO]     Getting pod...
2021-09-01 07:33:55 Kale mlmdutils:104        [INFO]     Successfully retrieved pod
2021-09-01 07:33:55 Kale mlmdutils:105        [INFO]     Getting workflow name from pod...
2021-09-01 07:33:55 Kale mlmdutils:109        [INFO]     Successfully retrieved workflow name: kale-test-2lq4m
2021-09-01 07:33:55 Kale mlmdutils:110        [INFO]     Getting workflow...
Traceback (most recent call last):
  File "/tmp/tmp.pGfFr6iV77", line 35, in <module>
    _outputs = hej(**_parsed_args)
  File "/tmp/tmp.pGfFr6iV77", line 3, in hej
    _kale_mlmdutils.init_metadata()
  File "/root/pyenv/lib/python3.7/site-packages/kale/common/mlmdutils.py", line 537, in init_metadata
    mlmd_instance = MLMetadata()
  File "/root/pyenv/lib/python3.7/site-packages/kale/common/mlmdutils.py", line 112, in __init__
    self.pod_namespace)
  File "/root/pyenv/lib/python3.7/site-packages/kale/common/workflowutils.py", line 73, in get_workflow
    ARGO_WORKFLOWS_PLURAL, name)
  File "/root/pyenv/lib/python3.7/site-packages/kubernetes/client/api/custom_objects_api.py", line 1484, in get_namespaced_custom_object
    return self.get_namespaced_custom_object_with_http_info(group, version, namespace, plural, name, **kwargs)  # noqa: E501
  File "/root/pyenv/lib/python3.7/site-packages/kubernetes/client/api/custom_objects_api.py", line 1605, in get_namespaced_custom_object_with_http_info
    collection_formats=collection_formats)
  File "/root/pyenv/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 353, in call_api
    _preload_content, _request_timeout, _host)
  File "/root/pyenv/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 184, in __call_api
    _request_timeout=_request_timeout)
  File "/root/pyenv/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 377, in request
    headers=headers)
  File "/root/pyenv/lib/python3.7/site-packages/kubernetes/client/rest.py", line 243, in GET
    query_params=query_params)
  File "/root/pyenv/lib/python3.7/site-packages/kubernetes/client/rest.py", line 233, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': '55fcf2fc-2f05-4286-9e95-cb916b633246', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': '6b4284f3-6c8a-4ff6-9175-c9cc05603c3b', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'c15d461f-7449-4812-903b-59f654fe74ee', 'Date': 'Wed, 01 Sep 2021 07:33:55 GMT', 'Content-Length': '387'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"workflows.argoproj.io \"kale-test-2lq4m\" is forbidden: User \"system:serviceaccount:jars:default-editor\" cannot get resource \"workflows\" in API group \"argoproj.io\" in the namespace \"jars\"","reason":"Forbidden","details":{"name":"kale-test-2lq4m","group":"argoproj.io","kind":"workflows"},"code":403}
```

Any help would be greatly appreciated!

---
Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by zijianjoy** [comment]
@yanniszark @elikatsis @kimwnasptd 

Hello Arrikto, is this an expected behavior for Kale needing this permission to get argo workflow? Would you like to consider adding permission for Kale to access Pipelines?

**Comment by ConverJens** [comment]
Any updates or thoughts on this?

**Comment by ConverJens** [comment]
@zijianjoy @elikatsis A fix for this issue was found here: https://github.com/kubeflow-kale/kale/issues/352.

However, should this be fixed permanently on the KFP side or is Kale doing something strange by needing this?
