### ISSUE TITLE
[sdk] ValueError: compiler cannot find the model-export-path

### ISSUE THREAD

**Issue by nurcandurak** [kubeflow/pipelines#6637]
### What steps did you take

I am building a scikit-learn model and want to deploy the model on aiplatform.

### What happened:

When I compile the pipeline, I am receiving the following error:
"ValueError: compiler cannot find the model-export-path"

### Environment:

model_file_path = f"{model_dir}/model.joblib"

  with tf.io.gfile.GFile(model_file_path, mode="wb") as training_file:
      joblib.dump(model, training_file)

I am pointing the model_file_path in the deployment process but it asks for model-export-path

**Comment by nurcandurak** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/dsl-compile", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/kfp/compiler/main.py", line 104, in main
    not args.disable_type_check,
  File "/usr/local/lib/python3.7/site-packages/kfp/compiler/main.py", line 91, in compile_pyfile
    _compile_pipeline_function(pipeline_funcs, function_name, output_path, type_check)
  File "/usr/local/lib/python3.7/site-packages/kfp/compiler/main.py", line 68, in _compile_pipeline_function
    kfp.compiler.Compiler().compile(pipeline_func, output_path, type_check)
  File "/usr/local/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 1038, in compile
    package_path=package_path)
  File "/usr/local/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 1092, in _create_and_write_workflow
    pipeline_conf)
  File "/usr/local/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 938, in _create_workflow
    pipeline_conf,
  File "/usr/local/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 713, in _create_pipeline_workflow
    templates = self._create_dag_templates(pipeline, op_transformers)
  File "/usr/local/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 667, in _create_dag_templates
    condition_params,
  File "/usr/local/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 387, in _get_dependencies
    raise ValueError('compiler cannot find the ' + upstream_op_name)
ValueError: compiler cannot find the model-export-path

**Comment by chensun** [comment]
@nurcandurak can you please share the complete pipeline code you were compiling? also which SDK version were you using?

**Comment by nurcandurak** [comment]
I use kfp= 1.6.1

And the code block is: 
from sklearn.linear_model import LinearRegression
import joblib

model = LinearRegression()
model.fit(training_data_set[feature_columns], training_data_set[target_col])

model_file_path = f"{model_dir}/model.joblib"

## Then there is ai_platform deploy operation, THere is no serving operation.
def aiplatform_deploy_op(
    model_uri: str,
    project_id: str,
    model_id: str,
    version_id: str,
    aiplatform_runtime_version: str,
    python_version: str,
    machine_type: str,
    model_logging: bool = False,
    region: str = "us-central1",
    framework: str = "SCIKIT-LEARN",

**Comment by chensun** [comment]
@nurcandurak KFP 1.6.1 is 6 months old, can you please try the latest sdk and see if the issue still exists. 
If yes, can you please provide a complete code to repro this?
The code you show seems like they're part of a component implementation?
```
from sklearn.linear_model import LinearRegression
import joblib

model = LinearRegression()
model.fit(training_data_set[feature_columns], training_data_set[target_col])

model_file_path = f"{model_dir}/model.joblib"
```
