### ISSUE TITLE
[sdk] dsl-compile-v2 fails to compile samples/v2/producer_consumer_param.py

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#6927]
### Environment

*  KFP SDK version:  master

### Steps to reproduce

```bash
$ cd github.com/kubeflow/pipelines
$ pip install -e sdk/python
$ cd samples/v2
$ dsl-compile-v2 --py producer_consumer_param.py --out a.json
Traceback (most recent call last):
  File "/home/gongyuan_kubeflow_org/github/kf/pipelines/sdk/python/kfp/components/_data_passing.py", line 235, in serialize_value
    serialized_value = serializer(value)
  File "/home/gongyuan_kubeflow_org/github/kf/pipelines/sdk/python/kfp/components/_data_passing.py", line 40, in _serialize_str
    str(str_value), str(type(str_value))))
TypeError: Value "{{channel:task=;name=text;type=String;}}" has type "<class 'kfp.v2.components.pipeline_channel.PipelineParameterChannel'>" instead of str.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gongyuan_kubeflow_org/miniconda3/envs/v2/bin/dsl-compile-v2", line 33, in <module>
    sys.exit(load_entry_point('kfp', 'console_scripts', 'dsl-compile-v2')())
  File "/home/gongyuan_kubeflow_org/github/kf/pipelines/sdk/python/kfp/v2/compiler/main.py", line 164, in main
    type_check=not args.disable_type_check,
  File "/home/gongyuan_kubeflow_org/github/kf/pipelines/sdk/python/kfp/v2/compiler/main.py", line 149, in compile_pyfile
    type_check=type_check,
  File "/home/gongyuan_kubeflow_org/github/kf/pipelines/sdk/python/kfp/v2/compiler/main.py", line 102, in _compile_pipeline_function
    type_check=type_check)
  File "/home/gongyuan_kubeflow_org/github/kf/pipelines/sdk/python/kfp/v2/compiler/compiler.py", line 99, in compile
    pipeline_parameters_override=pipeline_parameters,
  File "/home/gongyuan_kubeflow_org/github/kf/pipelines/sdk/python/kfp/v2/compiler/compiler.py", line 153, in _create_pipeline_v2
    pipeline_func(*args_list)
  File "/home/gongyuan_kubeflow_org/github/kf/pipelines/samples/v2/producer_consumer_param.py", line 61, in producer_consumer_param_pipeline
    producer = producer_op(input_text=text)
  File "/home/gongyuan_kubeflow_org/github/kf/pipelines/sdk/python/kfp/components/_dynamic.py", line 53, in Producer
    return dict_func(locals())  # noqa: F821 TODO
  File "/home/gongyuan_kubeflow_org/github/kf/pipelines/sdk/python/kfp/components/_components.py", line 389, in create_task_object_from_component_and_pythonic_arguments
    component_ref=component_ref,
  File "/home/gongyuan_kubeflow_org/github/kf/pipelines/sdk/python/kfp/components/_components.py", line 327, in _create_task_object_from_component_and_arguments
    **kwargs,
  File "/home/gongyuan_kubeflow_org/github/kf/pipelines/sdk/python/kfp/components/_components.py", line 278, in _create_task_spec_from_component_and_arguments
    input_type)
  File "/home/gongyuan_kubeflow_org/github/kf/pipelines/sdk/python/kfp/components/_data_passing.py", line 248, in serialize_value
    str(e),
ValueError: Failed to serialize the value "{{channel:task=;name=text;type=String;}}" of type "PipelineParameterChannel" to type "String". Exception: Value "{{channel:task=;name=text;type=String;}}" has type "<class 'kfp.v2.components.pipeline_channel.PipelineParameterChannel'>" instead of str.
```

### Expected result

The sample should compile.

### Materials and Reference

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by chensun** [comment]
This specific one is because of the mix use of v1 and v2 imports in the test sample file, which I'm fixing in https://github.com/kubeflow/pipelines/pull/6932

**Comment by Bobgy** [comment]
I wonder whether we can return a meaningful error message. This one is impossible to understand why.

**Comment by chensun** [comment]
> I wonder whether we can return a meaningful error message. This one is impossible to understand why.

Agree, will try to improve the message.
