### ISSUE TITLE
Unable to use tensorboard viewer using minio path

### ISSUE THREAD

**Issue by ramdootp** [kubeflow/pipelines#699]
<img width="458" alt="image" src="https://user-images.githubusercontent.com/25822222/51357053-17c20380-1ae3-11e9-81d0-d782f7d2db3b.png">

the tensorboard pod is running with the above metadata.json 
But it fails, reporting minio style path isn't supported by tensorboard. 

>>>>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/backend/application.py", line 307, in __call__
    return self.data_applications[clean_path](environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 308, in application
    resp = f(*args[:-2] + (request,))
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/backend/application.py", line 278, in _serve_plugins_listing
    response[plugin.plugin_name] = plugin.is_active()
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/plugins/beholder/beholder_plugin.py", line 71, in is_active
    return tf.gfile.Exists(summary_filename) and\
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 260, in file_exists
    pywrap_tensorflow.FileExists(compat.as_bytes(filename), status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
UnimplementedError: File system scheme 'minio' not implemented (file: 'minio://tensorboard/plugins/beholder/frame.summary')

Is this the correct way to use the minio path for metadata.json?
if not, let me know the correct way.

**Comment by yebrahim** [comment]
Tensorboard does not support reading from minio server, we're working on a way to use mounted volumes to save this data, in which case Tensorboard will just be reading from the local filesystem. See the discussion in https://github.com/kubeflow/pipelines/issues/489.

cc @Ark-kun

**Comment by ramdootp** [comment]
Thanks @yebrahim 

Is it the same with confusion matrix viewer, we are seeing similar issue.  The display shows blank screen

**Comment by vicaire** [comment]
@neuromage 

It seems that we could add support for mounted volumes in the viewer CRD for tensorboard that @neuromage did

**Comment by swiftdiaries** [comment]
I'd like to take this up and look into using the Viewer CRD from the Frontend for Tensorboard following discussions here: https://github.com/kubeflow/pipelines/pull/792#issuecomment-463299208
/cc @yebrahim 
/assign @swiftdiaries

**Comment by vicaire** [comment]
Thank you @swiftdiaries

**Comment by rileyjbauer** [comment]
@neuromage can this be closed with the Viewer CRD work Jing has done?

**Comment by neuromage** [comment]
I think this is technically possible (mounting volumes and having the TB pod read off that), but we don't provide the user with the ability to do this from our UI as yet. @swiftdiaries are you still interested in working on this?

**Comment by Dhaval08** [comment]
Does Kubeflow Pipeline now support local source for visualization?

**Comment by Bobgy** [comment]
It supports inline source, but not minio

**Comment by Focke-Wulf** [comment]
> It supports inline source, but not minio

hi, we are testing tensorboard in pipline, the documentation said not support inline source....

however we test souce in mino, it dose not work as well..

![logs](https://user-images.githubusercontent.com/26343300/89278910-4e398200-d679-11ea-9bb8-0425ab4c328e.png)

**Comment by Bobgy** [comment]
Ohh, sorry I missed you are talking about tensorboard. Inline is not supported

**Comment by kd303** [comment]
Hi @Bobgy , @swiftdiaries 

Is it possible to use a PV for Tensorboard working on non-cloud environments (local cluster running with Kubeflow 1.1) ?

**Comment by blacksailer** [comment]
@kd303 Hi

I've managed to use on local cluster with adding pre-defined PV. Here, in [this](https://github.com/kubeflow/pipelines/issues/4850) issue you can find sample configs to tensorboard component.

But for training component I have used PodDefault to attach the same volume to master/worker pods(I am using PyTorchJob component).

In result, in pipelines UI I can see two components: Tensorboard and PyTorch Component. (I have edited this [TfJob](https://github.com/kubeflow/pipelines/blob/79e5bf8c14aadfdf48f3bb12a37ccdf2ab099b4b/components/kubeflow/launcher/component.yaml) component to create PyTorch one)

**Comment by kd303** [comment]
@blacksailer Thanks, I will give it a go,

**Comment by Bobgy** [comment]
Hi all, I'm sending a PR to make it possible to use tensorboard viewer with minio path: https://github.com/kubeflow/pipelines/pull/5515

Feedback welcomed!
