### ISSUE TITLE
01/05/2022 Presubmit kubeflow-pipelines-tfx-python37 failure

### ISSUE THREAD

**Issue by chensun** [kubeflow/pipelines#7142]
https://oss-prow.knative.dev/view/gs/oss-prow/pr-logs/pull/kubeflow_pipelines/7112/kubeflow-pipelines-tfx-python37/1478839808884215808

```
2022-01-05 21:32:19.957501: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/home/prow/go/src/github.com/kubeflow/pipelines/tfx/tfx/orchestration/kubeflow/kubeflow_dag_runner_test.py", line 23, in <module>
    from tfx.components.statistics_gen import component as statistics_gen_component
  File "/usr/local/lib/python3.7/site-packages/tfx/components/__init__.py", line 29, in <module>
    from tfx.components.transform.component import Transform
  File "/usr/local/lib/python3.7/site-packages/tfx/components/transform/component.py", line 19, in <module>
    from tfx.components.transform import executor
  File "/usr/local/lib/python3.7/site-packages/tfx/components/transform/executor.py", line 26, in <module>
    import tensorflow_transform as tft
  File "/usr/local/lib/python3.7/site-packages/tensorflow_transform/__init__.py", line 18, in <module>
    from tensorflow_transform import experimental
  File "/usr/local/lib/python3.7/site-packages/tensorflow_transform/experimental/__init__.py", line 16, in <module>
    from tensorflow_transform.experimental.analyzers import *
  File "/usr/local/lib/python3.7/site-packages/tensorflow_transform/experimental/analyzers.py", line 30, in <module>
    from tensorflow_transform import analyzer_nodes
  File "/usr/local/lib/python3.7/site-packages/tensorflow_transform/analyzer_nodes.py", line 31, in <module>
    from future.utils import with_metaclass
ModuleNotFoundError: No module named 'future'
```

**Comment by chensun** [comment]
Pending the following change in tensorflow_transform being picked up by TFX:

https://github.com/tensorflow/transform/commit/e5e0560e092b3ba66138f2250cc31716c5405081#diff-be77950e10f2a3497862328c336509a3dc956d4b90bb81ae8c17f8e050e1a2b7
