### ISSUE TITLE
[backend] Error running xgboost_training_cm.py

### ISSUE THREAD

**Issue by Linchin** [kubeflow/pipelines#7363]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?   GCP marketplace

*  KFP version:  1.7.1

*  KFP SDK version: 

```
kfp                      1.8.11
kfp-pipeline-spec        0.1.13
kfp-server-api           1.8.1
```

### Steps to reproduce

Follow the steps given in the following link to deploy `xgboost_training_cm.py` 
https://github.com/kubeflow/pipelines/tree/master/samples/core/xgboost_training_cm

### Expected result

There shows an error with `dataproc-create-cluster` (the second block)
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/ml/kfp_component/launcher/__main__.py", line 45, in <module>
    main()
  File "/ml/kfp_component/launcher/__main__.py", line 42, in main
    launch(args.file_or_module, args.args)
  File "/ml/kfp_component/launcher/launcher.py", line 45, in launch
    return fire.Fire(module, command=args, name=module.__name__)
  File "/usr/local/lib/python3.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/usr/local/lib/python3.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/usr/local/lib/python3.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "/ml/kfp_component/google/dataproc/_create_cluster.py", line 76, in create_cluster
    client = DataprocClient()
  File "/ml/kfp_component/google/common/_utils.py", line 170, in __init__
    self._build_client()
TypeError: _build_client() takes 0 positional arguments but 1 was given
```

### Materials and Reference

N/A

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by greggdonovan** [comment]
Thank you! Should we see an update to the GCR image for [ml-pipeline-gcp](https://console.cloud.google.com/gcr/images/ml-pipeline/GLOBAL/ml-pipeline-gcp)? 

Are we sure the dataproc client is fixed? I don't see anything that calls [_create_client](https://github.com/kubeflow/pipelines/blob/master/components/gcp/container/component_sdk/python/kfp_component/google/dataproc/_client.py#L26). It seems like this [should be called _build_client](https://github.com/kubeflow/pipelines/blob/6965dbac2faee0411fc0ca9565fd9a9d7ef8e2bf/components/gcp/container/component_sdk/python/kfp_component/google/common/_utils.py#L170) for it to work.

**Comment by chensun** [comment]
@greggdonovan You're spot on. Please feel free to send a PR for the fix since you discovered it. Or I can do it as well if you wish.

Regarding the release of the ml-pipeline-gcp images. This set of components is actually being deprecated: https://github.com/kubeflow/pipelines/tree/master/components/gcp/dataproc#readme

We might still release an updated image with our next KFP release. But our goal is to drop the support and decouple it from KFP release.

**Comment by davidbellemare** [comment]
Ran into the same issue as the author. Since, those components files referencing that ml-pipeline-gcp images are being deprecated, whats the recommented way to manage dataproc (create/delete)? 

That means that code sample in the doc is not right anymore then:
https://www.kubeflow.org/docs/components/pipelines/introduction/#the-python-code-that-represents-the-pipeline
