### ISSUE TITLE
[bug] google_cloud_pipeline_components ModelBatchPredictOp()

### ISSUE THREAD

**Issue by Erin-Servian** [kubeflow/pipelines#7389]
### What steps did you take:
I was deploying a pipeline to Vertex AI that was doing Model Upload and Batch Prediction jobs. But I got an error when the pipeline was executing the Batch Prediction Job. The code is below:

```
from kfp.v2.google.client import AIPlatformClient
from google_cloud_pipeline_components import aiplatform as gcc_aip
from kfp.v2 import compiler, dsl

@dsl.pipeline(name="sample-pipeline",
    pipeline_root=pipeline_root)

def pipeline():
 
    model_upload_op = gcc_aip.ModelUploadOp(
        project=GCP_PROJECT_ID,
        display_name=model_display_name,
        artifact_uri=model_artifact_uri, 
        serving_container_image_uri=PREDICTION_IMAGE,
        serving_container_ports = [{"container_port": 8080}],
        serving_container_predict_route = "/predict",
        serving_container_health_route = "/health",
        labels=model_metadata
    )
    
    gcc_aip.ModelBatchPredictOp(
        project=GCP_PROJECT_ID,
        job_display_name=pipeline_id,
        model=model_upload_op.outputs["model"],
        gcs_source_uris=batch_prediction_data_uri,
        gcs_destination_output_uri_prefix=batch_prediction_results_uri,
        instances_format="csv",
        predictions_format="jsonl",
        machine_type = "n1-standard-2",
        starting_replica_count=1,
        max_replica_count=1,
    )
    
compiler.Compiler().compile(pipeline_func=pipeline, package_path="pipeline.json")

api_client = AIPlatformClient(project_id=GCP_PROJECT_ID, region=GCP_REGION)

response = api_client.create_run_from_job_spec(
    'pipeline.json',
    pipeline_root=pipeline_root
    )
```

### What happened:
The error messages are below:
```
Info  2022-03-07T21:29:52.083653660ZINFO:root:Job started for type: BatchPredictionJob
Error 2022-03-07T21:29:52.115350265ZTraceback (most recent call last):
Error 2022-03-07T21:29:52.115389275Z File "/opt/python3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
Error 2022-03-07T21:29:52.115585620Z "__main__", mod_spec)
Error 2022-03-07T21:29:52.115634257Z File "/opt/python3.7/lib/python3.7/runpy.py", line 85, in _run_code
Error 2022-03-07T21:29:52.115704257Z exec(code, run_globals)
Error 2022-03-07T21:29:52.115712908Z File "/opt/python3.7/lib/python3.7/site-packages/google_cloud_pipeline_components/container/v1/gcp_launcher/launcher.py", line 229, in <module>
Error 2022-03-07T21:29:52.115924803Z main(sys.argv[1:])
Error 2022-03-07T21:29:52.115938316Z File "/opt/python3.7/lib/python3.7/site-packages/google_cloud_pipeline_components/container/v1/gcp_launcher/launcher.py", line 225, in main
Error 2022-03-07T21:29:52.116124076Z _JOB_TYPE_TO_ACTION_MAP[job_type](**parsed_args)
Error 2022-03-07T21:29:52.116137398Z File "/opt/python3.7/lib/python3.7/site-packages/google_cloud_pipeline_components/container/v1/gcp_launcher/batch_prediction_job_remote_runner.py", line 95, in create_batch_prediction_job
Error 2022-03-07T21:29:52.116316276Z insert_artifact_into_payload(executor_input, payload))
Error 2022-03-07T21:29:52.116362741Z File "/opt/python3.7/lib/python3.7/site-packages/google_cloud_pipeline_components/container/v1/gcp_launcher/batch_prediction_job_remote_runner.py", line 47, in insert_artifact_into_payload
Error 2022-03-07T21:29:52.116380612Z job_spec = json.loads(payload)
Error 2022-03-07T21:29:52.116401022Z File "/opt/python3.7/lib/python3.7/json/__init__.py", line 348, in loads
Error 2022-03-07T21:29:52.116745671Z return _default_decoder.decode(s)
Error 2022-03-07T21:29:52.116771230Z File "/opt/python3.7/lib/python3.7/json/decoder.py", line 337, in decode
Error 2022-03-07T21:29:52.116975231Z obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Error 2022-03-07T21:29:52.117005384Z File "/opt/python3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
Error 2022-03-07T21:29:52.117186534Z raise JSONDecodeError("Expecting value", s, err.value) from None
Error 2022-03-07T21:29:52.117214480Zjson.decoder.JSONDecodeError: Expecting value: line 1 column 210 (char 209)
Info  2022-03-07T21:30:05.776338368ZJob is running.
Error 2022-03-07T21:30:05.834539659ZThe replica workerpool0-0 exited with a non-zero status of 1. 
```

### What did you expect to happen:
The Vertex AI Batch Prediction Job can be executed correctly through the pre-built component ModelBatchPredictOp().

### Environment:

*  How do you deploy Kubeflow Pipelines (KFP)?  
    I was using Vertex AI Notebook Instance and deploy the pipeline to Vertex AI Pipelines

*  KFP version:  v2

*  KFP SDK version:  1.8.11

* google-cloud-pipeline-components version:  1.0.0

### Labels

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by mdruby** [comment]
Any updates?  I'm having the same issue when creating a batch prediction job that consumes TFRecord files.

**Comment by mdruby** [comment]
Ah, I believe I found the issue.  I missed that the gcs_source_uris argument must be a list of strings.  I had passed a string and the quotes around the URI were removed in the payload JSON string.  It might be helpful to clarify the documentation here or add some type checking of the inputs.

**Comment by groovyhoon** [comment]
thanks mdruby. your comment was helpful in resolving my issue.

**Comment by kaamlaS** [comment]
Hi, 
I'm facing an issue in assigning the output of a component to the gcs_source_uris parameter in ModelBatchPredictOp. it says the type cant be of type "<class 'kfp.dsl.pipeline_channel.PipelineParameterChannel'> how do i fix this
