### ISSUE TITLE
[backend] Pipeline fails when adding Outputs

### ISSUE THREAD

**Issue by alexisgaziello** [kubeflow/pipelines#7475]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
Deployed latest Kubeflow version following the current master instructions on the [manifest](https://github.com/kubeflow/manifests) page.

*  KFP version: 

I'm afraid I cant find the version in "the left side navigation of user interface".
Could it be `build version dev_local`?

<img width="1884" alt="Screen Shot 2022-03-27 at 11 09 09 PM" src="https://user-images.githubusercontent.com/29357459/160319982-f9634470-7702-4c62-9408-5bfc7ecd1dcb.png">

*  KFP SDK version: 

kfp                      1.6.3
kfp-pipeline-spec        0.1.13
kfp-server-api           1.6.0

### Steps to reproduce

Create the simplest pipeline possible:

```python
@component
def convert_str_int(
    input_str: str,
    output_file: Output[Dataset],
) -> int:
    
    print(f"Converting string {input_str} to int ...")
    
    output_int = int(input_str)
    
    with open(output_file.path, 'w') as f:
        f.write(output_int)

    return output_int

    
# Define a pipeline and create a task from a component:
@dsl.pipeline(
    name='extremely-simple-pipeline',
)
def extremely_simple_pipeline(
    input_str: str,
):
    convert_str_int_task = convert_str_int(
        input_str=input_str,
    )

arguments = {
    "input_str": "10",
}

client.create_run_from_pipeline_func(
    extremely_simple_pipeline,
    mode=kfp.dsl.PipelineExecutionMode.V2_COMPATIBLE,
    # You can optionally override your pipeline_root when submitting the run too:
    # pipeline_root='gs://my-pipeline-root/example-pipeline',
    arguments=arguments,
)

```
### Expected result

Have a pipeline that runs

### Actual result

Pipeline fails. It doesn't even execute the code inside the component.

If I remove the Output, it works.

I've been trying to follow the instructions in the official documentation, and I don't know what I'm missing.

Pod logs:

```
time="2022-03-28T03:03:32.844Z" level=info msg="capturing logs" argo=true
Traceback (most recent call last):
  File "/tmp/tmp.lSqglRpd6S", line 828, in <module>
    executor_main()
  File "/tmp/tmp.lSqglRpd6S", line 822, in executor_main
    function_to_execute=function_to_execute)
  File "/tmp/tmp.lSqglRpd6S", line 549, in __init__
    artifacts_list[0])
  File "/tmp/tmp.lSqglRpd6S", line 562, in _make_output_artifact
    os.makedirs(os.path.dirname(artifact.path), exist_ok=True)
  File "/usr/local/lib/python3.7/posixpath.py", line 156, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
F0328 03:03:35.287326      20 main.go:56] Failed to execute component: exit status 1
time="2022-03-28T03:03:35.342Z" level=error msg="cannot save artifact /tmp/outputs/Output/data" argo=true error="stat /tmp/outputs/Output/data: no such file or directory"
time="2022-03-28T03:03:35.342Z" level=error msg="cannot save artifact /tmp/outputs/output_file/data" argo=true error="stat /tmp/outputs/output_file/data: no such file or directory"
Error: exit status 1
```

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexisgaziello** [comment]
It looks like KFP only supports Datasets that are saved in `gs`, `minio` or `s3`?


In [artifact_types.py](https://github.com/kubeflow/pipelines/blob/1c3e2768e6177d5d6e3f4b8eff8fafb9a3b76c1f/sdk/python/kfp/components/types/artifact_types.py) we can check the following code:

```python
    def _get_path(self) -> Optional[str]:
        if self.uri.startswith('gs://'):
            return _GCS_LOCAL_MOUNT_PREFIX + self.uri[len('gs://'):]
        elif self.uri.startswith('minio://'):
            return _MINIO_LOCAL_MOUNT_PREFIX + self.uri[len('minio://'):]
        elif self.uri.startswith('s3://'):
            return _S3_LOCAL_MOUNT_PREFIX + self.uri[len('s3://'):]
        return None

    def _set_path(self, path):
        if path.startswith(_GCS_LOCAL_MOUNT_PREFIX):
            path = 'gs://' + path[len(_GCS_LOCAL_MOUNT_PREFIX):]
        elif path.startswith(_MINIO_LOCAL_MOUNT_PREFIX):
            path = 'minio://' + path[len(_MINIO_LOCAL_MOUNT_PREFIX):]
        elif path.startswith(_S3_LOCAL_MOUNT_PREFIX):
            path = 's3://' + path[len(_S3_LOCAL_MOUNT_PREFIX):]
        self.uri = path
```

Note that `get_path` returns None if `uri` doesn't start with one of 3 predefined prefixes, which is causing my error.

Should we raise a ValueError instead? With a more detailed explanation of the cause of the error?


```python
    def _get_path(self) -> Optional[str]:
        if self.uri.startswith('gs://'):
            return _GCS_LOCAL_MOUNT_PREFIX + self.uri[len('gs://'):]
        elif self.uri.startswith('minio://'):
            return _MINIO_LOCAL_MOUNT_PREFIX + self.uri[len('minio://'):]
        elif self.uri.startswith('s3://'):
            return _S3_LOCAL_MOUNT_PREFIX + self.uri[len('s3://'):]
        
        raise ValueError("Detailed explanation and possible help to solve this error.")
```

**Comment by alexisgaziello** [comment]
The error was that I was passing an int instead of a string to f.write() ...
