### ISSUE TITLE
Failed to start pipeline 

### ISSUE THREAD

**Issue by eyalcha** [kubeflow/pipelines#7480]
### Environment

Standalone KFP

Bootstrapper fails when there is python package installed with -e

```
[D 06:36:56.914] Parsing Arguments.....
[I 06:36:56.916] 'model-0329063649':'pre' - starting operation 
[I 06:36:56.916] 'model-0329063649':'pre' - Installing packages 
Traceback (most recent call last):
  File "/jupyter-work-dir/bootstrapper.py", line 652, in <module>
    main()
  File "/jupyter-work-dir/bootstrapper.py", line 635, in main
    OpUtil.package_install(user_volume_path=input_params.get('user-volume-path'))
  File "/jupyter-work-dir/bootstrapper.py", line 524, in package_install
    current_packages = cls.package_list_to_dict("requirements-current.txt")
  File "/jupyter-work-dir/bootstrapper.py", line 571, in package_list_to_dict
    package_name, package_version = line.strip('\n').split(sep="==")
ValueError: not enough values to unpack (expected 2, got 1)
```

Here is the list of packages installed in the docker

```
# pip freeze
certifi==2021.10.8
joblib==1.1.0
minio==7.1.5
# Editable install with no version control (model-utils==0.0.4)
-e /model_utils
numpy==1.22.3
pandas==1.4.1
python-dateutil==2.8.2
pytz==2022.1
scikit-learn==1.0.2
scipy==1.8.0
six==1.16.0
threadpoolctl==3.1.0
urllib3==1.26.9
```

**Comment by eyalcha** [comment]
Not an issue of KFP
