### ISSUE TITLE
[backend] V2 pipelins can't save numpy files using Output[Dataset] notation

### ISSUE THREAD

**Issue by ConverJens** [kubeflow/pipelines#7561]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
Bundled with KF 1.5
*  KFP version: 
1.8.1
*  KFP SDK version: 
1.8.12

### Steps to reproduce

Create a simple component that saves a file in numpy format using the v2 artifact notation `Output[Dataset]`:

```
@component()
def numpy_test(output_data: Output[Dataset]):
    import numpy as np

    np_arr = np.array([1, 2, 3, 4])
    np.save(f"{output_data.path}/data.npy", np_arr)

```

### Expected result

File should be saved succesfully

### Materials and Reference

Logs from component execution:

```
time="2022-04-14T10:50:53.395Z" level=info msg="capturing logs" argo=true
I0414 10:50:53.419935      25 launcher.go:144] PipelineRoot defaults to "minio://kubeflow-internal/artifacts/v2".
I0414 10:50:53.420141      25 cache.go:143] Cannot detect ml-pipeline in the same namespace, default to ml-pipeline.kubeflow:8887 as KFP endpoint.
I0414 10:50:53.420147      25 cache.go:120] Connecting to cache endpoint ml-pipeline.kubeflow:8887
I0414 10:50:53.851228      25 launcher.go:193] enable caching
I0414 10:50:54.011769      25 object_store.go:305] Cannot detect minio-service in the same namespace, default to minio-service.kubeflow:9000 as MinIO endpoint.
[KFP Executor 2022-04-14 10:50:55,331 INFO]: Looking for component `numpy_test` in --component_module_path `/tmp/tmp.AgNinLaVsS/ephemeral_component.py`
[KFP Executor 2022-04-14 10:50:55,331 INFO]: Loading KFP component "numpy_test" from /tmp/tmp.AgNinLaVsS/ephemeral_component.py (directory "/tmp/tmp.AgNinLaVsS" and module name "ephemeral_component")
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/pyenv/lib/python3.7/site-packages/kfp/v2/components/executor_main.py", line 104, in <module>
    executor_main()
  File "/root/pyenv/lib/python3.7/site-packages/kfp/v2/components/executor_main.py", line 100, in executor_main
    executor.execute()
  File "/root/pyenv/lib/python3.7/site-packages/kfp/v2/components/executor.py", line 309, in execute
    result = self._func(**func_kwargs)
  File "/tmp/tmp.AgNinLaVsS/ephemeral_component.py", line 11, in numpy_test
    np.save(f"{output_data.path}/data.npy", np_arr)
  File "<__array_function__ internals>", line 6, in save
  File "/root/pyenv/lib/python3.7/site-packages/numpy/lib/npyio.py", line 525, in save
    file_ctx = open(file, "wb")
FileNotFoundError: [Errno 2] No such file or directory: '/minio/kubeflow-internal/artifacts/v2/pipeline/np-test-v2/e772b3c5-6608-429f-ac7f-e352853a19f6/numpy-test/output_data/data.npy'
F0414 10:50:55.585759      25 main.go:50] Failed to execute component: exit status 1
time="2022-04-14T10:50:55.587Z" level=error msg="cannot save artifact /tmp/outputs/output_data/data" argo=true error="stat /tmp/outputs/output_data/data: no such file or directory"
Error: exit status 1
```

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by andreclaudino** [comment]
I am experiencing the same problem, in version kfp sdk version 1.4.0 it worked fine.

My component code is this:

```Python
@dsl.component
def make_date_parser(datetime: str, input_format: str, output_format: str, days_to_add: int,
                     command: str = STARTUP_COMMAND, image_name: str = IMAGE_NAME, image_tag: str = IMAGE_TAG,
                     memory_limit: int = MEMORY_LIMIT, memory_request: int = MEMORY_REQUEST,
                     cpu_limit: int = CPU_LIMIT, cpu_request: int = CPU_REQUEST, display_name: str = DISPLAY_NAME,
                     ) -> ContainerOp:

    image = f"{image_name}:{image_tag}"

    operator = ContainerOp(
        name=CONTAINER_NAME,
        image=image,
        command=command,
        arguments=[
            "--input-format", input_format,
            "--output-format", output_format,
            "--save-to", OUTPUT_PATH,
            f"--add-days={days_to_add}",
            datetime
        ],
        file_outputs={
            'converted_date': OUTPUT_PATH,
        }
    )

    operator = operator.set_display_name(display_name)
    operator = setup_resources(operator, memory_request, memory_limit, cpu_request, cpu_limit)

    return operator
```

My output is similar to @ConverJens's output:

```
time="2022-04-15T04:06:32.738Z" level=info msg="capturing logs" argo=true
Original format: %d/%m/%Y %H:%M
Resulting format: %Y-%m-%d
Saving transformed dates to converted_date.txt
Results:
{ontem} -> 2022-04-14
time="2022-04-15T04:06:32.739Z" level=info msg="converted_date.txt -> /var/run/argo/outputs/parameters/converted_date.txt" argo=true
time="2022-04-15T04:06:32.739Z" level=error msg="cannot save artifact /tmp/outputs/Output/data" argo=true error="stat /tmp/outputs/Output/data: no such file or directory"
time="2022-04-15T04:06:32.739Z" level=info msg="converted_date.txt -> /var/run/argo/outputs/artifacts/converted_date.txt.tgz" argo=true
time="2022-04-15T04:06:32.739Z" level=info msg="Taring /converted_date.txt"
```

**Comment by Linchin** [comment]
KFP compatible mode is no longer supported, so try using KFP backend 2.0.0-alpha.1 and sdk  2.0.0-alpha.2 version and see if it works. You don't have to specify using compatible mode in v2 [ref](https://www.kubeflow.org/docs/components/pipelines/sdk-v2/v2-compatibility/#compiling-and-running-pipelines-in-v2-compatibility-mode), and also note that there is name space change. You need to change `import kfp.v2` to `import kfp`.

**Comment by rimolive** [comment]
Closing this issue. No activity for more than a year.

/close

**Comment by steve-offutt** [comment]
I know this issue is closed but I hope it saves someone some time!

I wanted to provide some feedback from my experience using numpy arrays in KFP since I too stumbled across this issue creating numpy artifacts using `kfp 2.8.0`. I think the issue may be with the way in which numpy saves the numpy arrays. It attempts to append a `.npy` to the filename if a string is given for the `file` argument. According to the docs on `numpy.save()`:
```
file : file, str, or pathlib.Path
File or filename to which the data is saved. If file is a file-object, then the filename is unchanged. If file is a string or Path, a .npy extension will be appended to the filename if it does not already have one.
```
I suppose numpy appending the file extension messes things up? Using a context manager on the `Output[Dataset]` variable fixed my issue!

```python
from kfp import dsl

@dsl.component(base_image='python:3.11')
def save_numpy_array(out: Output[Dataset]):
    import numpy as np

    data = np.array([1, 2, 3, 4])
    with open(out.path, 'wb') as f:
        np.save(f, data)
```
