### ISSUE TITLE
[backend] JSONDecodeError: in BigQuery `bigquery_create_model_job` execution

### ISSUE THREAD

**Issue by eshaingle** [kubeflow/pipelines#8103]
### What steps did you take ###
Executing big query create model functionality through pipeline using 

image: gcr.io/ml-pipeline/google-cloud-pipeline-components:1.0.13
command: [python3, -u, -m, google_cloud_pipeline_components.container.v1.gcp_launcher.launcher]
with type: `BigqueryCreateModelJob`,

Also followed the component.yaml format as mentioned here:

https://github.com/kubeflow/pipelines/blob/google-cloud-pipeline-components-1.0.13/components/google-cloud/google_cloud_pipeline_components/v1/bigquery/create_model/component.yaml

I get below error when executing the pipeline:

`Traceback (most recent call last):
  File "/opt/python3.7/lib/python3.7/site-packages/google_cloud_pipeline_components/container/v1/gcp_launcher/bigquery_job_remote_runner.py", line 332, in bigquery_create_model_job
    artifact_util.update_output_artifacts(executor_input, [bqml_model_artifact])
  File "/opt/python3.7/lib/python3.7/site-packages/google_cloud_pipeline_components/container/v1/gcp_launcher/utils/artifact_util.py", line 51, in update_output_artifacts
    executor_input_json = json.loads(executor_input)
  File "/opt/python3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/python3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/python3.7/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)`

This is because of the `--executor_input, "{{$}}",` param in the component.yaml file
It is not an input parameter so it should take and proceed but it fails.

### What did you expect to happen: ###
That the pipeline would run successfully

Please provide any suggestion/solution how to bypass the error and make the pipeline run success

**Comment by eshaingle** [comment]
Hi Team,
any suggestions here?
