### ISSUE TITLE
[bug] Unable to produce pipeline with basic Component I/O

### ISSUE THREAD

**Issue by MartinRogmann** [kubeflow/pipelines#8307]
### Environment

*  How do you deploy Kubeflow Pipelines (KFP)?

Installed kubeflow manifest **v1.6.0-rc.1** with **minikube v1.26.0** and **kubectl v1.21.14**

For detailed output:

minikube version: v1.26.0
commit: f4b412861bb746be73053c9f6d2895f12cf78565

kubectl  version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-15T14:17:29Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-15T14:11:36Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

*  KFP version:

*  KFP SDK version:

Inside notebook: pip list | grep kfp
kfp                          1.6.3
kfp-pipeline-spec            0.1.16
kfp-server-api               1.6.0

### Steps to reproduce

We tried to produce a basic pipeline that saves pandas dataframes in one component and uses it in the next component using artifacts. We experimented with both Output[Dataset] and OutputPath(str) and tried various samples from v1/v2 SDK without success.

To reproduce, create the following options:

**Imports**
```
import kfp
import kfp.dsl as dsl
from kfp.v2.dsl import component, Input, Output, InputPath, OutputPath, Dataset, Metrics, Model, Artifact
```

**Option A: Using csv**
```
@component(
    packages_to_install = ["pandas", "sklearn"],
)
def load(data: Output[Dataset]):
    import pandas as pd
    from sklearn import datasets

    dataset = datasets.load_iris()
    df = pd.DataFrame(data=dataset.data, columns= ["Petal Length", "Petal Width", "Sepal Length", "Sepal Width"])
    
    df.to_csv(data.path)

@component(
    packages_to_install = ["pandas"],
)
def print_head(data: Input[Dataset]):
    import pandas as pd
    df = pd.read_csv(data.path)
    print(df.head())

@dsl.pipeline(
    name='Iris',
    description='iris'
)
def pipeline():
    load_task = load()
    print_task = print_head(data=load_task.outputs["data"])

kfp.compiler.Compiler(mode=kfp.dsl.PipelineExecutionMode.V2_COMPATIBLE).compile(
    pipeline_func=pipeline,
    package_path='iris_csv.yaml')
```

**Option B: Using pickle**
```
@component(
    packages_to_install = ["pandas", "sklearn"],
)
def load(data: Output[Dataset]):
    import pickle
    import pandas as pd
    from sklearn import datasets

    dataset = datasets.load_iris()
    df = pd.DataFrame(data=dataset.data, columns= ["Petal Length", "Petal Width", "Sepal Length", "Sepal Width"])
    
    with open(data.path, "wb") as f:
        pickle.dump(df, f)

@component(
    packages_to_install = ["pandas"],
)
def print_head(data: Input[Dataset]):
    import pickle
    import pandas as pd
    
    with open(data.path, 'rb') as f:
        df = pickle.load(f)

    print(df.head())

@dsl.pipeline(
    name='Iris',
    description='iris'
)
def pipeline():
    load_task = load()
    print_task = print_head(data=load_task.outputs["data"])

kfp.compiler.Compiler(mode=kfp.dsl.PipelineExecutionMode.V2_COMPATIBLE).compile(
    pipeline_func=pipeline,
    package_path='iris_pickle.yaml')
```

**Option C: Using json**
```
@component(
    packages_to_install = ["pandas", "sklearn"],
)
def load(data: Output[Dataset]):
    import pandas as pd
    from sklearn import datasets

    dataset = datasets.load_iris()
    df = pd.DataFrame(data=dataset.data, columns= ["Petal Length", "Petal Width", "Sepal Length", "Sepal Width"])
    
    json_df = {"data": df}
    
    with open(data.path, "wb") as f:
        f.write(json.dumps(result, default=lambda df: json.loads(df.to_json())))

@component(
    packages_to_install = ["pandas"],
)
def print_head(data: Input[Dataset]):
    import pandas as pd
    
    with open(data.path, 'rb') as f:
        df = pd.DataFrame(json.loads(f.read())["data"])

    print(df.head())

@dsl.pipeline(
    name='Iris',
    description='iris'
)
def pipeline():
    load_task = load()
    print_task = print_head(data=load_task.outputs["data"])

kfp.compiler.Compiler(mode=kfp.dsl.PipelineExecutionMode.V2_COMPATIBLE).compile(
    pipeline_func=pipeline,
    package_path='iris_json.yaml')
```

All three options result in the following error:
```
time="2022-09-26T09:50:42.264Z" level=info msg="capturing logs" argo=true
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: 
https://pip.pypa.io/warnings/venv
Traceback (most recent call last):
  File "/tmp/tmp.CjkMbFoRTh", line 826, in <module>
    executor_main()
  File "/tmp/tmp.CjkMbFoRTh", line 820, in executor_main
    function_to_execute=function_to_execute)
  File "/tmp/tmp.CjkMbFoRTh", line 549, in __init__
    artifacts_list[0])
  File "/tmp/tmp.CjkMbFoRTh", line 562, in _make_output_artifact
    os.makedirs(os.path.dirname(artifact.path), exist_ok=True)
  File "/usr/local/lib/python3.7/posixpath.py", line 156, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
F0926 09:51:03.011047      26 main.go:56] Failed to execute component: exit status 1
time="2022-09-26T09:51:03.028Z" level=error msg="cannot save artifact /tmp/outputs/data/data" argo=true error="stat /tmp/outputs/data/data: no such file or directory"
Error: exit status 1
```

### Expected result

Clearer examples in https://github.com/kubeflow/pipelines/tree/master/samples. As it is hard to distinguish which sample are actually using the v1 or v2 syntax and are compatible with the latest version.

Can you provide a minimal working example that ideally also includes the use of multiple inputs and outputs and the logging of metrics and models. The samples we found in the docs or on github either use the deprecated container_ops instead of components or could not be run by us.

### Labels

/area sdk
/area samples
/area components

---

Impacted by this bug? Give it a 👍.

**Comment by Linchin** [comment]
Hi @MartinRogmann, maybe consider upgrading the kfp SDK to 1.8.14 and see if the error persists?

**Comment by MartinRogmann** [comment]
Hi @Linchin, that solved the problem. Thank you
