### ISSUE TITLE
[backend] ML Metadata writer errors with - Received message larger than max

### ISSUE THREAD

**Issue by Sharathmk99** [kubeflow/pipelines#8408]
### Environment

ML Metadata writes errors with below exception. Looks like we need to change default `max_receive_message_length` from 4194304 to bigger number.

Error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/ml_metadata/metadata_store/metadata_store.py", line 199, in _call_method
    response.CopyFrom(grpc_method(request, timeout=self._grpc_timeout_sec))
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.RESOURCE_EXHAUSTED
        details = "Received message larger than max (4765896 vs. 4194304)"
        debug_error_string = "{"created":"@1667318328.637859534","description":"Received message larger than max (4765896 vs. 4194304)","file":"src/core/ext/filters/message_size/message_size_filter.cc","file_line":206,"grpc_status":8}"
```

*  How did you deploy Kubeflow Pipelines (KFP)?

On-premises
*  KFP version: 1.7.0 

*  KFP SDK version: 

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by chensun** [comment]
Hi @Sharathmk99, I'm not sure if it's a good idea to allow configure the limit, there likely will be other system limitation, for example, at DB storage layer. 
Can you help explain a bit your use case, why did you get such large content for artifacts?

**Comment by Sharathmk99** [comment]
@chensun I was not facing this issue initially, but started to face once Kubeflow has more than 5k pipeline runs. Looks like we have to implement pagination on how metadata-writer queries metadata-server. Please see the issue here https://github.com/google/ml-metadata/issues/74 and https://github.com/google/ml-metadata/issues/42

**Comment by amirhessam88** [comment]
@chensun @Sharathmk99 
I would like to address my issue here as well since I think it has the same root cause.

I am using `kfp v1.8.9` and I see have bunch of recurring pipelines that run every 10 minutes; and after ~ 1 week (> 5000 runs), I get the following error:

```
──────────────────── Traceback (most recent call last) ──────────────────────╮
│ /usr/local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_s │
│ tore.py:213 in _call_method                                                  │
│                                                                              │
│    210 │   else:                                                             │
│    211 │     grpc_method = getattr(self._metadata_store_stub, method_name)   │
│    212 │     try:                                                            │
│ ❱  213 │   │   response.CopyFrom(grpc_method(request, timeout=self._grpc_tim │
│    214 │     except grpc.RpcError as e:                                      │
│    215 │   │   # RpcError code uses a tuple to specify error code and short  │
│    216 │   │   # description.                                                │
│                                                                              │
│ /usr/local/lib/python3.9/site-packages/grpc/_channel.py:946 in __call__      │
│                                                                              │
│    943 │   │   │   │    compression=None):                                   │
│    944 │   │   state, call, = self._blocking(request, timeout, metadata, cre │
│    945 │   │   │   │   │   │   │   │   │     wait_for_ready, compression)    │
│ ❱  946 │   │   return _end_unary_response_blocking(state, call, False, None) │
│    947 │                                                                     │
│    948 │   def with_call(self,                                               │
│    949 │   │   │   │     request,                                            │
│                                                                              │
│ /usr/local/lib/python3.9/site-packages/grpc/_channel.py:849 in               │
│ _end_unary_response_blocking                                                 │
│                                                                              │
│    846 │   │   else:                                                         │
│    847 │   │   │   return state.response                                     │
│    848 │   else:                                                             │
│ ❱  849 │   │   raise _InactiveRpcError(state)                                │
│    850                                                                       │
│    851                                                                       │
│    852 def _stream_unary_invocation_operationses(metadata, initial_metadata_ │
╰──────────────────────────────────────────────────────────────────────────────╯
_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.RESOURCE_EXHAUSTED
        details = "Received message larger than max (5282972 vs. 4194304)"
        debug_error_string = "UNKNOWN:Error received from peer 
metadata-grpc-service.kubeflow:8080 
{created_time:"2023-03-27T14:37:17.768468153+00:00", grpc_status:8, 
grpc_message:"Received message larger than max (5282972 vs. 4194304)"}"
>
During handling of the above exception, another exception occurred:
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /usr/local/lib/python3.9/runpy.py:197 in _run_module_as_main                 │
│                                                                              │
│   194 │   main_globals = sys.modules["__main__"].__dict__                    │
│   195 │   if alter_argv:                                                     │
│   196 │   │   sys.argv[0] = mod_spec.origin                                  │
│ ❱ 197 │   return _run_code(code, main_globals, None,                         │
│   198 │   │   │   │   │    "__main__", mod_spec)                             │
│   199                                                                        │
│   200 def run_module(mod_name, init_globals=None,                            │
│                                                                              │
│ /usr/local/lib/python3.9/runpy.py:87 in _run_code                            │
│                                                                              │
│    84 │   │   │   │   │      __loader__ = loader,                            │
│    85 │   │   │   │   │      __package__ = pkg_name,                         │
│    86 │   │   │   │   │      __spec__ = mod_spec)                            │
│ ❱  87 │   exec(code, run_globals)                                            │
│    88 │   return run_globals                                                 │
│    89                                                                        │
│    90 def _run_module_code(code, init_globals=None,                          │
│                                                                              │
│ /usr/local/lib/python3.9/site-packages/zenml/entrypoints/step_entrypoint.py: │
│ 62 in <module>                                                               │
│                                                                              │
│   59                                                                         │
│   60                                                                         │
│   61 if __name__ == "__main__":                                              │
│ ❱ 62 │   main()                                                              │
│   63                                                                         │
│                                                                              │
│ /usr/local/lib/python3.9/site-packages/zenml/entrypoints/step_entrypoint.py: │
│ 58 in main                                                                   │
│                                                                              │
│   55 │   entrypoint_config = entrypoint_config_class(arguments=remaining_arg │
│   56 │                                                                       │
│   57 │   # Run the entrypoint configuration                                  │
│ ❱ 58 │   entrypoint_config.run()                                             │
│   59                                                                         │
│   60                                                                         │
│   61 if __name__ == "__main__":                                              │
│                                                                              │
│ /usr/local/lib/python3.9/site-packages/zenml/entrypoints/step_entrypoint_con │
│ figuration.py:628 in run                                                     │
│                                                                              │
│   625 │   │   # Execute the actual step code.                                │
│   626 │   │   run_name = self.get_run_name(pipeline_name=pipeline_name)      │
│   627 │   │   orchestrator = Repository().active_stack.orchestrator          │
│ ❱ 628 │   │   execution_info = orchestrator.run_step(                        │
│   629 │   │   │   step=step, run_name=run_name, pb2_pipeline=pb2_pipeline    │
│   630 │   │   )                                                              │
│   631                                                                        │
│                                                                              │
│ /usr/local/lib/python3.9/site-packages/zenml/orchestrators/base_orchestrator │
│ .py:395 in run_step                                                          │
│                                                                              │
│   392 │   │   # This is where the step actually gets executed using the      │
│   393 │   │   # component_launcher                                           │
│   394 │   │   repo.active_stack.prepare_step_run()                           │
│ ❱ 395 │   │   execution_info = self._execute_step(component_launcher)        │
│   396 │   │   repo.active_stack.cleanup_step_run()                           │
│   397 │   │                                                                  │
│   398 │   │   return execution_info                                          │
│                                                                              │
│ /usr/local/lib/python3.9/site-packages/zenml/orchestrators/base_orchestrator │
│ .py:419 in _execute_step                                                     │
│                                                                              │
│   416 │   │   start_time = time.time()                                       │
│   417 │   │   logger.info(f"Step `{pipeline_step_name}` has started.")       │
│   418 │   │   try:                                                           │
│ ❱ 419 │   │   │   execution_info = tfx_launcher.launch()                     │
│   420 │   │   │   if execution_info and get_cache_status(execution_info):    │
│   421 │   │   │   │   logger.info(f"Using cached version of `{pipeline_step_ │
│   422 │   │   except RuntimeError as e:                                      │
│                                                                              │
│ /usr/local/lib/python3.9/site-packages/tfx/orchestration/portable/launcher.p │
│ y:528 in launch                                                              │
│                                                                              │
│   525 │   │   │   │   │   │   │   │   │   │      self._pipeline_runtime_spec │
│   526 │                                                                      │
│   527 │   # Runs as a normal node.                                           │
│ ❱ 528 │   execution_preparation_result = self._prepare_execution()           │
│   529 │   (execution_info, contexts,                                         │
│   530 │    is_execution_needed) = (execution_preparation_result.execution_in │
│   531 │   │   │   │   │   │   │    execution_preparation_result.contexts,    │
│                                                                              │
│ /usr/local/lib/python3.9/site-packages/tfx/orchestration/portable/launcher.p │
│ y:315 in _prepare_execution                                                  │
│                                                                              │
│   312 │     input_artifacts = resolved_inputs[0]                             │
│   313 │                                                                      │
│   314 │     # 4. Registers execution in metadata.                            │
│ ❱ 315 │     execution = self._register_or_reuse_execution(                   │
│   316 │   │     metadata_handler=m,                                          │
│   317 │   │     contexts=contexts,                                           │
│   318 │   │     input_artifacts=input_artifacts,                             │
│                                                                              │
│ /usr/local/lib/python3.9/site-packages/tfx/orchestration/portable/launcher.p │
│ y:225 in _register_or_reuse_execution                                        │
│                                                                              │
│   222 │     exec_properties: Optional[Mapping[str, types.Property]] = None,  │
│   223   ) -> metadata_store_pb2.Execution:                                   │
│   224 │   """Registers or reuses an execution in MLMD."""                    │
│ ❱ 225 │   executions = execution_lib.get_executions_associated_with_all_cont │
│   226 │   │   metadata_handler, contexts)                                    │
│   227 │   if len(executions) > 1:                                            │
│   228 │     raise RuntimeError('Expecting no more than one previous executio │
│                                                                              │
│ /usr/local/lib/python3.9/site-packages/tfx/orchestration/portable/mlmd/execu │
│ tion_lib.py:290 in get_executions_associated_with_all_contexts               │
│                                                                              │
│   287   """                                                                  │
│   288   executions_dict = None                                               │
│   289   for context in contexts:                                             │
│ ❱ 290 │   executions = metadata_handler.store.get_executions_by_context(cont │
│   291 │   if executions_dict is None:                                        │
│   292 │     executions_dict = {e.id: e for e in executions}                  │
│   293 │   else:                                                              │
│                                                                              │
│ /usr/local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_s │
│ tore.py:1328 in get_executions_by_context                                    │
│                                                                              │
│   1325 │                                                                     │
│   1326 │   request = metadata_store_service_pb2.GetExecutionsByContextReques │
│   1327 │   request.context_id = context_id                                   │
│ ❱ 1328 │   return self._call_method_with_list_options('GetExecutionsByContex │
│   1329 │   │   │   │   │   │   │   │   │   │   │      'executions', request, │
│   1330 │   │   │   │   │   │   │   │   │   │   │      list_options)          │
│   1331                                                                       │
│                                                                              │
│ /usr/local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_s │
│ tore.py:980 in _call_method_with_list_options                                │
│                                                                              │
│    977 │     if return_size and return_size < MAX_NUM_RESULT:                │
│    978 │   │   request.options.max_result_size = return_size                 │
│    979 │                                                                     │
│ ❱  980 │     self._call(method_name, request, response)                      │
│    981 │     entities = getattr(response, entity_field_name)                 │
│    982 │     for x in entities:                                              │
│    983 │   │   result.append(x)                                              │
│                                                                              │
│ /usr/local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_s │
│ tore.py:188 in _call                                                         │
│                                                                              │
│    185 │   avg_delay_sec = 2                                                 │
│    186 │   while True:                                                       │
│    187 │     try:                                                            │
│ ❱  188 │   │   return self._call_method(method_name, request, response)      │
│    189 │     except errors.AbortedError:                                     │
│    190 │   │   num_retries -= 1                                              │
│    191 │   │   if num_retries == 0:                                          │
│                                                                              │
│ /usr/local/lib/python3.9/site-packages/ml_metadata/metadata_store/metadata_s │
│ tore.py:218 in _call_method                                                  │
│                                                                              │
│    215 │   │   # RpcError code uses a tuple to specify error code and short  │
│    216 │   │   # description.                                                │
│    217 │   │   # 
https://grpc.github.io/grpc/python/_modules/grpc.html#Statu
 │
│ ❱  218 │   │   raise _make_exception(e.details(), e.code().value[0])  # pyty │
│    219                                                                       │
│    220   def _pywrap_cc_call(self, method, request, response) -> None:       │
│    221 │   """Calls method, serializing and deserializing inputs and outputs │
╰──────────────────────────────────────────────────────────────────────────────╯
ResourceExhaustedError: Received message larger than max (5282972 vs. 4194304)
``` 

I did read almost all the open/close related issues; and I am not sure this can be done from the client side in my case; considering I am just using the `kfp.Client()` (if there is a way I would like to implement it until this issue is fixed upstream);
Thanks

**Comment by amirhessam88** [comment]
BTW, we upgraded to `kubeflow` version `1.7` and this issue is now fixed.
