### ISSUE TITLE
[bug] Compiling a component raises AttributeError: 'NoneType' object has no attribute '_set_metadata'

### ISSUE THREAD

**Issue by Rabelaiss** [kubeflow/pipelines#8413]
Following the official documentation on Kubeflow V2 (link below), I'm trying to compile a simple component which just prints a string, but it raises an `AttributeError` which I don't understand. What's going on?

### Environment

Windows 11
Python 3.10.1
kfp 1.8.14
kfp-pipeline-spec 0.1.16
kfp-server-api 1.8.5

### Steps to reproduce

```
from kfp import dsl
@dsl.component
def printer():
    print('----o----')

from kfp import compiler
cmplr = compiler.Compiler()
cmplr.compile(printer, package_path='printer.yaml')
----o----
Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "C:\Users\gtu\AppData\Local\Programs\Python\Python310\lib\site-packages\kfp\compiler\compiler.py", line 1175, in compile
    self._create_and_write_workflow(
    File "C:\Users\gtu\AppData\Local\Programs\Python\Python310\lib\site-packages\kfp\compiler\compiler.py", line 1227, in _create_and_write_workflow
    workflow = self._create_workflow(pipeline_func, pipeline_name,
    File "C:\Users\gtu\AppData\Local\Programs\Python\Python310\lib\site-packages\kfp\compiler\compiler.py", line 1005, in _create_workflow
    pipeline_func(*args_list, **kwargs_dict)
    File "C:\Users\gtu\AppData\Local\Programs\Python\Python310\lib\site-packages\kfp\dsl\_component.py", line 118, in _component
    container_op._set_metadata(component_meta)
AttributeError: 'NoneType' object has no attribute '_set_metadata'
```

### Expected result

Generation of file `printer.yaml`.

### Materials and reference

https://www.kubeflow.org/docs/components/pipelines/v2/compile-a-pipeline/#compiling

### Labels

/area components

---

Impacted by this bug? Give it a 👍

**Comment by Rabelaiss** [comment]
solved installing V2 through `pip install kfp --pre`

**Comment by Rabelaiss** [comment]
solved installing V2 through `pip install kfp --pre`
