### ISSUE TITLE
[sdk] dsl.Condition throws Attribute error on valid condition in kfp.compiler.compiler_utilsL131

### ISSUE THREAD

**Issue by MatthewRalston** [kubeflow/pipelines#8627]
### Environment

*  KFP version:

Minikube v1.28.0
kubernetes 1.22.2
Kustomize v3.2.0
kubectl v1.25.5
Manifests v1.6.1
*  KFP SDK version: 

*  All dependencies version:

kfp 2.0.0b9
kfp-pipeline-spec 0.1.16
kfp-server-api 2.0.0a6
### Steps to reproduce

All you have to do is specify a `dsl.Condition` with a Python condition, and an attribute error is thrown when called on the 'bool' evaluated from the Python condition.
```python
@dsl.container_component
def gunzip(infile:dsl.InputPath(str), outfile:dsl.OutputPath(str)):
    return dsl.ContainerSpec(
        image='bitnami/minideb:latest',
        command=[
            'zcat '
            '$1 ',
            '> ',
            '$2 ',
            '||',
            'mv $1 $2'
        ],
        args=[infile, outfile]
    )


@dsl.pipeline(
    name='kubeflow-barebone-demo',
    description='kubeflow demo with minimal setup'
)
def rnaseq_pipeline(fastq1:str):
    # Step 1: checking file extension(s) for gzip compression
    with dsl.Condition(str(fastq1).endswith(".gz"), 'fastq1-needs-gunzip'):
        
        gunzip1 = gunzip(infile=fastq1)
```

#### Output
```python
Traceback (most recent call last):
  File "./pipeline.py", line 51, in <module>
    def rnaseq_pipeline(fastq1:dsl.Input[dsl.Dataset]):
  File "/home/matt/.pyenv/versions/miniconda3-4.7.12/lib/python3.7/site-packages/kfp/components/pipeline_context.py", line 67, in pipeline
    return component_factory.create_graph_component_from_func(func)
  File "/home/matt/.pyenv/versions/miniconda3-4.7.12/lib/python3.7/site-packages/kfp/components/component_factory.py", line 527, in create_graph_component_from_func
    name=component_name,
  File "/home/matt/.pyenv/versions/miniconda3-4.7.12/lib/python3.7/site-packages/kfp/components/graph_component.py", line 69, in __init__
    pipeline_outputs=pipeline_outputs,
  File "/home/matt/.pyenv/versions/miniconda3-4.7.12/lib/python3.7/site-packages/kfp/compiler/pipeline_spec_builder.py", line 1549, in create_pipeline_spec
    root_group)
  File "/home/matt/.pyenv/versions/miniconda3-4.7.12/lib/python3.7/site-packages/kfp/compiler/compiler_utils.py", line 146, in get_condition_channels_for_tasks
    _get_condition_channels_for_tasks_helper(root_group, [])
  File "/home/matt/.pyenv/versions/miniconda3-4.7.12/lib/python3.7/site-packages/kfp/compiler/compiler_utils.py", line 144, in _get_condition_channels_for_tasks_helper
    group, new_current_conditions_channels)
  File "/home/matt/.pyenv/versions/miniconda3-4.7.12/lib/python3.7/site-packages/kfp/compiler/compiler_utils.py", line 131, in _get_condition_channels_for_tasks_helper
    if isinstance(group.condition.left_operand,
AttributeError: 'bool' object has no attribute 'left_operand'
```

### Expected result

I'm not sure what was intended by the `left_operand` call, but I expected more documentation on how to use a conditional in Kubeflow pipelines.

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by chensun** [comment]
`str(fastq1).endswith(".gz")` is not a valid condition to `dsl.Condition`.
`dsl.Condition` expects two operants and an operator:

https://www.kubeflow.org/docs/components/pipelines/v2/author-a-pipeline/pipelines/#dslcondition
