### ISSUE TITLE
[sdk] `list_recurring_runs` needs a namespace filter even-though the kfpClient was instantiated with a namespace

### ISSUE THREAD

**Issue by JakeSummers** [kubeflow/pipelines#8777]
### Environment

*  KFP version: kubeflow 1.6 and kubeflow pipelines 1.8.3

*  KFP SDK version: 1.8.12

### Steps to reproduce

```
    # Create a kfp client with a namespace
    client = kfp.Client(kubeflow_host.host,
                        namespace="NamespaceJake", # NOTE: Namespace is provided here!
                        existing_token=token,
                        )

    # List recurring runs:     
    current_recurring_runs: ApiListJobsResponse = client.list_recurring_runs(page_token=None)

```

I get the following error: 

```
Traceback (most recent call last):
  ...
  File "code.py", line 66, in _find_recurring_run
    current_recurring_runs: ApiListJobsResponse = client.list_recurring_runs(page_token=None)
  File "/.../site-packages/kfp/_client.py", line 1200, in list_recurring_runs
    response = self._job_api.list_jobs(
  File "/.../site-packages/kfp_server_api/api/job_service_api.py", line 689, in list_jobs
    return self.list_jobs_with_http_info(**kwargs)  # noqa: E501
  File "/.../site-packages/kfp_server_api/api/job_service_api.py", line 790, in list_jobs_with_http_info
    return self.api_client.call_api(
  File "/.../site-packages/kfp_server_api/api_client.py", line 364, in call_api
    return self.__call_api(resource_path, method,
  File "/.../site-packages/kfp_server_api/api_client.py", line 188, in __call_api
    raise e
  File "/.../site-packages/kfp_server_api/api_client.py", line 181, in __call_api
    response_data = self.request(
  File "/.../site-packages/kfp_server_api/api_client.py", line 389, in request
    return self.rest_client.GET(url,
  File "/.../site-packages/kfp_server_api/rest.py", line 230, in GET
    return self.request("GET", url,
  File "/.../site-packages/kfp_server_api/rest.py", line 224, in request
    raise ApiException(http_resp=r)
kfp_server_api.exceptions.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'x-powered-by': 'Express', 'content-type': 'application/json', 'date': 'Wed, 01 Feb 2023 15:52:17 GMT', 'content-length': '437',  ...)
HTTP response body: {"error":"Invalid input error: ListJobs must filter by resource reference in multi-user mode.","code":3,"message":"Invalid input error: ListJobs must filter by resource reference in multi-user mode.","details":[{"@type":"type.googleapis.com/api.Error","error_message":"ListJobs must filter by resource reference in multi-user mode.","error_details":"Invalid input error: ListJobs must filter by resource reference in multi-user mode."}]}
```

### Expected result

When I instantiated the kfp client, I provided my namespace.  I should not need to provide the namespace to the `list_recurring_runs`.  

Impacted by this bug? Give it a 👍.

**Comment by JakeSummers** [comment]
Looking at this a bit further, it seems like it is not asking for the `namespace` but for the `experiment`.  

Changing this: 

```
    current_recurring_runs: ApiListJobsResponse = client.list_recurring_runs(page_token=None)
```

To this: 

```
    current_recurring_runs: ApiListJobsResponse = client.list_recurring_runs(page_token=None, experiment_id=123)
```

Fixed the issue.
