### ISSUE TITLE
[sdk] Imports from kfp.dsl cause error AttributeError: module 'kfp_server_api' has no attribute 'ApiPipelineSpec

### ISSUE THREAD

**Issue by vgarba2** [kubeflow/pipelines#8827]
### Environment

*  KFP version:
kfp==2.0.0b1

*  All dependencies version:
kfp-pipeline-spec==0.1.16
kfp-server-api==2.0.0b0

### Steps to reproduce

1. `from kfp import dsl`
2. Use any part of dsl, such as pipeline or component decorators

```
from kfp import dsl, compiler

@dsl.pipeline(
    name="test"
)
def pipeline_fn(
        location: str,
        project_id: str,
):
  print("hello world") 


compiler.Compiler().compile(
    pipeline_func=pipeline_fn,
    package_path='hello_world_pipeline.yaml')

```
4. Attempt to build component
5. Error results: 

`Traceback (most recent call last):
  File "/Users/viktorgarba/miniconda/envs/ml-env/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/viktorgarba/miniconda/envs/ml-env/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/viktorgarba/klover/attain-ai-ml/src/pipelines/bert_v1.py", line 1, in <module>
    from kfp import dsl, compiler
  File "/Users/viktorgarba/miniconda/envs/ml-env/lib/python3.9/site-packages/kfp/__init__.py", line 23, in <module>
    from kfp.client import Client  # pylint: disable=wrong-import-position
  File "/Users/viktorgarba/miniconda/envs/ml-env/lib/python3.9/site-packages/kfp/client/__init__.py", line 15, in <module>
    from kfp.client.client import Client
  File "/Users/viktorgarba/miniconda/envs/ml-env/lib/python3.9/site-packages/kfp/client/client.py", line 56, in <module>
    class JobConfig:
  File "/Users/viktorgarba/miniconda/envs/ml-env/lib/python3.9/site-packages/kfp/client/client.py", line 59, in JobConfig
    self, spec: kfp_server_api.ApiPipelineSpec,
AttributeError: module 'kfp_server_api' has no attribute 'ApiPipelineSpec'`

### Expected result

No error should occur. component yaml should be outout

### Materials and Reference

When downgrading `kfp-server-api` from `2.0.0b0` (which was deployed 4 hours ago) to `2.0.0a6` things work as expected

Impacted by this bug? Give it a 👍.

**Comment by micmarty-deepsense** [comment]
I've got the same error

**Comment by Linchin** [comment]
I will close this issue. Feel free to reopen the issue if there's any more problems.

**Comment by Princy-Malhotra** [comment]
> In my environment, upgrading kfp to 2.0.0b12 resolved this issue.

I tried upgrading to 2.0.0b12, but I have CSV files as input output of the components in my code. So, it gives an error : "typeerror: artifacts must have both a schema_title and a schema_version, separated by `@`. got: csv" . Can you suggest something for this?
