### ISSUE TITLE
[sdk] kfp 2.0.0.b11 (and other betas) incompatible with kfp_server_api version 2.0.0.b

### ISSUE THREAD

**Issue by anifort** [kubeflow/pipelines#8870]
### Description
KFP installation also install dependencies. this include kfp-server-api. It seems that kfp-server-api 2.0.0.b0 is now the required version for kfp 2.0.0.bX however the 2 are not compatible as kfp is attempting to use an attribute from  kfp-server-api thad does not exist. 

### Environment

*  KFP version: 2.0.0.b11. (But other 2.0.0.bx also have the same issue)
*  KFP SDK version: 2.0.0.b11
*  All dependencies version:

kfp                              2.0.0b11 \
kfp-pipeline-spec                0.2.0 \
kfp-server-api                   2.0.0b0 

### Steps to reproduce

pip install kfp==2.0.0.b11
python -c "import kfp"

*the import errors with:*
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/aniftos/Projects/propensity-modeling/.venv/lib/python3.10/site-packages/kfp/__init__.py", line 23, in <module>
    from kfp.client import Client
  File "/Users/aniftos/Projects/propensity-modeling/.venv/lib/python3.10/site-packages/kfp/client/__init__.py", line 20, in <module>
    from kfp.client.client import Client
  File "/Users/aniftos/Projects/propensity-modeling/.venv/lib/python3.10/site-packages/kfp/client/client.py", line 58, in <module>
    class JobConfig:
  File "/Users/aniftos/Projects/propensity-modeling/.venv/lib/python3.10/site-packages/kfp/client/client.py", line 61, in JobConfig
    self, spec: kfp_server_api.ApiPipelineSpec,
AttributeError: module 'kfp_server_api' has no attribute 'ApiPipelineSpec'. Did you mean: 'ApiPipeline'?
```

### Expected result
to be able to import kfp without errors 

### Materials and Reference

---

Impacted by this bug? Give it a 👍.

**Comment by gkcalat** [comment]
Hi @anifort!
To resolve it, please upgrade the `kfp` package to 2.0.0-b12
