### ISSUE TITLE
[bug] ml_metadata.errors.InternalError: mysql_real_connect on KFP Pipelines GCP Marketplace Deployment

### ISSUE THREAD

**Issue by AlirezaSadeghi** [kubeflow/pipelines#8969]
In the past few days, our TFX pipelines that run on, our long running KFP deployment on GCP, started to get intermittent failures related to `connecting to MLMD` in various different components during execution. Even the default TFX taxi pipeline can have a component that fails (non-deterministically, it can be `statisticsGen`, or `model training`, or any other), which usually with a few `Retry`s will work and go beyond that component, sometimes failing yet again in a downstream component, but other times successfully finishing execution.

The issue seems to be from when the TFX Driver wants to publish a metadata to MLMD, either at the beginning of execution, or at the end.

I'm not sure if it's a bug, or a misconfiguration that suddenly has happened due to infrastructure changes hidden to our team in the GKE cluster backing the KFP deployment, but most importantly, I'd want to know how to approach solving this problem. It seems the `grpc metadata service` in the GKE cluster has been running for around 6 months, and it's still RUNNING (not EXITED/TERMINATED/etc). 

Not sure what's going on and any help, links on what this piece is doing and what can be causes of failures would be super welcome, as this suddenly started impacting many nodes.

```bash

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ml_metadata/metadata_store/metadata_store.py", line 213, in _call_method
    response.CopyFrom(grpc_method(request, timeout=self._grpc_timeout_sec))
  File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "mysql_real_connect failed: errno: , error: "
	debug_error_string = "UNKNOWN:Error received from peer ipv4:10.42.6.72:8080 {created_time:"2023-03-09T18:11:55.333836586+00:00", grpc_status:13, grpc_message:"mysql_real_connect failed: errno: , error: "}"
>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/site-packages/tfx/orchestration/kubeflow/container_entrypoint.py", line 545, in <module>
    main(sys.argv[1:])
  File "/usr/local/lib/python3.8/site-packages/tfx/orchestration/kubeflow/container_entrypoint.py", line 526, in main
    execution_info = component_launcher.launch()
  File "/usr/local/lib/python3.8/site-packages/tfx/orchestration/portable/launcher.py", line 528, in launch
    execution_preparation_result = self._prepare_execution()
  File "/usr/local/lib/python3.8/site-packages/tfx/orchestration/portable/launcher.py", line 315, in _prepare_execution
    execution = self._register_or_reuse_execution(
  File "/usr/local/lib/python3.8/site-packages/tfx/orchestration/portable/launcher.py", line 241, in _register_or_reuse_execution
    return _register_execution(
  File "/usr/local/lib/python3.8/site-packages/tfx/orchestration/kubeflow/container_entrypoint.py", line 69, in _register_execution
    return execution_publish_utils.register_execution(
  File "/usr/local/lib/python3.8/site-packages/tfx/orchestration/portable/execution_publish_utils.py", line 264, in register_execution
    execution = execution_lib.prepare_execution(
  File "/usr/local/lib/python3.8/site-packages/tfx/orchestration/portable/mlmd/execution_lib.py", line 119, in prepare_execution
    execution.type_id = common_utils.register_type_if_not_exist(
  File "/usr/local/lib/python3.8/site-packages/tfx/orchestration/portable/mlmd/common_utils.py", line 74, in register_type_if_not_exist
    metadata_type = get_type_handler(metadata_type.name)
  File "/usr/local/lib/python3.8/site-packages/ml_metadata/metadata_store/metadata_store.py", line 765, in get_execution_type
    self._call('GetExecutionType', request, response)
  File "/usr/local/lib/python3.8/site-packages/ml_metadata/metadata_store/metadata_store.py", line 188, in _call
    return self._call_method(method_name, request, response)
  File "/usr/local/lib/python3.8/site-packages/ml_metadata/metadata_store/metadata_store.py", line 218, in _call_method
    raise _make_exception(e.details(), e.code().value[0])  # pytype: disable=attribute-error
ml_metadata.errors.InternalError: mysql_real_connect failed: errno: , error: 


```
### Environment

*  How do you deploy Kubeflow Pipelines (KFP)?

GCP Marketplace deployment of KFP only 
TFX Pipelines using tfx==1.7.*

*  KFP version:
1.8.5 

*  KFP SDK version:
Not relevant, this happens as part of the pipeline execution

### Steps to reproduce
Not sure, as this is GKE cluster related it seems.

### Expected result
Nodes should deterministically pass

### Materials and reference

---

Impacted by this bug? Give it a 👍.

**Comment by AlirezaSadeghi** [comment]
Ok so some further updates. We performed some testing, loading the artifacts in the pipeline dashboard we can see the same behavior.  the cloudsql proxy is healthy until it performs a large number of connections and then the readiness probe will sometimes fail.

Cloud SQL had 4k connection limit, increased it to 10K, not much of a behaviour difference.

Tailing the proxy logs we see a large number of "new connections", the grpc logs will have this message when there are problems:

Metadata_store_service_impl.cc:696] Failed to connect to the database: mysql_real_connect failed: errno: , error:

Basic testing of the proxy seems fine, its not until we have the more queries per second that this becomes an issue. This seems specific to KFP and how it is making these queries as single transactions or from a lack of connection pooling. 

We're running all of KFP services and pods in one node in GKE, can that be a culprit in anyway? that one node though is pretty large and KFP never exceeds half of RAM/CPU resources. Can it be due to `ulimit` soft/hard bounds on the one node, as the connections grow?

We have around 30 pipelines, each having around ~100 versions.

**Comment by AlirezaSadeghi** [comment]
Might also be related to https://github.com/kubeflow/pipelines/issues/8844, as we can't ever see the artifacts tab, and just clicking it fails the proxy.

**Comment by chensun** [comment]
> Can it be due to ulimit soft/hard bounds on the one node, as the connections grow?

I'm not an expert. Would you be able to get some help from GCP support regarding this question?

> Might also be related to https://github.com/kubeflow/pipelines/issues/8844, as we can't ever see the artifacts tab, and just clicking it fails the proxy.

The issue with Artifact tab is known, and we do have a work item to add pagination support: https://github.com/kubeflow/pipelines/issues/8986

However, I think the error you had from the call stack (which is TFX) is orthogonal to how KFP queries artifacts--the TFX pipeline to KFP is like any user code/pipeline. Would you be able to get some logs and metrics from Cloud SQL to see if the DB is really overloaded with connections and where are the connections coming from?
