### ISSUE TITLE
[sdk] Not able to install GCP artifact registry python package using pip_index_urls parameter in component

### ISSUE THREAD

**Issue by Rstar1998** [kubeflow/pipelines#9011]
*  KFP SDK version:  1.8.19
Hi folks
I need to install a private package from gcp artifact registry using pip_index_urls of the @component decorator in Kubeflow pipeline which is on GCP cluster. My index url looks like this => 

pip_index_urls = ["https://location-python.pkg.dev/project-id/repo-name/simple/  package_name==1.0.0"]

```
@component(pip_index_urls = ["https://location-python.pkg.dev/project-id/repo-name/simple/  package_name==1.0.0"],base_image="python:3.9")
def process_data( output_data : Output[Dataset]):
                 from private_package import some_function
                 some_function()
                
```

GCP Artifact python index url example:

```
  pip install --index-url https://us-central1-python.pkg.dev/PROJECT_ID/quickstart-python-repo/simple/ sampleproject

```
Reference : [GCP Documentation](https://cloud.google.com/artifact-registry/docs/python/store-python#download)

When I use this. It gives me a weird error. 
```

    time="2023-03-20T08:03:19.432Z" level=info msg="capturing logs" argo=true
    I0320 08:03:19.455992      21 cache.go:120] Connecting to cache endpoint ---------
    ERROR: Exception:
    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
        status = run_func(*args)
      File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
        return func(self, options, args)
      File "/usr/local/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 339, in run
        requirement_set = resolver.resolve(
      File "/usr/local/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
        result = self._result = resolver.resolve(
      File "/usr/local/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
        state = resolution.resolve(requirements, max_rounds=max_rounds)
      File "/usr/local/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
        self._add_to_criteria(self.state.criteria, r, parent=None)
      File "/usr/local/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
        if not criterion.candidates:
      File "/usr/local/lib/python3.9/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
        return bool(self._sequence)
      File "/usr/local/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
        return any(self)
      File "/usr/local/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
        return (c for c in iterator if id(c) not in self._incompatible_ids)
      File "/usr/local/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 44, in _iter_built
        for version, func in infos:
      File "/usr/local/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 294, in iter_index_candidate_infos
        result = self._finder.find_best_candidate(
      File "/usr/local/lib/python3.9/site-packages/pip/_internal/index/package_finder.py", line 868, in find_best_candidate
        candidates = self.find_all_candidates(project_name)
      File "/usr/local/lib/python3.9/site-packages/pip/_internal/index/package_finder.py", line 809, in find_all_candidates
        page_candidates = list(page_candidates_it)
      File "/usr/local/lib/python3.9/site-packages/pip/_internal/index/sources.py", line 134, in page_candidates
        yield from self._candidates_from_page(self._link)
      File "/usr/local/lib/python3.9/site-packages/pip/_internal/index/package_finder.py", line 769, in process_project_url
        html_page = self._link_collector.fetch_page(project_url)
      File "/usr/local/lib/python3.9/site-packages/pip/_internal/index/collector.py", line 566, in fetch_page
        return _get_html_page(location, session=self.session)
      File "/usr/local/lib/python3.9/site-packages/pip/_internal/index/collector.py", line 471, in _get_html_page
        resp = _get_html_response(url, session=session)
      File "/usr/local/lib/python3.9/site-packages/pip/_internal/index/collector.py", line 123, in _get_html_response
        resp = session.get(
      File "/usr/local/lib/python3.9/site-packages/pip/_vendor/requests/sessions.py", line 542, in get
        return self.request('GET', url, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/pip/_internal/network/session.py", line 454, in request
        return super().request(method, url, *args, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/pip/_vendor/requests/sessions.py", line 529, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/local/lib/python3.9/site-packages/pip/_vendor/requests/sessions.py", line 652, in send
        r = dispatch_hook('response', hooks, r, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/pip/_vendor/requests/hooks.py", line 31, in dispatch_hook
        _hook_data = hook(hook_data, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/pip/_internal/network/auth.py", line 270, in handle_401
        username, password, save = self._prompt_for_password(parsed.netloc)
      File "/usr/local/lib/python3.9/site-packages/pip/_internal/network/auth.py", line 233, in _prompt_for_password
        username = ask_input(f"User for {netloc}: ")
      File "/usr/local/lib/python3.9/site-packages/pip/_internal/utils/misc.py", line 200, in ask_input
        return input(message)
    EOFError: EOF when reading a line
    F0320 08:03:22.196366      21 main.go:50] Failed to execute component: exit status 2
    
    Error: exit status 1
    User for asia-south1-python.pkg.dev: 

```
Any workaround for this ?

**Comment by cjidboon94** [comment]
```@component(pip_index_urls = ["https://location-python.pkg.dev/project-id/repo-name/simple/ package_name==1.0.0"],base_image="python:3.9")```
should probably be => 
```@component(pip_index_urls=["https://location-python.pkg.dev/project-id/repo-name/simple/], packages_to_install=["package_name==1.0.0"], base_image="python:3.9")```

**Comment by connor-mccarthy** [comment]
@cjidboon94 is correct. Thanks!
