### ISSUE TITLE
[backend] Panic while connection to default cache endpoint ml-pipeline.kubeflow:8887

### ISSUE THREAD

**Issue by andre-lx** [kubeflow/pipelines#9702]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
Manifests
*  KFP version: 
2.0.0
*  KFP SDK version: 
```
kfp                   2.0.1
kfp-pipeline-spec     0.2.2
kfp-server-api        2.0.0
```

### Steps to reproduce

Hello, we are trying the migration from pipelines 1.8.5 to 2.0.0 but after the apply we are aheving some issues. 

Running the "hello world" example from the jupyerlab:
```python
from kfp import dsl
import kfp


from kfp import dsl

@dsl.component
def say_hello(name: str) -> str:
    hello_text = f'Hello, {name}!'
    print(hello_text)
    return hello_text

@dsl.pipeline
def hello_pipeline(recipient: str) -> str:
    hello_task = say_hello(name=recipient)
    return hello_task.output

from kfp import compiler

compiler.Compiler().compile(hello_pipeline, 'pipeline.yaml')

from kfp.client import Client

client = Client()
run = client.create_run_from_pipeline_package(
    'pipeline.yaml',
    arguments={
        'recipient': 'World',
    },
)
```

Or running the generated `pipeline.yaml` from the result directly though the UI, we always get the following error on the third pod that is started:

```
time="2023-07-05T14:19:23.912Z" level=info msg="capturing logs" argo=true
time="2023-07-05T14:19:23.945Z" level=info msg="capturing logs" argo=true
I0705 14:19:23.966873      51 launcher_v2.go:90] input ComponentSpec:{
  "inputDefinitions": {
    "parameters": {
      "name": {
        "parameterType": "STRING"
      }
    }
  },
  "outputDefinitions": {
    "parameters": {
      "Output": {
        "parameterType": "STRING"
      }
    }
  },
  "executorLabel": "exec-say-hello"
}
I0705 14:19:23.967498      51 cache.go:139] Cannot detect ml-pipeline in the same namespace, default to ml-pipeline.kubeflow:8887 as KFP endpoint.
I0705 14:19:23.967512      51 cache.go:116] Connecting to cache endpoint ml-pipeline.kubeflow:8887
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x941c29]

goroutine 1 [running]:
github.com/kubeflow/pipelines/backend/src/v2/metadata.(*Client).PublishExecution(0xc000b29920, {0x20a4878, 0xc000058040}, 0x0, 0x0, {0x0, 0x0, 0xc000b60000?}, 0x4)
	/go/src/github.com/kubeflow/pipelines/backend/src/v2/metadata/client.go:388 +0x69
github.com/kubeflow/pipelines/backend/src/v2/component.(*LauncherV2).publish(0x1d3c167?, {0x20a4878?, 0xc000058040?}, 0x1?, 0x1?, {0x0?, 0x1a51660?, 0xc0006a63a0?}, 0xc73bb0?)
	/go/src/github.com/kubeflow/pipelines/backend/src/v2/component/launcher_v2.go:266 +0x9b
github.com/kubeflow/pipelines/backend/src/v2/component.(*LauncherV2).Execute.func2()
	/go/src/github.com/kubeflow/pipelines/backend/src/v2/component/launcher_v2.go:144 +0x65
github.com/kubeflow/pipelines/backend/src/v2/component.(*LauncherV2).Execute(0xc00028e540, {0x20a4878, 0xc000058040})
	/go/src/github.com/kubeflow/pipelines/backend/src/v2/component/launcher_v2.go:156 +0x91e
main.run()
	/go/src/github.com/kubeflow/pipelines/backend/src/v2/cmd/launcher-v2/main.go:98 +0x3ed
main.main()
	/go/src/github.com/kubeflow/pipelines/backend/src/v2/cmd/launcher-v2/main.go:47 +0x19
time="2023-07-05T14:19:24.950Z" level=info msg="sub-process exited" argo=true error="<nil>"
Error: exit status 2
time="2023-07-05T14:19:25.918Z" level=info msg="sub-process exited" argo=true error="<nil>"
Error: exit status 2
```

The service `ml-pipeline.kubeflow:8887` exists.

Everything works great on version 1.8.5.

If you need the logs from the others two pods please let me know. I also check the logs in all the kubeflow services and I can't find any issue. 

Impacted by this bug? Give it a 👍.

**Comment by Linchin** [comment]
Hi @andre-lx, thank you for bringing up this issue. I tried the same pipeline on a newly deployed 2.0.0 cluster, and the run finished without issue. looking at the log you provided, we have 

> github.com/kubeflow/pipelines/backend/src/v2/metadata.(*Client).PublishExecution(0xc000b29920, {0x20a4878, 0xc000058040}, 0x0, 0x0, {0x0, 0x0, 0xc000b60000?}, 0x4)
	/go/src/github.com/kubeflow/pipelines/backend/src/v2/<b>metadata/client.go:388</b> +0x69

The metadata client seems to come from [version 2.0.0-rc.2](https://github.com/kubeflow/pipelines/blob/2.0.0-rc.2/backend/src/v2/metadata/client.go#L388) instead of [version 2.0.0](https://github.com/kubeflow/pipelines/blob/2.0.0/backend/src/v2/metadata/client.go#L412). Could you double check if you applied the manifest of version 2.0.0? Try apply the manifest again ([here](https://github.com/kubeflow/pipelines/blob/e03e31219387b587b700ba3e31a02df486aa364f/backend/src/v2/metadata/client.go#L412)) and see if the issue persists.

**Comment by Linchin** [comment]
Also, could you let me know which way you used to deploy KFP, standalone or via kubeflow?

**Comment by andre-lx** [comment]
Hi @Linchin, I just checked and we are using the following image: 
https://github.com/kubeflow/pipelines/blob/e03e31219387b587b700ba3e31a02df486aa364f/manifests/kustomize/base/metadata/base/kustomization.yaml#L10-L12

The deployment was done using the follwing file: https://github.com/kubeflow/pipelines/blob/2.0.0/manifests/kustomize/env/platform-agnostic-multi-user/kustomization.yaml

Thanks

**Comment by nithin8702** [comment]
Hi @andre-lx @Linchin 
Same issue we are also facing. Did you get a chance to fix it?

**Comment by andre-lx** [comment]
> Hi @andre-lx @Linchin Same issue we are also facing. Did you get a chance to fix it?

I had to revert it to 1.8.5 for now.

**Comment by nithin8702** [comment]
+ @chensun for visibility of this issue

**Comment by halilagin** [comment]
I have the same error. Here are the details.

1. Running in standalone mode
2.  Running in virtual cluster (everything is working but cannot run pipelines)
3. All pods are working
4. I can upload and run pipelines on UI, but the pod is failing
5. Using the pipelines version 2.0.0
6. Generating the pipeline with the command below
kfp dsl compile --py v2/hello_world.py --output hello_world.pipeline.json

**Comment by svn123** [comment]
I have faced a similar issue. I have full Kubeflow 1.8 environment installed and the pipeline backend metadata envoy is 2.0.3 version. Is this issue resolved?

**Comment by umka1332** [comment]
I've faced similar issue, and it was due to proxy setting on the pod/step. After removing proxy setting the issue was gone.

**Comment by pschoen-itsc** [comment]
@umka1332 This solved the problem for me also. But do you know a way how I can still set proxy env vars to connect to the internet?

**Comment by pschoen-itsc** [comment]
Just tested successfully that setting NO_PROXY to '*.kubeflow,*.local' seems to work together with http(s)_proxy

**Comment by ryanspaethlhsystems** [comment]
Is there a way to funnel the proxy after initializing the client?

**Comment by gregsheremeta** [comment]
If anyone following this can reliably reproduce this issue...

> we always get the following error on the third pod that is started

I also need to see the log on the second pod (driver) that is started. Thanks.

**Comment by suanshs** [comment]
> @umka1332 This solved the problem for me also. But do you know a way how I can still set proxy env vars to connect to the internet?



> Just tested successfully that setting NO_PROXY to '*.kubeflow,*.local' seems to work together with http(s)_proxy. It makes sense that the connection to ml-pipeline fails without NO_PROXY because then all traffic will be routed through the given proxy. It is just strange that it has seemed to work before updating kubeflow.

How did you solve this? I tried to set the no_proxy environment variables but it did not work for me.

**Comment by pschoen-itsc** [comment]
> > @umka1332 This solved the problem for me also. But do you know a way how I can still set proxy env vars to connect to the internet?
> 
> > Just tested successfully that setting NO_PROXY to '_.kubeflow,_.local' seems to work together with http(s)_proxy. It makes sense that the connection to ml-pipeline fails without NO_PROXY because then all traffic will be routed through the given proxy. It is just strange that it has seemed to work before updating kubeflow.
> 
> How did you solve this? I tried to set the no_proxy environment variables but it did not work for me. @umka1332

Important is to set `NO_PROXY` (so all uppercase). Also I had to add the kube api-server IP to NO_PROXY.

**Comment by stevenkitter** [comment]
1.8.1 kubeflow has the same problem....

**Comment by stevenkitter** [comment]
I solved this problem by delete proxy, you guys must delete proxy, if you need packages you need make a image that you can use.

**Comment by suanshs** [comment]
`from kfp import dsl
from kfp import compiler

@dsl.component()
def say_hello() :
    import time
    time.sleep(1900)
    hello_text = f'Hello!'
    print(hello_text)

@dsl.pipeline
def hello_pipeline():
    hello_task = say_hello()
    hello_task.set_env_variable(name='NO_PROXY', value='*.kubeflow,*.local')
    hello_task.set_env_variable(name='no_proxy', value='*.kubeflow,*.local')
    hello_task.set_caching_options(False)
    

compiler.Compiler().compile(hello_pipeline, package_path='pipeline.yaml')`

I tried running this but it did not work for me. Is there somethin I am missing here. @umka1332

**Comment by pschoen-itsc** [comment]
@suanshs Seems like you are having a different problem. If you don't have any proxies set to begin with, then you also should not need the NO_PROXY settings. Can you provide logs of all the containers of the failing pod?

**Comment by suanshs** [comment]
@pschoen-itsc 
Following are the logs from main container of the failing pod


```
time="2024-08-28T14:19:16.866Z" level=info msg="capturing logs" argo=true
time="2024-08-28T14:19:16.900Z" level=info msg="capturing logs" argo=true
I0828 14:19:16.922099      53 launcher_v2.go:90] input ComponentSpec:{
  "executorLabel": "exec-say-hello"
}
I0828 14:19:16.922671      53 cache.go:116] Connecting to cache endpoint ml-pipeline.kubeflow:8887
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x941c29]

goroutine 1 [running]:
github.com/kubeflow/pipelines/backend/src/v2/metadata.(*Client).PublishExecution(0xc000afc720, {0x20a4878, 0xc000196000}, 0x0, 0x0, {0x0, 0x0, 0xc0004dc000?}, 0x4)
	/go/src/github.com/kubeflow/pipelines/backend/src/v2/metadata/client.go:388 +0x69
github.com/kubeflow/pipelines/backend/src/v2/component.(*LauncherV2).publish(0x467387?, {0x20a4878?, 0xc000196000?}, 0x1?, 0x1?, {0x0?, 0x1a51660?, 0xc0004c6060?}, 0xbbfbb0?)
	/go/src/github.com/kubeflow/pipelines/backend/src/v2/component/launcher_v2.go:266 +0x9b
github.com/kubeflow/pipelines/backend/src/v2/component.(*LauncherV2).Execute.func2()
	/go/src/github.com/kubeflow/pipelines/backend/src/v2/component/launcher_v2.go:144 +0x65
github.com/kubeflow/pipelines/backend/src/v2/component.(*LauncherV2).Execute(0xc000306460, {0x20a4878, 0xc000196000})
	/go/src/github.com/kubeflow/pipelines/backend/src/v2/component/launcher_v2.go:156 +0x91e
main.run()
	/go/src/github.com/kubeflow/pipelines/backend/src/v2/cmd/launcher-v2/main.go:98 +0x3ed
main.main()
	/go/src/github.com/kubeflow/pipelines/backend/src/v2/cmd/launcher-v2/main.go:47 +0x19
time="2024-08-28T14:19:17.903Z" level=info msg="sub-process exited" argo=true error="<nil>"
Error: exit status 2
time="2024-08-28T14:19:18.871Z" level=info msg="sub-process exited" argo=true error="<nil>"
Error: exit status 2
```

**Comment by pschoen-itsc** [comment]
@suanshs Do you also have logs of the istio sidecar or do you have no istio deployed?

**Comment by mmazurekgda** [comment]
> Just tested successfully that setting NO_PROXY to '*.kubeflow,*.local' seems to work together with http(s)_proxy. It makes sense that the connection to ml-pipeline fails without NO_PROXY because then all traffic will be routed through the given proxy. It is just strange that it has seemed to work before updating kubeflow.

Thanks! This helped me a lot!

**Comment by cybernagle** [comment]
> @suanshs Do you also have logs of the istio sidecar or do you have no istio deployed?

Hi I'm facing the same issue when using istio-proxy sidecar injected.  and with NO_PROXY environment setup not able to fix such issue. :(

**Comment by cybernagle** [comment]
Hi Folks,
 
I was able to fix this issue, root cause of my issue is that, I was using istio sidecar inject into workflow  pods. 
But under init containers , kfp-launcher will try to connect to metadata-grpc-service with 8080 port first without istio-proxy ready yet. and I was found this issue https://github.com/istio/istio/issues/23802, as it suggested, add labels: 

> traffic.sidecar.istio.io/excludeOutboundPorts: "8080"

to container resolved it.

**Comment by umka1332** [comment]
Sorry for late response (fortunately I've gathered more knowladge about the topic now).
There are multiple issues with proxy, and it depends on what I was trying to do.
One way is to not adding proxy, but then you need to use custom `base_image` for components that already includes kfp sdk installed and to explicitly tell components to [not install kfp sdk](https://kubeflow-pipelines.readthedocs.io/en/stable/source/dsl.html#kfp.dsl.component.install_kfp_package). By default a pure python:3.7 image is used and kfp sdk is installed in runtime.
Other way is to add proxy and add appropriate for your cluster no_proxy, but you also need to additionally include `,.kubeflow` and probably `,.kubeflow,local` there. Please note that in this case `kubeflow` is the namespace, where kubeflow and/or ml-pipelines are installed.
Also whenever you set proxy - always set both upper case and lowercase variants of all `http_proxy`, `https_proxy` and `no_proxy` env vars just to be sure.

**Comment by Naegionn** [comment]
I have the same issue on kubeflow 1.9 with  KFP API 2.2 installed using charmed kubeflow.
It happens "randomly" roughly every 1/20 pods.

**Comment by arunbenoyv** [comment]
Hi I have been, facing the same issue and it's still not quite clear to me why this is happening. Is there any update on when it will be fixed or what is a workaround in the meantime.

**Comment by dandawg** [comment]
@arunbenoyv do you have an easy way to reproduce this on KF 1.9.1? Are you running the same example pipeline as above? Also, what is your environment? Are you running on a local cluster like kind?

**Comment by arunbenoyv** [comment]
Hi @dandawg : I'm running this on EKS, I have followed the same steps if installation as provided in the manifest github page branch 1.9.1. Following is the pipeline i have compiled and uploaded the yaml for pipline run via kubeflow.

I have a thread in kubeflow-pipeline slack channel. I will copy paste the info I had pasted there to this thread.

```
from kfp import dsl
import kfp
from kfp import dsl

@dsl.component
def say_hello(name: str) -> str:
    hello_text = f'Hello, {name}!'
    print(hello_text)
    return hello_text

@dsl.pipeline
def hello_pipeline(recipient: str) -> str:
    hello_task = say_hello(name=recipient)
    return hello_task.output

from kfp import compiler

compiler.Compiler().compile(hello_pipeline, 'pipeline.yaml')
```
Pod with error 

```
kgp -n kubeflow-user-example-com
NAME                           READY  STATUS   RESTARTS  AGE
hello-pipeline-xkbh9-system-container-driver-3512557064  0/2   Completed  0     4m1s
hello-pipeline-xkbh9-system-container-impl-2396298878   0/2   **Error**    0     3m51s
hello-pipeline-xkbh9-system-dag-driver-2860082384     0/2   Completed  0     4m21s
mnist-0                          2/2   Running   0     17h
```

Error log

```
time="2025-01-09T11:47:37.236Z" level=info msg="capturing logs" argo=true
I0109 11:47:37.283391   15 cache.go:139] Cannot detect ml-pipeline in the same namespace, default to ml-pipeline.kubeflow:8887 as KFP endpoint.
I0109 11:47:37.283528   15 cache.go:116] Connecting to cache endpoint ml-pipeline.kubeflow:8887
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1f0e15d]

goroutine 1 [running]:
github.com/kubeflow/pipelines/backend/src/v2/metadata.(*Client).PublishExecution(0xc000b372f0, {0x2bfc910, 0x4135420}, 0x0, 0x0, {0x0, 0x0, 0x2bd0fc0?}, 0x4)
	/go/src/github.com/kubeflow/pipelines/backend/src/v2/metadata/client.go:449 +0x5d
github.com/kubeflow/pipelines/backend/src/v2/component.(*LauncherV2).publish(0x0?, {0x2bfc910?, 0x4135420?}, 0x0?, 0xc00099fb28?, {0x0?, 0x1?, 0x1?}, 0x99fb38?)
	/go/src/github.com/kubeflow/pipelines/backend/src/v2/component/launcher_v2.go:270 +0x90
github.com/kubeflow/pipelines/backend/src/v2/component.(*LauncherV2).Execute.func2()
	/go/src/github.com/kubeflow/pipelines/backend/src/v2/component/launcher_v2.go:143 +0x5d
github.com/kubeflow/pipelines/backend/src/v2/component.(*LauncherV2).Execute(0xc000198d20, {0x2bfc910?, 0x4135420})
	/go/src/github.com/kubeflow/pipelines/backend/src/v2/component/launcher_v2.go:155 +0x9ee
main.run()
	/go/src/github.com/kubeflow/pipelines/backend/src/v2/cmd/launcher-v2/main.go:98 +0x3ec
main.main()
	/go/src/github.com/kubeflow/pipelines/backend/src/v2/cmd/launcher-v2/main.go:47 +0x13
time="2025-01-09T11:47:38.238Z" level=info msg="sub-process exited" argo=true error="<nil>"
Error: exit status 2
```

Deployments in kubeflow name space
```
NAME                           READY  STATUS  RESTARTS    AGE
admission-webhook-deployment-5644dcc957-wl2ll      1/1   Running  0       168m
cache-server-59dfb6fcfc-m2cv7              2/2   Running  0       14h
centraldashboard-74fc94fcf4-p6mwz            2/2   Running  0       16h
jupyter-web-app-deployment-7dbcd448fb-2d8hs       2/2   Running  0       10h
kserve-controller-manager-85f855bfb4-bxk8d        2/2   Running  0       16h
kserve-models-web-app-67f4b9dcfd-hfwnl          2/2   Running  0       16h
kubeflow-pipelines-profile-controller-7b7b8f44f7-xb9zf  1/1   Running  0       168m
metacontroller-0                     1/1   Running  0       15h
metadata-envoy-deployment-74dbc5bdcc-xcrpm        1/1   Running  0       16h
metadata-grpc-deployment-8496ffb98b-67gpk        2/2   Running  1 (168m ago)  168m
metadata-writer-7d7dfc5b8d-g8jsc             2/2   Running  0       15h
minio-7c77bc59b8-zc5dn                  2/2   Running  0       15h
ml-pipeline-bf9f88745-hztsl               2/2   Running  1 (16h ago)  16h
ml-pipeline-persistenceagent-f97777b7f-kzvwb       2/2   Running  0       10h
ml-pipeline-scheduledworkflow-6bbc87d49-97png      2/2   Running  0       16h
ml-pipeline-ui-6cf7f5d654-jz7r9             2/2   Running  1 (50m ago)  10h
ml-pipeline-viewer-crd-8685d84fb6-z8tmg         2/2   Running  1 (10h ago)  10h
ml-pipeline-visualizationserver-75b9c88599-rzcxl     2/2   Running  0       16h
mysql-758cd66576-l8c2s                  2/2   Running  0       16h
notebook-controller-deployment-6545dbccf4-vkckf     2/2   Running  1 (10h ago)  10h
profiles-deployment-5f46f7c9bb-rg5m6           3/3   Running  2 (168m ago)  168m
pvcviewer-controller-manager-74c69655f6-gm885      3/3   Running  0       15h
volumes-web-app-deployment-5b558895d6-trvp9       2/2   Running  0       15h
workflow-controller-784cfd9c97-9648g           2/2   Running  1 (15h ago)  15h
```
Services in kubeflow namespace

```
NAME                      TYPE    CLUSTER-IP    EXTERNAL-IP  PORT(S)       AGE
admission-webhook-service           ClusterIP  172.20.253.42  <none>    443/TCP       6d21h
cache-server                  ClusterIP  172.20.70.163  <none>    443/TCP       6d16h
centraldashboard                ClusterIP  172.20.242.130  <none>    80/TCP       6d21h
jupyter-web-app-service            ClusterIP  172.20.147.21  <none>    80/TCP       6d21h
kserve-controller-manager-metrics-service   ClusterIP  172.20.211.220  <none>    8443/TCP      5d21h
kserve-controller-manager-service       ClusterIP  172.20.84.188  <none>    8443/TCP      5d21h
kserve-models-web-app             ClusterIP  172.20.164.2   <none>    80/TCP       5d21h
kserve-webhook-server-service         ClusterIP  172.20.182.55  <none>    443/TCP       5d21h
kubeflow-pipelines-profile-controller     ClusterIP  172.20.226.244  <none>    80/TCP       6d16h
metadata-envoy-service             ClusterIP  172.20.85.217  <none>    9090/TCP      6d16h
metadata-grpc-service             ClusterIP  172.20.28.161  <none>    8080/TCP      6d16h
minio-service                 ClusterIP  172.20.60.77   <none>    9000/TCP      6d16h
ml-pipeline                  ClusterIP  172.20.90.91   <none>    8888/TCP,8887/TCP  6d16h
ml-pipeline-ui                 ClusterIP  172.20.245.92  <none>    80/TCP       6d16h
ml-pipeline-visualizationserver        ClusterIP  172.20.244.175  <none>    8888/TCP      6d16h
mysql                     ClusterIP  172.20.146.168  <none>    3306/TCP      6d16h
notebook-controller-service          ClusterIP  172.20.109.16  <none>    443/TCP       6d21h
profiles-kfam                 ClusterIP  172.20.5.253   <none>    8081/TCP      6d21h
pvcviewer-controller-manager-metrics-service  ClusterIP  172.20.5.194   <none>    8443/TCP      6d21h
pvcviewer-webhook-service           ClusterIP  172.20.119.182  <none>    443/TCP       6d21h
volumes-web-app-service            ClusterIP  172.20.64.175  <none>    80/TCP       6d21h
```

**Comment by mprahl** [comment]
I just tried installing Kubeflow Pipelines with the [v1.10.0-rc.3](https://github.com/kubeflow/manifests/releases/tag/v1.10.0-rc.3) manifests on a Kind cluster and I cannot reproduce the issue.

Could someone provide clear instructions on how they set up the environment and were able to reproduce it?

**Comment by arunbenoyv** [comment]
Hi @mprahl : Thank you for taking your time to analyze the issue. As mentioned in my previous comments I'm using the stable version **v 1.9.1** (https://github.com/kubeflow/manifests/tree/v1.9.1) of kubeflow manifest on **AWS EKS cluster**, Not v1.10.0-rc.3.

The only difference would be the oauth2 proxy installation (which should not have any bearing on this error) 
kustomize build common/oauth2-proxy/overlays/m2m-dex-and-eks/ | kubectl apply -f -

Rest of the steps are same

**Comment by mprahl** [comment]
@arunbenoyv I just tried it on an EKS cluster with the v1.9.1 manifests but used the option 1 of the "Oauth2-proxy" section and I still can't reproduce it.

Are you able to reproduce it on a fresh install?

**Comment by arunbenoyv** [comment]
@mprahl : I had tried multiple fresh installs in Jan/Feb. Let me see in a new cluster

**Comment by chjdev** [comment]
just ran into the same symptoms as @arunbenoyv and was able to resolve it in our setup. unfortunately i can't say whether it was the same root cause.

we're running 1.10.0 from kubeflow manifests on an OKD/openshift cluster

after digging around i found that the `metacontroller` is throwing errors:

<details>
<summary><pre>... is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: ...</pre></summary>
<pre>
{"level":"error","ts":"2025-04-06T08:43:18Z","msg":"Unhandled Error","logger":"UnhandledError","error":"failed to sync kubeflow-pipelines-profile-controller 'v1:Namespace::kubeflow-user-example-com': can't reconcile children for Namespace /kubeflow-user-example-com: [services \"ml-pipeline-visualizationserver\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>, services \"ml-pipeline-ui-artifact\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>, secrets \"mlpipeline-minio-artifact\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>, configmaps \"metadata-grpc-configmap\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>, deployments.apps \"ml-pipeline-visualizationserver\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>, deployments.apps \"ml-pipeline-ui-artifact\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>, destinationrules.networking.istio.io \"ml-pipeline-visualizationserver\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>, authorizationpolicies.security.istio.io \"ml-pipeline-visualizationserver\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>]","stacktrace":"metacontroller/pkg/controller/decorator.(*decoratorController).processNextWorkItem\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/decorator/controller.go:320\nmetacontroller/pkg/controller/decorator.(*decoratorController).worker\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/decorator/controller.go:308\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.32.0/pkg/util/wait/backoff.go:226\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.32.0/pkg/util/wait/backoff.go:227\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.32.0/pkg/util/wait/backoff.go:204\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.32.0/pkg/util/wait/backoff.go:161\nmetacontroller/pkg/controller/decorator.(*decoratorController).Start.func1.1\n\t/home/runner/work/metacontroller/metacontroller/pkg/controller/decorator/controller.go:282"}
</pre>
</details>

this seems to prevents the pipeline pod from talking to `ml-pipeline.kubeflow:8887` correctly.

after adding the following additional clusterrole to my deploy the errors from `metacontroller` dissapeared and the pipeline was able to run through.

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeflow-metacontroller-supplemental-cluster-role
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: 'false'
rules:
  - apiGroups:
      - ""
    resources:
      - "namespaces/finalizers"
      - "services/finalizers"
      - "configmaps/finalizers"
      - "secrets/finalizers"
    verbs:
      - "update"
  - apiGroups:
      - "apps"
    resources:
      - "deployments/finalizers"
    verbs:
      - "update"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeflow-metacontroller-supplemental-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: meta-controller-service
    namespace: kubeflow
roleRef:
  kind: ClusterRole
  name: kubeflow-metacontroller-supplemental-cluster-role
  apiGroup: rbac.authorization.k8s.io
```

**Comment by zakariaanzid** [comment]
Hello everyone, still facing the same issue.
Trying to automatically deploy a pre compiled kubeflow pipeline using argocd on a k3s vcluster running kfp 2.3.0
I made sure the versions match and everything. one of the pods related to the pipeline keeps crashing with the same error everytime. 

`hello-pipeline-lzq89-system-container-driver-247844000   0/2     Completed   0               114s
hello-pipeline-lzq89-system-container-impl-2765216198    0/2     Error       0               104s
hello-pipeline-lzq89-system-dag-driver-2182373784        0/2     Completed   0               2m4s` 

Here are the logs for that spec pod 

`time="2025-04-28T12:39:48.265Z" level=info msg="capturing logs" argo=true
I0428 12:39:48.301696      23 cache.go:116] Connecting to cache endpoint 10.43.99.60:8887
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1f0e15d]

goroutine 1 [running]:
github.com/kubeflow/pipelines/backend/src/v2/metadata.(*Client).PublishExecution(0xc0006b2ab0, {0x2bfc910, 0x4135420}, 0x0, 0x0, {0x0, 0x0, 0x2bd0fc0?}, 0x4)
        /go/src/github.com/kubeflow/pipelines/backend/src/v2/metadata/client.go:449 +0x5d
github.com/kubeflow/pipelines/backend/src/v2/component.(*LauncherV2).publish(0xc000ae3ae0?, {0x2bfc910?, 0x4135420?}, 0x2666876?, 0x31?, {0x0?, 0x1?, 0x1?}, 0xae3b38?)
        /go/src/github.com/kubeflow/pipelines/backend/src/v2/component/launcher_v2.go:270 +0x90
github.com/kubeflow/pipelines/backend/src/v2/component.(*LauncherV2).Execute.func2()
        /go/src/github.com/kubeflow/pipelines/backend/src/v2/component/launcher_v2.go:143 +0x5d
github.com/kubeflow/pipelines/backend/src/v2/component.(*LauncherV2).Execute(0xc0001e0a80, {0x2bfc910?, 0x4135420})
        /go/src/github.com/kubeflow/pipelines/backend/src/v2/component/launcher_v2.go:155 +0x9ee
main.run()
        /go/src/github.com/kubeflow/pipelines/backend/src/v2/cmd/launcher-v2/main.go:98 +0x3ec
main.main()
        /go/src/github.com/kubeflow/pipelines/backend/src/v2/cmd/launcher-v2/main.go:47 +0x13
time="2025-04-28T12:39:49.266Z" level=info msg="sub-process exited" argo=true error="<nil>"
Error: exit status 2`

Anyone has any idea how to solve this please ?

**Comment by hbelmiro** [comment]
@zakariaanzid this was fixed by https://github.com/kubeflow/pipelines/pull/11771, which is about to be released in KFP 2.5.

**Comment by zakariaanzid** [comment]
> [@zakariaanzid](https://github.com/zakariaanzid) this was fixed by [#11771](https://github.com/kubeflow/pipelines/pull/11771), which is about to be released in KFP 2.5.

Thanks a lot

**Comment by mvtech88** [comment]
Dear team, I am facing same issue as I am running KFP pipeline on kind cluster behind the corporate proxy. Could you please let me know where I can set this proxy parameter in the pipeline ?  I have installed the kubeflow stack on baremetal using the kustomize way as mentioned in the installation document. All apps installed by the kubeflow are up and running and I am triggering the pipeline from the kubeflow Notebook with example user kubeflow-user-example-com 

I am trying like this 
task1 = download_model()
    task1.set_caching_options(False)
   #task1.set_env_variable(name='https_proxy', value='http://x.x.x.x:8080')
    task1.set_env_variable(name='http_proxy', value='http://x.x.x.x:8080')
    task1.set_env_variable(name='HTTP_PROXY', value='http://x.x.x.x:8080')
    task1.set_env_variable(name='HTTPS_PROXY', value='http://x.x.x.x.:8080')
     task1.set_env_variable(name='no_proxy', value='localhost,127.0.0.1,.svc.cluster.local,kubernetes.default.svc,metadata-grpc-service,0,1,2,3,4,5,6,7,8,9')
    task1.set_env_variable(name='NO_PROXY', value='localhost,127.0.0.1,.svc.cluster.local,kubernetes.default.svc,metadata-grpc-service,0,1,2,3,4,5,6,7,8,9')

kfp version kfp 2.11.0

Any help will be appreciated. I am very new to this and don't have much experience.

**Comment by hbelmiro** [comment]
@mvtech88 you can see the new docs about the proxy config here:
https://www.kubeflow.org/docs/components/pipelines/operator-guides/server-config/#proxy

**Comment by mvtech88** [comment]
@hbelmiro : Thank you so much
