### ISSUE TITLE
(test): Fix periodic functional tests

### ISSUE THREAD

**Issue by gkcalat** [kubeflow/pipelines#9770]
It seems to me that the functional testing is [broken](https://oss.gprow.dev/?job=kubeflow-pipelines-periodic-functional-test) due to [outdated `kfp` version](https://oss.gprow.dev/view/gs/oss-prow/logs/kubeflow-pipelines-periodic-functional-test/1681338338910408704). 

We may need to fix the test and verify it (at least [locally](https://github.com/kubeflow/pipelines/blob/master/test/kfp-functional-test/README.md#run-kfp-functional-test-in-local)) before reviewing #9748.

_Originally posted by @gkcalat in https://github.com/kubeflow/pipelines/pull/9748#discussion_r1267026079_

/cc @chensun @Linchin @difince

**Comment by gkcalat** [comment]
@difince, thank you for looking into this.

Let's treat the process for updating requirements as a separate issue. For now, you can set `kfp==2.0.1` and generate a new requirements.txt.

For the dependency error, could you try 1) updating `kfp` to `2.0.1` and 2) running it via a docker? You can also try running the test under Python 3.7-3.9.

It's been 3 years since the instructions were last updated, so it may be worth trying to upgrade to a newer Python version (3.7 is EOL already).

/cc @chensun can you comment on the `update_requirements.sh` and the `pip-tools`?

**Comment by difince** [comment]
hi @gkcalat my update for today 
I tried both Python and Docker ways to run `kfp-functional-test` in local - both failed because of 401 exceptions.
```
ERROR:root:Failed to get healthz info attempt 5 of 5.
Traceback (most recent call last):
  File "/home/dianaa/git/pipelines/test/kfp-functional-test/diana_venv/lib/python3.10/site-packages/kfp/client/client.py", line 435, in get_kfp_healthz
    return self._healthz_api.get_healthz()
  File "/home/dianaa/git/pipelines/test/kfp-functional-test/diana_venv/lib/python3.10/site-packages/kfp_server_api/api/healthz_service_api.py", line 63, in get_healthz
    return self.get_healthz_with_http_info(**kwargs)  # noqa: E501
  File "/home/dianaa/git/pipelines/test/kfp-functional-test/diana_venv/lib/python3.10/site-packages/kfp_server_api/api/healthz_service_api.py", line 134, in get_healthz_with_http_info
    return self.api_client.call_api(
  File "/home/dianaa/git/pipelines/test/kfp-functional-test/diana_venv/lib/python3.10/site-packages/kfp_server_api/api_client.py", line 364, in call_api
    return self.__call_api(resource_path, method,
  File "/home/dianaa/git/pipelines/test/kfp-functional-test/diana_venv/lib/python3.10/site-packages/kfp_server_api/api_client.py", line 188, in __call_api
    raise e
  File "/home/dianaa/git/pipelines/test/kfp-functional-test/diana_venv/lib/python3.10/site-packages/kfp_server_api/api_client.py", line 181, in __call_api
    response_data = self.request(
  File "/home/dianaa/git/pipelines/test/kfp-functional-test/diana_venv/lib/python3.10/site-packages/kfp_server_api/api_client.py", line 389, in request
    return self.rest_client.GET(url,
  File "/home/dianaa/git/pipelines/test/kfp-functional-test/diana_venv/lib/python3.10/site-packages/kfp_server_api/rest.py", line 230, in GET
    return self.request("GET", url,
  File "/home/dianaa/git/pipelines/test/kfp-functional-test/diana_venv/lib/python3.10/site-packages/kfp_server_api/rest.py", line 224, in request
    raise ApiException(http_resp=r)
kfp_server_api.exceptions.ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Length': '1452', 'Content-Type': 'text/html; charset=utf-8', 'Date': 'Tue, 25 Jul 2023 14:28:55 GMT', 'Vary': 'Origin', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '0', 'Set-Cookie': 'S=cloud_datalab_tunnel=o5n06VLCFJWPiw-qYKW8qaofTtZo4x3eok1ivlC98Pk; Path=/; Max-Age=3600', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000'})
HTTP response body: 
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 401 (Unauthorized)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>401.</b> <ins>That’s an error.</ins>
  <p>  <ins>That’s all we know.</ins>
```
When I do `gcloud auth application-default login` I reference to my Gmail - Is this wrong?

**Comment by gkcalat** [comment]
The test has been fixed: https://oss.gprow.dev/?job=kubeflow-pipelines-periodic-functional-test
