### ISSUE TITLE
[sdk] KFP SDK 2.1.2 breaks when upgraded from an older version.

### ISSUE THREAD

**Issue by chensun** [kubeflow/pipelines#9820]
### Environment

*  KFP version:
N/A

*  KFP SDK version: 
2.1.2

*  All dependencies version:
N/A

### Steps to reproduce

- Step 1: `pip3 install kfp==2.0.1`
- Step 2: `pip3 install kfp==2.1.2`
- Step 3: `import kfp`

### Expected result

import kfp should work.

### Actual result

```
>>> import kfp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/kfp/__init__.py", line 23, in <module>
    from kfp import components
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/kfp/components/__init__.py", line 27, in <module>
    from kfp.components.load_yaml_utilities import load_component_from_file
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/kfp/components/load_yaml_utilities.py", line 20, in <module>
    from kfp.dsl import structures
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/kfp/dsl/structures.py", line 25, in <module>
    from kfp.dsl import placeholders
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/kfp/dsl/placeholders.py", line 22, in <module>
    from kfp.dsl.types import type_utils
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/kfp/dsl/types/type_utils.py", line 239, in <module>
    expected_spec: Union[structures.InputSpec, structures.OutputSpec],
AttributeError: partially initialized module 'kfp.dsl.structures' has no attribute 'InputSpec' (most likely due to a circular import)
```

**Comment by chensun** [comment]
We already yanked KFP SDK 2.1.2, so that users' won't upgrade to this version unless they pin the version specifically in the command.

In case you run into this issue, and stuck with a bad environment. The remedy steps are:
1. Uninstall both `kfp` and `kfp-dsl` package: `pip3 uninstall -y kfp kfp-dsl`
2. Reinstall an previous version, e.g.: `pip3 install kfp==2.0.1`.
