### ISSUE TITLE
[backend] metadata-writer deployment starts and then after sometime restarts with Connection reset by peer error

### ISSUE THREAD

**Issue by rscottwatson** [kubeflow/pipelines#9999]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)? Standalone with kustomize on Azure. manifests/kustomize/env/azure
*  KFP version: 2.0.1
*  KFP SDK version:  metadata-writer didn't return anything

### Steps to reproduce

I installed kubeflow 2.0.1 on Azure AKS 1.25.11 with an Azure managed mysql database running outside of the cluster.

### Expected result

I expect the metadata-writer service to keep running but it fails every 10 minutes or so and restarts.

### Materials and Reference

`# this is the error from the pod logs
Connected to the metadata store
Start watching Kubernetes Pods created by Argo
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 764, in read_chunked
    self._update_chunk_length()
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 694, in _update_chunk_length
    line = self._fp.fp.readline()
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/kfp/metadata_writer/metadata_writer.py", line 163, in <module>
    for event in pod_stream:
  File "/usr/local/lib/python3.7/site-packages/kubernetes/watch/watch.py", line 144, in stream
    for line in iter_resp_lines(resp):
  File "/usr/local/lib/python3.7/site-packages/kubernetes/watch/watch.py", line 48, in iter_resp_lines
    for seg in resp.read_chunked(decode_content=False):
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 793, in read_chunked
    self._original_response.close()
  File "/usr/local/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 455, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

`

---

Impacted by this bug? Give it a 👍.

**Comment by zijianjoy** [comment]
Hello @rscottwatson , is your metadata service running healthy?

**Comment by rscottwatson** [comment]
Which service is that?  I have metadata-envoy-deployment which is ok and so
is metadata-grpc-deployment.

At least there are no restarts and I don’t see anything in the logs that
would suggest something is wrong

Just the metadata-writer is still restarting.

**Comment by rscottwatson** [comment]
Hi James,

So we don’t have any traffic policies that would prevent any requests from
being made.  All the other services seem to be ok and we can run pipelines
and port forward to access the ui.

Since we are running in Azure I did use the env/azure as the base in the
kustomization.  Not sure if that did something different from what a non
azure deployment would look like.

Thanks
Scott

**Comment by zijianjoy** [comment]
cc @mosabami to look into this issue.

**Comment by rscottwatson** [comment]
Wanted to follow up and see if there is anything more I can provide to get to the bottom of this issue.

Thanks.

**Comment by ScottWatsonWork** [comment]
Adding a comment to keep this open as it has not been fixed or addressed.

**Comment by rscottwatson** [comment]
Please keep this open

**Comment by andrijaperovic** [comment]
@zijianjoy @mosabami any traction on this?
I see someone else created a very similar issue which has since then gone into a stale state & has been automatically closed:
https://github.com/kubeflow/pipelines/issues/10129
